/* Thèmes du quiz, dans l'ordre d'affichage. Module à part, minuscule : le menu,
   les réglages et le salon s'affichent sans attendre les ~500 Ko de questions
   (data.js et ses 26 fichiers), chargés en arrière-plan. */
export const CATEGORIES = [
  { id: "actu", label: "🗞️ Actus 2025-2026" },
  { id: "melange", label: "🎲 Assorti" },
  { id: "geo", label: "🌍 Géographie" },
  { id: "histoire", label: "🏛️ Histoire" },
  { id: "sciences", label: "🔬 Sciences" },
  { id: "culture", label: "🎨 Arts & Culture" },
  { id: "sport", label: "⚽ Sport" },
  { id: "nature", label: "🦁 Nature & Animaux" },
  { id: "gastro", label: "🍽️ Gastronomie" },
  { id: "cinema", label: "🎬 Cinéma" },
  { id: "series", label: "📺 Séries" },
  { id: "musique", label: "🎵 Musique" },
  { id: "jeuxvideo", label: "🎮 Jeux vidéo" },
  { id: "bdmanga", label: "💥 BD & Manga" },
  { id: "techweb", label: "💻 Tech & Web" },
  { id: "marques", label: "🏷️ Marques" },
  { id: "france", label: "🇫🇷 France" },
  { id: "institutions", label: "⚖️ Institutions" },
  { id: "economie", label: "💰 Économie" },
  { id: "religions", label: "☯️ Religions" },
  { id: "sante", label: "🩺 Santé" },
  { id: "records", label: "🏆 Records" },
  { id: "inventions", label: "💡 Inventions" },
  { id: "langue", label: "🔤 Langue" },
  { id: "citations", label: "💬 Citations" },
  { id: "insolite", label: "🤯 Insolite" },
];
