/* Quiz bank RECORDS - correct = 0-based index. */
export const Q_RECORDS = [
  { q: "Quel est le bâtiment le plus haut du monde ?", choices: ["Shanghai Tower", "Burj Khalifa", "Tour de Tokyo Skytree", "Merdeka 118"], correct: 1 },
  { q: "Quel animal terrestre est le plus rapide en course ?", choices: ["Le lévrier", "Le guépard", "L'antilope", "Le cheval"], correct: 1 },
  { q: "Quel est le plus grand océan du monde ?", choices: ["L'océan Atlantique", "L'océan Indien", "L'océan Pacifique", "L'océan Arctique"], correct: 2 },
  { q: "Quel est l'animal le plus grand ayant jamais existé ?", choices: ["Le baleine bleue", "Le brachiosaure", "L'éléphant d'Afrique", "Le cachalot"], correct: 0 },
  { q: "Quel métal est le plus abondant dans la croûte terrestre ?", choices: ["Le fer", "Le cuivre", "L'aluminium", "Le zinc"], correct: 2 },
  { q: "Quel est le désert le plus vaste du monde (désert chaud) ?", choices: ["Le Kalahari", "Le Sahara", "Le désert de Gobi", "Le désert d'Arabie"], correct: 1 },
  { q: "Quel est l'oiseau le plus rapide en piqué ?", choices: ["L'aigle royal", "Le faucon pèlerin", "Le martinet", "L'autour"], correct: 1 },
  { q: "Quel est le plus grand pays du monde par superficie ?", choices: ["Le Canada", "La Chine", "Les États-Unis", "La Russie"], correct: 3 },
  { q: "Quelle planète du système solaire est la plus grande ?", choices: ["Saturne", "Jupiter", "Neptune", "Uranus"], correct: 1 },
  { q: "Quel est l'animal le plus lourd sur terre ferme actuellement ?", choices: ["L'hippopotame", "Le rhinocéros blanc", "L'éléphant d'Afrique", "La girafe"], correct: 2 },
  { q: "Quel gaz est le plus abondant dans l'atmosphère terrestre ?", choices: ["L'oxygène", "Le dioxyde de carbone", "L'azote", "L'argon"], correct: 2 },
  { q: "Quel est l'os le plus long du corps humain ?", choices: ["Le tibia", "Le fémur", "L'humérus", "Le radius"], correct: 1 },
  { q: "Quelle est la substance naturelle la plus dure connue ?", choices: ["Le quartz", "Le corindon", "Le diamant", "Le titane"], correct: 2 },
  { q: "Quel est le plus petit os du corps humain ?", choices: ["L'étrier", "Le marteau", "L'enclume", "La rotule"], correct: 0 },
  { q: "Quel est le plus grand mammifère terrestre carnivore ?", choices: ["L'ours brun", "L'ours polaire", "Le tigre de Sibérie", "Le lion"], correct: 1 },
  { q: "Quel oiseau possède la plus grande envergure ?", choices: ["Le condor des Andes", "L'albatros hurleur", "Le pélican", "L'aigle royal"], correct: 1 },
  { q: "Quel est le plus long fleuve du continent africain ?", choices: ["Le Congo", "Le Niger", "Le Nil", "Le Zambèze"], correct: 2 },
  { q: "Quelle est la ville la plus peuplée du monde (aire urbaine) ?", choices: ["Delhi", "Tokyo", "Shanghai", "São Paulo"], correct: 1 },
  { q: "Quel est le plus grand État des États-Unis par superficie ?", choices: ["Le Texas", "La Californie", "L'Alaska", "Le Montana"], correct: 2 },
  { q: "Quelle créature vivante est considérée comme la plus grande par la masse ?", choices: ["Le séquoia géant", "La baleine bleue", "Un champignon (Armillaria)", "Le calmar géant"], correct: 2 },
  { q: "Quel est le point le plus profond des océans ?", choices: ["La fosse des Tonga", "La fosse des Mariannes", "La fosse du Japon", "La fosse de Porto Rico"], correct: 1 },
  { q: "Quelle est la chute d'eau la plus haute du monde ?", choices: ["Les chutes Victoria", "Le Salto Ángel", "Les chutes du Niagara", "Les chutes d'Iguazú"], correct: 1 },
  { q: "Quel est le plus grand lac d'eau douce du monde par superficie ?", choices: ["Le lac Victoria", "Le lac Supérieur", "Le lac Baïkal", "La mer Caspienne"], correct: 1 },
  { q: "Quel est le lac le plus profond du monde ?", choices: ["Le lac Tanganyika", "Le lac Baïkal", "La mer Caspienne", "Le lac Supérieur"], correct: 1 },
  { q: "Quel serpent est le plus long du monde ?", choices: ["L'anaconda vert", "Le python réticulé", "Le cobra royal", "Le boa constricteur"], correct: 1 },
  { q: "Quel est le plus grand désert du monde toutes catégories confondues ?", choices: ["Le Sahara", "L'Antarctique", "Le désert de Gobi", "L'Arctique"], correct: 1 },
  { q: "Quel animal détient le record du plus long temps de gestation ?", choices: ["La baleine bleue", "L'éléphant d'Afrique", "Le rhinocéros", "La girafe"], correct: 1 },
  { q: "Quel est le plus grand poisson du monde ?", choices: ["Le grand requin blanc", "Le requin-baleine", "Le thon rouge", "La raie manta"], correct: 1 },
  { q: "Quel est le plus grand reptile vivant du monde ?", choices: ["Le python réticulé", "Le crocodile marin", "Le dragon de Komodo", "L'alligator américain"], correct: 1 },
  { q: "Quel est le plus grand pays d'Amérique du Sud ?", choices: ["L'Argentine", "Le Pérou", "Le Brésil", "La Colombie"], correct: 2 },
  { q: "Quelle montagne est la plus haute du monde mesurée depuis sa base sous-marine ?", choices: ["L'Everest", "Le K2", "Le Mauna Kea", "L'Aconcagua"], correct: 2 },
  { q: "Quel est le plus grand mammifère volant du monde ?", choices: ["La roussette", "La chauve-souris vampire", "Le grand murin", "La pipistrelle"], correct: 0 },
  { q: "Quelle est la mer la plus salée du monde parmi ces plans d'eau ?", choices: ["La mer Rouge", "La mer Morte", "La mer Méditerranée", "La mer Caspienne"], correct: 1 },
  { q: "Quel est le plus grand organe du corps humain ?", choices: ["Le foie", "Les poumons", "La peau", "Les intestins"], correct: 2 },
  { q: "Quel arbre vivant est le plus haut du monde ?", choices: ["Le séquoia à feuilles d'if (redwood)", "Le baobab", "L'eucalyptus", "Le séquoia géant"], correct: 0 },
  { q: "Quel est l'insecte le plus lourd du monde ?", choices: ["Le scarabée goliath", "La mante religieuse", "Le criquet pèlerin", "Le lucane cerf-volant"], correct: 0 },
  { q: "Quel est le plus long os que l'on trouve dans l'oreille ?", choices: ["L'enclume", "Le marteau", "L'étrier", "Le tympan"], correct: 0 },
  { q: "Quelle est la capitale la plus haute du monde en altitude ?", choices: ["Quito", "Bogotá", "La Paz", "Katmandou"], correct: 2 },
  { q: "Quel est le plus grand félin du monde ?", choices: ["Le lion", "Le tigre", "Le jaguar", "Le léopard"], correct: 1 },
  { q: "Quel est le pont le plus long du monde (pont ferroviaire continu) ?", choices: ["Le pont du Danyang-Kunshan", "Le viaduc de Millau", "Le pont d'Akashi", "Le Golden Gate"], correct: 0 },
  { q: "Quel est le mammifère le plus rapide en milieu aquatique ?", choices: ["Le dauphin commun", "L'orque", "Le marsouin", "La baleine à bosse"], correct: 1 },
  { q: "Quel est le plus grand rongeur du monde ?", choices: ["Le castor", "Le capybara", "Le ragondin", "Le porc-épic"], correct: 1 },
  { q: "Quel est le plus long tunnel ferroviaire du monde ?", choices: ["Le tunnel du Saint-Gothard de base", "Le tunnel sous la Manche", "Le tunnel du Seikan", "Le tunnel du Simplon"], correct: 0 },
  { q: "Quel est le plus haut sommet du continent africain ?", choices: ["Le mont Kenya", "Le Kilimandjaro", "Le Ras Dashen", "Le mont Stanley"], correct: 1 },
  { q: "Quel est l'animal qui produit le son le plus fort du monde ?", choices: ["L'éléphant", "La baleine bleue", "Le cachalot", "Le lion"], correct: 2 },
  { q: "Quel est le plus grand amphibien vivant du monde ?", choices: ["La salamandre géante de Chine", "Le crapaud buffle", "La grenouille goliath", "Le triton"], correct: 0 },
  { q: "Quel est le plus grand stade du monde par capacité ?", choices: ["Le Maracanã", "Le stade du Premier-Mai (Pyongyang)", "Le Camp Nou", "Le Wembley"], correct: 1 },
  { q: "Quel est le plus long mur construit par l'homme ?", choices: ["Le mur d'Hadrien", "La Grande Muraille de Chine", "Le mur de Berlin", "Le limes romain"], correct: 1 },
  { q: "Quelle est la région habitée la plus froide du monde en moyenne ?", choices: ["Le Groenland", "Oïmiakon (Sibérie)", "Le nord du Canada", "L'Islande"], correct: 1 },
  { q: "Quel est le pays le plus densément peuplé du monde (parmi les grands) ?", choices: ["Le Bangladesh", "Les Pays-Bas", "La Corée du Sud", "L'Inde"], correct: 0 },
  { q: "Quel est le plus grand volcan du système solaire ?", choices: ["Le mont Olympe (Mars)", "Le Mauna Loa", "Le Vésuve", "L'Etna"], correct: 0 },
  { q: "Quel est l'objet le plus chaud connu du système solaire ?", choices: ["La surface de Vénus", "Le noyau du Soleil", "La surface du Soleil", "Le noyau de la Terre"], correct: 1 },
  { q: "Quel est le plus grand marsupial du monde ?", choices: ["Le koala", "Le kangourou roux", "Le wombat", "Le wallaby"], correct: 1 },
  { q: "Quel est le plus long fleuve du monde (débat, référence traditionnelle) ?", choices: ["L'Amazone", "Le Nil", "Le Yangtsé", "Le Mississippi"], correct: 1 },
  { q: "Quel est le plus grand fleuve du monde par débit ?", choices: ["Le Nil", "Le Congo", "L'Amazone", "Le Yangtsé"], correct: 2 },
  { q: "Quelle est la plus grande île du monde ?", choices: ["La Nouvelle-Guinée", "Bornéo", "Madagascar", "Le Groenland"], correct: 3 },
  { q: "Quel est l'animal terrestre le plus petit (mammifère) ?", choices: ["La musaraigne étrusque", "La souris", "Le rat-taupe", "La chauve-souris bourdon"], correct: 0 },
  { q: "Quel est le plus grand palais du monde par superficie ?", choices: ["Le château de Versailles", "La Cité interdite", "Le palais de Buckingham", "Le Kremlin"], correct: 1 },
  { q: "Quelle roue panoramique fut longtemps un record de hauteur en Europe ?", choices: ["La London Eye", "La grande roue de Vienne", "La roue de Paris", "La roue de Manchester"], correct: 0 },
  { q: "Quel est le plus grand récif corallien du monde ?", choices: ["Le récif de Belize", "La Grande Barrière de corail", "Le récif de la mer Rouge", "Le récif de Nouvelle-Calédonie"], correct: 1 },
  { q: "Quel est le plus grand canyon du monde en profondeur (canyon de rivière) ?", choices: ["Le Grand Canyon", "Le canyon du Colca", "Le canyon de Yarlung Tsangpo", "Le Fish River Canyon"], correct: 2 },
  { q: "Quel est le plus long système de grottes exploré du monde ?", choices: ["Le gouffre de Padirac", "Mammoth Cave (Kentucky)", "La grotte de Postojna", "Les grottes de Škocjan"], correct: 1 },
  { q: "Quel est le plus grand lac salé du monde (mer intérieure) ?", choices: ["Le Grand Lac Salé", "La mer Caspienne", "La mer d'Aral", "Le lac Titicaca"], correct: 1 },
  { q: "Quel est le plus grand mammifère marin après la baleine bleue ?", choices: ["Le cachalot", "Le rorqual commun", "L'orque", "La baleine à bosse"], correct: 1 },
  { q: "Quel est le plus long serpent venimeux du monde ?", choices: ["Le mamba noir", "Le cobra royal", "Le taïpan", "Le crotale"], correct: 1 },
  { q: "Quel est le plus grand désert de sel du monde ?", choices: ["Le salar d'Uyuni", "Le désert de Bonneville", "Le Chott el-Jérid", "La vallée de la Mort"], correct: 0 },
  { q: "Quelle est la plus grande péninsule du monde ?", choices: ["La péninsule scandinave", "La péninsule arabique", "La péninsule ibérique", "Le sous-continent indien"], correct: 1 },
  { q: "Quel est le plus haut sommet d'Amérique du Nord ?", choices: ["Le mont Rainier", "Le Denali (McKinley)", "Le mont Whitney", "Le mont Logan"], correct: 1 },
  { q: "Quel est le plus haut sommet d'Amérique du Sud ?", choices: ["L'Aconcagua", "Le Chimborazo", "L'Ojos del Salado", "Le Huascarán"], correct: 0 },
  { q: "Quel est le plus grand aéroport du monde par superficie ?", choices: ["Dubaï International", "L'aéroport du roi Fahd (Dammam)", "Atlanta", "Pékin-Daxing"], correct: 1 },
  { q: "Quel est le plus grand paquebot de croisière du monde (classe récente) ?", choices: ["Le Queen Mary 2", "Un navire de la classe Icon/Oasis", "Le Titanic", "Le France"], correct: 1 },
  { q: "Quel oiseau est le plus grand du monde ?", choices: ["L'émeu", "L'autruche", "Le casoar", "Le condor"], correct: 1 },
  { q: "Quel oiseau vivant est le plus petit du monde ?", choices: ["Le roitelet", "Le colibri d'Elena", "La mésange", "Le troglodyte"], correct: 1 },
  { q: "Quel est le plus grand mollusque connu (invertébré) ?", choices: ["Le poulpe géant", "Le calmar colossal", "La seiche géante", "Le nautile"], correct: 1 },
  { q: "Quel est le plus grand pays d'Europe par superficie (hors Russie) ?", choices: ["La France", "L'Espagne", "L'Ukraine", "La Suède"], correct: 2 },
  { q: "Quel est le plus grand parc national terrestre du monde ?", choices: ["Le parc de Yellowstone", "Le parc national du Nord-Est du Groenland", "Le Serengeti", "Le parc Kruger"], correct: 1 },
  { q: "Quel est le plus long boulevard/avenue emblématique cité comme très long ?", choices: ["Les Champs-Élysées", "La 9 de Julio (Buenos Aires)", "Broadway", "La Nevski (Saint-Pétersbourg)"], correct: 1 },
  { q: "Quel est le plus grand diamant taillé célèbre serti dans les joyaux britanniques ?", choices: ["Le Koh-i-Noor", "Le Cullinan I", "Le Hope", "Le Régent"], correct: 1 },
  { q: "Quel est le plus grand glacier hors régions polaires (parmi les plus longs) ?", choices: ["Le glacier d'Aletsch", "Le glacier Lambert", "Le glacier Baltoro", "Le glacier de la Mer de Glace"], correct: 2 },
  { q: "Quel est le plus petit pays du monde par superficie ?", choices: ["Monaco", "Le Vatican", "Nauru", "Saint-Marin"], correct: 1 },
  { q: "Quelle est la plus grande cascade du monde par largeur de rideau d'eau ?", choices: ["Les chutes du Niagara", "Les chutes Victoria", "Les chutes de Khône", "Les chutes d'Iguazú"], correct: 2 },
  { q: "Quel est le plus grand delta fluvial du monde ?", choices: ["Le delta du Nil", "Le delta du Gange-Brahmapoutre", "Le delta du Mississippi", "Le delta du Mékong"], correct: 1 },
  { q: "Quel est le plus grand plateau du monde en altitude et superficie ?", choices: ["Le plateau du Colorado", "Le plateau tibétain", "Le plateau éthiopien", "L'Altiplano"], correct: 1 },
  { q: "Quel est le plus grand isthme reliant deux continents (célèbre) ?", choices: ["L'isthme de Panama", "L'isthme de Suez", "L'isthme de Corinthe", "L'isthme de Kra"], correct: 0 },
  { q: "Quel est le plus haut barrage-poids en béton parmi ces grands ouvrages ?", choices: ["Le barrage Hoover", "Le barrage des Trois-Gorges", "Le barrage de Grande Dixence", "Le barrage d'Assouan"], correct: 2 },
  { q: "Quel est le plus grand golfe du monde ?", choices: ["Le golfe du Mexique", "Le golfe du Bengale", "Le golfe Persique", "Le golfe de Guinée"], correct: 1 },
];
