/* Quiz — GASTRONOMIE, 2e vague (fromages, cuisines du monde, desserts, vins, cocktails).
   Format compact : [question, BONNE RÉPONSE, leurre, leurre, leurre] (ordre des
   choix tiré au hasard à l'affichage). Du plus facile au plus difficile. */
const Q = [
  ["De quelle région le kouign-amann est-il originaire ?", "La Bretagne", "La Normandie", "Le Pays basque", "L'Alsace"],
  ["Avec quel lait est fabriqué le crottin de Chavignol ?", "Du lait de chèvre", "Du lait de brebis", "Du lait de vache", "Du lait de jument"],
  ["Quel fromage file et s'étire dans l'aligot de l'Aubrac ?", "La tome fraîche", "Le comté", "La raclette", "Le reblochon"],
  ["Quel fromage à pâte persillée est italien ?", "Le gorgonzola", "Le roquefort", "Le stilton", "La fourme d'Ambert"],
  ["Quel fromage grec en saumure est fait de lait de brebis ?", "La feta", "Le halloumi", "La ricotta", "Le kefalotyri"],
  ["De quel pays vient le halloumi, fromage qui se grille ?", "Chypre", "La Grèce", "La Turquie", "Le Liban"],
  ["Quel fromage néerlandais est enrobé de cire rouge ?", "L'édam", "Le gouda", "Le leerdammer", "La mimolette"],
  ["Quel fromage français à croûte orange est surnommé « boule de Lille » ?", "La mimolette", "Le maroilles", "Le comté", "L'édam"],
  ["Quel plat italien de riz crémeux se cuisine en ajoutant du bouillon peu à peu ?", "Le risotto", "La polenta", "Les gnocchis", "L'arancini"],
  ["Quelle soupe froide de tomates est andalouse ?", "Le gazpacho", "Le minestrone", "La garbure", "Le bortsch"],
  ["Comment appelle-t-on les tranches de poisson cru servies sans riz au Japon ?", "Le sashimi", "Le maki", "Le nigiri", "Le tempura"],
  ["Quel plat vietnamien est une soupe de nouilles de riz au bouillon de bœuf ?", "Le phở", "Le bánh mì", "Le ramen", "Le pad thaï"],
  ["Quel accompagnement coréen est fait de chou fermenté et pimenté ?", "Le kimchi", "Le bibimbap", "Le bulgogi", "Le tteok"],
  ["Quel pain plat indien est cuit contre la paroi d'un four tandoor ?", "Le naan", "Le chapati", "La pita", "La tortilla"],
  ["De quelle plante la gousse de vanille est-elle le fruit ?", "D'une orchidée", "D'un arbre à pain", "D'un palmier", "D'une liane de poivre"],
  ["Quel pays est le premier producteur mondial de vanille ?", "Madagascar", "Le Mexique", "Tahiti", "L'Inde"],
  ["Quel pays est le premier producteur mondial de cacao ?", "La Côte d'Ivoire", "Le Ghana", "Le Brésil", "L'Équateur"],
  ["Quel dessert est une crème recouverte d'une fine couche de sucre caramélisé au chalumeau ?", "La crème brûlée", "L'île flottante", "Le flan", "La panna cotta"],
  ["Quel gâteau en couronne, garni de crème pralinée, célèbre une course cycliste ?", "Le paris-brest", "Le saint-honoré", "L'opéra", "Le fraisier"],
  ["Quel gâteau porte le nom du saint patron des boulangers et des pâtissiers ?", "Le saint-honoré", "Le paris-brest", "Le saint-marc", "La religieuse"],
  ["Quel dessert associe choux, glace vanille et sauce chocolat chaude ?", "Les profiteroles", "Les éclairs", "La religieuse", "Le croquembouche"],
  ["Comment appelle-t-on les petits restaurants traditionnels de Lyon ?", "Les bouchons", "Les bistrots", "Les estaminets", "Les winstubs"],
  ["Quel vin effervescent est produit en Catalogne ?", "Le cava", "Le prosecco", "Le crémant", "Le lambrusco"],
  ["Quel vin liquoreux hongrois est surnommé « le vin des rois, le roi des vins » ?", "Le tokaji", "Le porto", "Le sauternes", "Le marsala"],
  ["Quel cépage rouge règne sur la Bourgogne ?", "Le pinot noir", "Le merlot", "Le cabernet sauvignon", "La syrah"],
  ["Quel cépage blanc donne le chablis ?", "Le chardonnay", "Le sauvignon", "Le riesling", "Le chenin"],
  ["Quel cépage domine les vins de Pomerol et de Saint-Émilion ?", "Le merlot", "Le pinot noir", "Le gamay", "Le grenache"],
  ["Quel cépage donne le beaujolais ?", "Le gamay", "Le pinot noir", "Le merlot", "La syrah"],
  ["Quelle eau-de-vie de pomme est normande ?", "Le calvados", "L'armagnac", "Le kirsch", "La mirabelle"],
  ["Quelle eau-de-vie de vin est produite en Gascogne ?", "L'armagnac", "Le cognac", "Le calvados", "Le marc"],
  ["Quel cocktail cubain mélange rhum, menthe, citron vert et eau gazeuse ?", "Le mojito", "Le daïquiri", "La piña colada", "Le cuba libre"],
  ["Quel cocktail associe champagne et jus d'orange ?", "Le mimosa", "Le bellini", "Le kir royal", "Le spritz"],
  ["Quel cocktail associe tequila, liqueur d'orange et citron vert ?", "La margarita", "La caïpirinha", "Le mojito", "Le cosmopolitan"],
  ["Quel cocktail brésilien est à base de cachaça et de citron vert ?", "La caïpirinha", "La margarita", "Le mojito", "Le pisco sour"],
  ["Quel apéritif italien orange se prépare avec du prosecco et de l'eau gazeuse ?", "Le spritz", "Le negroni", "Le bellini", "L'americano"],
  ["De quelle plante est tirée la tequila ?", "De l'agave", "De la canne à sucre", "Du maïs", "Du cactus nopal"],
  ["Comment appelle-t-on les bières brassées sous le contrôle de moines ?", "Les trappistes", "Les blanches", "Les lambics", "Les IPA"],
  ["Quel chef lyonnais a été élu « cuisinier du siècle » par le Gault et Millau ?", "Paul Bocuse", "Joël Robuchon", "Alain Ducasse", "Michel Guérard"],
  ["Quel chef français a cumulé le plus d'étoiles Michelin au monde de son vivant ?", "Joël Robuchon", "Paul Bocuse", "Alain Ducasse", "Pierre Gagnaire"],
  ["Comment appelle-t-on des légumes coupés en tout petits dés ?", "Une brunoise", "Une julienne", "Une chiffonnade", "Une mirepoix"],
  ["Comment appelle-t-on des légumes taillés en fins bâtonnets ?", "Une julienne", "Une brunoise", "Une jardinière", "Une macédoine"],
  ["Quelle sauce chaude associe beurre, jaunes d'œufs, échalote et estragon ?", "La béarnaise", "La hollandaise", "La béchamel", "La mayonnaise"],
  ["Quelle sauce blanche est faite de beurre, de farine et de lait ?", "La béchamel", "La béarnaise", "La hollandaise", "La sauce Mornay"],
  ["Quelle soupe est traditionnellement servie pour rompre le jeûne du ramadan au Maroc ?", "La harira", "Le gaspacho", "La chorba frik", "Le bortsch"],
  ["Quel plat libanais est une purée de pois chiches au tahini ?", "Le houmous", "Le taboulé", "Le falafel", "Le baba ganoush"],
  ["Quel plat mexicain est une galette de maïs garnie et pliée ?", "Le taco", "Le burrito", "La quesadilla", "Les nachos"],
  ["Quel plat hongrois est un ragoût de bœuf au paprika ?", "Le goulash", "Le bortsch", "Le pörkölt", "Le stroganov"],
  ["Quelle soupe d'Europe de l'Est doit sa couleur rouge à la betterave ?", "Le bortsch", "Le goulash", "La soupe au pistou", "Le gazpacho"],
  ["Quel plat suisse se partage autour d'un caquelon de fromage fondu ?", "La fondue", "La raclette", "La tartiflette", "Les rösti"],
  ["Quel plat écossais est une panse de mouton farcie ?", "Le haggis", "Le black pudding", "Le pie", "Le scotch egg"],
];
export const Q3_GASTRO = Q.map(([q, ...choices]) => ({ q, choices, correct: 0 }));
