/* Quiz bank FRANCE - correct = 0-based index. */
export const Q_FRANCE = [
  { q: "Dans quelle ville se trouve le célèbre palais des Papes ?", choices: ["Aix-en-Provence", "Avignon", "Arles", "Nîmes"], correct: 1 },
  { q: "Quel dessert est une spécialité traditionnelle de la ville de Bordeaux ?", choices: ["Le canelé", "Le kouign-amann", "La bêtise", "Le calisson"], correct: 0 },
  { q: "Le Mont-Saint-Michel se situe à la frontière entre la Normandie et quelle région ?", choices: ["Les Pays de la Loire", "La Bretagne", "Le Centre-Val de Loire", "La Nouvelle-Aquitaine"], correct: 1 },
  { q: "Quelle est la devise de la République française ?", choices: ["Liberté, Égalité, Solidarité", "Honneur et Patrie", "Liberté, Égalité, Fraternité", "Un pour tous, tous pour un"], correct: 2 },
  { q: "Quel fromage à pâte persillée est produit dans l'Aveyron ?", choices: ["Le comté", "Le roquefort", "Le reblochon", "Le maroilles"], correct: 1 },
  { q: "Quel monument parisien fut construit pour l'Exposition universelle de 1889 ?", choices: ["L'Arc de triomphe", "La tour Eiffel", "Le Sacré-Cœur", "Le Panthéon"], correct: 1 },
  { q: "La bouillabaisse est une spécialité emblématique de quelle ville ?", choices: ["Nice", "Marseille", "Toulon", "Montpellier"], correct: 1 },
  { q: "Quel animal figure comme symbole national officieux de la France ?", choices: ["L'aigle", "Le lion", "Le coq", "Le taureau"], correct: 2 },
  { q: "Dans quelle région trouve-t-on les célèbres alignements de menhirs de Carnac ?", choices: ["La Bretagne", "La Normandie", "L'Auvergne", "La Corse"], correct: 0 },
  { q: "Quel château de la Loire est célèbre pour son double escalier en spirale attribué à Léonard de Vinci ?", choices: ["Chenonceau", "Chambord", "Amboise", "Azay-le-Rideau"], correct: 1 },
  { q: "La choucroute est une spécialité traditionnelle de quelle région ?", choices: ["La Lorraine", "L'Alsace", "La Franche-Comté", "La Bourgogne"], correct: 1 },
  { q: "Comment s'appelle l'allégorie féminine qui personnifie la République française ?", choices: ["Jeanne", "Marianne", "Liberté", "France"], correct: 1 },
  { q: "Quelle ville est mondialement connue pour sa moutarde ?", choices: ["Dijon", "Reims", "Lyon", "Nancy"], correct: 0 },
  { q: "Le célèbre viaduc de Millau enjambe la vallée de quel cours d'eau ?", choices: ["La Dordogne", "Le Tarn", "La Garonne", "L'Aveyron"], correct: 1 },
  { q: "Quelle fête traditionnelle bretonne rassemble musiques et danses celtiques ?", choices: ["La feria", "Le fest-noz", "La ducasse", "La transhumance"], correct: 1 },
  { q: "Quel gâteau en forme de couronne est traditionnellement associé à l'Épiphanie dans le sud de la France ?", choices: ["La galette frangipane", "Le gâteau des rois", "Le pain d'épices", "La brioche vendéenne"], correct: 1 },
  { q: "Dans quelle ville se déroule le célèbre carnaval réputé pour ses batailles de fleurs ?", choices: ["Dunkerque", "Nice", "Cannes", "Menton"], correct: 1 },
  { q: "Le calisson est une confiserie traditionnelle de quelle ville ?", choices: ["Aix-en-Provence", "Montélimar", "Grasse", "Cavaillon"], correct: 0 },
  { q: "Quel pont médiéval de Cahors est un exemple remarquable d'architecture fortifiée ?", choices: ["Le pont d'Avignon", "Le pont Valentré", "Le pont du Gard", "Le pont Neuf"], correct: 1 },
  { q: "Quelle région est le berceau du fromage cantal et du saint-nectaire ?", choices: ["Le Limousin", "L'Auvergne", "Le Périgord", "La Savoie"], correct: 1 },
  { q: "Quelle spécialité charcutière est emblématique de la ville de Lyon ?", choices: ["La rosette", "Les rillettes", "Le boudin noir", "La quenelle"], correct: 0 },
  { q: "Le drapeau français est composé de trois bandes verticales de quelles couleurs, de gauche à droite ?", choices: ["Rouge, blanc, bleu", "Bleu, blanc, rouge", "Blanc, bleu, rouge", "Bleu, rouge, blanc"], correct: 1 },
  { q: "Dans quelle ville se trouve la basilique du Sacré-Cœur perchée sur une butte ?", choices: ["Lyon", "Paris", "Lourdes", "Marseille"], correct: 1 },
  { q: "Quel fromage savoyard est utilisé pour préparer la tartiflette ?", choices: ["Le beaufort", "Le reblochon", "L'abondance", "La tomme"], correct: 1 },
  { q: "Quel écrivain français a écrit « Les Misérables » et « Notre-Dame de Paris » ?", choices: ["Émile Zola", "Victor Hugo", "Alexandre Dumas", "Gustave Flaubert"], correct: 1 },
  { q: "Quelle est la spécialité sucrée traditionnelle de Montélimar ?", choices: ["Le nougat", "Le berlingot", "La pâte de fruits", "Le caramel"], correct: 0 },
  { q: "Quelle ville alsacienne est surnommée « la capitale de Noël » pour son marché réputé ?", choices: ["Colmar", "Strasbourg", "Mulhouse", "Sélestat"], correct: 1 },
  { q: "Le champagne est produit dans quelle région historique ?", choices: ["La Bourgogne", "La Champagne", "L'Alsace", "Le Bordelais"], correct: 1 },
  { q: "Quel plat à base de haricots et de viandes est une spécialité du Sud-Ouest ?", choices: ["Le cassoulet", "La garbure", "Le confit", "L'aligot"], correct: 0 },
  { q: "Quelle cathédrale gothique est célèbre pour avoir accueilli le sacre des rois de France ?", choices: ["Notre-Dame de Paris", "La cathédrale de Reims", "La cathédrale de Chartres", "La cathédrale d'Amiens"], correct: 1 },
  { q: "Le bonnet phrygien, symbole républicain, est traditionnellement de quelle couleur ?", choices: ["Bleu", "Blanc", "Rouge", "Vert"], correct: 2 },
  { q: "Quelle spécialité auvergnate mélange purée de pomme de terre et tomme fraîche ?", choices: ["La truffade", "L'aligot", "Le pounti", "La potée"], correct: 1 },
  { q: "Dans quelle ville se trouve le célèbre Palais idéal du Facteur Cheval ?", choices: ["Hauterives", "Vienne", "Valence", "Romans"], correct: 0 },
  { q: "Quel est le plus vaste château de la vallée de la Loire ?", choices: ["Chenonceau", "Chambord", "Cheverny", "Villandry"], correct: 1 },
  { q: "Quel gâteau breton fondant est fait de beurre, sucre et pâte feuilletée caramélisée ?", choices: ["Le far breton", "Le kouign-amann", "Le quatre-quarts", "La galette"], correct: 1 },
  { q: "Quel plat est traditionnellement associé à la Braderie de Lille ?", choices: ["La carbonnade", "Les moules-frites", "Le welsh", "Le potjevleesch"], correct: 1 },
  { q: "Grasse, capitale mondiale du parfum, se situe dans quel département ?", choices: ["Le Var", "Les Alpes-Maritimes", "Les Bouches-du-Rhône", "Le Vaucluse"], correct: 1 },
  { q: "Quel monument antique de Nîmes est un amphithéâtre romain toujours utilisé ?", choices: ["La Maison Carrée", "Les Arènes", "Le pont du Gard", "La tour Magne"], correct: 1 },
  { q: "Le kir est un apéritif associant vin blanc et quelle liqueur ?", choices: ["Liqueur de framboise", "Crème de cassis", "Liqueur de mûre", "Liqueur de pêche"], correct: 1 },
  { q: "Quelle célèbre statue offerte par la France se dresse à New York ?", choices: ["La statue de la Paix", "La statue de la Liberté", "La Victoire", "La Concorde"], correct: 1 },
  { q: "Quel fromage à croûte fleurie est originaire de Normandie ?", choices: ["Le camembert", "Le brie", "Le munster", "Le chaource"], correct: 0 },
  { q: "Quel col mythique des Alpes est régulièrement emprunté par le Tour de France ?", choices: ["Le col du Tourmalet", "Le col du Galibier", "Le col d'Aubisque", "Le col de la Faucille"], correct: 1 },
  { q: "Quelle cité médiévale fortifiée du Sud est classée au patrimoine mondial de l'UNESCO ?", choices: ["Carcassonne", "Aigues-Mortes", "Provins", "Rocamadour"], correct: 0 },
  { q: "Quel célèbre sculpteur français a réalisé « Le Penseur » et « Le Baiser » ?", choices: ["Camille Claudel", "Auguste Rodin", "Aristide Maillol", "Antoine Bourdelle"], correct: 1 },
  { q: "Quelle spécialité niçoise est une tarte à l'oignon garnie d'anchois et d'olives ?", choices: ["La socca", "La pissaladière", "Le pan-bagnat", "La ratatouille"], correct: 1 },
  { q: "Quelle région produit le célèbre pruneau d'Agen ?", choices: ["Le Périgord", "Le Lot-et-Garonne", "Le Gers", "La Dordogne"], correct: 1 },
  { q: "Quel est le nom du célèbre festival de théâtre qui se tient chaque été à Avignon ?", choices: ["Le Festival d'Avignon", "Les Chorégies", "Le Off", "Les Rencontres"], correct: 0 },
  { q: "Quelle boisson anisée est traditionnellement associée au Sud de la France ?", choices: ["Le pastis", "La chartreuse", "L'absinthe", "Le génépi"], correct: 0 },
  { q: "Quelle ville normande est célèbre pour sa tapisserie relatant la conquête de l'Angleterre ?", choices: ["Rouen", "Bayeux", "Caen", "Falaise"], correct: 1 },
  { q: "Quelle grande avenue parisienne relie la place de la Concorde à l'Arc de triomphe ?", choices: ["Le boulevard Haussmann", "Les Champs-Élysées", "La rue de Rivoli", "L'avenue Foch"], correct: 1 },
  { q: "Quelle spécialité lyonnaise est une boulette pochée à base de brochet ?", choices: ["Le tablier de sapeur", "La quenelle", "Le gras-double", "La cervelle de canut"], correct: 1 },
  { q: "Quel chef cuisinier est surnommé « le pape de la gastronomie lyonnaise » ?", choices: ["Alain Ducasse", "Paul Bocuse", "Joël Robuchon", "Bernard Loiseau"], correct: 1 },
  { q: "Quelle région française produit traditionnellement le sel de Guérande ?", choices: ["La Bretagne", "La Camargue", "La Charente", "La Vendée"], correct: 0 },
  { q: "Quel château Renaissance possède des jardins remarquables organisés en potagers décoratifs ?", choices: ["Chambord", "Villandry", "Chenonceau", "Blois"], correct: 1 },
  { q: "Quel est l'hymne national français ?", choices: ["Le Chant du départ", "La Marseillaise", "La Carmagnole", "Ça ira"], correct: 1 },
  { q: "Quel plat du Nord associe de la viande de bœuf mijotée à la bière ?", choices: ["Le hochepot", "La carbonnade flamande", "Le waterzooï", "Le potjevleesch"], correct: 1 },
  { q: "Quelle ville abrite le célèbre pont Saint-Bénézet, dit « pont d'Avignon » ?", choices: ["Arles", "Avignon", "Orange", "Tarascon"], correct: 1 },
  { q: "Quel massif volcanique d'Auvergne abrite le puy de Dôme ?", choices: ["Les monts du Cantal", "La chaîne des Puys", "Le Mézenc", "Le Sancy"], correct: 1 },
  { q: "Quel fromage franc-comtois à pâte pressée cuite est affiné plusieurs mois en meules ?", choices: ["Le morbier", "Le comté", "La cancoillotte", "Le mont-d'or"], correct: 1 },
  { q: "Quelle célèbre chanteuse française fut surnommée « la Môme » ?", choices: ["Barbara", "Édith Piaf", "Dalida", "Juliette Gréco"], correct: 1 },
  { q: "Quel plat provençal mijote plusieurs légumes d'été comme aubergines et courgettes ?", choices: ["La ratatouille", "La tapenade", "L'anchoïade", "La daube"], correct: 0 },
  { q: "Quelle grotte de Dordogne est célèbre pour ses peintures rupestres préhistoriques ?", choices: ["La grotte Chauvet", "La grotte de Lascaux", "La grotte Cosquer", "La grotte de Font-de-Gaume"], correct: 1 },
  { q: "Quelle confiserie dure est une spécialité de Carpentras ?", choices: ["Le berlingot", "Le calisson", "Le nougat", "La papaline"], correct: 0 },
  { q: "Quel département insulaire de la Méditerranée est surnommé « l'île de Beauté » ?", choices: ["Les Baléares", "La Corse", "La Sardaigne", "La Sicile"], correct: 1 },
  { q: "Quel célèbre architecte a conçu la pyramide de verre du Louvre ?", choices: ["Le Corbusier", "Ieoh Ming Pei", "Jean Nouvel", "Renzo Piano"], correct: 1 },
  { q: "Quelle spécialité du Périgord est un champignon souterrain très recherché ?", choices: ["Le cèpe", "La truffe", "La girolle", "La morille"], correct: 1 },
  { q: "Quelle célèbre dune de la côte atlantique est la plus haute d'Europe ?", choices: ["La dune du Pilat", "La pointe du Raz", "Le cap Blanc-Nez", "La flèche d'Arcachon"], correct: 0 },
  { q: "Quelle fête catholique attire chaque année de nombreux pèlerins à Lourdes ?", choices: ["L'Assomption", "La Toussaint", "La Pentecôte", "L'Ascension"], correct: 0 },
  { q: "Quel gâteau lorrain est une tarte salée aux œufs et aux lardons ?", choices: ["La flammekueche", "La quiche lorraine", "Le pâté lorrain", "La tourte"], correct: 1 },
  { q: "Quel célèbre couturier a lancé le « New Look » en 1947 ?", choices: ["Coco Chanel", "Christian Dior", "Hubert de Givenchy", "Cristóbal Balenciaga"], correct: 1 },
  { q: "Quelle région produit traditionnellement le cidre et le calvados ?", choices: ["La Bretagne", "La Normandie", "La Picardie", "Les Pays de la Loire"], correct: 1 },
  { q: "Quel palais royal proche de Paris est célèbre pour sa galerie des Glaces ?", choices: ["Le château de Fontainebleau", "Le château de Versailles", "Le château de Compiègne", "Le Grand Trianon"], correct: 1 },
  { q: "Quelle expression signifie « il pleut très fort » ?", choices: ["Il tombe des cordes", "Il fait un temps de chien", "Il gèle à pierre fendre", "Il fait la pluie et le beau temps"], correct: 0 },
  { q: "Quel biscuit en forme de coquillage est une spécialité de Commercy en Lorraine ?", choices: ["Le macaron", "La madeleine", "Le sablé", "La navette"], correct: 1 },
  { q: "Quelle ville du Sud-Ouest est réputée pour ses ferias et ses arènes ?", choices: ["Toulouse", "Bayonne", "Pau", "Agen"], correct: 1 },
];
