/* Quiz — banque ESPACE (astronomie, système solaire, conquête spatiale).
   Format compact : [question, BONNE RÉPONSE, leurre, leurre, leurre] (ordre des
   choix tiré au hasard à l'affichage). Du plus facile au plus difficile. */
const Q = [
  // — facile —
  ["Qui a été le premier homme à marcher sur la Lune ?", "Neil Armstrong", "Buzz Aldrin", "Youri Gagarine", "John Glenn"],
  ["Quelle étoile est la plus proche de la Terre ?", "Le Soleil", "Proxima du Centaure", "Sirius", "L'étoile polaire"],
  ["Quelle planète est la plus chaude du système solaire ?", "Vénus", "Mercure", "Mars", "Jupiter"],
  ["Qu'est-ce qu'une « étoile filante » ?", "Une poussière qui brûle dans l'atmosphère", "Une étoile qui meurt", "Une comète qui explose", "Un satellite en panne"],
  ["Quelle agence spatiale est américaine ?", "La NASA", "L'ESA", "Roscosmos", "La JAXA"],
  ["Comment s'appelle la station spatiale habitée en permanence depuis 2000 ?", "La Station spatiale internationale (ISS)", "Mir", "Skylab", "Saliout"],
  ["Quel astronaute français a séjourné dans l'ISS en 2016-2017 puis en 2021 ?", "Thomas Pesquet", "Jean-Loup Chrétien", "Patrick Baudry", "Philippe Perrin"],
  ["Quelle mission a déposé les premiers hommes sur la Lune ?", "Apollo 11", "Apollo 13", "Gemini 4", "Mercury 7"],
  ["Quelle planète tourne « couchée », presque sur le côté ?", "Uranus", "Neptune", "Saturne", "Mars"],
  ["Dans quelle constellation se trouve l'étoile polaire ?", "La Petite Ourse", "La Grande Ourse", "Orion", "Cassiopée"],
  ["Quelle planète porte le nom du dieu romain de la mer ?", "Neptune", "Uranus", "Mars", "Saturne"],
  ["Comment s'appelle la fusée européenne lancée depuis la Guyane ?", "Ariane", "Falcon", "Saturn V", "Longue Marche"],
  ["Où se trouve le centre spatial d'où décollent les fusées européennes ?", "À Kourou", "À Cayenne", "À Toulouse", "À Saint-Laurent-du-Maroni"],
  ["Comment appelle-t-on l'anneau de roches situé entre Mars et Jupiter ?", "La ceinture d'astéroïdes", "La ceinture de Kuiper", "Le nuage d'Oort", "Les anneaux de Mars"],
  // — moyen —
  ["Quel est le plus grand satellite de Saturne ?", "Titan", "Encelade", "Europe", "Ganymède"],
  ["Quel est le plus grand satellite naturel du système solaire ?", "Ganymède", "Titan", "Callisto", "La Lune"],
  ["Comment s'appellent les deux petites lunes de Mars ?", "Phobos et Déimos", "Io et Europe", "Titan et Rhéa", "Castor et Pollux"],
  ["Quelle comète célèbre revient environ tous les 76 ans ?", "La comète de Halley", "Hale-Bopp", "Shoemaker-Levy 9", "Tchouri"],
  ["Quel savant a découvert les satellites de Jupiter avec sa lunette en 1610 ?", "Galilée", "Kepler", "Copernic", "Newton"],
  ["Quelle grande galaxie voisine se dirige vers la Voie lactée ?", "Andromède", "Le Sombrero", "Le Tourbillon", "Le Grand Nuage de Magellan"],
  ["Quelle unité correspond à la distance parcourue par la lumière en un an ?", "L'année-lumière", "Le parsec", "L'unité astronomique", "Le mile nautique"],
  ["À quoi correspond une unité astronomique (UA) ?", "La distance moyenne Terre-Soleil", "La distance Terre-Lune", "Le diamètre de la Voie lactée", "Une année-lumière"],
  ["Quelle sonde est devenue en 2012 le premier objet humain à atteindre l'espace interstellaire ?", "Voyager 1", "Pioneer 10", "New Horizons", "Voyager 2"],
  ["Quelle sonde a survolé Pluton en 2015 ?", "New Horizons", "Cassini", "Juno", "Rosetta"],
  ["Quel rover de la NASA s'est posé sur Mars en 2021, accompagné d'un petit hélicoptère ?", "Perseverance", "Curiosity", "Spirit", "Opportunity"],
  ["Quelle mission Apollo a dû renoncer à la Lune après l'explosion d'un réservoir ?", "Apollo 13", "Apollo 11", "Apollo 8", "Apollo 17"],
  ["Qui est la première Française à être allée dans l'espace ?", "Claudie Haigneré", "Valentina Terechkova", "Sally Ride", "Marie Curie"],
  ["Pourquoi voit-on toujours la même face de la Lune ?", "Elle tourne sur elle-même aussi vite qu'autour de la Terre", "Elle ne tourne pas sur elle-même", "La Terre cache l'autre face", "L'autre face ne reflète pas la lumière"],
  ["Quelle est l'étoile la plus brillante du ciel nocturne ?", "Sirius", "Bételgeuse", "Véga", "L'étoile polaire"],
  ["Dans quelle constellation se trouvent les étoiles Bételgeuse et Rigel ?", "Orion", "Le Taureau", "La Grande Ourse", "Le Scorpion"],
  ["Quel groupe d'étoiles de la Grande Ourse ressemble à une casserole ?", "Le Grand Chariot", "Les Pléiades", "La Croix du Sud", "Le Triangle d'été"],
  ["Quel amas d'étoiles est aussi appelé « les Sept Sœurs » ?", "Les Pléiades", "Les Hyades", "Le Grand Chariot", "La Ceinture d'Orion"],
  ["Sur quelle planète se trouve la Grande Tache rouge, une tempête géante ?", "Jupiter", "Saturne", "Neptune", "Mars"],
  ["Quelle lune de Saturne projette des geysers d'eau depuis son pôle sud ?", "Encelade", "Titan", "Mimas", "Japet"],
  ["Quel satellite de Jupiter est le corps le plus volcanique du système solaire ?", "Io", "Europe", "Callisto", "Ganymède"],
  ["Quel volcan martien est la plus haute montagne connue du système solaire ?", "Olympus Mons", "L'Everest", "Maxwell Montes", "Le Mauna Kea"],
  ["Quelle est la température approximative de la surface du Soleil ?", "Environ 5 500 °C", "Environ 500 °C", "Environ 55 000 °C", "Environ 5,5 millions °C"],
  ["De quel élément le Soleil est-il principalement composé ?", "D'hydrogène", "De fer", "D'oxygène", "De carbone"],
  ["En quelle année des humains ont-ils fait le tour de la Lune pour la première fois (Apollo 8) ?", "1968", "1966", "1969", "1970"],
  ["Combien d'astronautes ont marché sur la Lune ?", "12", "2", "6", "24"],
  ["Comment s'appelle le programme de la NASA destiné à ramener des humains sur la Lune ?", "Artemis", "Apollo", "Gemini", "Mercury"],
  ["Quel pays a posé le premier engin sur la face cachée de la Lune, en 2019 ?", "La Chine", "Les États-Unis", "La Russie", "L'Inde"],
  ["Quel pays a réussi en 2023 le premier alunissage près du pôle Sud lunaire ?", "L'Inde", "La Chine", "Le Japon", "La Russie"],
  ["Comment appelle-t-on le point d'une orbite autour de la Terre le plus éloigné de celle-ci ?", "L'apogée", "Le périgée", "Le zénith", "Le nadir"],
  // — difficile —
  ["Quelle est l'étoile la plus proche du Soleil ?", "Proxima du Centaure", "Sirius", "Alpha du Centaure A", "L'étoile de Barnard"],
  ["À combien d'années-lumière environ se trouve Proxima du Centaure ?", "4,2", "0,4", "42", "420"],
  ["Sur quelle planète un jour dure-t-il plus longtemps qu'une année ?", "Vénus", "Mercure", "Mars", "Neptune"],
  ["Quelle planète compte le plus de lunes connues en 2025 ?", "Saturne", "Jupiter", "Uranus", "Neptune"],
  ["Quel astronome a montré que les planètes décrivent des ellipses autour du Soleil ?", "Johannes Kepler", "Tycho Brahe", "Copernic", "Galilée"],
  ["Quel astronome a découvert Uranus en 1781 ?", "William Herschel", "Edmond Halley", "Urbain Le Verrier", "Galilée"],
  ["Quelle planète a été trouvée par le calcul (Le Verrier, 1846) avant d'être observée ?", "Neptune", "Uranus", "Pluton", "Saturne"],
  ["Comment s'appelle la frontière d'un trou noir au-delà de laquelle rien ne ressort ?", "L'horizon des événements", "La singularité", "Le disque d'accrétion", "La sphère de Hill"],
  ["Quel âge a environ l'Univers ?", "13,8 milliards d'années", "4,6 milliards d'années", "100 millions d'années", "1 000 milliards d'années"],
  ["Quel âge a environ le système solaire ?", "4,6 milliards d'années", "13,8 milliards d'années", "460 millions d'années", "46 milliards d'années"],
  ["Comment appelle-t-on une étoile à neutrons qui émet des pulsations radio régulières ?", "Un pulsar", "Un quasar", "Une naine blanche", "Une géante bleue"],
  ["Quelle sonde européenne a étudié la comète Tchouri de 2014 à 2016 ?", "Rosetta", "Giotto", "Huygens", "Juice"],
  ["Quel atterrisseur européen s'est posé sur Titan en 2005 ?", "Huygens", "Cassini", "Philae", "Galileo"],
  ["Quelle sonde de la NASA est en orbite autour de Jupiter depuis 2016 ?", "Juno", "Galileo", "Cassini", "Dawn"],
  ["Quelle mission européenne lancée en 2023 part étudier les lunes glacées de Jupiter ?", "JUICE", "Rosetta", "Mars Express", "BepiColombo"],
  ["Comment s'appelait le module lunaire d'Apollo 11 ?", "Eagle", "Columbia", "Odyssey", "Falcon"],
  ["Quel astronaute d'Apollo 11 est resté en orbite pendant que ses collègues marchaient sur la Lune ?", "Michael Collins", "Jim Lovell", "John Young", "Gene Cernan"],
  ["Qui est le dernier homme à avoir marché sur la Lune, en 1972 ?", "Eugene Cernan", "Buzz Aldrin", "Alan Bean", "John Glenn"],
  ["Quelle planète naine est le plus grand objet de la ceinture d'astéroïdes ?", "Cérès", "Vesta", "Pallas", "Éris"],
  ["Quelle est la plus grande planète naine connue par son diamètre ?", "Pluton", "Éris", "Cérès", "Makemake"],
  ["Combien de temps met Neptune pour faire le tour du Soleil (environ) ?", "165 ans", "12 ans", "29 ans", "84 ans"],
  ["Quelle sonde japonaise a rapporté sur Terre les premiers grains d'un astéroïde, en 2010 ?", "Hayabusa", "OSIRIS-REx", "Rosetta", "Stardust"],
  ["Comment appelle-t-on la vitesse minimale pour échapper à l'attraction d'un astre ?", "La vitesse de libération", "La vitesse de satellisation", "La vitesse orbitale", "La vitesse limite"],
  ["Quelle est la vitesse de libération à la surface de la Terre (environ) ?", "11,2 km/s", "1,1 km/s", "112 km/s", "300 km/s"],
];
export const Q_ESPACE = Q.map(([q, ...choices]) => ({ q, choices, correct: 0 }));
