/* Quiz — banque GÉOGRAPHIE (capitales, pays, fleuves, reliefs, drapeaux, France).
   correct = index de la bonne réponse (0-based). Réponses vérifiées. */
export const Q_GEO = [
  { q: "Quelle est la capitale de l'Espagne ?", choices: ["Barcelone", "Madrid", "Séville", "Valence"], correct: 1 },
  { q: "Quelle est la capitale du Portugal ?", choices: ["Porto", "Faro", "Lisbonne", "Braga"], correct: 2 },
  { q: "Quelle est la capitale de l'Allemagne ?", choices: ["Munich", "Francfort", "Hambourg", "Berlin"], correct: 3 },
  { q: "Quelle est la capitale de l'Autriche ?", choices: ["Vienne", "Salzbourg", "Innsbruck", "Graz"], correct: 0 },
  { q: "Quelle est la capitale de la Suisse ?", choices: ["Zurich", "Berne", "Genève", "Lausanne"], correct: 1 },
  { q: "Quelle est la capitale de la Belgique ?", choices: ["Anvers", "Liège", "Bruxelles", "Gand"], correct: 2 },
  { q: "Quelle est la capitale officielle des Pays-Bas ?", choices: ["Rotterdam", "La Haye", "Utrecht", "Amsterdam"], correct: 3 },
  { q: "Quelle est la capitale du Danemark ?", choices: ["Copenhague", "Aarhus", "Odense", "Aalborg"], correct: 0 },
  { q: "Quelle est la capitale de la Suède ?", choices: ["Göteborg", "Stockholm", "Malmö", "Uppsala"], correct: 1 },
  { q: "Quelle est la capitale de la Finlande ?", choices: ["Tampere", "Turku", "Helsinki", "Oulu"], correct: 2 },
  { q: "Quelle est la capitale de l'Islande ?", choices: ["Akureyri", "Keflavik", "Selfoss", "Reykjavik"], correct: 3 },
  { q: "Quelle est la capitale de l'Irlande ?", choices: ["Dublin", "Cork", "Galway", "Belfast"], correct: 0 },
  { q: "Quelle est la capitale de la Pologne ?", choices: ["Cracovie", "Varsovie", "Gdansk", "Wroclaw"], correct: 1 },
  { q: "Quelle est la capitale de la République tchèque ?", choices: ["Brno", "Ostrava", "Prague", "Pilsen"], correct: 2 },
  { q: "Quelle est la capitale de la Slovaquie ?", choices: ["Kosice", "Zilina", "Nitra", "Bratislava"], correct: 3 },
  { q: "Quelle est la capitale de la Hongrie ?", choices: ["Budapest", "Debrecen", "Szeged", "Miskolc"], correct: 0 },
  { q: "Quelle est la capitale de la Roumanie ?", choices: ["Cluj", "Bucarest", "Timisoara", "Iasi"], correct: 1 },
  { q: "Quelle est la capitale de la Bulgarie ?", choices: ["Plovdiv", "Varna", "Sofia", "Burgas"], correct: 2 },
  { q: "Quelle est la capitale de la Grèce ?", choices: ["Thessalonique", "Patras", "Le Pirée", "Athènes"], correct: 3 },
  { q: "Quelle est la capitale de la Turquie ?", choices: ["Ankara", "Istanbul", "Izmir", "Antalya"], correct: 0 },
  { q: "Quelle est la capitale de la Russie ?", choices: ["Saint-Pétersbourg", "Moscou", "Kazan", "Novossibirsk"], correct: 1 },
  { q: "Quelle est la capitale de l'Ukraine ?", choices: ["Odessa", "Lviv", "Kiev", "Kharkiv"], correct: 2 },
  { q: "Quelle est la capitale de la Croatie ?", choices: ["Split", "Dubrovnik", "Rijeka", "Zagreb"], correct: 3 },
  { q: "Quelle est la capitale de la Serbie ?", choices: ["Belgrade", "Novi Sad", "Nis", "Kragujevac"], correct: 0 },
  { q: "Quelle est la capitale de l'Estonie ?", choices: ["Riga", "Tallinn", "Vilnius", "Tartu"], correct: 1 },
  { q: "Quelle est la capitale de la Lettonie ?", choices: ["Tallinn", "Vilnius", "Riga", "Kaunas"], correct: 2 },
  { q: "Quelle est la capitale de la Lituanie ?", choices: ["Riga", "Tallinn", "Kaunas", "Vilnius"], correct: 3 },
  { q: "Quelle est la capitale du Maroc ?", choices: ["Rabat", "Casablanca", "Marrakech", "Fès"], correct: 0 },
  { q: "Quelle est la capitale de l'Algérie ?", choices: ["Oran", "Alger", "Constantine", "Annaba"], correct: 1 },
  { q: "Quelle est la capitale de la Tunisie ?", choices: ["Sfax", "Sousse", "Tunis", "Bizerte"], correct: 2 },
  { q: "Quelle est la capitale du Sénégal ?", choices: ["Saint-Louis", "Thiès", "Ziguinchor", "Dakar"], correct: 3 },
  { q: "Quelle est la capitale officielle de la Côte d'Ivoire ?", choices: ["Yamoussoukro", "Abidjan", "Bouaké", "San-Pédro"], correct: 0 },
  { q: "Quelle est la capitale du Nigeria ?", choices: ["Lagos", "Abuja", "Kano", "Ibadan"], correct: 1 },
  { q: "Quelle est la capitale du Kenya ?", choices: ["Mombasa", "Kisumu", "Nairobi", "Nakuru"], correct: 2 },
  { q: "Quelle est la capitale de l'Éthiopie ?", choices: ["Djibouti", "Asmara", "Gondar", "Addis-Abeba"], correct: 3 },
  { q: "Quelle est la capitale de Madagascar ?", choices: ["Antananarivo", "Toamasina", "Mahajanga", "Antsirabe"], correct: 0 },
  { q: "Quelle est la capitale du Cameroun ?", choices: ["Douala", "Yaoundé", "Garoua", "Bafoussam"], correct: 1 },
  { q: "Quelle est la capitale de la République démocratique du Congo ?", choices: ["Lubumbashi", "Goma", "Kinshasa", "Kisangani"], correct: 2 },
  { q: "Quelle est la capitale du Mali ?", choices: ["Tombouctou", "Gao", "Mopti", "Bamako"], correct: 3 },
  { q: "Quelle est la capitale des États-Unis ?", choices: ["Washington", "New York", "Los Angeles", "Chicago"], correct: 0 },
  { q: "Quelle est la capitale du Mexique ?", choices: ["Guadalajara", "Mexico", "Monterrey", "Cancún"], correct: 1 },
  { q: "Quelle est la capitale de Cuba ?", choices: ["Santiago de Cuba", "Varadero", "La Havane", "Trinidad"], correct: 2 },
  { q: "Quelle est la capitale de la Colombie ?", choices: ["Medellín", "Cali", "Carthagène", "Bogota"], correct: 3 },
  { q: "Quelle est la capitale du Venezuela ?", choices: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto"], correct: 0 },
  { q: "Quelle est la capitale du Pérou ?", choices: ["Cuzco", "Lima", "Arequipa", "Trujillo"], correct: 1 },
  { q: "Quelle est la capitale de l'Équateur ?", choices: ["Guayaquil", "Cuenca", "Quito", "Ambato"], correct: 2 },
  { q: "Quelle est la capitale du Chili ?", choices: ["Valparaiso", "Concepción", "Antofagasta", "Santiago"], correct: 3 },
  { q: "Quelle est la capitale de l'Argentine ?", choices: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"], correct: 0 },
  { q: "Quelle est la capitale de l'Uruguay ?", choices: ["Punta del Este", "Montevideo", "Salto", "Colonia"], correct: 1 },
  { q: "Quelle est la capitale du Brésil ?", choices: ["Rio de Janeiro", "São Paulo", "Brasilia", "Salvador"], correct: 2 },
  { q: "Quelle est la capitale de la Chine ?", choices: ["Shanghai", "Hong Kong", "Canton", "Pékin"], correct: 3 },
  { q: "Quelle est la capitale du Japon ?", choices: ["Tokyo", "Osaka", "Kyoto", "Yokohama"], correct: 0 },
  { q: "Quelle est la capitale de la Corée du Sud ?", choices: ["Busan", "Séoul", "Incheon", "Daegu"], correct: 1 },
  { q: "Quelle est la capitale de la Corée du Nord ?", choices: ["Kaesong", "Wonsan", "Pyongyang", "Hamhung"], correct: 2 },
  { q: "Quelle est la capitale de la Mongolie ?", choices: ["Erdenet", "Darkhan", "Khovd", "Oulan-Bator"], correct: 3 },
  { q: "Quelle est la capitale de l'Inde ?", choices: ["New Delhi", "Bombay", "Calcutta", "Madras"], correct: 0 },
  { q: "Quelle est la capitale du Pakistan ?", choices: ["Karachi", "Islamabad", "Lahore", "Peshawar"], correct: 1 },
  { q: "Quelle est la capitale du Népal ?", choices: ["Pokhara", "Lalitpur", "Katmandou", "Biratnagar"], correct: 2 },
  { q: "Quelle est la capitale du Vietnam ?", choices: ["Hô Chi Minh-Ville", "Da Nang", "Hué", "Hanoï"], correct: 3 },
  { q: "Quelle est la capitale du Cambodge ?", choices: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville"], correct: 0 },
  { q: "Quelle est la capitale de l'Indonésie ?", choices: ["Bali", "Jakarta", "Surabaya", "Bandung"], correct: 1 },
  { q: "Quelle est la capitale des Philippines ?", choices: ["Cebu", "Davao", "Manille", "Quezon"], correct: 2 },
  { q: "Quelle est la capitale de la Malaisie ?", choices: ["Penang", "Johor Bahru", "Malacca", "Kuala Lumpur"], correct: 3 },
  { q: "Quelle est la capitale de l'Iran ?", choices: ["Téhéran", "Ispahan", "Chiraz", "Tabriz"], correct: 0 },
  { q: "Quelle est la capitale de l'Irak ?", choices: ["Bassorah", "Bagdad", "Mossoul", "Erbil"], correct: 1 },
  { q: "Quelle est la capitale du Liban ?", choices: ["Tripoli", "Saïda", "Beyrouth", "Byblos"], correct: 2 },
  { q: "Quelle est la capitale de la Jordanie ?", choices: ["Pétra", "Aqaba", "Irbid", "Amman"], correct: 3 },
  { q: "Quelle est la capitale de l'Arabie saoudite ?", choices: ["Riyad", "Djeddah", "La Mecque", "Médine"], correct: 0 },
  { q: "Quelle est la capitale des Émirats arabes unis ?", choices: ["Dubaï", "Abou Dabi", "Charjah", "Ajman"], correct: 1 },
  { q: "Quelle est la capitale du Qatar ?", choices: ["Al Rayyan", "Al Khor", "Doha", "Lusail"], correct: 2 },
  { q: "Quelle est la capitale de la Nouvelle-Zélande ?", choices: ["Auckland", "Christchurch", "Hamilton", "Wellington"], correct: 3 },
  { q: "Quelle est la capitale de la Géorgie (pays) ?", choices: ["Tbilissi", "Batoumi", "Koutaïssi", "Erevan"], correct: 0 },
  { q: "Quelle est la capitale de l'Arménie ?", choices: ["Bakou", "Erevan", "Tbilissi", "Gyumri"], correct: 1 },
  { q: "Quelle est la capitale de la Norvège ?", choices: ["Bergen", "Trondheim", "Oslo", "Stavanger"], correct: 2 },
  { q: "Quelle est la capitale de la Libye ?", choices: ["Benghazi", "Misrata", "Syrte", "Tripoli"], correct: 3 },
  { q: "Quel pays a dépassé la Chine comme pays le plus peuplé du monde en 2023 ?", choices: ["L'Inde", "Les États-Unis", "L'Indonésie", "Le Nigeria"], correct: 0 },
  { q: "Quel est le plus grand pays du monde par sa superficie ?", choices: ["Le Canada", "La Russie", "La Chine", "Les États-Unis"], correct: 1 },
  { q: "Quel est le deuxième plus grand pays du monde par sa superficie ?", choices: ["La Chine", "Les États-Unis", "Le Canada", "Le Brésil"], correct: 2 },
  { q: "Grâce à ses territoires d'outre-mer, quel pays compte le plus de fuseaux horaires ?", choices: ["La Russie", "Les États-Unis", "Le Royaume-Uni", "La France"], correct: 3 },
  { q: "Lequel de ces pays n'a aucun accès à la mer ?", choices: ["La Suisse", "Le Portugal", "La Croatie", "Le Vietnam"], correct: 0 },
  { q: "Quel fleuve traverse Londres ?", choices: ["La Severn", "La Tamise", "La Mersey", "L'Avon"], correct: 1 },
  { q: "Quel fleuve traverse Rome ?", choices: ["Le Pô", "L'Arno", "Le Tibre", "L'Adige"], correct: 2 },
  { q: "Quel fleuve européen traverse le plus de capitales (Vienne, Bratislava, Budapest, Belgrade) ?", choices: ["Le Rhin", "L'Elbe", "La Volga", "Le Danube"], correct: 3 },
  { q: "Quel est le plus long fleuve entièrement situé en France ?", choices: ["La Loire", "La Seine", "Le Rhône", "La Garonne"], correct: 0 },
  { q: "Quel est le plus long fleuve d'Europe ?", choices: ["Le Danube", "La Volga", "Le Rhin", "Le Dniepr"], correct: 1 },
  { q: "Quel fleuve a le plus grand débit du monde ?", choices: ["Le Nil", "Le Congo", "L'Amazone", "Le Yangzi"], correct: 2 },
  { q: "Sur quel fleuve se trouvent les chutes Victoria ?", choices: ["Le Congo", "Le Niger", "Le Nil", "Le Zambèze"], correct: 3 },
  { q: "Quel est le lac le plus profond du monde ?", choices: ["Le lac Baïkal", "Le lac Tanganyika", "Le lac Supérieur", "Le lac Victoria"], correct: 0 },
  { q: "Quelle est la plus grande étendue d'eau fermée du monde, appelée « mer » ?", choices: ["La mer d'Aral", "La mer Caspienne", "La mer Morte", "Le lac Victoria"], correct: 1 },
  { q: "Quel lac d'altitude est partagé entre le Pérou et la Bolivie ?", choices: ["Le lac Titien", "Le lac Poopó", "Le lac Titicaca", "Le lac Atitlán"], correct: 2 },
  { q: "Quel point du globe est le plus bas à l'air libre (environ -430 m) ?", choices: ["La vallée de la Mort", "Le lac Assal", "La dépression de Qattara", "La mer Morte"], correct: 3 },
  { q: "Quel canal relie la Méditerranée à la mer Rouge ?", choices: ["Le canal de Suez", "Le canal de Panama", "Le canal de Corinthe", "Le canal de Kiel"], correct: 0 },
  { q: "Quel canal relie l'Atlantique au Pacifique en Amérique centrale ?", choices: ["Le canal de Suez", "Le canal de Panama", "Le canal du Nicaragua", "Le canal de Kiel"], correct: 1 },
  { q: "Quel détroit sépare l'Europe de l'Asie à Istanbul ?", choices: ["Gibraltar", "Les Dardanelles", "Le Bosphore", "Ormuz"], correct: 2 },
  { q: "Quel est le deuxième plus haut sommet du monde ?", choices: ["Le Kangchenjunga", "Le Lhotse", "Le Makalu", "Le K2"], correct: 3 },
  { q: "Quel est le plus haut sommet d'Afrique ?", choices: ["Le Kilimandjaro", "Le mont Kenya", "Le Ruwenzori", "Le Ras Dashan"], correct: 0 },
  { q: "Quel est le plus haut sommet d'Amérique du Sud ?", choices: ["Le Huascarán", "L'Aconcagua", "Le Chimborazo", "L'Ojos del Salado"], correct: 1 },
  { q: "Quelle est l'altitude approximative du Mont Blanc ?", choices: ["3 810 m", "4 300 m", "4 810 m", "5 210 m"], correct: 2 },
  { q: "Quel volcan domine la baie de Naples ?", choices: ["L'Etna", "Le Stromboli", "Le Vulcano", "Le Vésuve"], correct: 3 },
  { q: "Sur quelle île italienne se trouve l'Etna ?", choices: ["La Sicile", "La Sardaigne", "Capri", "Ischia"], correct: 0 },
  { q: "Quel volcan sacré est le point culminant du Japon ?", choices: ["Le Sakurajima", "Le mont Fuji", "L'Aso", "L'Ontake"], correct: 1 },
  { q: "Quel désert est considéré comme le plus aride du monde ?", choices: ["Le Sahara", "Le Gobi", "L'Atacama", "Le Kalahari"], correct: 2 },
  { q: "Dans quels pays s'étend principalement le désert de Gobi ?", choices: ["Iran et Irak", "Kazakhstan et Russie", "Inde et Pakistan", "Chine et Mongolie"], correct: 3 },
  { q: "Quelle est la plus grande île de la mer Méditerranée ?", choices: ["La Sicile", "La Sardaigne", "Chypre", "La Corse"], correct: 0 },
  { q: "Quelle est la plus grande île du Japon ?", choices: ["Hokkaido", "Honshu", "Kyushu", "Shikoku"], correct: 1 },
  { q: "À quel pays appartient l'île de Tasmanie ?", choices: ["La Nouvelle-Zélande", "L'Indonésie", "L'Australie", "Le Royaume-Uni"], correct: 2 },
  { q: "À quel pays appartiennent les îles Canaries ?", choices: ["Le Portugal", "Le Maroc", "L'Italie", "L'Espagne"], correct: 3 },
  { q: "À quel pays appartient l'archipel de Madère ?", choices: ["Le Portugal", "L'Espagne", "La France", "L'Italie"], correct: 0 },
  { q: "À quel pays appartient le Groenland ?", choices: ["Le Canada", "Le Danemark", "La Norvège", "L'Islande"], correct: 1 },
  { q: "Quel État américain est un archipel du Pacifique ?", choices: ["La Floride", "L'Alaska", "Hawaï", "La Californie"], correct: 2 },
  { q: "Quelle île française est surnommée « l'île de Beauté » ?", choices: ["La Réunion", "Belle-Île", "Oléron", "La Corse"], correct: 3 },
  { q: "Quel est le seul drapeau national qui ne soit pas rectangulaire (ni carré) ?", choices: ["Celui du Népal", "Celui de la Suisse", "Celui du Vatican", "Celui du Qatar"], correct: 0 },
  { q: "Quels drapeaux nationaux sont carrés ?", choices: ["Japon et Corée", "Suisse et Vatican", "Monaco et Andorre", "Malte et Chypre"], correct: 1 },
  { q: "Que représente le drapeau du Japon ?", choices: ["Une fleur de cerisier", "Une vague", "Un disque solaire rouge", "Un dragon"], correct: 2 },
  { q: "Quelle feuille figure sur le drapeau du Canada ?", choices: ["Une feuille de chêne", "Une feuille de vigne", "Une feuille de bouleau", "Une feuille d'érable"], correct: 3 },
  { q: "Combien d'étoiles compte le drapeau des États-Unis ?", choices: ["50", "48", "51", "52"], correct: 0 },
  { q: "Combien de bandes compte le drapeau des États-Unis ?", choices: ["15", "13", "12", "10"], correct: 1 },
  { q: "Quelles sont les couleurs du drapeau allemand, de haut en bas ?", choices: ["Rouge, noir, or", "Or, rouge, noir", "Noir, rouge, or", "Noir, or, rouge"], correct: 2 },
  { q: "Quelles sont les couleurs du drapeau italien ?", choices: ["Bleu, blanc, rouge", "Vert, jaune, rouge", "Rouge, blanc, vert horizontal", "Vert, blanc, rouge"], correct: 3 },
  { q: "Quelle devise figure sur le drapeau du Brésil ?", choices: ["Ordem e Progresso", "Liberdade", "Deus e o Brasil", "Uniao e Forca"], correct: 0 },
  { q: "Quelle est la monnaie du Royaume-Uni ?", choices: ["L'euro", "La livre sterling", "Le franc", "La couronne"], correct: 1 },
  { q: "Quelle est la monnaie de la Suisse ?", choices: ["L'euro", "La couronne suisse", "Le franc suisse", "Le mark"], correct: 2 },
  { q: "Quelle est la monnaie de la Russie ?", choices: ["Le zloty", "La hryvnia", "Le lev", "Le rouble"], correct: 3 },
  { q: "Quelle est la monnaie de l'Inde ?", choices: ["La roupie", "Le baht", "Le ringgit", "Le taka"], correct: 0 },
  { q: "Quelle est la monnaie du Brésil ?", choices: ["Le peso", "Le real", "Le bolivar", "Le sol"], correct: 1 },
  { q: "Quelle est la monnaie du Mexique ?", choices: ["Le real", "Le dollar mexicain", "Le peso", "Le colon"], correct: 2 },
  { q: "Quelle est la monnaie de la Pologne ?", choices: ["Le forint", "La couronne", "Le leu", "Le zloty"], correct: 3 },
  { q: "Quelle mer borde la Côte d'Azur ?", choices: ["La Méditerranée", "L'Adriatique", "La mer Tyrrhénienne", "La mer Égée"], correct: 0 },
  { q: "Quelle mer sépare l'Italie des Balkans ?", choices: ["La mer Ionienne", "La mer Adriatique", "La mer Égée", "La mer Noire"], correct: 1 },
  { q: "Quel océan borde la côte ouest de la France ?", choices: ["Le Pacifique", "L'océan Indien", "L'Atlantique", "L'Arctique"], correct: 2 },
  { q: "Quelle mer borde à la fois la Turquie, l'Ukraine et la Roumanie ?", choices: ["La mer Caspienne", "La mer Égée", "La mer de Marmara", "La mer Noire"], correct: 3 },
  { q: "Combien la France compte-t-elle de régions métropolitaines depuis 2016 ?", choices: ["13", "22", "16", "10"], correct: 0 },
  { q: "Combien d'arrondissements compte Paris ?", choices: ["18", "20", "22", "16"], correct: 1 },
  { q: "Quel est le plus grand département français par sa superficie ?", choices: ["La Gironde", "Les Landes", "La Guyane", "La Dordogne"], correct: 2 },
  { q: "Quelle ville française est surnommée « la Ville rose » ?", choices: ["Albi", "Montauban", "Perpignan", "Toulouse"], correct: 3 },
  { q: "Quelle est la plus ancienne grande ville de France, fondée par les Grecs ?", choices: ["Marseille", "Lyon", "Bordeaux", "Nice"], correct: 0 },
  { q: "Quelle ville était la capitale des Gaules à l'époque romaine ?", choices: ["Paris", "Lyon", "Reims", "Arles"], correct: 1 },
  { q: "Dans quelle région se trouve le Mont-Saint-Michel ?", choices: ["La Bretagne", "Les Pays de la Loire", "La Normandie", "Les Hauts-de-France"], correct: 2 },
  { q: "Quel roi a fait construire le château de Chambord ?", choices: ["Louis XIV", "Henri IV", "Louis XI", "François Ier"], correct: 3 },
  { q: "Où siège le Parlement européen ?", choices: ["Strasbourg", "Bruxelles", "Luxembourg", "Francfort"], correct: 0 },
  { q: "Dans quelle ville se trouve la plus haute dune d'Europe ?", choices: ["Biscarrosse", "La Teste-de-Buch (dune du Pilat)", "Lacanau", "Hossegor"], correct: 1 },
  { q: "Quel célèbre aqueduc romain se trouve près de Nîmes ?", choices: ["Le pont d'Avignon", "Le pont Valentré", "Le pont du Gard", "Le pont Neuf"], correct: 2 },
  { q: "Dans quel département se trouvent les grottes de Lascaux ?", choices: ["Le Lot", "L'Ardèche", "L'Aveyron", "La Dordogne"], correct: 3 },
  { q: "Quel est le plus haut pont routier de France, inauguré en 2004 ?", choices: ["Le viaduc de Millau", "Le pont de Normandie", "Le pont de Tancarville", "Le viaduc de Garabit"], correct: 0 },
  { q: "Avec quel pays la France partage-t-elle sa plus longue frontière terrestre (via la Guyane) ?", choices: ["L'Espagne", "Le Brésil", "L'Allemagne", "La Belgique"], correct: 1 },
  { q: "Combien la France compte-t-elle de départements et régions d'outre-mer (DROM) ?", choices: ["3", "4", "5", "7"], correct: 2 },
  { q: "Quelle principauté est enclavée entre la France et l'Espagne, dans les Pyrénées ?", choices: ["Monaco", "Le Liechtenstein", "Saint-Marin", "Andorre"], correct: 3 },
  { q: "Quel micro-État est entièrement enclavé dans la ville de Rome ?", choices: ["Le Vatican", "Saint-Marin", "Malte", "Monaco"], correct: 0 },
  { q: "Entre quels pays est enclavé le Liechtenstein ?", choices: ["France et Italie", "Suisse et Autriche", "Allemagne et Autriche", "Suisse et Italie"], correct: 1 },
  { q: "En quelle année le tunnel sous la Manche a-t-il été inauguré ?", choices: ["1984", "1989", "1994", "1999"], correct: 2 },
  { q: "Quelle ligne TGV a été la première mise en service, en 1981 ?", choices: ["Paris-Lille", "Paris-Bordeaux", "Paris-Strasbourg", "Paris-Lyon"], correct: 3 },
  { q: "Quelle chaîne de montagnes sépare la France de l'Espagne ?", choices: ["Les Pyrénées", "Les Alpes", "Le Jura", "Les Vosges"], correct: 0 },
  { q: "Quelle chaîne de montagnes sépare la France de l'Italie ?", choices: ["Le Massif central", "Les Alpes", "Les Pyrénées", "Les Cévennes"], correct: 1 },
  { q: "Dans quel massif se trouve le puy de Dôme ?", choices: ["Les Vosges", "Le Jura", "Le Massif central", "Les Alpes"], correct: 2 },
  { q: "Quel fleuve se jette dans la Méditerranée près de la Camargue ?", choices: ["La Garonne", "La Loire", "La Seine", "Le Rhône"], correct: 3 },
  { q: "Dans quel océan se trouvent les Maldives ?", choices: ["L'océan Indien", "Le Pacifique", "L'Atlantique", "L'Arctique"], correct: 0 },
  { q: "Dans quel pays se trouve Bora-Bora ?", choices: ["Les Fidji", "La France (Polynésie française)", "Les États-Unis", "La Nouvelle-Zélande"], correct: 1 },
  { q: "Quelle est la capitale de la Polynésie française ?", choices: ["Nouméa", "Bora-Bora", "Papeete", "Moorea"], correct: 2 },
  { q: "Nouméa est la capitale de quel territoire français ?", choices: ["La Polynésie française", "Wallis-et-Futuna", "Mayotte", "La Nouvelle-Calédonie"], correct: 3 },
  { q: "Quelle ville sainte est commune aux trois grandes religions monothéistes ?", choices: ["Jérusalem", "La Mecque", "Rome", "Istanbul"], correct: 0 },
  { q: "Dans quel pays se trouve la cité antique de Pétra ?", choices: ["L'Égypte", "La Jordanie", "La Syrie", "Le Liban"], correct: 1 },
  { q: "Dans quel pays se trouve le temple d'Angkor Vat ?", choices: ["La Thaïlande", "Le Vietnam", "Le Cambodge", "Le Laos"], correct: 2 },
  { q: "Dans quel pays se trouve le Taj Mahal ?", choices: ["Le Pakistan", "Le Bangladesh", "Le Népal", "L'Inde"], correct: 3 },
  { q: "Dans quel pays se trouvent les statues moaï ?", choices: ["Le Chili (île de Pâques)", "Le Pérou", "La Polynésie française", "L'Équateur"], correct: 0 },
  { q: "Dans quelle ville se trouve la Sagrada Família ?", choices: ["Madrid", "Barcelone", "Séville", "Valence"], correct: 1 },
  { q: "Dans quelle ville se trouve le Kremlin ?", choices: ["Saint-Pétersbourg", "Kiev", "Moscou", "Minsk"], correct: 2 },
  { q: "Dans quelle ville se dresse la statue du Christ Rédempteur ?", choices: ["São Paulo", "Lisbonne", "Buenos Aires", "Rio de Janeiro"], correct: 3 },
  { q: "Dans quelle ville se trouve l'opéra aux voiles blanches emblématiques ?", choices: ["Sydney", "Melbourne", "Auckland", "Singapour"], correct: 0 },
  { q: "Dans quelle ville se trouve le Burj Khalifa, plus haute tour du monde ?", choices: ["Abou Dabi", "Dubaï", "Doha", "Riyad"], correct: 1 },
  { q: "Dans quelle ville américaine se trouve le Golden Gate Bridge ?", choices: ["Los Angeles", "Seattle", "San Francisco", "New York"], correct: 2 },
  { q: "La statue de la Liberté a été offerte aux États-Unis par quel pays ?", choices: ["Le Royaume-Uni", "L'Espagne", "L'Italie", "La France"], correct: 3 },
  { q: "Avec quel pays la Suisse partage-t-elle le lac Léman ?", choices: ["La France", "L'Italie", "L'Autriche", "L'Allemagne"], correct: 0 },
  { q: "Quel pays est surnommé « le pays du Soleil-Levant » ?", choices: ["La Chine", "Le Japon", "La Corée du Sud", "La Thaïlande"], correct: 1 },
  { q: "Quel pays est surnommé « le pays des kangourous » ?", choices: ["La Nouvelle-Zélande", "L'Afrique du Sud", "L'Australie", "L'Argentine"], correct: 2 },
  { q: "Quel pays est surnommé « la Botte » ?", choices: ["L'Espagne", "La Grèce", "Le Portugal", "L'Italie"], correct: 3 },
  { q: "Quelle ville est surnommée « la Grosse Pomme » ?", choices: ["New York", "Chicago", "Los Angeles", "Boston"], correct: 0 },
  { q: "Quelle ville est surnommée « la Ville lumière » ?", choices: ["Londres", "Paris", "Rome", "Vienne"], correct: 1 },
  { q: "Quelle ville italienne est célèbre pour ses canaux et ses gondoles ?", choices: ["Florence", "Milan", "Venise", "Vérone"], correct: 2 },
  { q: "Quelle capitale européenne est bâtie sur 14 îles ?", choices: ["Copenhague", "Helsinki", "Amsterdam", "Stockholm"], correct: 3 },
  { q: "Quel pays compte le plus de volcans actifs au monde ?", choices: ["L'Indonésie", "Le Japon", "L'Islande", "L'Italie"], correct: 0 },
  { q: "Sur quelle faille géologique se trouve San Francisco ?", choices: ["La faille nord-anatolienne", "La faille de San Andreas", "La dorsale médio-atlantique", "La fosse des Mariannes"], correct: 1 },
  { q: "Quel est le point le plus profond des océans ?", choices: ["La fosse de Porto Rico", "La fosse des Tonga", "La fosse des Mariannes", "La fosse du Japon"], correct: 2 },
  { q: "Quelle ligne imaginaire sépare l'hémisphère Nord de l'hémisphère Sud ?", choices: ["Le tropique du Cancer", "Le méridien de Greenwich", "Le tropique du Capricorne", "L'équateur"], correct: 3 },
  { q: "Quel méridien sert de référence pour les fuseaux horaires ?", choices: ["Celui de Greenwich", "Celui de Paris", "Celui de Rome", "Celui de New York"], correct: 0 },
  { q: "Combien y a-t-il de fuseaux horaires principaux sur Terre ?", choices: ["12", "24", "36", "48"], correct: 1 },
  { q: "Quel cercle polaire traverse le nord de la Scandinavie ?", choices: ["Le cercle antarctique", "Le tropique du Cancer", "Le cercle arctique", "L'équateur"], correct: 2 },
  { q: "Quel continent est le plus froid et le plus sec du monde ?", choices: ["L'Arctique", "La Sibérie", "Le Groenland", "L'Antarctique"], correct: 3 },
  { q: "Quelle est la capitale du Ghana ?", choices: ["Accra", "Kumasi", "Tamale", "Takoradi"], correct: 0 },
  { q: "Quelle est la capitale de Haïti ?", choices: ["Cap-Haïtien", "Port-au-Prince", "Gonaïves", "Jacmel"], correct: 1 },
  { q: "Quelle est la capitale de la Jamaïque ?", choices: ["Montego Bay", "Ocho Rios", "Kingston", "Negril"], correct: 2 },
  { q: "Quelle est la capitale de la Bosnie-Herzégovine ?", choices: ["Mostar", "Banja Luka", "Tuzla", "Sarajevo"], correct: 3 },
  { q: "Quelle est la capitale de l'Albanie ?", choices: ["Tirana", "Durrës", "Vlorë", "Shkodër"], correct: 0 },
  { q: "Quelle est la capitale de la Slovénie ?", choices: ["Maribor", "Ljubljana", "Celje", "Koper"], correct: 1 },
  { q: "Quelle est la capitale de Chypre ?", choices: ["Limassol", "Larnaca", "Nicosie", "Paphos"], correct: 2 },
  { q: "Quelle est la capitale de Malte ?", choices: ["Sliema", "Mdina", "Rabat", "La Valette"], correct: 3 },
  { q: "Quelle est la capitale du Luxembourg ?", choices: ["Luxembourg", "Esch-sur-Alzette", "Differdange", "Dudelange"], correct: 0 },
  { q: "Quelle est la capitale de l'Écosse ?", choices: ["Glasgow", "Édimbourg", "Aberdeen", "Dundee"], correct: 1 },
  { q: "Quelle est la capitale du pays de Galles ?", choices: ["Swansea", "Newport", "Cardiff", "Bangor"], correct: 2 },
  { q: "Quelle est la capitale de l'Irlande du Nord ?", choices: ["Dublin", "Derry", "Lisburn", "Belfast"], correct: 3 },
  { q: "Quel État insulaire se trouve au sud de l'Inde ?", choices: ["Le Sri Lanka", "Les Maldives", "L'île Maurice", "Les Seychelles"], correct: 0 },
  { q: "Quel pays d'Afrique de l'Est est célèbre pour le Kilimandjaro et le Serengeti ?", choices: ["Le Kenya", "La Tanzanie", "L'Ouganda", "L'Éthiopie"], correct: 1 },
  { q: "Quel désert couvre une grande partie du Botswana et de la Namibie ?", choices: ["Le Sahara", "Le Namib seul", "Le Kalahari", "Le Karoo"], correct: 2 },
  { q: "Quelle capitale sud-américaine est la plus haute du monde (siège du gouvernement, ~3 640 m) ?", choices: ["Quito", "Bogota", "Sucre", "La Paz"], correct: 3 },
  { q: "Quel pays a pour emblème un cèdre sur son drapeau ?", choices: ["Le Liban", "La Syrie", "Chypre", "La Tunisie"], correct: 0 },
  { q: "Quel pays scandinave possède les fjords les plus célèbres ?", choices: ["La Suède", "La Norvège", "Le Danemark", "La Finlande"], correct: 1 },
  { q: "Quelle région française est célèbre pour ses menhirs de Carnac ?", choices: ["La Normandie", "L'Auvergne", "La Bretagne", "Le Périgord"], correct: 2 },
  { q: "Quel massif français est le plus ancien ?", choices: ["Les Alpes", "Les Pyrénées", "Le Jura", "Le Massif armoricain"], correct: 3 },
  { q: "La Camargue est célèbre pour ses chevaux blancs, ses taureaux et… ?", choices: ["Ses flamants roses", "Ses ours", "Ses loups", "Ses aigles"], correct: 0 },
  { q: "Quelle est la plus grande forêt de France métropolitaine ?", choices: ["La forêt de Fontainebleau", "La forêt des Landes", "La forêt d'Orléans", "La forêt de Tronçais"], correct: 1 },
  { q: "Quel village fortifié médiéval du sud de la France est classé à l'UNESCO ?", choices: ["Saint-Malo", "Provins", "Carcassonne", "Vézelay"], correct: 2 },
  { q: "De quelle couleur est la terre des Ocres de Roussillon, en Provence ?", choices: ["Noire", "Blanche", "Verte", "Ocre-rouge"], correct: 3 },
];
