/* Quiz bank MUSIQUE - correct = 0-based index. */
export const Q_MUSIQUE = [
  { q: "Quel groupe britannique a sorti l'album 'The Dark Side of the Moon' en 1973 ?", choices: ["Led Zeppelin", "Pink Floyd", "The Rolling Stones", "Deep Purple"], correct: 1 },
  { q: "Qui est surnommé le 'King of Pop' ?", choices: ["Elvis Presley", "Prince", "Michael Jackson", "James Brown"], correct: 2 },
  { q: "Quel chanteur français a interprété 'Ne me quitte pas' ?", choices: ["Charles Aznavour", "Jacques Brel", "Georges Brassens", "Léo Ferré"], correct: 1 },
  { q: "Combien de membres composaient le groupe The Beatles ?", choices: ["3", "4", "5", "6"], correct: 1 },
  { q: "Quel instrument Jimi Hendrix jouait-il principalement ?", choices: ["La batterie", "La basse", "La guitare", "Le clavier"], correct: 2 },
  { q: "Quelle chanteuse a interprété le tube 'Rolling in the Deep' ?", choices: ["Amy Winehouse", "Adele", "Duffy", "Lily Allen"], correct: 1 },
  { q: "Quel groupe suédois a remporté l'Eurovision en 1974 avec 'Waterloo' ?", choices: ["Roxette", "ABBA", "Ace of Base", "Europe"], correct: 1 },
  { q: "Quel rappeur américain a sorti l'album 'The Marshall Mathers LP' ?", choices: ["Jay-Z", "50 Cent", "Eminem", "Snoop Dogg"], correct: 2 },
  { q: "Qui a chanté 'La Vie en rose' ?", choices: ["Édith Piaf", "Dalida", "Mistinguett", "Barbara"], correct: 0 },
  { q: "Quel groupe de rock a pour chanteur Freddie Mercury ?", choices: ["The Who", "Queen", "Genesis", "Dire Straits"], correct: 1 },
  { q: "Combien de cordes possède une guitare classique standard ?", choices: ["4", "5", "6", "7"], correct: 2 },
  { q: "Quel festival de musique se tient chaque été à Glastonbury ?", choices: ["Le festival de Glastonbury", "Coachella", "Tomorrowland", "Roskilde"], correct: 0 },
  { q: "Quel chanteur français est l'auteur de 'Comme d'habitude', reprise en anglais sous le titre 'My Way' ?", choices: ["Michel Sardou", "Claude François", "Joe Dassin", "Michel Polnareff"], correct: 1 },
  { q: "Quelle chanteuse a sorti l'album 'Like a Virgin' en 1984 ?", choices: ["Cyndi Lauper", "Madonna", "Whitney Houston", "Tina Turner"], correct: 1 },
  { q: "Quel groupe irlandais a pour chanteur Bono ?", choices: ["The Cranberries", "U2", "Coldplay", "The Corrs"], correct: 1 },
  { q: "Quel instrument à vent est associé au jazz et à Louis Armstrong ?", choices: ["Le saxophone", "La trompette", "La clarinette", "Le trombone"], correct: 1 },
  { q: "Quel rappeur français fait partie du groupe NTM avec Kool Shen ?", choices: ["JoeyStarr", "MC Solaar", "Akhenaton", "Booba"], correct: 0 },
  { q: "Quelle est la nationalité du groupe Rammstein ?", choices: ["Autrichienne", "Allemande", "Suisse", "Néerlandaise"], correct: 1 },
  { q: "Qui a interprété le tube 'Billie Jean' ?", choices: ["Prince", "Lionel Richie", "Michael Jackson", "Stevie Wonder"], correct: 2 },
  { q: "Quel groupe britannique a sorti la chanson 'Bohemian Rhapsody' ?", choices: ["The Beatles", "Queen", "The Rolling Stones", "Oasis"], correct: 1 },
  { q: "Quel chanteur belge est l'auteur de 'Le Plat pays' ?", choices: ["Jacques Brel", "Adamo", "Arno", "Stromae"], correct: 0 },
  { q: "Quel duo français électronique est connu pour ses casques de robots ?", choices: ["Justice", "Daft Punk", "Air", "Cassius"], correct: 1 },
  { q: "Quelle chanteuse américaine a chanté 'I Will Always Love You' dans le film Bodyguard ?", choices: ["Mariah Carey", "Whitney Houston", "Céline Dion", "Diana Ross"], correct: 1 },
  { q: "Quel groupe de grunge avait pour chanteur Kurt Cobain ?", choices: ["Pearl Jam", "Soundgarden", "Nirvana", "Alice in Chains"], correct: 2 },
  { q: "Quel chanteur français interprète 'Formidable' et 'Papaoutai' ?", choices: ["Christine and the Queens", "Stromae", "Orelsan", "M"], correct: 1 },
  { q: "Quel pays organise traditionnellement le concours Eurovision de la chanson ?", choices: ["Un pays différent chaque année", "Toujours la Suisse", "Toujours le Royaume-Uni", "Toujours la France"], correct: 0 },
  { q: "Quel groupe de rock australien a sorti 'Highway to Hell' ?", choices: ["INXS", "AC/DC", "Midnight Oil", "Men at Work"], correct: 1 },
  { q: "Qui a composé et chanté 'Purple Rain' ?", choices: ["Prince", "Michael Jackson", "David Bowie", "George Michael"], correct: 0 },
  { q: "Quel chanteur français est surnommé le 'taulier' du rock français ?", choices: ["Eddy Mitchell", "Johnny Hallyday", "Dick Rivers", "Jacques Dutronc"], correct: 1 },
  { q: "Quelle chanteuse canadienne a interprété la chanson-titre du film Titanic ?", choices: ["Shania Twain", "Céline Dion", "Alanis Morissette", "Avril Lavigne"], correct: 1 },
  { q: "Quel groupe britannique est mené par les frères Gallagher ?", choices: ["Blur", "Oasis", "Pulp", "The Verve"], correct: 1 },
  { q: "Quel instrument possède des touches noires et blanches ?", choices: ["La harpe", "Le piano", "Le violon", "La batterie"], correct: 1 },
  { q: "Quel rappeur américain a été tué en 1996 à Las Vegas ?", choices: ["The Notorious B.I.G.", "Tupac Shakur", "Nas", "Dr. Dre"], correct: 1 },
  { q: "Quel artiste français a interprété 'Mistral gagnant' ?", choices: ["France Gall", "Renaud", "Vanessa Paradis", "Cœur de pirate"], correct: 1 },
  { q: "Quel groupe suédois a chanté 'The Final Countdown' ?", choices: ["Europe", "ABBA", "Roxette", "Ace of Base"], correct: 0 },
  { q: "Quel chanteur britannique a créé le personnage de Ziggy Stardust ?", choices: ["Elton John", "David Bowie", "Freddie Mercury", "Rod Stewart"], correct: 1 },
  { q: "Quelle est la ville d'origine du groupe The Beatles ?", choices: ["Londres", "Manchester", "Liverpool", "Birmingham"], correct: 2 },
  { q: "Quel chanteur français a sorti l'album 'Racine carrée' en 2013 ?", choices: ["Maître Gims", "Stromae", "Orelsan", "Bigflo & Oli"], correct: 1 },
  { q: "Quel groupe américain a pour chanteuse Gwen Stefani ?", choices: ["No Doubt", "Garbage", "The Cranberries", "Paramore"], correct: 0 },
  { q: "Quel style musical est né en Jamaïque et associé à Bob Marley ?", choices: ["Le ska", "Le reggae", "Le calypso", "Le dancehall"], correct: 1 },
  { q: "Qui a chanté 'Like a Rolling Stone' et est prix Nobel de littérature 2016 ?", choices: ["Neil Young", "Bob Dylan", "Bruce Springsteen", "Leonard Cohen"], correct: 1 },
  { q: "Quelle chanteuse a interprété 'Vogue' et 'Material Girl' ?", choices: ["Kylie Minogue", "Madonna", "Janet Jackson", "Paula Abdul"], correct: 1 },
  { q: "Quel rappeur français est l'auteur de 'Bella' et fait partie de la Sexion d'Assaut ?", choices: ["Black M", "Maître Gims", "Booba", "Kaaris"], correct: 1 },
  { q: "Quel groupe de rock a sorti 'Satisfaction' en 1965 ?", choices: ["The Beatles", "The Rolling Stones", "The Kinks", "The Animals"], correct: 1 },
  { q: "Quel chanteur américain est surnommé 'The Boss' ?", choices: ["Bob Dylan", "Bruce Springsteen", "Tom Petty", "John Mellencamp"], correct: 1 },
  { q: "Quelle chanteuse française a chanté 'Poupée de cire, poupée de son', vainqueur de l'Eurovision 1965 ?", choices: ["Sylvie Vartan", "France Gall", "Sheila", "Françoise Hardy"], correct: 1 },
  { q: "Quel groupe britannique a sorti l'album 'A Rush of Blood to the Head' ?", choices: ["Radiohead", "Coldplay", "Muse", "Travis"], correct: 1 },
  { q: "Quel instrument à quatre cordes est plus grave que le violon et plus aigu que le violoncelle ?", choices: ["La contrebasse", "L'alto", "La mandoline", "Le banjo"], correct: 1 },
  { q: "Quel chanteur a interprété 'Imagine' ?", choices: ["Paul McCartney", "John Lennon", "George Harrison", "Ringo Starr"], correct: 1 },
  { q: "Quelle chanteuse britannique est décédée en 2011 après l'album 'Back to Black' ?", choices: ["Adele", "Amy Winehouse", "Duffy", "Joss Stone"], correct: 1 },
  { q: "Quel groupe de hard rock a pour chanteur Axl Rose ?", choices: ["Aerosmith", "Guns N' Roses", "Bon Jovi", "Mötley Crüe"], correct: 1 },
  { q: "Quel chanteur français a interprété 'Les Champs-Élysées' ?", choices: ["Joe Dassin", "Michel Fugain", "Sacha Distel", "Gilbert Bécaud"], correct: 0 },
  { q: "Quel DJ français est connu pour 'Titanium' et 'When Love Takes Over' ?", choices: ["Bob Sinclar", "David Guetta", "Martin Solveig", "DJ Snake"], correct: 1 },
  { q: "Quel groupe américain a sorti 'Smells Like Teen Spirit' en 1991 ?", choices: ["Pearl Jam", "Nirvana", "Red Hot Chili Peppers", "Green Day"], correct: 1 },
  { q: "Quelle chanteuse a interprété 'Hung Up' avec un sample d'ABBA ?", choices: ["Kylie Minogue", "Madonna", "Britney Spears", "Christina Aguilera"], correct: 1 },
  { q: "Quel chanteur français est l'auteur de 'La Bohème' ?", choices: ["Charles Aznavour", "Yves Montand", "Charles Trenet", "Tino Rossi"], correct: 0 },
  { q: "Quel groupe britannique de rock progressif a chanté 'Another Brick in the Wall' ?", choices: ["Genesis", "Pink Floyd", "Yes", "King Crimson"], correct: 1 },
  { q: "Quel rappeur américain a fondé le label Death Row Records avec Suge Knight ?", choices: ["Ice Cube", "Dr. Dre", "Snoop Dogg", "Eazy-E"], correct: 1 },
  { q: "Quelle chanteuse française interprète 'Christine' sous le nom de Christine and the Queens ?", choices: ["Héloïse Letissier", "Pomme", "Angèle", "Clara Luciani"], correct: 0 },
  { q: "Quel festival de musique électronique a lieu chaque année à Boom en Belgique ?", choices: ["Tomorrowland", "Ultra", "Awakenings", "Sónar"], correct: 0 },
  { q: "Quel chanteur britannique a interprété 'Rocket Man' et 'Your Song' ?", choices: ["Rod Stewart", "Elton John", "George Michael", "Phil Collins"], correct: 1 },
  { q: "Quel groupe de metal a sorti l'album 'Master of Puppets' ?", choices: ["Iron Maiden", "Metallica", "Slayer", "Megadeth"], correct: 1 },
  { q: "Quelle chanteuse belge a chanté 'Tout oublier' et 'Balance ton quoi' ?", choices: ["Angèle", "Lous and the Yakuza", "Selah Sue", "Typh Barrow"], correct: 0 },
  { q: "Quel groupe américain funk a pour chanteur Anthony Kiedis ?", choices: ["Faith No More", "Red Hot Chili Peppers", "Rage Against the Machine", "Jane's Addiction"], correct: 1 },
  { q: "Quel artiste français a interprété 'Quelqu'un m'a dit' ?", choices: ["Vincent Delerm", "Benjamin Biolay", "Bénabar", "Carla Bruni"], correct: 3 },
  { q: "Quel rappeur américain a sorti 'The College Dropout' en 2004 ?", choices: ["Jay-Z", "Kanye West", "Lil Wayne", "Common"], correct: 1 },
  { q: "Quel chanteur français est le leader du groupe Téléphone ?", choices: ["Jean-Louis Aubert", "Bernard Lavilliers", "Alain Bashung", "Daniel Balavoine"], correct: 0 },
  { q: "Quel instrument électronique inventé au XXe siècle se joue sans contact physique ?", choices: ["Le synthétiseur", "Le thérémine", "Le vocodeur", "La boîte à rythmes"], correct: 1 },
  { q: "Quelle chanteuse américaine a interprété '...Baby One More Time' en 1998 ?", choices: ["Christina Aguilera", "Britney Spears", "Jessica Simpson", "Mandy Moore"], correct: 1 },
  { q: "Quel groupe norvégien a chanté 'Take On Me' ?", choices: ["A-ha", "Röyksopp", "Kygo", "Aqua"], correct: 0 },
  { q: "Quel chanteur français est l'auteur de 'Göttingen', hymne à la réconciliation franco-allemande ?", choices: ["Barbara", "Juliette Gréco", "Anne Sylvestre", "Cora Vaucaire"], correct: 0 },
  { q: "Quel groupe britannique a sorti l'album 'OK Computer' en 1997 ?", choices: ["Blur", "Radiohead", "Oasis", "Pulp"], correct: 1 },
  { q: "Quel rappeur toulousain forme un duo avec son frère sous le nom Bigflo & Oli ?", choices: ["Bigflo", "Oli", "Les deux", "Aucun, c'est un seul artiste"], correct: 2 },
  { q: "Quel chanteur américain a interprété 'What's Going On' en 1971 ?", choices: ["Stevie Wonder", "Marvin Gaye", "Al Green", "Otis Redding"], correct: 1 },
  { q: "Quelle est la couleur associée à l'album des Beatles surnommé 'l'album blanc' ?", choices: ["Le rouge", "Le blanc", "Le noir", "Le bleu"], correct: 1 },
  { q: "Quel chanteur jamaïcain est l'auteur de 'No Woman, No Cry' ?", choices: ["Peter Tosh", "Bob Marley", "Jimmy Cliff", "Burning Spear"], correct: 1 },
  { q: "Quelle chanteuse américaine a sorti l'album 'Lemonade' en 2016 ?", choices: ["Rihanna", "Beyoncé", "Alicia Keys", "Nicki Minaj"], correct: 1 },
  { q: "Quel groupe français new wave a chanté 'L'Aventurier' et 'Trois nuits par semaine' ?", choices: ["Indochine", "Taxi Girl", "Marquis de Sade", "Kas Product"], correct: 0 },
  { q: "Quel chanteur britannique du groupe Wham! a ensuite chanté 'Careless Whisper' en solo ?", choices: ["Andrew Ridgeley", "George Michael", "Boy George", "Rick Astley"], correct: 1 },
  { q: "Quel chanteur français est l'auteur de 'Je t'aime moi non plus' avec Jane Birkin ?", choices: ["Serge Gainsbourg", "Alain Delon", "Michel Polnareff", "Jacques Dutronc"], correct: 0 },
  { q: "Quel groupe de rock britannique a pour guitariste Jimmy Page ?", choices: ["Deep Purple", "Led Zeppelin", "Black Sabbath", "The Who"], correct: 1 },
  { q: "Qui a chanté 'Waka Waka' pour la Coupe du monde de football 2010 ?", choices: ["Jennifer Lopez", "Shakira", "Ricky Martin", "Gloria Estefan"], correct: 1 },
];
