/* Quiz bank NATURE - correct = 0-based index. */
export const Q_NATURE = [
  { q: "Quel est l'animal terrestre le plus rapide du monde ?", choices: ["Le lion", "Le guépard", "L'antilope", "Le lévrier"], correct: 1 },
  { q: "Quel est le plus grand animal ayant jamais existé sur Terre ?", choices: ["Le baleine bleue", "Le diplodocus", "Le cachalot", "L'éléphant de savane"], correct: 0 },
  { q: "Combien de cœurs possède une pieuvre ?", choices: ["Un", "Deux", "Trois", "Quatre"], correct: 2 },
  { q: "Quel oiseau est capable de voler en marche arrière ?", choices: ["Le martinet", "Le colibri", "L'hirondelle", "Le rouge-gorge"], correct: 1 },
  { q: "Quel est le plus grand mammifère terrestre actuel ?", choices: ["Le rhinocéros", "L'hippopotame", "L'éléphant d'Afrique", "La girafe"], correct: 2 },
  { q: "Quelle est la plus grande espèce de manchot ?", choices: ["Le manchot royal", "Le manchot empereur", "Le manchot papou", "Le gorfou"], correct: 1 },
  { q: "Combien d'yeux possède une abeille ?", choices: ["Deux", "Trois", "Cinq", "Huit"], correct: 2 },
  { q: "Quel animal a la morsure la plus puissante du règne animal ?", choices: ["Le crocodile marin", "Le grand requin blanc", "Le lion", "Le tigre"], correct: 0 },
  { q: "Quel arbre est considéré comme le plus grand du monde ?", choices: ["Le chêne", "Le baobab", "Le séquoia à feuilles d'if", "Le sapin de Douglas"], correct: 2 },
  { q: "Quel est le plus profond océan de la planète ?", choices: ["L'océan Atlantique", "L'océan Indien", "L'océan Arctique", "L'océan Pacifique"], correct: 3 },
  { q: "Quel animal ne dort jamais totalement en mettant en veille la moitié de son cerveau ?", choices: ["Le dauphin", "Le requin", "La tortue", "Le phoque"], correct: 0 },
  { q: "Quel est l'insecte le plus meurtrier pour l'homme ?", choices: ["L'abeille", "Le moustique", "La guêpe", "La fourmi"], correct: 1 },
  { q: "À quelle classe appartiennent les araignées ?", choices: ["Les insectes", "Les arachnides", "Les myriapodes", "Les crustacés"], correct: 1 },
  { q: "Quel est le plus long serpent du monde ?", choices: ["Le cobra royal", "L'anaconda vert", "Le python réticulé", "Le boa constricteur"], correct: 2 },
  { q: "Quel animal possède le plus long cou du règne animal ?", choices: ["L'autruche", "Le cygne", "La girafe", "Le lama"], correct: 2 },
  { q: "De quelle couleur est le sang d'un poulpe ?", choices: ["Rouge", "Bleu", "Vert", "Incolore"], correct: 1 },
  { q: "Quel est le plus grand poisson du monde ?", choices: ["Le grand requin blanc", "Le requin-baleine", "La raie manta", "Le thon rouge"], correct: 1 },
  { q: "Quelle est la seule espèce de perroquet incapable de voler ?", choices: ["Le kakapo", "Le cacatoès", "L'ara", "Le gris du Gabon"], correct: 0 },
  { q: "Quel mammifère pond des œufs ?", choices: ["Le pangolin", "L'ornithorynque", "Le paresseux", "La chauve-souris"], correct: 1 },
  { q: "Quel est l'animal le plus venimeux au monde ?", choices: ["Le cobra royal", "La méduse-boîte", "Le scorpion", "La vipère"], correct: 1 },
  { q: "Combien de temps peut vivre une tortue géante des Galápagos ?", choices: ["Environ 30 ans", "Environ 60 ans", "Plus de 100 ans", "Environ 20 ans"], correct: 2 },
  { q: "Quel gaz les plantes absorbent-elles principalement lors de la photosynthèse ?", choices: ["L'oxygène", "Le dioxyde de carbone", "L'azote", "L'hydrogène"], correct: 1 },
  { q: "Quel est le plus grand désert chaud du monde ?", choices: ["Le désert de Gobi", "Le Sahara", "Le désert d'Arabie", "Le Kalahari"], correct: 1 },
  { q: "Quel animal change de couleur pour se camoufler ?", choices: ["Le caméléon", "Le gecko", "L'iguane", "Le varan"], correct: 0 },
  { q: "Quel est le plus grand félin du monde ?", choices: ["Le lion", "Le tigre", "Le jaguar", "Le léopard"], correct: 1 },
  { q: "Combien de pattes possède un mille-pattes de l'espèce la plus commune ?", choices: ["Toujours mille", "Un nombre variable selon l'espèce", "Exactement cent", "Exactement cinquante"], correct: 1 },
  { q: "Quel oiseau est le plus grand du monde ?", choices: ["Le condor", "L'aigle royal", "L'autruche", "L'émeu"], correct: 2 },
  { q: "Quelle est la plante à la croissance la plus rapide du monde ?", choices: ["Le bambou", "Le nénuphar", "Le lierre", "Le liseron"], correct: 0 },
  { q: "Quel dinosaure carnivore est célèbre pour ses petits bras ?", choices: ["Le vélociraptor", "Le tyrannosaure", "L'allosaure", "Le spinosaure"], correct: 1 },
  { q: "Quel animal possède des empreintes digitales très proches de celles de l'homme ?", choices: ["Le chimpanzé", "Le koala", "Le gorille", "L'orang-outan"], correct: 1 },
  { q: "Quelle est la principale cause du phénomène des marées ?", choices: ["Le vent", "L'attraction de la Lune", "La rotation des courants", "La température de l'eau"], correct: 1 },
  { q: "Quel est l'oiseau national symbole des États-Unis, aussi grand rapace ?", choices: ["Le faucon pèlerin", "Le pygargue à tête blanche", "Le condor de Californie", "Le balbuzard"], correct: 1 },
  { q: "Quel animal marin est connu pour ses jets d'encre ?", choices: ["Le requin", "La seiche", "La baleine", "Le dauphin"], correct: 1 },
  { q: "Quel est le plus rapide de tous les oiseaux en piqué ?", choices: ["L'aigle royal", "Le martinet", "Le faucon pèlerin", "L'albatros"], correct: 2 },
  { q: "À quel groupe d'animaux appartient la baleine ?", choices: ["Les poissons", "Les mammifères", "Les amphibiens", "Les reptiles"], correct: 1 },
  { q: "Quel est le plus petit oiseau du monde ?", choices: ["Le roitelet", "Le colibri d'Elena", "Le troglodyte", "La mésange"], correct: 1 },
  { q: "Quel phénomène naturel est mesuré par l'échelle de Richter ?", choices: ["Les ouragans", "Les séismes", "Les tornades", "Les éruptions"], correct: 1 },
  { q: "Quel animal a la peau qui inspire les combinaisons de nage grâce à ses écailles ?", choices: ["Le dauphin", "Le requin", "Le thon", "Le maquereau"], correct: 1 },
  { q: "Quelle plante carnivore se referme rapidement sur ses proies ?", choices: ["Le népenthès", "La dionée attrape-mouche", "La drosera", "La sarracénie"], correct: 1 },
  { q: "Quel est le plus grand reptile vivant actuel ?", choices: ["Le crocodile marin", "L'anaconda", "Le dragon de Komodo", "La tortue luth"], correct: 0 },
  { q: "Combien d'ailes possède une mouche ?", choices: ["Deux", "Quatre", "Six", "Aucune"], correct: 0 },
  { q: "Quel mammifère est le seul capable de voler activement ?", choices: ["L'écureuil volant", "La chauve-souris", "Le colugo", "Le pétaure"], correct: 1 },
  { q: "Quel arbre perd ses feuilles en automne ?", choices: ["Le pin", "Le sapin", "Le chêne", "L'épicéa"], correct: 2 },
  { q: "Quelle est la couche de l'atmosphère qui contient l'ozone protecteur ?", choices: ["La troposphère", "La stratosphère", "La mésosphère", "La thermosphère"], correct: 1 },
  { q: "Quel animal peut régénérer un membre perdu ?", choices: ["Le lézard", "L'axolotl", "Le crapaud", "La grenouille"], correct: 1 },
  { q: "Quelle est la plus grande forêt tropicale du monde ?", choices: ["La forêt du Congo", "L'Amazonie", "La forêt de Bornéo", "La taïga"], correct: 1 },
  { q: "Quel oiseau migrateur parcourt la plus grande distance annuelle ?", choices: ["La cigogne", "La sterne arctique", "L'hirondelle", "L'oie sauvage"], correct: 1 },
  { q: "Quel est l'animal terrestre le plus lourd ?", choices: ["L'hippopotame", "Le rhinocéros blanc", "L'éléphant d'Afrique", "Le bison"], correct: 2 },
  { q: "Quelle substance les abeilles produisent-elles à partir du nectar ?", choices: ["La cire", "Le miel", "La propolis", "La gelée royale"], correct: 1 },
  { q: "Quel type de racine caractérise la carotte ?", choices: ["Une racine fasciculée", "Une racine pivotante", "Une racine adventive", "Une racine aérienne"], correct: 1 },
  { q: "Quel est le plus grand invertébré connu ?", choices: ["Le calmar géant", "La pieuvre commune", "Le crabe royal", "La méduse crinière de lion"], correct: 0 },
  { q: "Quel animal possède le plus grand cerveau du règne animal ?", choices: ["L'éléphant", "Le cachalot", "L'humain", "La baleine bleue"], correct: 1 },
  { q: "Quel phénomène provoque les aurores boréales ?", choices: ["La pollution lumineuse", "Le vent solaire", "Les nuages ioniques", "Les éruptions volcaniques"], correct: 1 },
  { q: "Quelle est la période géologique où vivaient de nombreux dinosaures juste avant leur extinction ?", choices: ["Le Jurassique", "Le Crétacé", "Le Trias", "Le Permien"], correct: 1 },
  { q: "Quel animal utilise l'écholocalisation pour se repérer ?", choices: ["Le hibou", "La chauve-souris", "Le renard", "Le loup"], correct: 1 },
  { q: "Quelle est la plus grande espèce d'ours ?", choices: ["L'ours brun", "L'ours polaire", "L'ours noir", "Le grizzly"], correct: 1 },
  { q: "Quel élément est indispensable à la photosynthèse en plus de l'eau et du CO2 ?", choices: ["La lumière", "Le sable", "Le vent", "Le sel"], correct: 0 },
  { q: "Quel animal est connu pour son venin bien qu'étant un mammifère mâle ?", choices: ["Le hérisson", "L'ornithorynque", "La taupe", "Le blaireau"], correct: 1 },
  { q: "Quel est le plus grand lac d'eau douce du monde par superficie ?", choices: ["Le lac Baïkal", "Le lac Supérieur", "Le lac Victoria", "La mer Caspienne"], correct: 1 },
  { q: "Quel animal marin possède huit bras et deux tentacules ?", choices: ["La pieuvre", "Le calmar", "La méduse", "L'étoile de mer"], correct: 1 },
  { q: "Quelle est la fonction principale des racines d'une plante ?", choices: ["La photosynthèse", "L'absorption de l'eau et des nutriments", "La reproduction", "La respiration exclusive"], correct: 1 },
  { q: "Quel animal peut survivre dans l'espace grâce à sa résistance extrême ?", choices: ["Le tardigrade", "La fourmi", "Le cafard", "Le nématode"], correct: 0 },
  { q: "Quel est le plus venimeux des serpents terrestres ?", choices: ["Le cobra royal", "Le taïpan du désert", "Le mamba noir", "La vipère heurtante"], correct: 1 },
  { q: "Quelle est la plus haute chute d'eau du monde ?", choices: ["Les chutes du Niagara", "Le Salto Ángel", "Les chutes Victoria", "Les chutes d'Iguazú"], correct: 1 },
  { q: "Quel animal possède une trompe préhensile ?", choices: ["Le tapir", "L'éléphant", "Le fourmilier", "Le rhinocéros"], correct: 1 },
  { q: "Quel arbre produit les glands ?", choices: ["Le hêtre", "Le chêne", "Le châtaignier", "Le noyer"], correct: 1 },
  { q: "Quelle est la principale composante de l'atmosphère terrestre ?", choices: ["L'oxygène", "L'azote", "Le dioxyde de carbone", "L'argon"], correct: 1 },
  { q: "Quel animal est le symbole de la lenteur ?", choices: ["La tortue", "Le paresseux", "L'escargot", "Le koala"], correct: 1 },
  { q: "Quel est le plus grand rongeur du monde ?", choices: ["Le castor", "Le capybara", "Le ragondin", "Le porc-épic"], correct: 1 },
  { q: "Quelle est la structure qui donne leur couleur verte aux feuilles ?", choices: ["La cellulose", "La chlorophylle", "La sève", "Le xylème"], correct: 1 },
  { q: "Quel animal peut fermer ses narines pour rester sous l'eau très longtemps ?", choices: ["Le castor", "L'hippopotame", "La loutre", "Le phoque"], correct: 3 },
  { q: "Quel dinosaure herbivore portait des plaques osseuses sur le dos et des pointes à la queue ?", choices: ["Le tricératops", "Le stégosaure", "L'ankylosaure", "Le brachiosaure"], correct: 1 },
  { q: "Quel est le plus grand océan par superficie ?", choices: ["L'Atlantique", "Le Pacifique", "L'Indien", "L'Arctique"], correct: 1 },
  { q: "Quel animal possède une langue plus longue que son corps ?", choices: ["Le fourmilier", "Le caméléon", "Le tamandua", "La grenouille"], correct: 1 },
  { q: "Quelle est la plus grande espèce de requin après le requin-baleine ?", choices: ["Le grand requin blanc", "Le requin pèlerin", "Le requin-tigre", "Le requin-marteau"], correct: 1 },
  { q: "Quel phénomène désigne le cycle de l'eau dans la nature ?", choices: ["La condensation seule", "Le cycle hydrologique", "L'érosion", "La sédimentation"], correct: 1 },
  { q: "Quel animal a la gestation la plus longue parmi les mammifères ?", choices: ["La baleine bleue", "L'éléphant", "Le rhinocéros", "La girafe"], correct: 1 },
  { q: "Quel oiseau est célèbre pour imiter les sons et les voix ?", choices: ["Le perroquet", "Le corbeau", "Le merle", "Le rossignol"], correct: 0 },
  { q: "Quelle est la plante la plus haute du monde par sa taille adulte ?", choices: ["Le bambou géant", "L'eucalyptus régnant", "Le palmier", "Le peuplier"], correct: 1 },
  { q: "Quel type de nuage annonce généralement les orages ?", choices: ["Le cirrus", "Le cumulonimbus", "Le stratus", "L'altocumulus"], correct: 1 },
  { q: "Quel animal possède le plus grand nombre de dents ?", choices: ["Le requin", "Le crocodile", "La limace", "L'escargot"], correct: 3 },
  { q: "Quel est l'animal le plus grand du monde à vivre sur la terre ferme durant la préhistoire, un dinosaure sauropode ?", choices: ["Le tyrannosaure", "L'argentinosaure", "Le vélociraptor", "Le ptéranodon"], correct: 1 },
  { q: "Quelle est la fonction de la sève brute chez une plante ?", choices: ["Transporter les sucres", "Transporter l'eau et les minéraux des racines aux feuilles", "Fabriquer l'oxygène", "Protéger contre le froid"], correct: 1 },
  { q: "Quel animal hiberne durant l'hiver en réduisant fortement son métabolisme ?", choices: ["Le renard", "La marmotte", "Le cerf", "Le lièvre"], correct: 1 },
  { q: "Quel est le plus grand groupe d'animaux en nombre d'espèces ?", choices: ["Les mammifères", "Les insectes", "Les poissons", "Les oiseaux"], correct: 1 },
];
