/* Quiz — banque PHILOSOPHIE & IDÉES (philosophes, courants, sciences humaines).
   Format compact : [niveau, question, BONNE RÉPONSE, leurre, leurre, leurre] (ordre des
   choix tiré au hasard à l'affichage).
   Niveau : 1 facile, 2 moyen, 3 expert. */
const Q = [
  [1, "Quel philosophe a raconté l'allégorie de la caverne dans « La République » ?", "Platon", "Aristote", "Socrate", "Épicure"],
  [2, "Quel philosophe vivait dans une jarre et aurait demandé à Alexandre de « s'ôter de son soleil » ?", "Diogène", "Socrate", "Épicure", "Zénon"],
  [1, "Quel penseur florentin a écrit « Le Prince » ?", "Machiavel", "Dante", "Érasme", "Thomas More"],
  [1, "Quels philosophes ont dirigé l'« Encyclopédie » au XVIIIe siècle ?", "Diderot et d'Alembert", "Voltaire et Rousseau", "Montesquieu et Voltaire", "Condorcet et Turgot"],
  [1, "Quel penseur allemand a écrit « Le Capital » ?", "Karl Marx", "Adam Smith", "Max Weber", "Hegel"],
  [2, "Qui a écrit avec Karl Marx le « Manifeste du parti communiste » ?", "Friedrich Engels", "Lénine", "Proudhon", "Bakounine"],
  [2, "Quel philosophe a écrit « Le Mythe de Sisyphe » ?", "Albert Camus", "Jean-Paul Sartre", "Simone de Beauvoir", "André Malraux"],
  [1, "Que signifie le mot « philosophie » en grec ?", "L'amour de la sagesse", "La science des étoiles", "L'art de bien parler", "La recherche de Dieu"],
  [2, "Comment appelle-t-on la branche de la philosophie qui réfléchit au beau et à l'art ?", "L'esthétique", "L'éthique", "La logique", "La métaphysique"],
  [2, "Quel psychiatre suisse a théorisé l'« inconscient collectif » et les archétypes ?", "Carl Gustav Jung", "Sigmund Freud", "Alfred Adler", "Jacques Lacan"],
  [1, "Quel stratège chinois aurait écrit « L'Art de la guerre » ?", "Sun Tzu", "Confucius", "Lao-tseu", "Mencius"],
  [2, "Quel philosophe a écrit les « Essais » au XVIe siècle ?", "Michel de Montaigne", "Blaise Pascal", "François Rabelais", "René Descartes"],
  [3, "Dans quel ouvrage Thomas Hobbes reprend-il la formule « L'homme est un loup pour l'homme » ?", "Le Léviathan", "Le Prince", "Du contrat social", "L'Utopie"],
  [2, "Quel philosophe a résumé l'existentialisme par « L'existence précède l'essence » ?", "Jean-Paul Sartre", "Albert Camus", "Martin Heidegger", "Maurice Merleau-Ponty"],
  [2, "Quelle école philosophique fondée par Zénon prône d'accepter ce qui ne dépend pas de nous ?", "Le stoïcisme", "L'épicurisme", "Le cynisme", "Le scepticisme"],
  [2, "Quel philosophe grec voyait dans des plaisirs simples et mesurés la clé du bonheur ?", "Épicure", "Zénon de Kition", "Diogène", "Héraclite"],
  [2, "Quel empereur romain stoïcien a écrit les « Pensées pour moi-même » ?", "Marc Aurèle", "Néron", "Auguste", "Hadrien"],
  [2, "Quel philosophe stoïcien fut le précepteur de Néron ?", "Sénèque", "Épictète", "Cicéron", "Marc Aurèle"],
  [3, "Quel philosophe grec a dit qu'« on ne se baigne jamais deux fois dans le même fleuve » ?", "Héraclite", "Parménide", "Thalès", "Démocrite"],
  [2, "Quel philosophe grec a imaginé que la matière est faite d'atomes insécables ?", "Démocrite", "Aristote", "Héraclite", "Pythagore"],
  [2, "Quel livre fondateur du taoïsme est attribué à Lao-tseu ?", "Le Tao-tö-king", "Les Entretiens", "L'Art de la guerre", "Le Yi-king"],
  [2, "Sur quoi porte le célèbre « pari » de Blaise Pascal ?", "L'existence de Dieu", "La fin du monde", "La forme de la Terre", "Le hasard des dés"],
  [2, "Quel philosophe néerlandais a écrit l'« Éthique » ?", "Baruch Spinoza", "René Descartes", "Gottfried Leibniz", "Érasme"],
  [2, "Quel humaniste de Rotterdam a écrit l'« Éloge de la folie » ?", "Érasme", "Thomas More", "Montaigne", "Rabelais"],
  [3, "Quel humaniste anglais a inventé le mot « utopie » ?", "Thomas More", "Érasme", "Francis Bacon", "Thomas Hobbes"],
  [2, "Quel philosophe a donné son nom au « rasoir » qui écarte les hypothèses inutiles ?", "Guillaume d'Ockham", "Francis Bacon", "John Locke", "David Hume"],
  [3, "Quel philosophe danois est considéré comme le précurseur de l'existentialisme ?", "Søren Kierkegaard", "Friedrich Nietzsche", "Arthur Schopenhauer", "Karl Jaspers"],
  [2, "Quel philosophe allemand a écrit « Être et Temps » (1927) ?", "Martin Heidegger", "Edmund Husserl", "Hegel", "Emmanuel Kant"],
  [2, "Quelle philosophe a parlé de « la banalité du mal » à propos du procès Eichmann ?", "Hannah Arendt", "Simone Weil", "Simone de Beauvoir", "Rosa Luxemburg"],
  [2, "Quel philosophe a écrit « Surveiller et punir » ?", "Michel Foucault", "Gilles Deleuze", "Jacques Derrida", "Pierre Bourdieu"],
  [3, "Quel philosophe français est associé à la « déconstruction » ?", "Jacques Derrida", "Michel Foucault", "Gilles Deleuze", "Jacques Lacan"],
  [2, "Quel sociologue a écrit « La Distinction », sur les goûts et les classes sociales ?", "Pierre Bourdieu", "Émile Durkheim", "Raymond Aron", "Edgar Morin"],
  [2, "Quel sociologue a étudié le suicide comme un fait social, en 1897 ?", "Émile Durkheim", "Max Weber", "Auguste Comte", "Pierre Bourdieu"],
  [3, "Quel philosophe a inventé le mot « sociologie » ?", "Auguste Comte", "Émile Durkheim", "Max Weber", "Alexis de Tocqueville"],
  [2, "Qui a écrit « De la démocratie en Amérique » (1835) ?", "Alexis de Tocqueville", "Montesquieu", "Benjamin Constant", "Raymond Aron"],
  [3, "Quel philosophe écossais a remis en cause l'idée de causalité ?", "David Hume", "Adam Smith", "John Locke", "George Berkeley"],
  [3, "Quel philosophe anglais voyait l'esprit du nouveau-né comme une « table rase » ?", "John Locke", "Thomas Hobbes", "David Hume", "Francis Bacon"],
  [3, "Quel philosophe a fondé l'utilitarisme : « le plus grand bonheur du plus grand nombre » ?", "Jeremy Bentham", "Thomas Hobbes", "Adam Smith", "Edmund Burke"],
  [2, "Quel philosophe a écrit « Le Monde comme volonté et comme représentation » ?", "Arthur Schopenhauer", "Hegel", "Kant", "Nietzsche"],
  [2, "Quel philosophe a fondé le Lycée, son école à Athènes ?", "Aristote", "Platon", "Épicure", "Zénon"],
  [2, "Quelle école de philosophie se réunissait dans un « jardin » à Athènes ?", "L'épicurisme", "Le stoïcisme", "Le cynisme", "Le platonisme"],
  [3, "D'où vient le nom des stoïciens ?", "Du Portique d'Athènes où ils se réunissaient", "Du nom de leur fondateur", "D'un mot grec signifiant « courage »", "D'une île de la mer Égée"],
  [2, "Quel philosophe a écrit « La Phénoménologie de l'esprit » (1807) ?", "Hegel", "Fichte", "Schelling", "Kant"],
  [3, "Quel philosophe a fondé la phénoménologie au début du XXe siècle ?", "Edmund Husserl", "Martin Heidegger", "Henri Bergson", "Maurice Merleau-Ponty"],
  [3, "Quel philosophe français a reçu le prix Nobel de littérature en 1927 ?", "Henri Bergson", "Jean-Paul Sartre", "Albert Camus", "Romain Rolland"],
  [2, "Quel philosophe autrichien a écrit le « Tractatus logico-philosophicus » ?", "Ludwig Wittgenstein", "Karl Popper", "Rudolf Carnap", "Bertrand Russell"],
  [3, "Quel philosophe a défini la science par la « réfutabilité » de ses théories ?", "Karl Popper", "Thomas Kuhn", "Ludwig Wittgenstein", "Auguste Comte"],
  [3, "Quel philosophe a popularisé le terme de « changement de paradigme » en sciences ?", "Thomas Kuhn", "Karl Popper", "Paul Feyerabend", "Gaston Bachelard"],
  [3, "Quel philosophe américain a écrit « Théorie de la justice » (1971) ?", "John Rawls", "Robert Nozick", "Noam Chomsky", "Richard Rorty"],
  [2, "Quel anthropologue français a écrit « Tristes Tropiques » ?", "Claude Lévi-Strauss", "Marcel Mauss", "Pierre Bourdieu", "Philippe Descola"],
  [3, "Quel sociologue allemand a écrit « L'Éthique protestante et l'esprit du capitalisme » ?", "Max Weber", "Karl Marx", "Georg Simmel", "Norbert Elias"],
  [3, "Quel philosophe grec a formulé les paradoxes d'Achille et la tortue ?", "Zénon d'Élée", "Zénon de Kition", "Parménide", "Pythagore"],
  [3, "Quelle philosophe française, morte en 1943, a écrit « La Pesanteur et la Grâce » ?", "Simone Weil", "Simone de Beauvoir", "Hannah Arendt", "Édith Stein"],
  [2, "Quel psychanalyste français a affirmé que « l'inconscient est structuré comme un langage » ?", "Jacques Lacan", "Françoise Dolto", "Gilles Deleuze", "Michel Foucault"],
  [2, "Quel courant philosophique antique doutait qu'on puisse atteindre une vérité certaine ?", "Le scepticisme", "Le stoïcisme", "L'épicurisme", "Le platonisme"],
];
export const Q_PHILO = Q.map(([d, q, ...choices]) => ({ d, q, choices, correct: 0 }));
