/* Quiz — CINÉMA, 2e vague (réalisateurs, palmarès, classiques, cinéma français).
   Format compact : [niveau, question, BONNE RÉPONSE, leurre, leurre, leurre] (ordre des
   choix tiré au hasard à l'affichage).
   Niveau : 1 facile, 2 moyen, 3 expert. */
const Q = [
  [1, "Quel film a remporté l'Oscar du meilleur film en 2024 ?", "Oppenheimer", "Barbie", "Pauvres Créatures", "Anatomie d'une chute"],
  [2, "Quel film de Justine Triet a remporté la Palme d'or en 2023 ?", "Anatomie d'une chute", "Titane", "La Vie d'Adèle", "Le Règne animal"],
  [3, "Quel réalisateur iranien a remporté la Palme d'or en 2025 ?", "Jafar Panahi", "Asghar Farhadi", "Abbas Kiarostami", "Mohammad Rasoulof"],
  [1, "Quel film français détient le record d'entrées en salle pour un film national ?", "Bienvenue chez les Ch'tis", "Intouchables", "La Grande Vadrouille", "Les Visiteurs"],
  [1, "Quel film de 1966 avec Bourvil et Louis de Funès a longtemps détenu le record d'entrées ?", "La Grande Vadrouille", "Le Corniaud", "La Folie des grandeurs", "Les Aventures de Rabbi Jacob"],
  [1, "Quel réalisateur a tourné « Le Grand Bleu » et « Léon » ?", "Luc Besson", "Jean-Jacques Annaud", "Jean-Pierre Jeunet", "Claude Lelouch"],
  [2, "Quel réalisateur a tourné « La Haine » en 1995 ?", "Mathieu Kassovitz", "Jacques Audiard", "Cédric Klapisch", "Luc Besson"],
  [2, "Quel réalisateur de la Nouvelle Vague a tourné « Les Quatre Cents Coups » ?", "François Truffaut", "Jean-Luc Godard", "Éric Rohmer", "Claude Chabrol"],
  [2, "Quel réalisateur a tourné « À bout de souffle » avec Jean-Paul Belmondo ?", "Jean-Luc Godard", "François Truffaut", "Jacques Demy", "Louis Malle"],
  [1, "Quel acteur incarne Jacquouille la Fripouille dans « Les Visiteurs » ?", "Christian Clavier", "Jean Reno", "Gérard Jugnot", "Thierry Lhermitte"],
  [1, "Quel film de Francis Veber met en scène François Pignon invité par moquerie ?", "Le Dîner de cons", "La Chèvre", "Les Compères", "L'Emmerdeur"],
  [2, "Comment s'appelle l'ordinateur du vaisseau dans « 2001, l'Odyssée de l'espace » ?", "HAL 9000", "Skynet", "Mère", "Jarvis"],
  [2, "Quel réalisateur a tourné « Le Parrain » ?", "Francis Ford Coppola", "Martin Scorsese", "Brian De Palma", "Sergio Leone"],
  [2, "Quel acteur incarne Vito Corleone dans le premier « Parrain » ?", "Marlon Brando", "Al Pacino", "Robert De Niro", "James Caan"],
  [1, "Quel acteur lance « You talkin' to me? » devant son miroir dans « Taxi Driver » ?", "Robert De Niro", "Al Pacino", "Joe Pesci", "Harvey Keitel"],
  [2, "Quel réalisateur néo-zélandais a adapté « Le Seigneur des anneaux » ?", "Peter Jackson", "Jane Campion", "Taika Waititi", "Guillermo del Toro"],
  [2, "Quel réalisateur coréen a tourné « Parasite », Palme d'or et Oscar du meilleur film ?", "Bong Joon-ho", "Park Chan-wook", "Kim Ki-duk", "Hirokazu Kore-eda"],
  [2, "Quel acteur a reçu l'Oscar pour son interprétation du Joker en 2020 ?", "Joaquin Phoenix", "Heath Ledger", "Jared Leto", "Brad Pitt"],
  [1, "Quelle actrice française a reçu l'Oscar pour son rôle d'Édith Piaf dans « La Môme » ?", "Marion Cotillard", "Juliette Binoche", "Audrey Tautou", "Isabelle Huppert"],
  [1, "Quel acteur français a reçu l'Oscar du meilleur acteur pour « The Artist » ?", "Jean Dujardin", "Omar Sy", "Vincent Cassel", "Gérard Depardieu"],
  [2, "Quelle actrice française a reçu l'Oscar pour « Le Patient anglais » ?", "Juliette Binoche", "Marion Cotillard", "Isabelle Adjani", "Catherine Deneuve"],
  [2, "Combien de films compte la saga principale de la famille Skywalker dans « Star Wars » ?", "9", "6", "7", "12"],
  [1, "Comment s'appelle le psychiatre cannibale du « Silence des agneaux » ?", "Hannibal Lecter", "Norman Bates", "Jack Torrance", "Patrick Bateman"],
  [1, "Quel film de 1939 suit Scarlett O'Hara pendant la guerre de Sécession ?", "Autant en emporte le vent", "Casablanca", "Le Magicien d'Oz", "Ben-Hur"],
  [1, "Quel film de Charlie Chaplin se moque du travail à la chaîne ?", "Les Temps modernes", "Le Kid", "Le Dictateur", "La Ruée vers l'or"],
  [2, "Quel réalisateur japonais a tourné « Les Sept Samouraïs » ?", "Akira Kurosawa", "Yasujirō Ozu", "Hayao Miyazaki", "Takeshi Kitano"],
  [2, "Quel réalisateur italien a tourné « La Dolce Vita » ?", "Federico Fellini", "Roberto Rossellini", "Luchino Visconti", "Sergio Leone"],
  [2, "Quel réalisateur espagnol a tourné « Tout sur ma mère » et « Volver » ?", "Pedro Almodóvar", "Luis Buñuel", "Alejandro Amenábar", "Carlos Saura"],
  [2, "Quel cinéaste français a tourné « Le Voyage dans la Lune » en 1902 ?", "Georges Méliès", "Louis Lumière", "Charles Pathé", "Léon Gaumont"],
  [3, "Quel film de 1927 est considéré comme le premier long métrage parlant ?", "Le Chanteur de jazz", "Metropolis", "Les Lumières de la ville", "Nosferatu"],
  [2, "Quelle récompense suprême décerne le festival de Berlin ?", "L'Ours d'or", "Le Lion d'or", "La Palme d'or", "La Coquille d'or"],
  [2, "Quelle récompense suprême décerne la Mostra de Venise ?", "Le Lion d'or", "L'Ours d'or", "La Palme d'or", "Le Léopard d'or"],
  [1, "Quel réalisateur italien est le maître du western spaghetti ?", "Sergio Leone", "Federico Fellini", "Dario Argento", "Bernardo Bertolucci"],
  [2, "Quel compositeur a signé les musiques des westerns de Sergio Leone ?", "Ennio Morricone", "John Williams", "Hans Zimmer", "Nino Rota"],
  [2, "Quel compositeur a écrit les musiques de « Star Wars », « Jaws » et « Indiana Jones » ?", "John Williams", "Hans Zimmer", "Danny Elfman", "Howard Shore"],
  [2, "Quel compositeur allemand a signé les musiques d'« Inception » et du « Roi lion » ?", "Hans Zimmer", "John Williams", "Alexandre Desplat", "James Horner"],
  [3, "Quel compositeur a écrit la musique du « Fabuleux Destin d'Amélie Poulain » ?", "Yann Tiersen", "Alexandre Desplat", "Michel Legrand", "Vladimir Cosma"],
  [2, "Quel film de Jacques Demy est entièrement chanté ?", "Les Parapluies de Cherbourg", "Peau d'âne", "Lola", "Les Demoiselles de Rochefort"],
  [1, "Quel duo d'acteurs forme le couple Asterix-Obélix dans « Mission Cléopâtre » ?", "Christian Clavier et Gérard Depardieu", "Clovis Cornillac et Gérard Depardieu", "Guillaume Canet et Gilles Lellouche", "Édouard Baer et Jamel Debbouze"],
  [1, "Quel film de 2011 avec Omar Sy et François Cluzet a réuni plus de 19 millions de spectateurs ?", "Intouchables", "Le Sens de la fête", "Bienvenue chez les Ch'tis", "Qu'est-ce qu'on a fait au Bon Dieu ?"],
  [2, "Quel film de 1994 suit Andy Dufresne dans la prison de Shawshank ?", "Les Évadés", "La Ligne verte", "Le Prisonnier", "Papillon"],
  [1, "Quel acteur a remporté l'Oscar en 2016 pour « The Revenant » ?", "Leonardo DiCaprio", "Matthew McConaughey", "Eddie Redmayne", "Tom Hardy"],
  // — Expert, 3e vague (2026-10) —
  [3, "Quel film a reçu la toute première Palme d'or sous ce nom, en 1955 ?", "Marty", "La Strada", "Les Diaboliques", "Sept ans de réflexion"],
  [3, "Quel film d'Eisenstein (1925) contient la célèbre scène de l'escalier d'Odessa ?", "Le Cuirassé Potemkine", "Octobre", "La Grève", "Alexandre Nevski"],
  [3, "Quel réalisateur japonais a signé « Voyage à Tokyo » en 1953 ?", "Yasujirō Ozu", "Akira Kurosawa", "Kenji Mizoguchi", "Nagisa Ōshima"],
  [3, "Quelle actrice détient le record de quatre Oscars de la meilleure actrice ?", "Katharine Hepburn", "Meryl Streep", "Ingrid Bergman", "Bette Davis"],
  [3, "Quel acteur est le seul à avoir reçu trois Oscars du meilleur acteur ?", "Daniel Day-Lewis", "Jack Nicholson", "Marlon Brando", "Tom Hanks"],
  [3, "Quel film muet de Fritz Lang (1927) montre une ville futuriste et une femme-robot ?", "Metropolis", "Nosferatu", "M le maudit", "Le Cabinet du docteur Caligari"],
  [3, "Quel film a été le premier à remporter les cinq grands Oscars, en 1935 ?", "New York-Miami", "Vol au-dessus d'un nid de coucou", "Autant en emporte le vent", "Les Temps modernes"],
  [3, "Quel compositeur a écrit la musique de « Psychose » d'Hitchcock ?", "Bernard Herrmann", "Ennio Morricone", "John Williams", "Max Steiner"],
];
export const Q3_CINEMA = Q.map(([d, q, ...choices]) => ({ d, q, choices, correct: 0 }));
