/* Quiz bank SERIES - correct = 0-based index. */
export const Q_SERIES = [
  { q: "Dans Breaking Bad, quel est le métier initial de Walter White ?", choices: ["Médecin", "Professeur de chimie", "Avocat", "Policier"], correct: 1 },
  { q: "Dans Friends, quel est le métier de Ross Geller ?", choices: ["Paléontologue", "Chef cuisinier", "Acteur", "Musicien"], correct: 0 },
  { q: "Quelle plateforme a produit la série Stranger Things ?", choices: ["Amazon Prime Video", "Disney+", "Netflix", "HBO"], correct: 2 },
  { q: "Dans Game of Thrones, quelle maison a pour devise 'Winter is Coming' ?", choices: ["Lannister", "Targaryen", "Baratheon", "Stark"], correct: 3 },
  { q: "Dans La Casa de Papel, quel est le surnom du cerveau du braquage ?", choices: ["Le Professeur", "Berlin", "Tokyo", "Rio"], correct: 0 },
  { q: "Dans quelle ville se déroule principalement la série Friends ?", choices: ["Los Angeles", "New York", "Chicago", "Boston"], correct: 1 },
  { q: "Dans The Office (version US), qui est le patron de la succursale de Scranton au début ?", choices: ["Jim Halpert", "Dwight Schrute", "Michael Scott", "Andy Bernard"], correct: 2 },
  { q: "Quel acteur incarne Walter White dans Breaking Bad ?", choices: ["Bryan Cranston", "Aaron Paul", "Bob Odenkirk", "Giancarlo Esposito"], correct: 0 },
  { q: "Dans Game of Thrones, comment surnomme-t-on Daenerys en lien avec ses dragons ?", choices: ["La Reine du Nord", "La Mère des Dragons", "La Briseuse de Glace", "La Dame de Fer"], correct: 1 },
  { q: "Dans Stranger Things, quelle jeune fille possède des pouvoirs télékinésiques ?", choices: ["Max", "Nancy", "Onze (Eleven)", "Robin"], correct: 2 },
  { q: "Dans Friends, comment s'appelle le café où les personnages se retrouvent ?", choices: ["The Coffee House", "Central Perk", "Café Nervosa", "The Grind"], correct: 1 },
  { q: "Quelle série met en scène la famille Soprano et la mafia du New Jersey ?", choices: ["The Wire", "Boardwalk Empire", "Les Soprano", "Peaky Blinders"], correct: 2 },
  { q: "Dans Breaking Bad, quel est le nom de code utilisé par Walter White ?", choices: ["Heisenberg", "Scarface", "Mr. White", "El Jefe"], correct: 0 },
  { q: "Quelle série espagnole raconte un braquage de la Fabrique nationale de la monnaie ?", choices: ["Elite", "La Casa de Papel", "Vis a vis", "Toy Boy"], correct: 1 },
  { q: "Dans Game of Thrones, qui est surnommé 'le Lutin' ?", choices: ["Tyrion Lannister", "Jaime Lannister", "Petyr Baelish", "Varys"], correct: 0 },
  { q: "Quel acteur joue Sheldon Cooper dans The Big Bang Theory ?", choices: ["Johnny Galecki", "Jim Parsons", "Kunal Nayyar", "Simon Helberg"], correct: 1 },
  { q: "Dans Friends, quelles deux sœurs jumelles sont incarnées par Lisa Kudrow ?", choices: ["Monica et Rachel", "Phoebe et Ursula", "Emily et Janice", "Susan et Carol"], correct: 1 },
  { q: "Quelle série suit les employés d'un hôpital de Seattle ?", choices: ["Dr House", "Urgences", "Grey's Anatomy", "Scrubs"], correct: 2 },
  { q: "Dans The Walking Dead, comment appelle-t-on le plus souvent les zombies ?", choices: ["Les rôdeurs", "Les infectés", "Les mordus", "Les damnés"], correct: 0 },
  { q: "Quelle plateforme diffuse The Mandalorian ?", choices: ["Netflix", "Disney+", "Apple TV+", "HBO Max"], correct: 1 },
  { q: "Dans Breaking Bad, qui est l'ancien élève associé de Walter White ?", choices: ["Hank Schrader", "Gustavo Fring", "Jesse Pinkman", "Saul Goodman"], correct: 2 },
  { q: "Quelle série met en vedette un avocat véreux nommé Saul Goodman ?", choices: ["Better Call Saul", "Suits", "Damages", "How to Get Away with Murder"], correct: 0 },
  { q: "Dans Game of Thrones, quel est le trône convoité par les grandes maisons ?", choices: ["Le Trône d'Or", "Le Trône de Fer", "Le Trône de Verre", "Le Trône d'Ébène"], correct: 1 },
  { q: "Quel acteur incarne Geralt de Riv dans The Witcher de Netflix ?", choices: ["Henry Cavill", "Chris Hemsworth", "Charlie Hunnam", "Sam Heughan"], correct: 0 },
  { q: "Dans Friends, quel personnage prononce souvent 'How you doin'?' ?", choices: ["Ross", "Chandler", "Joey", "Gunther"], correct: 2 },
  { q: "Quelle série britannique suit une famille de gangsters de Birmingham dans les années 1920 ?", choices: ["Peaky Blinders", "Downton Abbey", "Gangs of London", "Sherlock"], correct: 0 },
  { q: "Dans The Office (US), quel personnage cultive une ferme de betteraves ?", choices: ["Kevin Malone", "Dwight Schrute", "Stanley Hudson", "Creed Bratton"], correct: 1 },
  { q: "Quelle série de HBO se déroule dans le monde médiéval de Westeros ?", choices: ["Vikings", "The Last Kingdom", "Game of Thrones", "Rome"], correct: 2 },
  { q: "Dans Stranger Things, dans quelle ville fictive se déroule l'action ?", choices: ["Hawkins", "Riverdale", "Derry", "Twin Peaks"], correct: 0 },
  { q: "Quel acteur joue Dexter Morgan, expert médico-légal et tueur en série ?", choices: ["Michael C. Hall", "Kiefer Sutherland", "Timothy Olyphant", "Hugh Laurie"], correct: 0 },
  { q: "Dans La Casa de Papel, les braqueurs portent des masques à l'effigie de quel artiste ?", choices: ["Che Guevara", "Salvador Dalí", "Picasso", "Frida Kahlo"], correct: 1 },
  { q: "Quelle série médicale a pour personnage principal un diagnosticien misanthrope et boiteux ?", choices: ["Grey's Anatomy", "Dr House", "Scrubs", "New Amsterdam"], correct: 1 },
  { q: "Dans Friends, quel animal Ross adopte-t-il un temps ?", choices: ["Un chat", "Un chien", "Un singe", "Un perroquet"], correct: 2 },
  { q: "Quelle série de science-fiction met en scène un parc rempli d'androïdes appelés hôtes ?", choices: ["Black Mirror", "Westworld", "Altered Carbon", "Devs"], correct: 1 },
  { q: "Dans Breaking Bad, quelle couleur caractérise la méthamphétamine de Walter White ?", choices: ["Rouge", "Bleue", "Verte", "Rose"], correct: 1 },
  { q: "Quel est le nom de la série dérivée de Breaking Bad centrée sur un avocat ?", choices: ["El Camino", "Better Call Saul", "Ozark", "Fargo"], correct: 1 },
  { q: "Dans Game of Thrones, qui est le père biologique de Jon Snow révélé plus tard ?", choices: ["Ned Stark", "Robert Baratheon", "Rhaegar Targaryen", "Tywin Lannister"], correct: 2 },
  { q: "Quelle sitcom suit quatre amis scientifiques et leur voisine Penny ?", choices: ["Community", "The Big Bang Theory", "Silicon Valley", "New Girl"], correct: 1 },
  { q: "Dans Stranger Things, quel monde parallèle menace Hawkins ?", choices: ["Le Monde d'En Bas (Upside Down)", "La Zone Fantôme", "Le Vide", "Le Néant"], correct: 0 },
  { q: "Quelle série anthologique explore les dérives de la technologie et est diffusée sur Netflix ?", choices: ["Love, Death & Robots", "Black Mirror", "The Twilight Zone", "Electric Dreams"], correct: 1 },
  { q: "Dans Friends, qui épouse Monica ?", choices: ["Ross", "Joey", "Chandler", "Richard"], correct: 2 },
  { q: "Quel acteur incarne Eddard 'Ned' Stark dans Game of Thrones ?", choices: ["Sean Bean", "Liam Cunningham", "Charles Dance", "Iain Glen"], correct: 0 },
  { q: "Quelle série suit les détenues de la prison de Litchfield ?", choices: ["Vis a vis", "Orange Is the New Black", "Wentworth", "Prison Break"], correct: 1 },
  { q: "Dans The Office (US), comment s'appelle l'entreprise de papier ?", choices: ["Dunder Mifflin", "Sabre", "Vance Refrigeration", "Michael Scott Paper"], correct: 0 },
  { q: "Quelle série met en scène Sherlock Holmes dans le Londres moderne avec Benedict Cumberbatch ?", choices: ["Elementary", "Sherlock", "Luther", "Endeavour"], correct: 1 },
  { q: "Dans Stranger Things, quel est le monstre principal de la première saison ?", choices: ["Le Mind Flayer", "Le Demogorgon", "Vecna", "Le Demodog"], correct: 1 },
  { q: "Quel acteur joue Jesse Pinkman dans Breaking Bad ?", choices: ["Aaron Paul", "Dean Norris", "RJ Mitte", "Jesse Plemons"], correct: 0 },
  { q: "Quelle série française de Netflix met en scène un gentleman cambrioleur inspiré d'Arsène Lupin ?", choices: ["Marseille", "Lupin", "Braqueurs", "Family Business"], correct: 1 },
  { q: "Dans Friends, quel personnage est un acteur jouant dans le soap 'Les Jours de notre vie' ?", choices: ["Ross", "Chandler", "Joey", "Gunther"], correct: 2 },
  { q: "Quelle série AMC suit un groupe de survivants après une apocalypse zombie ?", choices: ["The Walking Dead", "Z Nation", "The Last of Us", "Black Summer"], correct: 0 },
  { q: "Dans Game of Thrones, quel personnage est surnommé 'Le Roi de la Nuit' ?", choices: ["Le chef des Marcheurs Blancs", "Ramsay Bolton", "Joffrey", "Euron Greyjoy"], correct: 0 },
  { q: "Quel service de streaming appartient à Amazon ?", choices: ["Hulu", "Peacock", "Prime Video", "Paramount+"], correct: 2 },
  { q: "Dans Dexter, dans quelle ville américaine se déroule la série ?", choices: ["Los Angeles", "Miami", "New Orleans", "Las Vegas"], correct: 1 },
  { q: "Quelle série de Netflix suit une famille blanchissant de l'argent dans le Missouri ?", choices: ["Bloodline", "Ozark", "Narcos", "Animal Kingdom"], correct: 1 },
  { q: "Dans Friends, quelle est la profession de Chandler Bing pendant la majeure partie de la série ?", choices: ["Chef", "Publicitaire", "Analyste de données statistiques", "Photographe"], correct: 2 },
  { q: "Quel acteur incarne Tony Soprano dans Les Soprano ?", choices: ["James Gandolfini", "Ray Liotta", "Robert De Niro", "Al Pacino"], correct: 0 },
  { q: "Quelle série suit les enquêtes du FBI sur des tueurs en série dans les années 1970-80 ?", choices: ["Criminal Minds", "Mindhunter", "True Detective", "Hannibal"], correct: 1 },
  { q: "Dans The Crown, quelle souveraine britannique est au centre de la série ?", choices: ["Victoria", "Élisabeth II", "Anne", "Marie Stuart"], correct: 1 },
  { q: "Dans Breaking Bad, quel est le lien de Hank avec Walter White ?", choices: ["Son frère", "Son beau-frère", "Son cousin", "Son voisin"], correct: 1 },
  { q: "Quelle série met en scène des élèves d'une école privée espagnole huppée ?", choices: ["Elite", "Physique ou Chimie", "Skam", "Sex Education"], correct: 0 },
  { q: "Dans Game of Thrones, quel est le nom du dragon noir de Daenerys ?", choices: ["Rhaegal", "Viserion", "Drogon", "Balerion"], correct: 2 },
  { q: "Quelle série britannique se déroule dans le domaine aristocratique de la famille Crawley ?", choices: ["Downton Abbey", "The Crown", "Bridgerton", "Poldark"], correct: 0 },
  { q: "Dans Stranger Things, à quel jeu de rôle jouent Mike et ses amis ?", choices: ["Warhammer", "Donjons & Dragons", "Magic", "Talisman"], correct: 1 },
  { q: "Quel acteur joue le rôle-titre dans la série House of Cards (version US) ?", choices: ["Kevin Spacey", "Bryan Cranston", "Jeff Daniels", "Michael Douglas"], correct: 0 },
  { q: "Dans Friends, quel personnage travaille dans la mode et sort avec Ross ?", choices: ["Monica", "Phoebe", "Rachel", "Janice"], correct: 2 },
  { q: "Quelle série de Netflix retrace la vie du baron de la drogue Pablo Escobar ?", choices: ["El Chapo", "Narcos", "Snowfall", "ZeroZeroZero"], correct: 1 },
  { q: "Dans The Big Bang Theory, quelle est la phrase fétiche de Sheldon ?", choices: ["Legen-dary", "Bazinga", "D'oh", "How you doin'"], correct: 1 },
  { q: "Quelle série suit des adolescents et leurs dérives dans un lycée américain, avec Zendaya ?", choices: ["13 Reasons Why", "Euphoria", "Riverdale", "Sex Education"], correct: 1 },
  { q: "Dans Game of Thrones, quelle famille règne à Port-Réal au début de la série ?", choices: ["Les Stark", "Les Tyrell", "Les Baratheon", "Les Martell"], correct: 2 },
  { q: "Quel acteur incarne le Docteur en premier dans le reboot de Doctor Who lancé en 2005 ?", choices: ["Matt Smith", "David Tennant", "Christopher Eccleston", "Peter Capaldi"], correct: 2 },
  { q: "Dans Vikings, quel guerrier légendaire est le héros des premières saisons ?", choices: ["Ragnar Lodbrok", "Rollo", "Björn", "Floki"], correct: 0 },
  { q: "Quelle plateforme a diffusé la série The Handmaid's Tale (La Servante écarlate) aux États-Unis ?", choices: ["Netflix", "Hulu", "HBO", "Showtime"], correct: 1 },
  { q: "Dans Friends, dans quelle ville Ross et Rachel se marient-ils par accident ?", choices: ["Paris", "Las Vegas", "Londres", "New York"], correct: 1 },
  { q: "Quelle série suit les frères Winchester chassant des créatures surnaturelles ?", choices: ["Supernatural", "Grimm", "Buffy", "The Vampire Diaries"], correct: 0 },
  { q: "Dans Peaky Blinders, quel est le nom de famille du clan principal ?", choices: ["Shelby", "Solomon", "Kimber", "Gray"], correct: 0 },
  { q: "Quel acteur joue Cersei Lannister dans Game of Thrones ?", choices: ["Emilia Clarke", "Lena Headey", "Sophie Turner", "Gwendoline Christie"], correct: 1 },
  { q: "Dans Better Call Saul, quel est le vrai nom de Saul Goodman ?", choices: ["Jimmy McGill", "Chuck McGill", "Howard Hamlin", "Mike Ehrmantraut"], correct: 0 },
  { q: "Quelle série met en scène un professeur de chimie devenu criminel après un diagnostic de cancer ?", choices: ["Ozark", "Breaking Bad", "Fargo", "The Shield"], correct: 1 },
  { q: "Dans Stranger Things, quel personnage travaille dans un magasin de glaces à la saison 3 ?", choices: ["Dustin", "Steve Harrington", "Jonathan", "Lucas"], correct: 1 },
  { q: "Quelle série médicale des années 1990-2000 a révélé George Clooney ?", choices: ["Urgences (ER)", "Chicago Hope", "Dr House", "Grey's Anatomy"], correct: 0 },
  { q: "Dans La Casa de Papel, quel braqueur porte le nom d'une ville italienne ?", choices: ["Denver", "Berlin", "Nairobi", "Palermo"], correct: 3 },
  { q: "Quel acteur incarne Don Draper dans Mad Men ?", choices: ["Jon Hamm", "Jared Harris", "John Slattery", "Vincent Kartheiser"], correct: 0 },
  { q: "Dans Friends, quel personnage est obsédé par le rangement et la propreté ?", choices: ["Phoebe", "Monica", "Rachel", "Janice"], correct: 1 },
  { q: "Quelle série HBO suit des enquêteurs dans une Louisiane sombre avec McConaughey et Harrelson ?", choices: ["The Wire", "True Detective", "Sharp Objects", "Mare of Easttown"], correct: 1 },
  { q: "Dans Game of Thrones, quel personnage lance la réplique 'You know nothing, Jon Snow' ?", choices: ["Daenerys", "Ygritte", "Sansa", "Melisandre"], correct: 1 },
];
