/* Quiz — SANTÉ & CORPS HUMAIN, 2e vague. Format compact : [question, BONNE RÉPONSE,
   leurre ×3] (ordre des choix tiré au hasard à l'affichage). */
const Q = [
  ["Quel groupe sanguin est le receveur universel ?", "AB positif", "O négatif", "A positif", "B négatif"],
  ["Combien de vertèbres cervicales possède un être humain ?", "7", "5", "12", "3"],
  ["Quel est le muscle le plus volumineux du corps humain ?", "Le grand fessier", "Le biceps", "Le quadriceps", "Le cœur"],
  ["Combien de paires de côtes possède un être humain ?", "12", "10", "14", "24"],
  ["Quelle hormone est surnommée « l'hormone du stress » ?", "Le cortisol", "L'insuline", "La mélatonine", "L'ocytocine"],
  ["Quelle hormone règle le cycle du sommeil ?", "La mélatonine", "L'adrénaline", "Le cortisol", "La thyroxine"],
  ["Quelle hormone, sécrétée lors d'un câlin ou d'un accouchement, est dite « de l'attachement » ?", "L'ocytocine", "La testostérone", "Le cortisol", "L'adrénaline"],
  ["Quelle partie colorée de l'œil entoure la pupille ?", "L'iris", "La rétine", "La cornée", "Le cristallin"],
  ["Quelle partie du fond de l'œil capte la lumière ?", "La rétine", "L'iris", "La cornée", "La pupille"],
  ["Combien de fois par minute le cœur bat-il environ au repos ?", "60 à 80 fois", "20 à 30 fois", "120 à 140 fois", "200 fois"],
  ["Combien de saveurs de base distingue-t-on aujourd'hui, umami compris ?", "5", "3", "4", "7"],
  ["Quel virus est responsable du sida ?", "Le VIH", "Le VHB", "Le HPV", "Le SRAS"],
  ["Quelle maladie a été déclarée éradiquée en 1980 grâce à la vaccination ?", "La variole", "La polio", "La rougeole", "La tuberculose"],
  ["Quel médecin anglais a décrit la circulation du sang en 1628 ?", "William Harvey", "Edward Jenner", "Joseph Lister", "Alexander Fleming"],
  ["Quel médecin allemand a découvert le bacille de la tuberculose ?", "Robert Koch", "Louis Pasteur", "Rudolf Virchow", "Paul Ehrlich"],
  ["Quelle partie du cerveau gère surtout l'équilibre et la coordination ?", "Le cervelet", "L'hippocampe", "Le lobe frontal", "L'hypothalamus"],
  ["Quelle structure du cerveau joue un rôle clé dans la mémoire ?", "L'hippocampe", "Le cervelet", "Le bulbe rachidien", "L'hypophyse"],
  ["Quelle glande, en forme de papillon, se trouve à la base du cou ?", "La thyroïde", "L'hypophyse", "Le thymus", "La parotide"],
  ["Quel liquide la vésicule biliaire stocke-t-elle ?", "La bile", "L'insuline", "Le suc gastrique", "La lymphe"],
  ["Où commence la digestion de l'amidon ?", "Dans la bouche", "Dans l'estomac", "Dans l'intestin grêle", "Dans le côlon"],
  ["Quelle est la longueur approximative de l'intestin grêle d'un adulte ?", "6 à 7 mètres", "1 mètre", "20 mètres", "50 centimètres"],
  ["Quelle carence provoque l'anémie la plus courante ?", "Une carence en fer", "Une carence en calcium", "Une carence en sodium", "Une carence en vitamine D"],
  ["Comment appelle-t-on la peur irrationnelle des araignées ?", "L'arachnophobie", "L'agoraphobie", "La claustrophobie", "L'acrophobie"],
  ["Comment appelle-t-on la peur des espaces clos ?", "La claustrophobie", "L'agoraphobie", "L'acrophobie", "L'hydrophobie"],
  ["Comment appelle-t-on la peur du vide et des hauteurs ?", "L'acrophobie", "La claustrophobie", "L'agoraphobie", "La nyctophobie"],
];
export const Q3_SANTE = Q.map(([q, ...choices]) => ({ q, choices, correct: 0 }));
