/* Quiz — banque MATHS & LOGIQUE (calcul, géométrie, grands mathématiciens, énigmes).
   Format compact : [niveau, question, BONNE RÉPONSE, leurre, leurre, leurre] (ordre des
   choix tiré au hasard à l'affichage).
   Niveau : 1 facile, 2 moyen, 3 expert. */
const Q = [
  [1, "Quelle est la racine carrée de 81 ?", "9", "8", "7", "18"],
  [1, "Combien de côtés a un octogone ?", "8", "6", "10", "12"],
  [1, "Comment appelle-t-on un angle de 90° ?", "Un angle droit", "Un angle aigu", "Un angle obtus", "Un angle plat"],
  [1, "Comment appelle-t-on un angle de 180° ?", "Un angle plat", "Un angle droit", "Un angle obtus", "Un angle rentrant"],
  [2, "Combien vaut 2 puissance 10 ?", "1 024", "1 000", "512", "2 048"],
  [2, "Combien d'arêtes possède un cube ?", "12", "6", "8", "24"],
  [1, "Combien de sommets possède un cube ?", "8", "6", "12", "4"],
  [2, "Sur un dé classique, quelle est la somme de deux faces opposées ?", "7", "6", "8", "12"],
  [1, "Comment s'écrit 2025 en chiffres romains ?", "MMXXV", "MMXV", "MMCCV", "MDXXV"],
  [1, "Quel est le périmètre d'un carré de 5 cm de côté ?", "20 cm", "25 cm", "10 cm", "15 cm"],
  [1, "Quelle est l'aire d'un rectangle de 4 m sur 6 m ?", "24 m²", "20 m²", "10 m²", "48 m²"],
  [1, "Comment appelle-t-on le résultat d'une multiplication ?", "Le produit", "La somme", "Le quotient", "La différence"],
  [1, "Comment appelle-t-on le résultat d'une division ?", "Le quotient", "Le produit", "Le reste", "La somme"],
  [1, "Quel nombre vient ensuite : 2, 4, 8, 16… ?", "32", "24", "20", "64"],
  [1, "Quel nombre vient ensuite : 1, 1, 2, 3, 5, 8… ?", "13", "11", "12", "16"],
  [1, "Quel nombre vient ensuite : 1, 4, 9, 16, 25… ?", "36", "30", "35", "49"],
  [1, "Quel nombre vient ensuite : 2, 3, 5, 7, 11… ?", "13", "12", "14", "15"],
  [1, "Combien de mois de l'année comptent au moins 28 jours ?", "Les 12", "1", "2", "6"],
  [1, "Un fermier a 17 moutons ; tous meurent sauf 9. Combien lui en reste-t-il ?", "9", "8", "0", "17"],
  [2, "Combien font 0,1 × 0,1 ?", "0,01", "0,1", "0,2", "1"],
  [2, "Combien font 1 + 2 + 3 + … + 10 ?", "55", "45", "50", "100"],
  [1, "Combien mesure chaque angle d'un triangle équilatéral ?", "60°", "45°", "90°", "30°"],
  [1, "Quelle est la somme des angles intérieurs d'un quadrilatère ?", "360°", "180°", "270°", "540°"],
  [1, "Comment s'appelle le côté opposé à l'angle droit dans un triangle rectangle ?", "L'hypoténuse", "La médiane", "La bissectrice", "La hauteur"],
  [2, "Un triangle rectangle a deux côtés de 3 et 4 autour de l'angle droit. Combien mesure le troisième ?", "5", "6", "7", "4,5"],
  [1, "Quelle formule donne l'aire d'un disque de rayon r ?", "π × r²", "2 × π × r", "π × r", "4 × r"],
  [1, "Quelle formule donne le périmètre d'un cercle de rayon r ?", "2 × π × r", "π × r²", "π × r", "r²"],
  [2, "Combien vaut 5 ! (factorielle de 5) ?", "120", "25", "60", "720"],
  [3, "Combien vaut 0 ! (factorielle de zéro) ?", "1", "0", "10", "Elle n'existe pas"],
  [2, "Quelle est la valeur approchée de la racine carrée de 2 ?", "1,414", "1,732", "1,2", "2,236"],
  [2, "Comment appelle-t-on un polygone à 12 côtés ?", "Un dodécagone", "Un décagone", "Un hendécagone", "Un icosagone"],
  [2, "Combien de faces possède un icosaèdre ?", "20", "12", "10", "24"],
  [2, "Comment appelle-t-on un nombre égal à la somme de ses diviseurs, comme 6 = 1 + 2 + 3 ?", "Un nombre parfait", "Un nombre premier", "Un nombre carré", "Un nombre d'or"],
  [2, "Quelle est la valeur approchée du nombre d'or ?", "1,618", "3,142", "2,718", "1,414"],
  [3, "Quelle est la valeur approchée de la constante e, base du logarithme népérien ?", "2,718", "3,142", "1,618", "1,732"],
  [2, "Combien y a-t-il de nombres premiers entre 1 et 20 ?", "8", "6", "7", "10"],
  [1, "Quel est le plus grand diviseur commun de 12 et 18 ?", "6", "3", "2", "36"],
  [1, "Quel est le plus petit multiple commun de 4 et 6 ?", "12", "24", "10", "2"],
  [3, "Combien de diagonales possède un hexagone ?", "9", "6", "12", "3"],
  [2, "Avec deux dés, quelle somme a le plus de chances de sortir ?", "7", "6", "8", "12"],
  [1, "Quelle est la probabilité d'obtenir « pile » deux fois de suite ?", "1 sur 4", "1 sur 2", "1 sur 3", "1 sur 8"],
  [1, "Combien de codes différents permet un cadenas à 4 molettes de 0 à 9 ?", "10 000", "1 000", "9 999", "40"],
  [2, "Quel mathématicien grec a rédigé les « Éléments », base de la géométrie ?", "Euclide", "Pythagore", "Archimède", "Thalès"],
  [2, "Quel Français a laissé un « dernier théorème » démontré seulement en 1994 ?", "Pierre de Fermat", "Blaise Pascal", "René Descartes", "Évariste Galois"],
  [3, "Qui a démontré le dernier théorème de Fermat ?", "Andrew Wiles", "Grigori Perelman", "Alan Turing", "Henri Poincaré"],
  [3, "Quel mathématicien russe a refusé la médaille Fields après avoir démontré la conjecture de Poincaré ?", "Grigori Perelman", "Andrew Wiles", "Andreï Kolmogorov", "Cédric Villani"],
  [1, "Quel mathématicien français, médaillé Fields en 2010, est reconnaissable à sa lavallière ?", "Cédric Villani", "Laurent Lafforgue", "Alain Connes", "Jean-Pierre Serre"],
  [1, "Quelle récompense, souvent comparée au Nobel, distingue les mathématiciens de moins de 40 ans ?", "La médaille Fields", "Le prix Turing", "Le prix Pulitzer", "La médaille Copley"],
  [1, "Quel savant a inventé la « pascaline », une des premières machines à calculer ?", "Blaise Pascal", "René Descartes", "Gottfried Leibniz", "Isaac Newton"],
  [1, "À quel philosophe et mathématicien doit-on le repère « cartésien » ?", "René Descartes", "Blaise Pascal", "Pierre de Fermat", "Joseph Fourier"],
  [2, "Qui a inventé le calcul infinitésimal à la même époque que Newton ?", "Gottfried Wilhelm Leibniz", "Leonhard Euler", "Carl Friedrich Gauss", "Blaise Pascal"],
  [1, "Quel chiffre, venu d'Inde par les savants arabes, n'existe pas en chiffres romains ?", "Le zéro", "Le un", "Le dix", "Le cent"],
  [2, "Une batte et une balle coûtent 1,10 € au total, la batte coûtant 1 € de plus que la balle. Combien coûte la balle ?", "5 centimes", "10 centimes", "1 centime", "15 centimes"],
  [2, "Si 5 machines font 5 objets en 5 minutes, combien de temps faut-il à 100 machines pour 100 objets ?", "5 minutes", "100 minutes", "20 minutes", "1 minute"],
  [2, "Un nénuphar double chaque jour et couvre tout l'étang en 48 jours. Quand en couvrait-il la moitié ?", "Le 47e jour", "Le 24e jour", "Le 12e jour", "Le 46e jour"],
  [2, "Quel nombre est égal aux deux tiers de lui-même plus 10 ?", "30", "15", "20", "60"],
  [2, "Combien vaut un « gogol » (googol, à l'origine du nom Google) ?", "10 puissance 100", "10 puissance 10", "10 puissance 1 000", "Un milliard de milliards"],
  [2, "Quel nombre s'écrit CDXLIV en chiffres romains ?", "444", "464", "644", "446"],
  [3, "En français, combien de zéros compte un trillion ?", "18", "12", "9", "15"],
  [2, "Quel mot anglais correspond à notre « milliard » ?", "A billion", "A million", "A trillion", "A gazillion"],
  [3, "Quel jeune mathématicien français, mort en duel à 20 ans en 1832, a donné son nom à une théorie ?", "Évariste Galois", "Henri Poincaré", "Joseph Fourier", "Augustin Cauchy"],
  [3, "Quel mathématicien suisse a introduit les notations e, i et f(x) ?", "Leonhard Euler", "Jacques Bernoulli", "Carl Friedrich Gauss", "Joseph-Louis Lagrange"],
  [3, "Quelle célèbre égalité relie e, i, π, 1 et 0 ?", "L'identité d'Euler", "Le théorème de Gauss", "La formule de Viète", "La loi de Bernoulli"],
  [2, "Quel « prince des mathématiciens » aurait calculé enfant la somme des nombres de 1 à 100 ?", "Carl Friedrich Gauss", "Leonhard Euler", "Bernhard Riemann", "Isaac Newton"],
  [3, "Quelle conjecture sur les nombres premiers, posée en 1859, est l'un des grands problèmes du millénaire ?", "L'hypothèse de Riemann", "La conjecture de Poincaré", "La conjecture de Goldbach", "Le théorème de Fermat"],
  [3, "Quelle conjecture affirme que tout nombre pair supérieur à 2 est la somme de deux nombres premiers ?", "La conjecture de Goldbach", "L'hypothèse de Riemann", "La conjecture de Syracuse", "La conjecture de Poincaré"],
  [3, "Combien de prix d'un million de dollars ont été promis pour les « problèmes du millénaire » en 2000 ?", "7", "3", "10", "12"],
  [3, "Quelle mathématicienne a été la première femme médaillée Fields, en 2014 ?", "Maryam Mirzakhani", "Emmy Noether", "Sophie Germain", "Ada Lovelace"],
  [3, "Quelle mathématicienne allemande a donné son nom à un théorème liant symétries et lois de conservation ?", "Emmy Noether", "Sophie Germain", "Sofia Kovalevskaïa", "Hypatie"],
  [1, "Comment appelle-t-on une figure dont chaque morceau ressemble au tout, comme le flocon de Koch ?", "Une fractale", "Une hyperbole", "Une spirale", "Un tesseract"],
  [2, "Quel mathématicien a popularisé les fractales dans les années 1970-1980 ?", "Benoît Mandelbrot", "Alan Turing", "John Nash", "Kurt Gödel"],
  [2, "Quel logicien a démontré en 1931 qu'aucun système mathématique ne peut tout prouver de lui-même ?", "Kurt Gödel", "Bertrand Russell", "David Hilbert", "Alan Turing"],
  [2, "Combien de faces possède un dodécaèdre ?", "12", "10", "20", "8"],
  [3, "Combien existe-t-il de solides de Platon (polyèdres réguliers convexes) ?", "5", "3", "7", "12"],
  [2, "Combien de façons y a-t-il de ranger 4 livres différents sur une étagère ?", "24", "16", "12", "4"],
  [2, "Dans un groupe de 23 personnes, quelle est environ la probabilité que deux partagent le même anniversaire ?", "Environ 50 %", "Environ 6 %", "Environ 23 %", "Environ 90 %"],
];
export const Q_MATHS = Q.map(([d, q, ...choices]) => ({ d, q, choices, correct: 0 }));
