/* Quiz bank SPORT - correct = 0-based index. */
export const Q_SPORT = [
  { q: "Dans quel pays a eu lieu la première Coupe du monde de football en 1930 ?", choices: ["Brésil", "Uruguay", "Italie", "Argentine"], correct: 1 },
  { q: "Quel joueur a marqué le fameux but de la « main de Dieu » en 1986 ?", choices: ["Pelé", "Diego Maradona", "Zico", "Michel Platini"], correct: 1 },
  { q: "Combien de joueurs composent une équipe de football sur le terrain ?", choices: ["9", "10", "11", "12"], correct: 2 },
  { q: "Quel pays a remporté la Coupe du monde de football 1998 ?", choices: ["Brésil", "France", "Italie", "Allemagne"], correct: 1 },
  { q: "Quel club détient le record de victoires en Ligue des champions ?", choices: ["FC Barcelone", "Bayern Munich", "Real Madrid", "AC Milan"], correct: 2 },
  { q: "Quel joueur brésilien est surnommé « O Rei » (le Roi) ?", choices: ["Ronaldo", "Pelé", "Garrincha", "Rivaldo"], correct: 1 },
  { q: "Dans quelle ville se sont déroulés les premiers Jeux olympiques modernes en 1896 ?", choices: ["Paris", "Athènes", "Rome", "Londres"], correct: 1 },
  { q: "Tous les combien d'années ont lieu les Jeux olympiques d'été ?", choices: ["2 ans", "3 ans", "4 ans", "5 ans"], correct: 2 },
  { q: "Quel nageur américain détient le record du plus grand nombre de médailles d'or olympiques ?", choices: ["Mark Spitz", "Michael Phelps", "Ryan Lochte", "Ian Thorpe"], correct: 1 },
  { q: "Quel sprinteur jamaïcain détient le record du monde du 100 mètres ?", choices: ["Yohan Blake", "Asafa Powell", "Usain Bolt", "Tyson Gay"], correct: 2 },
  { q: "Combien de tournois composent le Grand Chelem de tennis ?", choices: ["3", "4", "5", "6"], correct: 1 },
  { q: "Sur quelle surface se joue le tournoi de Wimbledon ?", choices: ["Terre battue", "Gazon", "Dur", "Moquette"], correct: 1 },
  { q: "Quel tournoi du Grand Chelem se joue à Paris sur terre battue ?", choices: ["US Open", "Open d'Australie", "Roland-Garros", "Wimbledon"], correct: 2 },
  { q: "Quel joueur suisse a longtemps détenu le record de titres masculins à Wimbledon ?", choices: ["Rafael Nadal", "Roger Federer", "Novak Djokovic", "Pete Sampras"], correct: 1 },
  { q: "Quelle joueuse américaine possède le plus de titres du Grand Chelem en simple à l'ère Open ?", choices: ["Steffi Graf", "Serena Williams", "Martina Navratilova", "Venus Williams"], correct: 1 },
  { q: "Quelle est la couleur du maillot du leader du Tour de France ?", choices: ["Vert", "Jaune", "Blanc", "Rouge"], correct: 1 },
  { q: "Quel coureur américain a été déchu de ses sept titres du Tour de France pour dopage ?", choices: ["Greg LeMond", "Lance Armstrong", "Floyd Landis", "Tyler Hamilton"], correct: 1 },
  { q: "Que récompense le maillot vert sur le Tour de France ?", choices: ["Le meilleur grimpeur", "Le meilleur sprinteur", "Le meilleur jeune", "Le meilleur équipier"], correct: 1 },
  { q: "Combien de joueurs composent une équipe de rugby à XV sur le terrain ?", choices: ["13", "15", "11", "7"], correct: 1 },
  { q: "Quel pays a remporté la première Coupe du monde de rugby en 1987 ?", choices: ["Australie", "Nouvelle-Zélande", "Afrique du Sud", "France"], correct: 1 },
  { q: "Comment s'appelle la danse traditionnelle exécutée par l'équipe de rugby néo-zélandaise avant les matchs ?", choices: ["Le sirtaki", "Le haka", "Le tango", "Le flamenco"], correct: 1 },
  { q: "Combien de points vaut un essai au rugby à XV ?", choices: ["3", "5", "7", "2"], correct: 1 },
  { q: "Dans quel sport professionnel évolue la ligue nord-américaine NBA ?", choices: ["Baseball", "Football américain", "Basket-ball", "Hockey"], correct: 2 },
  { q: "Quel joueur, surnommé « His Airness », a remporté six titres NBA avec les Chicago Bulls ?", choices: ["Magic Johnson", "Michael Jordan", "Larry Bird", "Kobe Bryant"], correct: 1 },
  { q: "Combien de points vaut un panier réussi derrière la ligne à trois points au basket ?", choices: ["2", "3", "4", "1"], correct: 1 },
  { q: "Quel pilote allemand a remporté sept titres de champion du monde de Formule 1 avec Ferrari notamment ?", choices: ["Sebastian Vettel", "Michael Schumacher", "Niki Lauda", "Nico Rosberg"], correct: 1 },
  { q: "Quelle écurie italienne est la plus ancienne et la plus titrée de Formule 1 ?", choices: ["McLaren", "Ferrari", "Williams", "Lotus"], correct: 1 },
  { q: "Dans quel pays se déroule le célèbre Grand Prix de Monaco ?", choices: ["Italie", "France", "Monaco", "Suisse"], correct: 2 },
  { q: "Quelle nage n'est PAS l'une des quatre nages olympiques ?", choices: ["Brasse", "Dos", "Papillon", "Nage indienne"], correct: 3 },
  { q: "Quelle épreuve d'athlétisme combine dix disciplines pour les hommes ?", choices: ["Heptathlon", "Pentathlon", "Décathlon", "Triathlon"], correct: 2 },
  { q: "Quelle est la distance officielle d'un marathon ?", choices: ["40 km", "42,195 km", "45 km", "38 km"], correct: 1 },
  { q: "Quel pays organise traditionnellement le tournoi de tennis de l'Open d'Australie ?", choices: ["Nouvelle-Zélande", "Australie", "Afrique du Sud", "Royaume-Uni"], correct: 1 },
  { q: "Quel footballeur français a été capitaine de l'équipe championne du monde en 1998 ?", choices: ["Zinédine Zidane", "Didier Deschamps", "Laurent Blanc", "Marcel Desailly"], correct: 1 },
  { q: "Combien de buts a marqué Zinédine Zidane en finale de la Coupe du monde 1998 ?", choices: ["1", "2", "3", "0"], correct: 1 },
  { q: "Quel pays a remporté la Coupe du monde de football 2014 au Brésil ?", choices: ["Argentine", "Allemagne", "Pays-Bas", "Brésil"], correct: 1 },
  { q: "Quel gardien de but russe est considéré comme l'un des meilleurs de l'histoire, surnommé « l'Araignée noire » ?", choices: ["Dino Zoff", "Lev Yachine", "Gordon Banks", "Peter Schmeichel"], correct: 1 },
  { q: "Quel joueur portugais a remporté cinq Ballons d'Or et évolué au Real Madrid ?", choices: ["Luís Figo", "Cristiano Ronaldo", "Eusébio", "Rui Costa"], correct: 1 },
  { q: "Dans quel sport Tiger Woods s'est-il illustré comme champion ?", choices: ["Tennis", "Golf", "Baseball", "Cricket"], correct: 1 },
  { q: "Quelle discipline consiste à enchaîner natation, cyclisme et course à pied ?", choices: ["Pentathlon", "Triathlon", "Biathlon", "Décathlon"], correct: 1 },
  { q: "Quel sport d'hiver combine ski de fond et tir à la carabine ?", choices: ["Combiné nordique", "Biathlon", "Saut à ski", "Skeleton"], correct: 1 },
  { q: "Quel boxeur américain se surnommait lui-même « The Greatest » ?", choices: ["Mike Tyson", "Muhammad Ali", "Joe Frazier", "George Foreman"], correct: 1 },
  { q: "Combien de rounds compte au maximum un championnat du monde de boxe professionnelle moderne ?", choices: ["10", "12", "15", "8"], correct: 1 },
  { q: "Quel pays a remporté le plus de Coupes du monde de football masculin ?", choices: ["Allemagne", "Brésil", "Italie", "Argentine"], correct: 1 },
  { q: "Combien de fois le Brésil a-t-il remporté la Coupe du monde de football ?", choices: ["4", "5", "6", "3"], correct: 1 },
  { q: "Quelle joueuse allemande a remporté 22 titres du Grand Chelem en simple ?", choices: ["Steffi Graf", "Monica Seles", "Martina Hingis", "Justine Henin"], correct: 0 },
  { q: "Dans quel sport décerne-t-on la Coupe Stanley ?", choices: ["Basket-ball", "Hockey sur glace", "Baseball", "Football américain"], correct: 1 },
  { q: "Quel est le trophée remis au vainqueur du Super Bowl ?", choices: ["Trophée Larry O'Brien", "Trophée Vince Lombardi", "Coupe Stanley", "Commissioner's Trophy"], correct: 1 },
  { q: "Quel cycliste belge, surnommé « le Cannibale », a remporté cinq Tours de France ?", choices: ["Bernard Hinault", "Eddy Merckx", "Miguel Indurain", "Jacques Anquetil"], correct: 1 },
  { q: "Outre Jacques Anquetil, quel autre coureur français a remporté cinq Tours de France ?", choices: ["Laurent Fignon", "Bernard Hinault", "Raymond Poulidor", "Bernard Thévenet"], correct: 1 },
  { q: "Quel athlète américain a remporté quatre médailles d'or aux JO de Berlin 1936 ?", choices: ["Carl Lewis", "Jesse Owens", "Ralph Boston", "Bob Beamon"], correct: 1 },
  { q: "Quel athlète américain a égalé les quatre médailles d'or de Jesse Owens aux JO de 1984 ?", choices: ["Michael Johnson", "Carl Lewis", "Maurice Greene", "Justin Gatlin"], correct: 1 },
  { q: "Quel pays domine historiquement le tennis de table international ?", choices: ["Japon", "Chine", "Corée du Sud", "Allemagne"], correct: 1 },
  { q: "Dans quel sport s'affrontent les équipes de la Premier League anglaise ?", choices: ["Rugby", "Cricket", "Football", "Hockey"], correct: 2 },
  { q: "Quel club anglais est surnommé « les Red Devils » (les Diables rouges) ?", choices: ["Liverpool", "Manchester United", "Arsenal", "Chelsea"], correct: 1 },
  { q: "Quelle compétition oppose les meilleurs clubs de football d'Europe chaque année ?", choices: ["Coupe du monde", "Ligue des champions", "Copa America", "Coupe des confédérations"], correct: 1 },
  { q: "Quel joueur argentin a remporté le Ballon d'Or à de multiples reprises au FC Barcelone ?", choices: ["Sergio Agüero", "Lionel Messi", "Diego Maradona", "Gabriel Batistuta"], correct: 1 },
  { q: "Dans quel sport les termes « service » et « ace » sont-ils employés ?", choices: ["Golf", "Tennis", "Escrime", "Aviron"], correct: 1 },
  { q: "Quelle est la durée réglementaire d'un match de football (temps de jeu) ?", choices: ["80 minutes", "90 minutes", "100 minutes", "60 minutes"], correct: 1 },
  { q: "Combien de temps dure une mi-temps au football ?", choices: ["30 minutes", "40 minutes", "45 minutes", "50 minutes"], correct: 2 },
  { q: "Quel événement cycliste, avec le Tour de France, fait partie des grands tours ?", choices: ["Paris-Roubaix", "Tour d'Italie (Giro)", "Milan-San Remo", "Flèche Wallonne"], correct: 1 },
  { q: "Quel est le nom du grand tour cycliste espagnol ?", choices: ["La Vuelta", "Le Giro", "Le Tour", "La Ronde"], correct: 0 },
  { q: "Dans quel sport les termes « strike » et « home run » sont-ils utilisés ?", choices: ["Cricket", "Baseball", "Handball", "Bowling"], correct: 1 },
  { q: "Quelle ville a accueilli les Jeux olympiques d'été de 1992 ?", choices: ["Atlanta", "Barcelone", "Séoul", "Sydney"], correct: 1 },
  { q: "Quelle ville française a accueilli les Jeux olympiques d'été en 1924 et 2024 ?", choices: ["Lyon", "Marseille", "Paris", "Grenoble"], correct: 2 },
  { q: "Quel joueur de tennis espagnol est surnommé « le Roi de la terre battue » ?", choices: ["Carlos Alcaraz", "Rafael Nadal", "David Ferrer", "Juan Carlos Ferrero"], correct: 1 },
  { q: "Combien de titres à Roland-Garros Rafael Nadal a-t-il remportés au total ?", choices: ["12", "14", "16", "10"], correct: 1 },
  { q: "Quel entraîneur écossais légendaire a dirigé Manchester United pendant plus de 25 ans ?", choices: ["Arsène Wenger", "Alex Ferguson", "José Mourinho", "Kenny Dalglish"], correct: 1 },
  { q: "Quel joueur néerlandais est associé au « football total » des années 1970 ?", choices: ["Marco van Basten", "Johan Cruyff", "Ruud Gullit", "Frank Rijkaard"], correct: 1 },
  { q: "Dans quel sport se déroule le tournoi des Six Nations ?", choices: ["Football", "Rugby", "Cricket", "Handball"], correct: 1 },
  { q: "Quelle nation forme le Tournoi des Six Nations avec la France, l'Angleterre, l'Écosse, le Pays de Galles et l'Irlande ?", choices: ["Allemagne", "Italie", "Espagne", "Portugal"], correct: 1 },
  { q: "Quel pilote brésilien de Formule 1 est décédé lors du Grand Prix de Saint-Marin en 1994 ?", choices: ["Nelson Piquet", "Ayrton Senna", "Emerson Fittipaldi", "Rubens Barrichello"], correct: 1 },
  { q: "Quel pilote britannique a remporté plusieurs titres de champion du monde de F1 avec Mercedes dans les années 2010 ?", choices: ["Jenson Button", "Lewis Hamilton", "David Coulthard", "Nigel Mansell"], correct: 1 },
  { q: "Quel est le trophée décerné à l'équipe victorieuse des finales NBA ?", choices: ["Trophée Larry O'Brien", "Coupe Vince Lombardi", "Trophée MVP", "Coupe des champions"], correct: 0 },
  { q: "Quel joueur américain a marqué 100 points lors d'un seul match NBA en 1962 ?", choices: ["Bill Russell", "Wilt Chamberlain", "Kareem Abdul-Jabbar", "Jerry West"], correct: 1 },
  { q: "Quel nageur détient le record de 7 médailles d'or aux JO de Munich 1972 ?", choices: ["Michael Phelps", "Mark Spitz", "Matt Biondi", "Ian Thorpe"], correct: 1 },
  { q: "Quel sport pratique-t-on à Roland-Garros, Wimbledon et l'US Open ?", choices: ["Golf", "Tennis", "Squash", "Badminton"], correct: 1 },
  { q: "Quelle ancienne athlète tchécoslovaque puis américaine détient le record de titres à Wimbledon en simple dames (9) ?", choices: ["Chris Evert", "Martina Navratilova", "Billie Jean King", "Margaret Court"], correct: 1 },
  { q: "Quel pays a remporté la Coupe du monde de football 2010 en Afrique du Sud ?", choices: ["Pays-Bas", "Espagne", "Allemagne", "Uruguay"], correct: 1 },
  { q: "Quel joueur français a remporté le Ballon d'Or en 1998 après le titre mondial ?", choices: ["Thierry Henry", "Zinédine Zidane", "Youri Djorkaeff", "Emmanuel Petit"], correct: 1 },
  { q: "Combien de points marque-t-on avec un lancer franc réussi au basket ?", choices: ["1", "2", "3", "0"], correct: 0 },
  { q: "Quel athlète jamaïcain a remporté le 100 m et le 200 m à trois JO consécutifs ?", choices: ["Yohan Blake", "Usain Bolt", "Justin Gatlin", "Carl Lewis"], correct: 1 },
  { q: "Quelle est la hauteur réglementaire d'un panier de basket-ball ?", choices: ["2,75 m", "3,05 m", "3,50 m", "2,50 m"], correct: 1 },
  { q: "Quel sport d'hiver consiste à descendre une piste glacée tête la première sur une luge ?", choices: ["Bobsleigh", "Luge", "Skeleton", "Curling"], correct: 2 },
  { q: "Quel sport d'hiver se joue avec des pierres glissées sur la glace vers une cible ?", choices: ["Hockey", "Curling", "Patinage", "Skeleton"], correct: 1 },
  { q: "Quel footballeur allemand, surnommé « le Kaiser », a gagné la Coupe du monde comme joueur puis comme sélectionneur ?", choices: ["Gerd Müller", "Franz Beckenbauer", "Lothar Matthäus", "Karl-Heinz Rummenigge"], correct: 1 },
];
