/* Quiz bank MARQUES - correct = 0-based index. */
export const Q_MARQUES = [
  { q: "Que représente le logo de la marque Apple ?", choices: ["Une poire", "Une pomme croquée", "Une cerise", "Une orange"], correct: 1 },
  { q: "De quel pays est originaire la marque automobile Ferrari ?", choices: ["Allemagne", "France", "Italie", "Espagne"], correct: 2 },
  { q: "Quel animal figure sur le logo de Lacoste ?", choices: ["Un caïman/crocodile", "Un lézard", "Un serpent", "Un dauphin"], correct: 0 },
  { q: "Quelle marque utilise le slogan « Just Do It » ?", choices: ["Adidas", "Puma", "Nike", "Reebok"], correct: 2 },
  { q: "Le logo de Mercedes-Benz est une étoile à combien de branches ?", choices: ["Trois", "Quatre", "Cinq", "Six"], correct: 0 },
  { q: "Quelle entreprise a pour logo une sirène à double queue ?", choices: ["Costa Coffee", "Starbucks", "Nespresso", "Dunkin'"], correct: 1 },
  { q: "De quel pays vient la marque automobile Toyota ?", choices: ["Corée du Sud", "Chine", "Japon", "Thaïlande"], correct: 2 },
  { q: "Quel est le secteur d'activité principal de la société Boeing ?", choices: ["Automobile", "Aéronautique", "Électronique", "Textile"], correct: 1 },
  { q: "Combien de bandes forme le logo d'Adidas dans sa version classique ?", choices: ["Deux", "Trois", "Quatre", "Cinq"], correct: 1 },
  { q: "Quelle marque de luxe a pour emblème deux « C » entrelacés ?", choices: ["Chanel", "Cartier", "Céline", "Chloé"], correct: 0 },
  { q: "Que signifie le mot anglais « blackberry », à l'origine du nom de la marque ?", choices: ["Une fraise", "Une mûre", "Une framboise", "Une myrtille"], correct: 1 },
  { q: "La marque Nutella appartient à quel groupe italien ?", choices: ["Barilla", "Ferrero", "Lavazza", "Perfetti"], correct: 1 },
  { q: "Quel constructeur automobile a pour emblème un lion ?", choices: ["Renault", "Citroën", "Peugeot", "Fiat"], correct: 2 },
  { q: "Quel oiseau est la mascotte historique de la marque de céréales Kellogg's Corn Flakes ?", choices: ["Un toucan", "Un coq (Cornelius)", "Un aigle", "Un perroquet"], correct: 1 },
  { q: "Quelle entreprise technologique a pour siège Cupertino en Californie ?", choices: ["Microsoft", "Apple", "Google", "Amazon"], correct: 1 },
  { q: "Le slogan « L'Oréal, parce que je le vaux bien » appartient à quel secteur ?", choices: ["Automobile", "Cosmétiques", "Alimentaire", "Banque"], correct: 1 },
  { q: "De quel pays est originaire la marque de voitures Volvo ?", choices: ["Allemagne", "Suède", "Norvège", "Danemark"], correct: 1 },
  { q: "Quelle marque a pour logo une coquille (Shell signifie coquillage) ?", choices: ["BP", "Total", "Shell", "Esso"], correct: 2 },
  { q: "Quelle grande entreprise a pour logo une flèche allant du A au Z ?", choices: ["eBay", "Amazon", "Alibaba", "AliExpress"], correct: 1 },
  { q: "Quelle marque de soda a pour rival historique Pepsi ?", choices: ["Fanta", "Sprite", "Coca-Cola", "Orangina"], correct: 2 },
  { q: "Quel logo représente une pomme croquée en couleurs arc-en-ciel dans sa version des années 1980 ?", choices: ["IBM", "Apple", "Atari", "Commodore"], correct: 1 },
  { q: "Quelle marque automobile allemande a pour emblème quatre anneaux entrelacés ?", choices: ["BMW", "Audi", "Opel", "Volkswagen"], correct: 1 },
  { q: "Que représente le logo bleu et blanc de BMW selon l'interprétation populaire ?", choices: ["Une hélice d'avion", "Une roue", "Un bouclier", "Un moteur"], correct: 0 },
  { q: "Quelle entreprise suédoise est spécialisée dans le mobilier en kit ?", choices: ["H&M", "IKEA", "Electrolux", "Volvo"], correct: 1 },
  { q: "Quel est le secteur d'activité de la société Pfizer ?", choices: ["Pharmacie", "Agroalimentaire", "Informatique", "Chimie du pétrole"], correct: 0 },
  { q: "Quelle marque de luxe française est symbolisée par les initiales « LV » entrelacées ?", choices: ["Louis Vuitton", "Longchamp", "Lanvin", "Lancel"], correct: 0 },
  { q: "Quel animal figure sur le logo de la marque de voitures Jaguar ?", choices: ["Un puma", "Un léopard", "Un jaguar (félin bondissant)", "Un lynx"], correct: 2 },
  { q: "Le slogan « Think Different » a été utilisé par quelle entreprise ?", choices: ["IBM", "Apple", "Dell", "Intel"], correct: 1 },
  { q: "Quelle marque de fast-food a pour symbole un « M » doré (Golden Arches) ?", choices: ["Burger King", "McDonald's", "Quick", "KFC"], correct: 1 },
  { q: "De quel pays est originaire la marque automobile Hyundai ?", choices: ["Japon", "Chine", "Corée du Sud", "Taïwan"], correct: 2 },
  { q: "Quelle marque de sport a pour logo un félin bondissant (puma) ?", choices: ["Puma", "Nike", "Kappa", "Le Coq Sportif"], correct: 0 },
  { q: "Quel colonel est la mascotte de la chaîne KFC ?", choices: ["Colonel Mustard", "Colonel Sanders", "Colonel Kilgore", "Colonel Blake"], correct: 1 },
  { q: "Quelle entreprise a pour slogan historique « Connecting People » ?", choices: ["Ericsson", "Nokia", "Motorola", "Samsung"], correct: 1 },
  { q: "Quel constructeur automobile a pour logo un losange ?", choices: ["Peugeot", "Citroën", "Renault", "Dacia"], correct: 2 },
  { q: "Quelle marque de luxe italienne est associée au logo de la Méduse ?", choices: ["Prada", "Versace", "Gucci", "Armani"], correct: 1 },
  { q: "Quel est le secteur d'activité de la société Michelin ?", choices: ["Pneumatiques", "Cosmétiques", "Électroménager", "Agroalimentaire"], correct: 0 },
  { q: "Quel bonhomme blanc formé de pneus est la mascotte de Michelin ?", choices: ["Bibendum", "Monsieur Propre", "Gaston", "Le Géant Vert"], correct: 0 },
  { q: "Quelle entreprise de moteurs de recherche a un logo aux quatre couleurs (bleu, rouge, jaune, vert) ?", choices: ["Yahoo", "Bing", "Google", "Ask"], correct: 2 },
  { q: "De quel pays vient la marque automobile Škoda ?", choices: ["Pologne", "Tchéquie", "Slovaquie", "Hongrie"], correct: 1 },
  { q: "Quelle marque a pour slogan « Red Bull donne des ailes » ?", choices: ["Monster", "Red Bull", "Burn", "Dark Dog"], correct: 1 },
  { q: "Quel géant vert est la mascotte d'une marque de légumes en conserve ?", choices: ["Hulk", "Le Géant Vert", "Gogo", "Groot"], correct: 1 },
  { q: "Quelle entreprise informatique est surnommée « Big Blue » ?", choices: ["Intel", "IBM", "HP", "Dell"], correct: 1 },
  { q: "Quelle marque de luxe britannique est célèbre pour son motif à carreaux (tartan beige) ?", choices: ["Burberry", "Barbour", "Mulberry", "Aquascutum"], correct: 0 },
  { q: "Quel est le secteur d'activité principal de la société Airbus ?", choices: ["Automobile", "Aéronautique", "Ferroviaire", "Naval"], correct: 1 },
  { q: "Quelle firme automobile a pour emblème un cheval cabré noir sur fond jaune ?", choices: ["Lamborghini", "Ferrari", "Maserati", "Porsche"], correct: 1 },
  { q: "Quel animal figure sur l'emblème de Lamborghini ?", choices: ["Un cheval", "Un taureau", "Un scorpion", "Un dragon"], correct: 1 },
  { q: "Quelle marque de céréales a pour mascotte un tigre nommé Tony ?", choices: ["Chocapic", "Frosties", "Coco Pops", "Miel Pops"], correct: 1 },
  { q: "De quel pays est originaire la marque SEAT ?", choices: ["Italie", "Espagne", "Portugal", "France"], correct: 1 },
  { q: "Quelle entreprise a pour logo un « swoosh » (virgule) ?", choices: ["Nike", "Umbro", "Fila", "Asics"], correct: 0 },
  { q: "Quel groupe de luxe français possède Louis Vuitton, Dior et Moët & Chandon ?", choices: ["Kering", "LVMH", "Richemont", "Hermès Group"], correct: 1 },
  { q: "Quelle marque a pour slogan « À fond la forme » associé à un produit laitier ?", choices: ["Danone", "Yoplait", "Actimel", "Kiri"], correct: 0 },
  { q: "Quel est le secteur d'activité de la société Nestlé ?", choices: ["Agroalimentaire", "Cosmétiques", "Automobile", "Pharmacie"], correct: 0 },
  { q: "Quel oiseau bleu était le logo historique du réseau social Twitter ?", choices: ["Un merle", "Un rouge-gorge", "Un oiseau bleu stylisé", "Un moineau"], correct: 2 },
  { q: "Quelle marque automobile a pour emblème un trident ?", choices: ["Maserati", "Alfa Romeo", "Lancia", "Bugatti"], correct: 0 },
  { q: "Quelle marque de rasoirs a pour slogan « La perfection au masculin » ?", choices: ["Bic", "Gillette", "Wilkinson", "Philips"], correct: 1 },
  { q: "De quel pays est originaire la marque de montres Rolex ?", choices: ["France", "Suisse", "Allemagne", "Autriche"], correct: 1 },
  { q: "Quelle marque a pour logo un chevron double (deux chevrons superposés) ?", choices: ["Peugeot", "Citroën", "DS", "Opel"], correct: 1 },
  { q: "Quelle entreprise américaine de logiciels a créé le système Windows ?", choices: ["Apple", "Microsoft", "Oracle", "Adobe"], correct: 1 },
  { q: "Quelle marque de bière irlandaise brune a une harpe pour emblème ?", choices: ["Heineken", "Guinness", "Carlsberg", "Kronenbourg"], correct: 1 },
  { q: "Quel personnage barbu en rouge est associé aux publicités de Coca-Cola à Noël ?", choices: ["Le Père Fouettard", "Le Père Noël", "Saint Nicolas", "Un lutin"], correct: 1 },
  { q: "Quelle marque de luxe a pour symbole un cheval tirant une calèche (mors et attelage) ?", choices: ["Hermès", "Gucci", "Longchamp", "Delvaux"], correct: 0 },
  { q: "Quel était le secteur d'activité de la société Samsung à ses origines, avant l'électronique ?", choices: ["Commerce (épicerie/textile)", "Automobile", "Banque", "Sidérurgie"], correct: 0 },
  { q: "Quelle marque de chaussures de sport japonaise a un nom acronyme signifiant « un esprit sain dans un corps sain » ?", choices: ["Mizuno", "Asics", "Onitsuka", "Yonex"], correct: 1 },
  { q: "Quel constructeur automobile allemand est associé à la ville de Wolfsburg ?", choices: ["BMW", "Volkswagen", "Mercedes", "Audi"], correct: 1 },
  { q: "Quelle chaîne de restauration a pour slogan « Have it your way » (à ta façon) ?", choices: ["McDonald's", "Burger King", "Subway", "Wendy's"], correct: 1 },
  { q: "Quelle entreprise de streaming a un logo « N » rouge sur fond noir ?", choices: ["Hulu", "Netflix", "Disney+", "HBO"], correct: 1 },
  { q: "Quel est le pays d'origine de la marque de bière Heineken ?", choices: ["Belgique", "Pays-Bas", "Allemagne", "Danemark"], correct: 1 },
  { q: "Quelle marque de luxe est célèbre pour ses foulards en soie et son orange caractéristique ?", choices: ["Hermès", "Chanel", "Dior", "Fendi"], correct: 0 },
  { q: "Quel personnage moustachu et chauve nettoie tout dans les publicités d'un produit ménager ?", choices: ["Monsieur Propre", "Le Géant Vert", "Bibendum", "Mister Clean Junior"], correct: 0 },
  { q: "Quelle marque automobile porte le nom de son fondateur Enzo, célèbre pour ses voitures de sport rouges ?", choices: ["Lamborghini", "Ferrari", "Maserati", "Pagani"], correct: 1 },
  { q: "Quel réseau social professionnel a un logo bleu avec les lettres « in » ?", choices: ["Viadeo", "LinkedIn", "Xing", "Indeed"], correct: 1 },
  { q: "Quelle marque de café en dosettes a pour égérie publicitaire un célèbre acteur disant « What else ? » ?", choices: ["Senseo", "Nespresso", "Tassimo", "Dolce Gusto"], correct: 1 },
  { q: "Quel est le secteur d'activité de la société Bayer ?", choices: ["Chimie et pharmacie", "Automobile", "Textile", "Banque"], correct: 0 },
  { q: "Quelle marque de sport française a pour logo un coq ?", choices: ["Lacoste", "Le Coq Sportif", "Airness", "Eden Park"], correct: 1 },
  { q: "De quel pays est originaire la marque automobile Land Rover ?", choices: ["États-Unis", "Royaume-Uni", "Allemagne", "Japon"], correct: 1 },
  { q: "Quelle entreprise a pour slogan « I'm lovin' it » (« C'est tout ce que j'aime ») ?", choices: ["KFC", "McDonald's", "Burger King", "Subway"], correct: 1 },
  { q: "Quelle marque de stylos et briquets française porte un nom de trois lettres ?", choices: ["Bic", "Waterman", "Reynolds", "Pilot"], correct: 0 },
  { q: "Quel logo représente trois diamants (losanges) assemblés ?", choices: ["Mazda", "Mitsubishi", "Subaru", "Suzuki"], correct: 1 },
  { q: "Quelle marque de luxe italienne a pour logo un triangle inversé sur ses sacs ?", choices: ["Prada", "Gucci", "Bottega Veneta", "Miu Miu"], correct: 0 },
  { q: "Quelle entreprise a popularisé le slogan « Parce que vous le valez bien » ?", choices: ["Nivea", "L'Oréal", "Garnier", "Yves Rocher"], correct: 1 },
  { q: "Quel toucan est la mascotte des céréales Froot Loops ?", choices: ["Toucan Sam", "Woody", "Zazu", "Rio"], correct: 0 },
  { q: "De quel pays est originaire la marque de meubles et décoration Muji ?", choices: ["Chine", "Japon", "Corée du Sud", "Singapour"], correct: 1 },
  { q: "Quelle marque automobile américaine a pour emblème un ovale bleu ?", choices: ["Chevrolet", "Ford", "Dodge", "Chrysler"], correct: 1 },
];
