/* Quiz — banque ARTS & CULTURE (littérature, peinture, musique, cinéma, langues, mythologie).
   correct = index de la bonne réponse (0-based). Réponses vérifiées. */
export const Q_CULTURE = [
  { q: "Qui a écrit « Le Comte de Monte-Cristo » ?", choices: ["Alexandre Dumas", "Victor Hugo", "Jules Verne", "Balzac"], correct: 0 },
  { q: "Qui a écrit « Les Trois Mousquetaires » ?", choices: ["Victor Hugo", "Alexandre Dumas", "Émile Zola", "Stendhal"], correct: 1 },
  { q: "Qui a écrit « Madame Bovary » ?", choices: ["Balzac", "Zola", "Gustave Flaubert", "Maupassant"], correct: 2 },
  { q: "Qui a écrit « Germinal » ?", choices: ["Hugo", "Maupassant", "Flaubert", "Émile Zola"], correct: 3 },
  { q: "Qui a écrit « Le Rouge et le Noir » ?", choices: ["Stendhal", "Balzac", "Flaubert", "Zola"], correct: 0 },
  { q: "Quel auteur a créé la saga « Vingt mille lieues sous les mers » ?", choices: ["Hugo", "Jules Verne", "Dumas", "Maupassant"], correct: 1 },
  { q: "Qui a écrit « À la recherche du temps perdu » ?", choices: ["Camus", "Gide", "Marcel Proust", "Sartre"], correct: 2 },
  { q: "Qui a écrit « L'Étranger » ?", choices: ["Sartre", "Malraux", "Gide", "Albert Camus"], correct: 3 },
  { q: "Qui a écrit « Les Fleurs du mal » ?", choices: ["Charles Baudelaire", "Rimbaud", "Verlaine", "Mallarmé"], correct: 0 },
  { q: "Quel poète a écrit « Le Bateau ivre » à seulement 16 ans ?", choices: ["Baudelaire", "Arthur Rimbaud", "Verlaine", "Apollinaire"], correct: 1 },
  { q: "Qui a écrit la pièce « Cyrano de Bergerac » ?", choices: ["Molière", "Racine", "Edmond Rostand", "Corneille"], correct: 2 },
  { q: "Quel dramaturge a écrit « Le Misanthrope » et « Tartuffe » ?", choices: ["Racine", "Corneille", "Beaumarchais", "Molière"], correct: 3 },
  { q: "Quel écrivain a créé le personnage de Gargantua ?", choices: ["Rabelais", "Montaigne", "Ronsard", "Villon"], correct: 0 },
  { q: "Qui a écrit « Le Petit Prince » ?", choices: ["Camus", "Saint-Exupéry", "Giono", "Pagnol"], correct: 1 },
  { q: "Quel auteur britannique a écrit « Roméo et Juliette » ?", choices: ["Dickens", "Wilde", "Shakespeare", "Byron"], correct: 2 },
  { q: "Qui a écrit la saga « Harry Potter » ?", choices: ["Tolkien", "C.S. Lewis", "Roald Dahl", "J.K. Rowling"], correct: 3 },
  { q: "Qui a écrit « Le Seigneur des anneaux » ?", choices: ["J.R.R. Tolkien", "George R.R. Martin", "C.S. Lewis", "Ursula K. Le Guin"], correct: 0 },
  { q: "Quel auteur a écrit « 1984 » ?", choices: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"], correct: 1 },
  { q: "Quel auteur russe a écrit « Guerre et Paix » ?", choices: ["Dostoïevski", "Tchekhov", "Léon Tolstoï", "Gogol"], correct: 2 },
  { q: "Quel auteur russe a écrit « Crime et Châtiment » ?", choices: ["Tolstoï", "Tchekhov", "Pouchkine", "Dostoïevski"], correct: 3 },
  { q: "Quel détective a été créé par Arthur Conan Doyle ?", choices: ["Sherlock Holmes", "Hercule Poirot", "Maigret", "Arsène Lupin"], correct: 0 },
  { q: "Quelle romancière a créé le détective Hercule Poirot ?", choices: ["P.D. James", "Agatha Christie", "Patricia Highsmith", "Ruth Rendell"], correct: 1 },
  { q: "Quel gentleman cambrioleur a été créé par Maurice Leblanc ?", choices: ["Fantômas", "Rocambole", "Arsène Lupin", "Rouletabille"], correct: 2 },
  { q: "Quel commissaire est le héros des romans de Georges Simenon ?", choices: ["Bourrel", "San-Antonio", "Navarro", "Maigret"], correct: 3 },
  { q: "Qui a peint « La Joconde » ?", choices: ["Léonard de Vinci", "Raphaël", "Michel-Ange", "Botticelli"], correct: 0 },
  { q: "Qui a peint « La Nuit étoilée » ?", choices: ["Monet", "Van Gogh", "Cézanne", "Gauguin"], correct: 1 },
  { q: "Qui a peint « Guernica » ?", choices: ["Dalí", "Miró", "Picasso", "Braque"], correct: 2 },
  { q: "Qui a peint « Les Nymphéas » ?", choices: ["Renoir", "Degas", "Manet", "Claude Monet"], correct: 3 },
  { q: "Quel peintre espagnol est célèbre pour ses montres molles ?", choices: ["Salvador Dalí", "Picasso", "Goya", "Vélasquez"], correct: 0 },
  { q: "Quel mouvement Monet a-t-il fondé avec son tableau « Impression, soleil levant » ?", choices: ["Le cubisme", "L'impressionnisme", "Le fauvisme", "Le surréalisme"], correct: 1 },
  { q: "Quel peintre néerlandais a peint « La Jeune Fille à la perle » ?", choices: ["Rembrandt", "Van Gogh", "Vermeer", "Bosch"], correct: 2 },
  { q: "Quel peintre a fondé le cubisme avec Picasso ?", choices: ["Matisse", "Léger", "Gris", "Georges Braque"], correct: 3 },
  { q: "Qui a sculpté « Le Penseur » ?", choices: ["Auguste Rodin", "Camille Claudel", "Giacometti", "Maillol"], correct: 0 },
  { q: "Qui a peint le plafond de la chapelle Sixtine ?", choices: ["Raphaël", "Michel-Ange", "Léonard de Vinci", "Le Titien"], correct: 1 },
  { q: "Quel peintre a coupé une partie de sa propre oreille ?", choices: ["Gauguin", "Cézanne", "Van Gogh", "Toulouse-Lautrec"], correct: 2 },
  { q: "Quel artiste a peint la « Marilyn Monroe » multicolore façon pop art ?", choices: ["Lichtenstein", "Basquiat", "Hockney", "Andy Warhol"], correct: 3 },
  { q: "Quel compositeur autrichien, enfant prodige, a écrit « La Flûte enchantée » ?", choices: ["Mozart", "Haydn", "Schubert", "Beethoven"], correct: 0 },
  { q: "Quel compositeur allemand est devenu sourd mais a continué à composer ?", choices: ["Bach", "Beethoven", "Brahms", "Wagner"], correct: 1 },
  { q: "Quel compositeur baroque allemand a écrit « Les Quatre Saisons » ? (attention !)", choices: ["Bach", "Haendel", "Vivaldi", "Telemann"], correct: 2 },
  { q: "De quel pays était le compositeur Frédéric Chopin d'origine ?", choices: ["La France", "L'Autriche", "La Hongrie", "La Pologne"], correct: 3 },
  { q: "Quel instrument à clavier a 88 touches ?", choices: ["Le piano", "L'orgue", "L'accordéon", "Le clavecin"], correct: 0 },
  { q: "Combien de cordes possède un violon ?", choices: ["6", "4", "5", "7"], correct: 1 },
  { q: "Quel instrument de la famille des cuivres est le plus grave ?", choices: ["La trompette", "Le cor", "Le tuba", "Le trombone"], correct: 2 },
  { q: "Quelle famille d'instruments comprend la flûte et la clarinette ?", choices: ["Les cuivres", "Les percussions", "Les cordes", "Les bois"], correct: 3 },
  { q: "Combien de musiciens compte un quatuor ?", choices: ["4", "2", "3", "5"], correct: 0 },
  { q: "Quel groupe britannique a chanté « Let It Be » ?", choices: ["The Rolling Stones", "The Beatles", "The Who", "Pink Floyd"], correct: 1 },
  { q: "Quel groupe a chanté « Bohemian Rhapsody » ?", choices: ["Led Zeppelin", "The Beatles", "Queen", "The Doors"], correct: 2 },
  { q: "Qui est surnommé « le King » du rock'n'roll ?", choices: ["Chuck Berry", "Little Richard", "Buddy Holly", "Elvis Presley"], correct: 3 },
  { q: "Quel chanteur américain est surnommé « le King of Pop » ?", choices: ["Michael Jackson", "Prince", "Stevie Wonder", "James Brown"], correct: 0 },
  { q: "Quelle chanteuse a interprété « Rolling in the Deep » ?", choices: ["Beyoncé", "Adele", "Rihanna", "Amy Winehouse"], correct: 1 },
  { q: "Quel groupe suédois a chanté « Dancing Queen » ?", choices: ["Roxette", "Ace of Base", "ABBA", "Europe"], correct: 2 },
  { q: "Quelle chanteuse française a interprété « Non, je ne regrette rien » ?", choices: ["Dalida", "Barbara", "Mireille Mathieu", "Édith Piaf"], correct: 3 },
  { q: "Quel chanteur belge a écrit « Ne me quitte pas » ?", choices: ["Jacques Brel", "Adamo", "Stromae", "Arno"], correct: 0 },
  { q: "Quel chanteur français est l'auteur de « Comme d'habitude » (adaptée en « My Way ») ?", choices: ["Aznavour", "Claude François", "Johnny Hallyday", "Michel Sardou"], correct: 1 },
  { q: "Quel artiste belge a chanté « Alors on danse » et « Papaoutai » ?", choices: ["Angèle", "Damso", "Stromae", "Orelsan"], correct: 2 },
  { q: "Quel groupe français a chanté « Aux Champs-Élysées » ? (interprète)", choices: ["Michel Fugain", "Michel Delpech", "Sacha Distel", "Joe Dassin"], correct: 3 },
  { q: "Quel réalisateur a tourné « E.T. » et « Jurassic Park » ?", choices: ["Steven Spielberg", "George Lucas", "James Cameron", "Ridley Scott"], correct: 0 },
  { q: "Quel réalisateur a créé la saga « Star Wars » ?", choices: ["Spielberg", "George Lucas", "Kubrick", "Coppola"], correct: 1 },
  { q: "Quel film de James Cameron a longtemps détenu le record du box-office ?", choices: ["Titanic", "Terminator", "Avatar", "Aliens"], correct: 2 },
  { q: "Quel acteur incarne Jack dans « Titanic » ?", choices: ["Brad Pitt", "Matt Damon", "Johnny Depp", "Leonardo DiCaprio"], correct: 3 },
  { q: "Quel studio d'animation a créé « Le Voyage de Chihiro » ?", choices: ["Le studio Ghibli", "Pixar", "DreamWorks", "Disney"], correct: 0 },
  { q: "Quel est le premier long-métrage entièrement en images de synthèse (Pixar, 1995) ?", choices: ["Shrek", "Toy Story", "Le Roi lion", "Nemo"], correct: 1 },
  { q: "Quel réalisateur est surnommé « le maître du suspense » ?", choices: ["Kubrick", "Scorsese", "Alfred Hitchcock", "Tarantino"], correct: 2 },
  { q: "Quel film de 1972 raconte l'histoire de la famille Corleone ?", choices: ["Les Affranchis", "Scarface", "Casino", "Le Parrain"], correct: 3 },
  { q: "Quel acteur joue le rôle-titre dans « Forrest Gump » ?", choices: ["Tom Hanks", "Tom Cruise", "Kevin Costner", "Robin Williams"], correct: 0 },
  { q: "Quelle actrice tient le fouet dans « Kill Bill » ? (rôle principal)", choices: ["Angelina Jolie", "Uma Thurman", "Scarlett Johansson", "Charlize Theron"], correct: 1 },
  { q: "Quel réalisateur français a tourné « Amélie Poulain » ?", choices: ["Luc Besson", "Jacques Audiard", "Jean-Pierre Jeunet", "Michel Gondry"], correct: 2 },
  { q: "Quelle comédie française réunit les Ch'tis et le Sud en 2008 ?", choices: ["Les Visiteurs", "La Grande Vadrouille", "Le Dîner de cons", "Bienvenue chez les Ch'tis"], correct: 3 },
  { q: "Quel personnage vit dans un ananas au fond de l'océan ?", choices: ["Bob l'éponge", "Némo", "Dory", "Sébastien"], correct: 0 },
  { q: "Quelle princesse Disney perd une pantoufle de verre ?", choices: ["Blanche-Neige", "Cendrillon", "Belle", "Raiponce"], correct: 1 },
  { q: "Dans quel dessin animé retrouve-t-on Simba et Mufasa ?", choices: ["Le Livre de la jungle", "Bambi", "Le Roi lion", "Tarzan"], correct: 2 },
  { q: "Quel personnage de dessin animé mange des épinards pour devenir fort ?", choices: ["Titi", "Bugs Bunny", "Tom", "Popeye"], correct: 3 },
  { q: "Quelle est la langue la plus parlée au monde (locuteurs natifs) ?", choices: ["Le mandarin", "L'anglais", "L'espagnol", "Le hindi"], correct: 0 },
  { q: "Dans quel pays parle-t-on le portugais comme langue officielle, en Amérique du Sud ?", choices: ["L'Argentine", "Le Brésil", "Le Chili", "La Colombie"], correct: 1 },
  { q: "Quelle langue est officielle en Autriche ?", choices: ["L'autrichien", "Le hongrois", "L'allemand", "Le tchèque"], correct: 2 },
  { q: "Combien de lettres compte l'alphabet grec ?", choices: ["21", "26", "28", "24"], correct: 3 },
  { q: "Quelle langue ancienne est à l'origine de la plupart des mots scientifiques, avec le grec ?", choices: ["Le latin", "L'hébreu", "L'arabe", "Le sanskrit"], correct: 0 },
  { q: "Comment dit-on « merci » en espagnol ?", choices: ["Grazie", "Gracias", "Obrigado", "Danke"], correct: 1 },
  { q: "Comment dit-on « bonjour » en italien ?", choices: ["Hola", "Guten Tag", "Buongiorno", "Bom dia"], correct: 2 },
  { q: "Comment dit-on « au revoir » en allemand ?", choices: ["Ciao", "Adios", "Arrivederci", "Auf Wiedersehen"], correct: 3 },
  { q: "Dans la mythologie grecque, qui est le roi des dieux ?", choices: ["Zeus", "Poséidon", "Hadès", "Apollon"], correct: 0 },
  { q: "Quel dieu grec règne sur les mers ?", choices: ["Zeus", "Poséidon", "Hermès", "Arès"], correct: 1 },
  { q: "Quel dieu grec règne sur les Enfers ?", choices: ["Zeus", "Poséidon", "Hadès", "Cronos"], correct: 2 },
  { q: "Quelle déesse grecque incarne l'amour et la beauté ?", choices: ["Athéna", "Héra", "Artémis", "Aphrodite"], correct: 3 },
  { q: "Quel héros grec a un talon comme unique point faible ?", choices: ["Achille", "Ulysse", "Hercule", "Persée"], correct: 0 },
  { q: "Quel héros grec a accompli douze travaux ?", choices: ["Thésée", "Héraclès (Hercule)", "Jason", "Persée"], correct: 1 },
  { q: "Quel monstre grec avait des serpents à la place des cheveux ?", choices: ["La Chimère", "Le Minotaure", "Méduse", "L'Hydre"], correct: 2 },
  { q: "Quel héros grec a tué le Minotaure dans le labyrinthe ?", choices: ["Persée", "Achille", "Jason", "Thésée"], correct: 3 },
  { q: "Comment s'appelle le dieu romain équivalent de Zeus ?", choices: ["Jupiter", "Neptune", "Mars", "Mercure"], correct: 0 },
  { q: "Quel dieu romain de la guerre a donné son nom à une planète et un mois ?", choices: ["Jupiter", "Mars", "Vénus", "Saturne"], correct: 1 },
  { q: "Dans la mythologie nordique, qui est le dieu du tonnerre ?", choices: ["Odin", "Loki", "Thor", "Freyr"], correct: 2 },
  { q: "Quel est le dieu principal, borgne, de la mythologie nordique ?", choices: ["Thor", "Loki", "Baldr", "Odin"], correct: 3 },
  { q: "Dans la mythologie égyptienne, quel dieu a une tête de faucon ?", choices: ["Horus", "Anubis", "Rê", "Seth"], correct: 0 },
  { q: "Quel dieu égyptien à tête de chacal veille sur les morts ?", choices: ["Horus", "Anubis", "Osiris", "Thot"], correct: 1 },
  { q: "Quel oiseau mythique renaît de ses cendres ?", choices: ["L'aigle", "Le griffon", "Le phénix", "Le corbeau"], correct: 2 },
  { q: "Quelle créature mythique est mi-homme mi-cheval ?", choices: ["Le minotaure", "Le satyre", "Le faune", "Le centaure"], correct: 3 },
  { q: "Quel roi légendaire a retiré l'épée Excalibur du rocher ?", choices: ["Le roi Arthur", "Charlemagne", "Roland", "Lancelot"], correct: 0 },
  { q: "Quel magicien conseille le roi Arthur ?", choices: ["Gandalf", "Merlin", "Morgane", "Dumbledore"], correct: 1 },
  { q: "Quel prix littéraire français est le plus prestigieux ?", choices: ["Le prix Femina", "Le prix Renaudot", "Le prix Goncourt", "Le prix Médicis"], correct: 2 },
  { q: "Quel prix récompense chaque année des œuvres dans plusieurs domaines dont la paix ?", choices: ["Le prix Pulitzer", "Le prix Booker", "Le César", "Le prix Nobel"], correct: 3 },
  { q: "Quelle récompense couronne les meilleurs films américains chaque année ?", choices: ["Les Oscars", "Les César", "Les BAFTA", "Les Golden Globes"], correct: 0 },
  { q: "Quelle récompense couronne les meilleurs films français ?", choices: ["Les Oscars", "Les César", "Les Molières", "Les Victoires"], correct: 1 },
  { q: "Quel festival de cinéma décerne la Palme d'or ?", choices: ["Venise", "Berlin", "Cannes", "Deauville"], correct: 2 },
  { q: "Quelle récompense honore le théâtre en France ?", choices: ["Les César", "Les Victoires", "Les Oscars", "Les Molières"], correct: 3 },
  { q: "Quel style musical est né à La Nouvelle-Orléans au début du XXe siècle ?", choices: ["Le jazz", "Le rock", "La soul", "Le blues"], correct: 0 },
  { q: "Quel style musical jamaïcain a été popularisé par Bob Marley ?", choices: ["Le ska", "Le reggae", "Le calypso", "Le dancehall"], correct: 1 },
  { q: "De quel pays le flamenco est-il originaire ?", choices: ["Le Portugal", "L'Italie", "L'Espagne", "Le Mexique"], correct: 2 },
  { q: "Quel style de danse et de musique est associé à l'Argentine ?", choices: ["La salsa", "La samba", "Le fado", "Le tango"], correct: 3 },
  { q: "Quel écrivain a créé le personnage de Tarzan ?", choices: ["Edgar Rice Burroughs", "Kipling", "Conan Doyle", "Jack London"], correct: 0 },
  { q: "Quel auteur a écrit « Le Livre de la jungle » ?", choices: ["Jack London", "Rudyard Kipling", "Robert Louis Stevenson", "Daniel Defoe"], correct: 1 },
  { q: "Quel roman met en scène un naufragé nommé Robinson Crusoé ?", choices: ["L'Île au trésor", "Vendredi", "Robinson Crusoé", "Moby Dick"], correct: 2 },
  { q: "Quel capitaine poursuit une baleine blanche dans « Moby Dick » ?", choices: ["Nemo", "Crochet", "Flint", "Achab"], correct: 3 },
  { q: "Quel auteur a écrit « Notre-Dame de Paris » ?", choices: ["Victor Hugo", "Balzac", "Zola", "Dumas"], correct: 0 },
  { q: "Comment s'appelle le sonneur de cloches de Notre-Dame de Paris ?", choices: ["Frollo", "Quasimodo", "Phœbus", "Gringoire"], correct: 1 },
  { q: "Qui a composé « La Marche turque » ?", choices: ["Beethoven", "Bach", "Mozart", "Haydn"], correct: 2 },
  { q: "Quelle œuvre de Beethoven contient « l'Ode à la joie » ?", choices: ["La 5e Symphonie", "La 3e Symphonie", "La 6e Symphonie", "La 9e Symphonie"], correct: 3 },
  { q: "Quelle mélodie de Beethoven est mondialement connue par ses quatre notes initiales ?", choices: ["La 5e Symphonie", "La Lettre à Élise", "La 9e Symphonie", "Le Clair de lune"], correct: 0 },
  { q: "Quel compositeur français a écrit « Boléro » ?", choices: ["Debussy", "Maurice Ravel", "Saint-Saëns", "Fauré"], correct: 1 },
  { q: "Quel compositeur français est célèbre pour « Clair de lune » ?", choices: ["Ravel", "Berlioz", "Claude Debussy", "Bizet"], correct: 2 },
  { q: "Quel opéra de Bizet met en scène une cigarière andalouse ?", choices: ["La Traviata", "Aïda", "Tosca", "Carmen"], correct: 3 },
  { q: "Quel peintre norvégien a réalisé « Le Cri » ?", choices: ["Edvard Munch", "Klimt", "Schiele", "Kandinsky"], correct: 0 },
  { q: "Quel peintre autrichien a réalisé « Le Baiser » recouvert d'or ?", choices: ["Munch", "Gustav Klimt", "Schiele", "Kokoschka"], correct: 1 },
  { q: "Quel artiste de rue britannique reste anonyme et fait des pochoirs politiques ?", choices: ["Shepard Fairey", "Jean-Michel Basquiat", "Banksy", "Keith Haring"], correct: 2 },
  { q: "Quel style architectural se caractérise par des arcs-boutants et de grandes cathédrales ?", choices: ["Le roman", "Le baroque", "Le classique", "Le gothique"], correct: 3 },
  { q: "Quel musée parisien est installé dans une ancienne gare ?", choices: ["Le musée d'Orsay", "Le Louvre", "Le Centre Pompidou", "Le musée Rodin"], correct: 0 },
  { q: "Quel célèbre tableau est exposé au musée du Louvre ?", choices: ["Le Cri", "La Joconde", "La Nuit étoilée", "Guernica"], correct: 1 },
  { q: "Quelle danseuse était le sujet favori des tableaux d'Edgar Degas ?", choices: ["Les chanteuses", "Les actrices", "Les ballerines", "Les couturières"], correct: 2 },
  { q: "Quel instrument Django Reinhardt, légende du jazz, jouait-il ?", choices: ["Le piano", "La trompette", "La contrebasse", "La guitare"], correct: 3 },
  { q: "Quel auteur a écrit « Le Vieil Homme et la Mer » ?", choices: ["Ernest Hemingway", "Steinbeck", "Faulkner", "Fitzgerald"], correct: 0 },
  { q: "Quel roman de F. Scott Fitzgerald décrit les Années folles américaines ?", choices: ["Tendre est la nuit", "Gatsby le Magnifique", "L'Envers du paradis", "Le Dernier Nabab"], correct: 1 },
  { q: "Quel écrivain a créé James Bond ?", choices: ["John le Carré", "Frederick Forsyth", "Ian Fleming", "Tom Clancy"], correct: 2 },
  { q: "Quel numéro d'agent secret est associé à James Bond ?", choices: ["001", "003", "008", "007"], correct: 3 },
  { q: "Quel écrivain danois est célèbre pour ses contes comme « La Petite Sirène » ?", choices: ["Andersen", "Perrault", "Les frères Grimm", "La Fontaine"], correct: 0 },
  { q: "Quel auteur français est célèbre pour ses fables mettant en scène des animaux ?", choices: ["Perrault", "Jean de La Fontaine", "Voltaire", "Molière"], correct: 1 },
  { q: "Quel auteur a écrit les contes « Cendrillon » et « Le Chat botté » ?", choices: ["Andersen", "Grimm", "Charles Perrault", "La Fontaine"], correct: 2 },
  { q: "Quel philosophe grec est l'auteur de « La République » ?", choices: ["Socrate", "Aristote", "Épicure", "Platon"], correct: 3 },
  { q: "Quel philosophe des Lumières a écrit « Candide » ?", choices: ["Voltaire", "Rousseau", "Diderot", "Montesquieu"], correct: 0 },
  { q: "Quel philosophe a écrit « Du contrat social » ?", choices: ["Voltaire", "Jean-Jacques Rousseau", "Kant", "Hobbes"], correct: 1 },
  { q: "Quel philosophe a dit « Je pense, donc je suis » ?", choices: ["Pascal", "Kant", "Descartes", "Spinoza"], correct: 2 },
  { q: "Quelle célèbre statue grecque, sans bras, est exposée au Louvre ?", choices: ["La Victoire de Samothrace", "Le Discobole", "L'Aurige", "La Vénus de Milo"], correct: 3 },
  { q: "Quel groupe de rock a pour chanteur Mick Jagger ?", choices: ["The Rolling Stones", "The Who", "Led Zeppelin", "The Kinks"], correct: 0 },
  { q: "Quel guitariste légendaire a joué à Woodstock en 1969 ?", choices: ["Eric Clapton", "Jimi Hendrix", "Jimmy Page", "Carlos Santana"], correct: 1 },
  { q: "Quel groupe irlandais a pour chanteur Bono ?", choices: ["Coldplay", "Oasis", "U2", "The Cranberries"], correct: 2 },
  { q: "Quelle chanteuse est surnommée « la Môme » ?", choices: ["Dalida", "Barbara", "Juliette Gréco", "Édith Piaf"], correct: 3 },
  { q: "Quel film d'animation Disney met en scène une reine des glaces nommée Elsa ?", choices: ["La Reine des neiges", "Raiponce", "Vaiana", "Rebelle"], correct: 0 },
  { q: "Quel super-héros est aussi le milliardaire Bruce Wayne ?", choices: ["Superman", "Batman", "Iron Man", "Spider-Man"], correct: 1 },
  { q: "Quel super-héros est mordu par une araignée radioactive ?", choices: ["Batman", "Hulk", "Spider-Man", "Daredevil"], correct: 2 },
  { q: "Quel réalisateur a tourné « Pulp Fiction » et « Django Unchained » ?", choices: ["Scorsese", "Fincher", "Nolan", "Quentin Tarantino"], correct: 3 },
  { q: "Quel réalisateur britannique a tourné « Inception » et « Interstellar » ?", choices: ["Christopher Nolan", "Ridley Scott", "Danny Boyle", "Guy Ritchie"], correct: 0 },
  { q: "Quelle trilogie de Peter Jackson se déroule en Terre du Milieu ?", choices: ["Harry Potter", "Le Seigneur des anneaux", "Narnia", "À la croisée des mondes"], correct: 1 },
  { q: "Quelle saga de science-fiction met en scène les Jedi et les Sith ?", choices: ["Star Trek", "Dune", "Star Wars", "Battlestar Galactica"], correct: 2 },
  { q: "Quel dessinateur belge a créé Tintin ?", choices: ["Peyo", "Franquin", "Morris", "Hergé"], correct: 3 },
  { q: "Quel dessinateur a créé les Schtroumpfs ?", choices: ["Peyo", "Uderzo", "Goscinny", "Hergé"], correct: 0 },
  { q: "Quels héros gaulois résistent aux Romains grâce à une potion magique ?", choices: ["Tintin et Milou", "Astérix et Obélix", "Lucky Luke", "Gaston Lagaffe"], correct: 1 },
  { q: "Quel cowboy de BD « tire plus vite que son ombre » ?", choices: ["Blueberry", "Buck Danny", "Lucky Luke", "Jerry Spring"], correct: 2 },
  { q: "Quelle BD franco-belge suit un jeune reporter et son chien blanc ?", choices: ["Spirou", "Gaston", "Boule et Bill", "Tintin"], correct: 3 },
  { q: "Quel manga culte suit un ninja hyperactif rêvant de devenir Hokage ?", choices: ["Naruto", "One Piece", "Bleach", "Dragon Ball"], correct: 0 },
  { q: "Quel manga suit Luffy et son équipage de pirates au chapeau de paille ?", choices: ["Naruto", "One Piece", "Fairy Tail", "Hunter x Hunter"], correct: 1 },
  { q: "Quel personnage de manga cherche les Dragon Balls ?", choices: ["Naruto", "Luffy", "Son Goku", "Ichigo"], correct: 2 },
  { q: "Quel chef-d'œuvre du Louvre a été volé en 1911 puis retrouvé ?", choices: ["La Vénus de Milo", "Le Radeau de la Méduse", "Le Sacre de Napoléon", "La Joconde"], correct: 3 },
];
