/* Quiz — MUSIQUE, 2e vague (classique, rock, chanson française, rap, solfège).
   Format compact : [niveau, question, BONNE RÉPONSE, leurre, leurre, leurre] (ordre des
   choix tiré au hasard à l'affichage).
   Niveau : 1 facile, 2 moyen, 3 expert. */
const Q = [
  [2, "Combien de symphonies Beethoven a-t-il composées ?", "9", "5", "7", "12"],
  [1, "Quel compositeur a écrit l'opéra « Carmen » ?", "Georges Bizet", "Giuseppe Verdi", "Giacomo Puccini", "Jules Massenet"],
  [2, "Quel compositeur a écrit la musique du ballet « Le Lac des cygnes » ?", "Piotr Ilitch Tchaïkovski", "Igor Stravinsky", "Sergueï Prokofiev", "Maurice Ravel"],
  [2, "Quel compositeur italien a écrit « La Traviata » ?", "Giuseppe Verdi", "Giacomo Puccini", "Gioachino Rossini", "Vincenzo Bellini"],
  [2, "Quel compositeur allemand a écrit le cycle « L'Anneau du Nibelung » ?", "Richard Wagner", "Johannes Brahms", "Robert Schumann", "Richard Strauss"],
  [3, "Quel compositeur a écrit l'oratorio « Le Messie » et son « Alléluia » ?", "Georg Friedrich Haendel", "Jean-Sébastien Bach", "Joseph Haydn", "Antonio Vivaldi"],
  [2, "Quel compositeur a écrit les « Variations Goldberg » ?", "Jean-Sébastien Bach", "Mozart", "Beethoven", "Haendel"],
  [3, "Quel compositeur français a écrit les « Gymnopédies » ?", "Erik Satie", "Claude Debussy", "Maurice Ravel", "Gabriel Fauré"],
  [2, "Quel compositeur a écrit « Le Carnaval des animaux » ?", "Camille Saint-Saëns", "Paul Dukas", "Maurice Ravel", "Hector Berlioz"],
  [3, "Quel compositeur a écrit le conte musical « Pierre et le Loup » ?", "Sergueï Prokofiev", "Igor Stravinsky", "Dmitri Chostakovitch", "Nikolaï Rimski-Korsakov"],
  [3, "Quel compositeur a écrit « Le Sacre du printemps », qui fit scandale en 1913 ?", "Igor Stravinsky", "Sergueï Prokofiev", "Claude Debussy", "Maurice Ravel"],
  [3, "Quel compositeur a écrit la « Symphonie fantastique » ?", "Hector Berlioz", "Camille Saint-Saëns", "César Franck", "Georges Bizet"],
  [3, "Quel compositeur italien a écrit l'opéra « Tosca » et « Madame Butterfly » ?", "Giacomo Puccini", "Giuseppe Verdi", "Gioachino Rossini", "Gaetano Donizetti"],
  [2, "Combien de lignes compte une portée musicale ?", "5", "4", "6", "7"],
  [1, "Quelle clé sert à lire les notes aiguës, comme celles du violon ?", "La clé de sol", "La clé de fa", "La clé d'ut", "La clé de la"],
  [2, "De quel instrument joue le virtuose Yo-Yo Ma ?", "Du violoncelle", "Du violon", "Du piano", "De l'alto"],
  [1, "Quel est le plus grave des instruments à cordes frottées de l'orchestre ?", "La contrebasse", "Le violoncelle", "L'alto", "La harpe"],
  [3, "Quel était le vrai nom de Freddie Mercury ?", "Farrokh Bulsara", "Fred Bulsar", "Freddie Mercurio", "Frederick Moore"],
  [1, "Quelle chanteuse est surnommée « la reine de la pop » ?", "Madonna", "Britney Spears", "Whitney Houston", "Mariah Carey"],
  [3, "Qui a été la dernière gagnante de l'Eurovision pour la France, en 1977 ?", "Marie Myriam", "Frida Boccara", "Patricia Kaas", "France Gall"],
  [3, "Quel pays a remporté l'Eurovision 2025 ?", "L'Autriche", "La Suède", "Israël", "La France"],
  [3, "Avec quelle chanson Slimane a-t-il représenté la France à l'Eurovision 2024 ?", "Mon amour", "Voilà", "Évidemment", "Mon cœur"],
  [2, "Quel rappeur caennais a sorti l'album « Civilisation » en 2021 ?", "Orelsan", "Nekfeu", "Vald", "Lomepal"],
  [1, "Quel groupe de rap marseillais a sorti « L'École du micro d'argent » ?", "IAM", "NTM", "Fonky Family", "Psy 4 de la rime"],
  [1, "Quel duo de rap réunissait JoeyStarr et Kool Shen ?", "Suprême NTM", "IAM", "Assassin", "Ministère A.M.E.R."],
  [1, "Quelle chanteuse a connu le succès en 2010 avec « Je veux » ?", "Zaz", "Zazie", "Nolwenn Leroy", "Camille"],
  [1, "Quelle chanteuse franco-malienne a fait un tube mondial avec « Djadja » ?", "Aya Nakamura", "Angèle", "Dadju", "Wejdene"],
  [1, "Quel DJ français a produit « Titanium » avec Sia ?", "David Guetta", "Bob Sinclar", "Martin Solveig", "DJ Snake"],
  [2, "Quel DJ français a produit « Turn Down for What » et « Taki Taki » ?", "DJ Snake", "David Guetta", "Kungs", "Petit Biscuit"],
  [2, "Quel chanteur a interprété « Le Poinçonneur des Lilas » ?", "Serge Gainsbourg", "Boris Vian", "Georges Brassens", "Jacques Dutronc"],
  [2, "Quel chanteur a interprété « Le Sud » en 1975 ?", "Nino Ferrer", "Joe Dassin", "Michel Delpech", "Christophe"],
  [2, "Qui est le chanteur du groupe Indochine ?", "Nicola Sirkis", "Bertrand Cantat", "Jean-Louis Aubert", "Thomas Bangalter"],
  [1, "Quel groupe chantait « L'Aventurier » en 1982 ?", "Indochine", "Téléphone", "Noir Désir", "Les Rita Mitsouko"],
  [1, "Quel groupe de rock français a été fondé par Jean-Louis Aubert et Louis Bertignac ?", "Téléphone", "Indochine", "Trust", "Noir Désir"],
  [2, "Quelle chanteuse a interprété « Résiste » et « Ella, elle l'a » ?", "France Gall", "Sylvie Vartan", "Véronique Sanson", "Jeanne Mas"],
  [2, "Quel festival de musique se tient chaque été à Carhaix, dans le Finistère ?", "Les Vieilles Charrues", "Les Eurockéennes", "Rock en Seine", "Les Francofolies"],
  [2, "Quel festival britannique géant se tient dans une ferme du Somerset ?", "Glastonbury", "Reading", "Coachella", "Download"],
  [1, "Quel festival se tient chaque printemps dans le désert californien ?", "Coachella", "Burning Man", "Lollapalooza", "Glastonbury"],
  [1, "Quelle chanteuse a été la plus écoutée au monde sur Spotify en 2023 et 2024 ?", "Taylor Swift", "Billie Eilish", "Beyoncé", "Adele"],
  [1, "Comment s'appelle la tournée record de Taylor Swift (2023-2024) ?", "The Eras Tour", "Reputation Tour", "Lover Fest", "1989 World Tour"],
  [1, "Quel rappeur canadien a sorti « Hotline Bling » et « God's Plan » ?", "Drake", "The Weeknd", "Kanye West", "Travis Scott"],
  [3, "Quel rappeur a gagné un prix Pulitzer de musique en 2018 ?", "Kendrick Lamar", "Jay-Z", "Eminem", "Kanye West"],
  [1, "Quel chanteur jamaïcain est la légende du reggae ?", "Bob Marley", "Peter Tosh", "Jimmy Cliff", "Burning Spear"],
  [1, "Quel rappeur américain se fait aussi appeler Slim Shady ?", "Eminem", "Snoop Dogg", "50 Cent", "Dr. Dre"],
  [1, "Quelle chanteuse est surnommée « Queen B » ?", "Beyoncé", "Rihanna", "Britney Spears", "Lady Gaga"],
];
export const Q3_MUSIQUE = Q.map(([d, q, ...choices]) => ({ d, q, choices, correct: 0 }));
