/* Quiz — banque TÉLÉ & MÉDIAS (émissions, animateurs, presse et radio françaises).
   Format compact : [question, BONNE RÉPONSE, leurre, leurre, leurre] (ordre des
   choix tiré au hasard à l'affichage). Du plus facile au plus difficile. */
const Q = [
  // — facile —
  ["Dans quel jeu télévisé les candidats affrontent-ils les énigmes du père Fouras ?", "Fort Boyard", "Koh-Lanta", "Intervilles", "Pékin Express"],
  ["Quel jeu d'aventure télévisé se déroule sur une île, avec des épreuves et des conseils d'élimination ?", "Koh-Lanta", "Fort Boyard", "Pékin Express", "Loft Story"],
  ["Quel jeu de culture générale Jean-Luc Reichmann présente-t-il à midi sur TF1 ?", "Les 12 Coups de midi", "Questions pour un champion", "Tout le monde veut prendre sa place", "Slam"],
  ["Quel journaliste présente « Questions pour un champion » depuis 2016 ?", "Samuel Étienne", "Julien Lepers", "Nagui", "Cyril Féraud"],
  ["Qui a présenté « Questions pour un champion » de 1988 à 2015 ?", "Julien Lepers", "Samuel Étienne", "Jean-Pierre Foucault", "Laurent Romejko"],
  ["Quel animateur présente « N'oubliez pas les paroles ! » ?", "Nagui", "Cyril Féraud", "Arthur", "Jean-Luc Reichmann"],
  ["Quel jeu demande d'estimer au plus près le prix d'objets ?", "Le Juste Prix", "Le Maillon faible", "Des chiffres et des lettres", "Motus"],
  ["Dans quel jeu fallait-il deviner des mots dans une grille et éviter la boule noire ?", "Motus", "Pyramide", "Des chiffres et des lettres", "Slam"],
  ["Dans quelle émission des coachs se retournent-ils dans leur fauteuil en écoutant des voix ?", "The Voice", "Nouvelle Star", "Star Academy", "La France a un incroyable talent"],
  ["Quelle émission de 2001 a enfermé des candidats dans un loft filmé jour et nuit ?", "Loft Story", "Secret Story", "Star Academy", "L'Île de la tentation"],
  ["Quel concours de cuisine télévisé oppose des chefs professionnels ?", "Top Chef", "MasterChef", "Le Meilleur Pâtissier", "Un dîner presque parfait"],
  ["Dans quelle émission des inconnus s'invitent-ils à dîner et se notent-ils ?", "Un dîner presque parfait", "Top Chef", "Cauchemar en cuisine", "Le Meilleur Pâtissier"],
  ["Quel chef présente « Cauchemar en cuisine » en France ?", "Philippe Etchebest", "Cyril Lignac", "Thierry Marx", "Jean-François Piège"],
  ["Quel journaliste a présenté le 20 h de TF1 de 1987 à 2008 ?", "Patrick Poivre d'Arvor", "Jean-Pierre Pernaut", "David Pujadas", "Laurent Delahousse"],
  ["Quel journaliste a présenté le 13 h de TF1 pendant 33 ans ?", "Jean-Pierre Pernaut", "Patrick Poivre d'Arvor", "Jean-Claude Narcy", "Yves Mourousi"],
  ["Dans quelle émission pour enfants vivait Casimir, un gentil dinosaure orange ?", "L'Île aux enfants", "Récré A2", "Le Club Dorothée", "Les Minikeums"],
  ["Quelle émission de TF1 a diffusé de nombreux dessins animés japonais dans les années 1990 ?", "Le Club Dorothée", "Récré A2", "Les Minikeums", "L'Île aux enfants"],
  ["Quelle émission satirique de Canal+ mettait en scène des marionnettes en latex ?", "Les Guignols de l'info", "Le Petit Journal", "Groland", "Nulle part ailleurs"],
  ["Sur quelle chaîne est diffusée l'émission « Quotidien » de Yann Barthès ?", "TMC", "TF1", "Canal+", "France 2"],
  ["Quelle chaîne française a été en 1984 la première chaîne payante du pays ?", "Canal+", "TF1", "M6", "Arte"],
  ["Quel journal satirique paraît chaque mercredi depuis 1915 ?", "Le Canard enchaîné", "Charlie Hebdo", "Le Monde", "Libération"],
  ["Quel est le grand quotidien sportif français ?", "L'Équipe", "Le Parisien", "Le Figaro", "Ouest-France"],
  ["Qui présente « Cash Investigation » sur France 2 ?", "Élise Lucet", "Anne-Sophie Lapix", "Léa Salamé", "Marie Drucker"],
  ["Quelle émission de vulgarisation scientifique Fred et Jamy présentaient-ils depuis leur camion ?", "C'est pas sorcier", "E=M6", "Le Monde de Jamy", "Les Escapades de Petitrenaud"],
  ["Quel feuilleton quotidien de France 3 se déroulait dans le quartier du Mistral, à Marseille ?", "Plus belle la vie", "Demain nous appartient", "Un si grand soleil", "Ici tout commence"],
  // — moyen —
  ["Quelle chaîne d'information en continu a été lancée en 2005 ?", "BFMTV", "LCI", "franceinfo", "CNews"],
  ["Quelle chaîne culturelle franco-allemande a été créée en 1992 ?", "Arte", "France 5", "TV5 Monde", "Euronews"],
  ["Quel est le quotidien régional le plus diffusé de France ?", "Ouest-France", "Le Parisien", "Sud Ouest", "La Voix du Nord"],
  ["Quel quotidien a été fondé en 1944 par Hubert Beuve-Méry ?", "Le Monde", "Libération", "Le Figaro", "L'Humanité"],
  ["Quel quotidien Jean-Paul Sartre a-t-il cofondé en 1973 ?", "Libération", "Le Monde", "L'Humanité", "Le Nouvel Observateur"],
  ["Quel est le plus ancien quotidien français encore publié, né en 1826 ?", "Le Figaro", "Le Monde", "La Croix", "Le Parisien"],
  ["Quelle agence de presse française est l'une des trois plus grandes du monde ?", "L'AFP", "Reuters", "Associated Press", "Bloomberg"],
  ["Quel animateur présente « Fort Boyard » depuis 2003 ?", "Olivier Minne", "Patrice Laffont", "Cyril Féraud", "Jean-Luc Reichmann"],
  ["Quel animateur a présenté « Qui veut gagner des millions ? » en France de 2000 à 2016 ?", "Jean-Pierre Foucault", "Arthur", "Nagui", "Jean-Luc Reichmann"],
  ["Quel petit homme de Fort Boyard apporte les clés aux candidats ?", "Passe-Partout", "Félindra", "La Boule", "Le père Fouras"],
  ["Comment s'appelle le personnage de Fort Boyard qui frappe le gong ?", "La Boule", "Passe-Partout", "Le père Fouras", "Félindra"],
  ["Quel animateur présente « Vivement dimanche » depuis 1998 ?", "Michel Drucker", "Jacques Martin", "Laurent Ruquier", "Michel Denisot"],
  ["Quel animateur de « L'École des fans » faisait chanter les enfants le dimanche ?", "Jacques Martin", "Michel Drucker", "Jean-Pierre Foucault", "Pascal Sevran"],
  ["Quel animateur présentait « La Chance aux chansons » ?", "Pascal Sevran", "Jacques Martin", "Michel Drucker", "Guy Lux"],
  ["Dans quelle émission de cuisine officiait la truculente Maïté ?", "La Cuisine des mousquetaires", "Bon appétit bien sûr", "Les Carnets de Julie", "Top Chef"],
  ["Quel grand chef présentait « Bon appétit bien sûr » ?", "Joël Robuchon", "Paul Bocuse", "Cyril Lignac", "Alain Ducasse"],
  ["Qui présente « Les Carnets de Julie » sur France 3 ?", "Julie Andrieu", "Julie Gayet", "Julie Depardieu", "Julie Zenatti"],
  ["Quelle émission de Stéphane Bern raconte la vie des grands personnages historiques ?", "Secrets d'histoire", "C'est pas sorcier", "Des racines et des ailes", "Faut pas rêver"],
  ["Quel magazine de M6 vulgarisait la science avec Mac Lesggy ?", "E=M6", "C'est pas sorcier", "Capital", "Zone interdite"],
  ["Quel magazine de M6 traite d'économie et de consommation depuis 1988 ?", "Capital", "Zone interdite", "Envoyé spécial", "Complément d'enquête"],
  ["Quel magazine de reportages de France 2 a été créé en 1990 ?", "Envoyé spécial", "Complément d'enquête", "Cash Investigation", "Zone interdite"],
  ["Quel animateur en noir a présenté « Tout le monde en parle » ?", "Thierry Ardisson", "Laurent Ruquier", "Marc-Olivier Fogiel", "Michel Field"],
  ["Quelle émission de Laurent Ruquier réunissait des chroniqueurs le samedi soir de 2006 à 2020 ?", "On n'est pas couché", "Tout le monde en parle", "C à vous", "Le Grand Journal"],
  ["Quel animateur a succédé à Philippe Bouvard aux « Grosses Têtes » de RTL en 2014 ?", "Laurent Ruquier", "Thierry Ardisson", "Christophe Dechavanne", "Arthur"],
  ["Quelle radio publique d'information en continu a été lancée en 1987 ?", "France Info", "France Inter", "RTL", "Europe 1"],
  ["Dans quelle ville se déroule le feuilleton « Demain nous appartient » ?", "Sète", "Marseille", "Montpellier", "Nice"],
  ["Dans quelle ville se déroule le feuilleton « Un si grand soleil » ?", "Montpellier", "Sète", "Marseille", "Toulouse"],
  ["Quel commandant de police télé était interprété par Roger Hanin ?", "Navarro", "Julie Lescaut", "Le commissaire Moulin", "Le commissaire Cordier"],
  ["Quel commissaire de télévision était interprété par Yves Rénier ?", "Le commissaire Moulin", "Navarro", "Maigret", "Le commissaire Cordier"],
  ["Quel jeu télévisé, né en 1965, est célèbre pour son épreuve « Le compte est bon » ?", "Des chiffres et des lettres", "Questions pour un champion", "Pyramide", "Motus"],
  ["Quel journaliste a repris la présentation du 20 h de TF1 en semaine en 2012 ?", "Gilles Bouleau", "Laurent Delahousse", "Julian Bugier", "David Pujadas"],
  // — difficile —
  ["Quelle chaîne, lancée en 1986 et disparue en 1992, fut la première chaîne privée gratuite de France ?", "La Cinq", "TV6", "M6", "Canal+"],
  ["En quelle année TF1 a-t-elle été privatisée ?", "1987", "1981", "1992", "1975"],
  ["En quelle année la télévision en couleur est-elle arrivée en France ?", "1967", "1957", "1977", "1972"],
  ["Quel procédé de télévision en couleur a été inventé en France ?", "Le SECAM", "Le PAL", "Le NTSC", "Le MPEG"],
  ["En quelle année la TNT, télévision numérique terrestre, a-t-elle été lancée en France ?", "2005", "1995", "2000", "2011"],
  ["Quel animateur était surnommé « Monsieur Cinéma » ?", "Pierre Tchernia", "Eddy Mitchell", "Jacques Martin", "Michel Drucker"],
  ["Quelle émission d'Eddy Mitchell diffusait de vieux films américains en double programme ?", "La Dernière Séance", "Le Cinéma de minuit", "Le Masque et la Plume", "Ciné-club"],
  ["Quelle émission de France Inter critique films et livres depuis 1955 ?", "Le Masque et la Plume", "Radioscopie", "Le Jeu des 1 000 euros", "Les Grosses Têtes"],
  ["Quel jeu radiophonique de France Inter, né en 1958, s'appelait autrefois « le jeu des 1 000 francs » ?", "Le Jeu des 1 000 euros", "Les Grosses Têtes", "La Bonne Paye", "Le Masque et la Plume"],
  ["Quels animateurs ont présenté « Intervilles » à ses débuts, en 1962 ?", "Guy Lux et Léon Zitrone", "Jacques Martin et Michel Drucker", "Jean-Pierre Foucault et Nagui", "Pierre Tchernia et Pierre Sabbagh"],
  ["Quelle émission pour ados de France 3 était animée par des marionnettes, de 1993 à 2002 ?", "Les Minikeums", "Le Club Dorothée", "Récré A2", "Hugo Délire"],
  ["Quel animateur présentait « Ça se discute », émission de société de France 2 ?", "Jean-Luc Delarue", "Thierry Ardisson", "Christophe Dechavanne", "Mireille Dumas"],
];
export const Q_TELE = Q.map(([q, ...choices]) => ({ q, choices, correct: 0 }));
