/* Quiz — SPORT, 2e vague (règles, records, champions récents, grands événements).
   Format compact : [niveau, question, BONNE RÉPONSE, leurre, leurre, leurre] (ordre des
   choix tiré au hasard à l'affichage).
   Niveau : 1 facile, 2 moyen, 3 expert. */
const Q = [
  [2, "Combien de points vaut une transformation au rugby ?", "2", "1", "3", "5"],
  [2, "Combien de joueurs compte une équipe de handball sur le terrain ?", "7", "5", "6", "11"],
  [2, "Comment appelle-t-on un trou réussi en un coup de moins que le par, au golf ?", "Un birdie", "Un eagle", "Un bogey", "Un albatros"],
  [1, "Quel joueur détient le record de titres du Grand Chelem en simple messieurs ?", "Novak Djokovic", "Rafael Nadal", "Roger Federer", "Pete Sampras"],
  [1, "Quel club a remporté le plus de Ligues des champions ?", "Le Real Madrid", "L'AC Milan", "Le Bayern Munich", "Liverpool"],
  [1, "Quel club français a remporté la Ligue des champions en 1993 ?", "L'Olympique de Marseille", "Le Paris Saint-Germain", "L'AS Monaco", "Les Girondins de Bordeaux"],
  [1, "Quel club a remporté la Ligue des champions 2025 ?", "Le Paris Saint-Germain", "L'Inter Milan", "Le Real Madrid", "Arsenal"],
  [1, "Quel joueur français a remporté le Ballon d'or 2022 ?", "Karim Benzema", "Kylian Mbappé", "Antoine Griezmann", "N'Golo Kanté"],
  [1, "Qui a marqué un triplé en finale de la Coupe du monde 2022 ?", "Kylian Mbappé", "Lionel Messi", "Olivier Giroud", "Julián Álvarez"],
  [3, "Combien de minutes dure un match de NBA, prolongations exclues ?", "48 minutes", "40 minutes", "60 minutes", "90 minutes"],
  [1, "Quel basketteur français a été choisi en premier lors de la draft NBA 2023 ?", "Victor Wembanyama", "Rudy Gobert", "Tony Parker", "Evan Fournier"],
  [2, "Dans quelle équipe NBA joue Victor Wembanyama ?", "Les San Antonio Spurs", "Les Los Angeles Lakers", "Les Boston Celtics", "Les Chicago Bulls"],
  [1, "Quel nageur français a remporté quatre titres olympiques individuels aux Jeux de Paris 2024 ?", "Léon Marchand", "Florent Manaudou", "Maxime Grousset", "Yannick Agnel"],
  [2, "Combien de médailles d'or la France a-t-elle remportées aux Jeux de Paris 2024 ?", "16", "10", "24", "33"],
  [1, "Quel est le record du monde du 100 m établi par Usain Bolt en 2009 ?", "9,58 s", "9,69 s", "9,79 s", "9,48 s"],
  [2, "Quel perchiste suédois bat régulièrement son propre record du monde ?", "Armand Duplantis", "Renaud Lavillenie", "Sergueï Bubka", "Sam Kendricks"],
  [1, "Quel biathlète français a remporté cinq titres olympiques ?", "Martin Fourcade", "Quentin Fillon Maillet", "Raphaël Poirée", "Simon Fourcade"],
  [1, "Quelle course cycliste est surnommée « l'Enfer du Nord » ?", "Paris-Roubaix", "Liège-Bastogne-Liège", "Le Tour des Flandres", "Milan-San Remo"],
  [1, "Quel maillot porte le meilleur grimpeur du Tour de France ?", "Le maillot à pois", "Le maillot vert", "Le maillot blanc", "Le maillot jaune"],
  [1, "Quel maillot récompense le classement par points du Tour de France ?", "Le maillot vert", "Le maillot à pois", "Le maillot blanc", "Le maillot rouge"],
  [1, "Lequel de ces coureurs a gagné cinq fois le Tour de France ?", "Bernard Hinault", "Laurent Fignon", "Greg LeMond", "Louison Bobet"],
  [2, "Quels pilotes détiennent le record de sept titres de champion du monde de F1 ?", "Michael Schumacher et Lewis Hamilton", "Ayrton Senna et Alain Prost", "Sebastian Vettel et Max Verstappen", "Juan Manuel Fangio et Lewis Hamilton"],
  [2, "Quel pilote a été champion du monde de F1 de 2021 à 2024 ?", "Max Verstappen", "Lewis Hamilton", "Charles Leclerc", "Lando Norris"],
  [2, "Quel pilote français a été quatre fois champion du monde de F1 ?", "Alain Prost", "Jean Alesi", "René Arnoux", "Pierre Gasly"],
  [3, "Quel skipper a remporté le Vendée Globe 2024-2025 ?", "Charlie Dalin", "Yoann Richomme", "Jean Le Cam", "Armel Le Cléac'h"],
  [2, "Quel art martial coréen privilégie les coups de pied ?", "Le taekwondo", "Le karaté", "Le kung-fu", "L'aïkido"],
  [2, "Combien de points faut-il pour gagner un set de badminton ?", "21", "11", "15", "25"],
  [2, "Combien de points faut-il pour gagner une manche de tennis de table ?", "11", "15", "21", "10"],
  [2, "Combien de joueurs compte une équipe de baseball sur le terrain ?", "9", "7", "10", "11"],
  [2, "Quel trophée récompense le vainqueur de la Coupe du monde de rugby ?", "La coupe Webb Ellis", "Le trophée Calcutta", "La coupe Bledisloe", "Le bouclier de Brennus"],
  [1, "Quel pays a remporté la Coupe du monde de rugby 2023 ?", "L'Afrique du Sud", "La Nouvelle-Zélande", "La France", "L'Angleterre"],
  [2, "Quel pays a remporté le plus de Coupes du monde de rugby ?", "L'Afrique du Sud", "La Nouvelle-Zélande", "L'Australie", "L'Angleterre"],
  [2, "Quel trophée récompense le champion de France de rugby ?", "Le bouclier de Brennus", "La coupe Webb Ellis", "La coupe Gambardella", "Le trophée Yves du Manoir"],
  [2, "Quel pays a remporté le Tournoi des Six Nations 2025 ?", "La France", "L'Irlande", "L'Angleterre", "L'Écosse"],
  [1, "Quel demi de mêlée français a été élu meilleur joueur du monde World Rugby en 2021 ?", "Antoine Dupont", "Romain Ntamack", "Grégory Alldritt", "Thomas Ramos"],
  [1, "Où se dérouleront les Jeux olympiques d'hiver de 2030 ?", "Dans les Alpes françaises", "À Salt Lake City", "En Suède", "À Sapporo"],
  [1, "Dans quelles villes se sont tenus les Jeux olympiques d'hiver de 2026 ?", "Milan et Cortina d'Ampezzo", "Turin et Sestrières", "Innsbruck et Kitzbühel", "Stockholm et Åre"],
  [1, "Quel pays organise la Coupe du monde de football 2026 avec le Canada et le Mexique ?", "Les États-Unis", "Le Brésil", "L'Argentine", "Cuba"],
  [1, "Quel joueur a disputé et remporté la finale de la Coupe du monde 2022 comme capitaine de l'Argentine ?", "Lionel Messi", "Ángel Di María", "Emiliano Martínez", "Lautaro Martínez"],
  [1, "Combien de Coupes du monde la France a-t-elle remportées ?", "2", "1", "3", "4"],
  [2, "Quel joueur français détient le record de buts en équipe de France ?", "Olivier Giroud", "Thierry Henry", "Kylian Mbappé", "Antoine Griezmann"],
  [1, "Quel sélectionneur a mené les Bleus au titre mondial en 2018 ?", "Didier Deschamps", "Aimé Jacquet", "Laurent Blanc", "Zinédine Zidane"],
  [2, "Quel sélectionneur a mené les Bleus au titre mondial en 1998 ?", "Aimé Jacquet", "Didier Deschamps", "Roger Lemerre", "Michel Hidalgo"],
  [1, "Dans quel sport parle-t-on de « wicket » et de « batteur » ?", "Le cricket", "Le baseball", "Le golf", "Le hockey"],
  [1, "Quel sport consiste à faire glisser des pierres de granit sur la glace ?", "Le curling", "Le bobsleigh", "La pétanque sur glace", "Le skeleton"],
  [1, "Comment appelle-t-on le petit but en bois visé à la pétanque ?", "Le cochonnet", "Le bouchon", "La quille", "Le palet"],
  // — Expert, 3e vague (2026-10) —
  [3, "Quel surnom porte le trophée de la Coupe Davis de tennis ?", "Le Saladier d'argent", "La Cruche d'argent", "Le Vase d'or", "La Coupe des Mousquetaires"],
  [3, "En quelle année le premier Tour de France a-t-il été couru ?", "1903", "1896", "1910", "1919"],
  [3, "Quel boxeur français, champion du monde des poids moyens en 1948, fut le compagnon d'Édith Piaf ?", "Marcel Cerdan", "Georges Carpentier", "Jean-Claude Bouttier", "Fabrice Tiozzo"],
  [3, "Combien de joueurs par équipe sont dans l'eau lors d'un match de water-polo ?", "7", "5", "6", "8"],
  [3, "Quel pays a remporté la première Coupe du monde de football féminine, en 1991 ?", "Les États-Unis", "La Norvège", "L'Allemagne", "La Chine"],
  [3, "Quelle discipline le « Fosbury flop » a-t-il révolutionnée en 1968 ?", "Le saut en hauteur", "Le saut à la perche", "Le triple saut", "Le saut en longueur"],
  [3, "Quel Français a été champion olympique du 50 m nage libre à Londres, en 2012 ?", "Florent Manaudou", "Yannick Agnel", "Alain Bernard", "Frédérick Bousquet"],
  [3, "Quel joueur détient le record de buts sur une saison de championnat de France, avec 44 buts ?", "Josip Skoblar", "Jean-Pierre Papin", "Zlatan Ibrahimović", "Kylian Mbappé"],
  [3, "Quelle athlète française a remporté le 200 m et le 400 m aux Jeux d'Atlanta, en 1996 ?", "Marie-José Pérec", "Christine Arron", "Muriel Hurtis", "Eunice Barber"],
  [3, "Quel pilote a remporté le tout premier championnat du monde de Formule 1, en 1950 ?", "Giuseppe Farina", "Juan Manuel Fangio", "Alberto Ascari", "Stirling Moss"],
];
export const Q3_SPORT = Q.map(([d, q, ...choices]) => ({ d, q, choices, correct: 0 }));
