/* Quiz — GÉOGRAPHIE, 2e vague (capitales moins connues, fleuves, sommets, frontières).
   Format compact : [niveau, question, BONNE RÉPONSE, leurre, leurre, leurre] (ordre des
   choix tiré au hasard à l'affichage).
   Niveau : 1 facile, 2 moyen, 3 expert. */
const Q = [
  [1, "Quelle est la capitale du Viêt Nam ?", "Hanoï", "Hô-Chi-Minh-Ville", "Hué", "Da Nang"],
  [2, "Quelle est la capitale de l'Azerbaïdjan ?", "Bakou", "Erevan", "Tbilissi", "Achgabat"],
  [2, "Quelle est la capitale du Burkina Faso ?", "Ouagadougou", "Bamako", "Niamey", "Bobo-Dioulasso"],
  [3, "Quelle est la capitale de la Tanzanie ?", "Dodoma", "Dar es Salam", "Zanzibar", "Arusha"],
  [3, "Quelle est la capitale du Kazakhstan ?", "Astana", "Almaty", "Bichkek", "Tachkent"],
  [3, "Quelle est la capitale de la Birmanie (Myanmar) ?", "Naypyidaw", "Rangoun", "Mandalay", "Bagan"],
  [2, "Quel pays a pour capitale Kigali ?", "Le Rwanda", "Le Burundi", "L'Ouganda", "Le Kenya"],
  [3, "Quel pays a pour capitale Tachkent ?", "L'Ouzbékistan", "Le Kazakhstan", "Le Tadjikistan", "Le Kirghizistan"],
  [1, "Quel pays a pour capitale Katmandou ?", "Le Népal", "Le Bhoutan", "Le Tibet", "Le Bangladesh"],
  [1, "Quel pays a pour capitale Doha ?", "Le Qatar", "Bahreïn", "Le Koweït", "Oman"],
  [2, "Quel pays a pour capitale Mascate ?", "Oman", "Le Yémen", "Bahreïn", "Le Koweït"],
  [2, "Quel pays a pour capitale Montevideo ?", "L'Uruguay", "Le Paraguay", "L'Argentine", "La Bolivie"],
  [2, "Quel pays a pour capitale Asuncion ?", "Le Paraguay", "L'Uruguay", "La Bolivie", "L'Équateur"],
  [2, "Quel pays a pour capitale Quito ?", "L'Équateur", "La Colombie", "Le Pérou", "Le Venezuela"],
  [2, "Quel pays a pour capitale La Valette ?", "Malte", "Chypre", "Monaco", "Saint-Marin"],
  [2, "Quel pays a pour capitale Nicosie ?", "Chypre", "Malte", "La Grèce", "La Crète"],
  [3, "Quel pays a pour capitale Podgorica ?", "Le Monténégro", "La Serbie", "L'Albanie", "La Macédoine du Nord"],
  [3, "Quel pays a pour capitale Skopje ?", "La Macédoine du Nord", "Le Monténégro", "Le Kosovo", "La Bulgarie"],
  [3, "Quel pays a pour capitale Chisinau ?", "La Moldavie", "La Roumanie", "L'Ukraine", "La Biélorussie"],
  [2, "Quel pays a pour capitale Vaduz ?", "Le Liechtenstein", "Le Luxembourg", "Andorre", "Monaco"],
  [3, "Quelle est la capitale constitutionnelle de la Bolivie ?", "Sucre", "La Paz", "Santa Cruz", "Cochabamba"],
  [2, "Quel est le plus grand pays d'Afrique par la superficie ?", "L'Algérie", "La RD Congo", "Le Soudan", "La Libye"],
  [2, "Quel est le pays le plus peuplé d'Afrique ?", "Le Nigeria", "L'Éthiopie", "L'Égypte", "La RD Congo"],
  [3, "Quel est le plus petit pays d'Afrique continentale ?", "La Gambie", "Djibouti", "L'Eswatini", "Le Rwanda"],
  [3, "Combien de pays le Danube traverse-t-il ?", "10", "4", "7", "14"],
  [2, "Quelles capitales le Danube traverse-t-il ?", "Vienne, Bratislava, Budapest et Belgrade", "Vienne, Prague, Budapest et Bucarest", "Berlin, Vienne, Budapest et Sofia", "Munich, Vienne, Zagreb et Belgrade"],
  [2, "Quel cours d'eau traverse Prague ?", "La Vltava", "Le Danube", "L'Elbe", "L'Oder"],
  [2, "Quel fleuve traverse Lisbonne ?", "Le Tage", "Le Douro", "Le Guadalquivir", "L'Èbre"],
  [2, "Quel fleuve traverse Séville ?", "Le Guadalquivir", "Le Tage", "L'Èbre", "Le Guadiana"],
  [3, "Quel fleuve traverse Varsovie ?", "La Vistule", "L'Oder", "L'Elbe", "Le Dniepr"],
  [2, "Quel fleuve traverse Bagdad ?", "Le Tigre", "L'Euphrate", "Le Jourdain", "Le Nil"],
  [2, "Sur quel fleuve se trouve le barrage des Trois-Gorges ?", "Le Yangzi Jiang", "Le fleuve Jaune", "Le Mékong", "L'Amour"],
  [1, "Quel fleuve d'Asie du Sud-Est traverse le Laos et le Cambodge avant son delta vietnamien ?", "Le Mékong", "L'Irrawaddy", "Le Gange", "Le Salouen"],
  [2, "Quel est le plus grand lac d'Afrique ?", "Le lac Victoria", "Le lac Tanganyika", "Le lac Malawi", "Le lac Tchad"],
  [3, "Quel est le plus grand lac d'Europe ?", "Le lac Ladoga", "Le lac Léman", "Le lac Balaton", "Le lac Vänern"],
  [1, "Quel est le plus grand lac alpin ?", "Le lac Léman", "Le lac de Constance", "Le lac de Garde", "Le lac Majeur"],
  [2, "Quel lac, partagé par l'Allemagne, la Suisse et l'Autriche, est traversé par le Rhin ?", "Le lac de Constance", "Le lac Léman", "Le lac de Garde", "Le lac de Neuchâtel"],
  [1, "Quelle mer baigne Venise et la côte croate ?", "La mer Adriatique", "La mer Égée", "La mer Tyrrhénienne", "La mer Ligurienne"],
  [1, "Quelle mer baigne Athènes ?", "La mer Égée", "La mer Ionienne", "La mer Adriatique", "La mer Noire"],
  [1, "Quel détroit sépare l'Asie de l'Amérique ?", "Le détroit de Béring", "Le détroit de Magellan", "Le détroit d'Ormuz", "Le détroit de Malacca"],
  [2, "Quel détroit sépare la Sicile du reste de l'Italie ?", "Le détroit de Messine", "Les bouches de Bonifacio", "Le canal d'Otrante", "Le détroit de Gibraltar"],
  [1, "Quel détroit sépare la Corse de la Sardaigne ?", "Les bouches de Bonifacio", "Le détroit de Messine", "Le canal de Corse", "Le détroit de Sicile"],
  [2, "Par quel détroit passe une grande partie du pétrole du golfe Persique ?", "Le détroit d'Ormuz", "Le détroit de Malacca", "Le Bosphore", "Le détroit de Béring"],
  [1, "Quel désert couvre une grande partie de la Mongolie et du nord de la Chine ?", "Le Gobi", "Le Taklamakan", "Le Thar", "Le Karakoum"],
  [2, "Quel désert côtier longe l'océan Atlantique en Namibie ?", "Le Namib", "Le Kalahari", "Le Karoo", "Le Sahel"],
  [1, "Quelle chaîne de montagnes traverse le Maroc ?", "L'Atlas", "Le Rif seul", "Les Aurès", "Le Hoggar"],
  [3, "Quel est le plus haut sommet d'Océanie ?", "Le Puncak Jaya", "L'Aoraki (mont Cook)", "Le Kosciuszko", "Le mont Wilhelm"],
  [3, "Quel est le plus haut sommet de l'Antarctique ?", "Le mont Vinson", "Le mont Erebus", "Le mont Kirkpatrick", "Le mont Sidley"],
  [3, "Combien de sommets dépassent 8 000 mètres sur Terre ?", "14", "7", "10", "21"],
  [3, "Quel est le plus haut sommet des Pyrénées ?", "L'Aneto", "Le Vignemale", "Le pic du Midi de Bigorre", "Le mont Perdu"],
  [3, "Quel est le plus haut sommet des Vosges ?", "Le Grand Ballon", "Le Hohneck", "Le Donon", "Le ballon d'Alsace"],
  [2, "Quelle est la plus grande île d'Europe ?", "La Grande-Bretagne", "L'Islande", "L'Irlande", "La Sicile"],
  [3, "Quels pays se partagent l'île de Bornéo ?", "L'Indonésie, la Malaisie et Brunei", "L'Indonésie et les Philippines", "La Malaisie et la Thaïlande", "L'Indonésie seule"],
  [1, "Quel pays est formé de plus de 17 000 îles ?", "L'Indonésie", "Les Philippines", "Le Japon", "La Grèce"],
  [2, "Quelle ville américaine est surnommée « la ville des vents » ?", "Chicago", "Boston", "Seattle", "Détroit"],
  [2, "Quelle est la ville la plus peuplée du Canada ?", "Toronto", "Montréal", "Vancouver", "Ottawa"],
  [3, "Quels sont les deux pays d'Amérique du Sud sans frontière avec le Brésil ?", "Le Chili et l'Équateur", "Le Chili et l'Argentine", "L'Équateur et la Colombie", "Le Pérou et le Chili"],
  [2, "Quel pays d'Amérique du Sud n'a pas d'accès à la mer, comme la Bolivie ?", "Le Paraguay", "L'Uruguay", "L'Équateur", "Le Suriname"],
  [2, "Quel pays est entièrement enclavé dans l'Afrique du Sud ?", "Le Lesotho", "L'Eswatini", "Le Botswana", "Le Malawi"],
  [2, "Quels États sont entièrement enclavés dans l'Italie ?", "Saint-Marin et le Vatican", "Monaco et Malte", "Andorre et Monaco", "Le Liechtenstein et Saint-Marin"],
  [1, "Dans quel pays se trouve la ville de Tombouctou ?", "Le Mali", "Le Niger", "La Mauritanie", "Le Burkina Faso"],
  [1, "Dans quel pays se trouve la région de Cappadoce, célèbre pour ses montgolfières ?", "La Turquie", "La Grèce", "L'Arménie", "L'Iran"],
  [2, "Entre quels pays se trouvent les chutes d'Iguazú ?", "L'Argentine et le Brésil", "Le Brésil et le Paraguay", "L'Argentine et l'Uruguay", "Le Brésil et la Bolivie"],
  [1, "Quelles chutes géantes marquent la frontière entre la Zambie et le Zimbabwe ?", "Les chutes Victoria", "Les chutes d'Iguazú", "Les chutes de Tugela", "Les chutes du Niagara"],
  [2, "Dans quel pays se trouve la plaine du Serengeti ?", "La Tanzanie", "Le Kenya", "L'Ouganda", "Le Botswana"],
];
export const Q3_GEO = Q.map(([d, q, ...choices]) => ({ d, q, choices, correct: 0 }));
