/* Quiz — CINÉMA, 2e vague (réalisateurs, palmarès, classiques, cinéma français).
   Format compact : [question, BONNE RÉPONSE, leurre, leurre, leurre] (ordre des
   choix tiré au hasard à l'affichage). Du plus facile au plus difficile. */
const Q = [
  ["Quel film a remporté l'Oscar du meilleur film en 2024 ?", "Oppenheimer", "Barbie", "Pauvres Créatures", "Anatomie d'une chute"],
  ["Quel film de Justine Triet a remporté la Palme d'or en 2023 ?", "Anatomie d'une chute", "Titane", "La Vie d'Adèle", "Le Règne animal"],
  ["Quel réalisateur iranien a remporté la Palme d'or en 2025 ?", "Jafar Panahi", "Asghar Farhadi", "Abbas Kiarostami", "Mohammad Rasoulof"],
  ["Quel film français détient le record d'entrées en salle pour un film national ?", "Bienvenue chez les Ch'tis", "Intouchables", "La Grande Vadrouille", "Les Visiteurs"],
  ["Quel film de 1966 avec Bourvil et Louis de Funès a longtemps détenu le record d'entrées ?", "La Grande Vadrouille", "Le Corniaud", "La Folie des grandeurs", "Les Aventures de Rabbi Jacob"],
  ["Quel réalisateur a tourné « Le Grand Bleu » et « Léon » ?", "Luc Besson", "Jean-Jacques Annaud", "Jean-Pierre Jeunet", "Claude Lelouch"],
  ["Quel réalisateur a tourné « La Haine » en 1995 ?", "Mathieu Kassovitz", "Jacques Audiard", "Cédric Klapisch", "Luc Besson"],
  ["Quel réalisateur de la Nouvelle Vague a tourné « Les Quatre Cents Coups » ?", "François Truffaut", "Jean-Luc Godard", "Éric Rohmer", "Claude Chabrol"],
  ["Quel réalisateur a tourné « À bout de souffle » avec Jean-Paul Belmondo ?", "Jean-Luc Godard", "François Truffaut", "Jacques Demy", "Louis Malle"],
  ["Quel acteur incarne Jacquouille la Fripouille dans « Les Visiteurs » ?", "Christian Clavier", "Jean Reno", "Gérard Jugnot", "Thierry Lhermitte"],
  ["Quel film de Francis Veber met en scène François Pignon invité par moquerie ?", "Le Dîner de cons", "La Chèvre", "Les Compères", "L'Emmerdeur"],
  ["Comment s'appelle l'ordinateur du vaisseau dans « 2001, l'Odyssée de l'espace » ?", "HAL 9000", "Skynet", "Mère", "Jarvis"],
  ["Quel réalisateur a tourné « Le Parrain » ?", "Francis Ford Coppola", "Martin Scorsese", "Brian De Palma", "Sergio Leone"],
  ["Quel acteur incarne Vito Corleone dans le premier « Parrain » ?", "Marlon Brando", "Al Pacino", "Robert De Niro", "James Caan"],
  ["Quel acteur lance « You talkin' to me? » devant son miroir dans « Taxi Driver » ?", "Robert De Niro", "Al Pacino", "Joe Pesci", "Harvey Keitel"],
  ["Quel réalisateur néo-zélandais a adapté « Le Seigneur des anneaux » ?", "Peter Jackson", "Jane Campion", "Taika Waititi", "Guillermo del Toro"],
  ["Quel réalisateur coréen a tourné « Parasite », Palme d'or et Oscar du meilleur film ?", "Bong Joon-ho", "Park Chan-wook", "Kim Ki-duk", "Hirokazu Kore-eda"],
  ["Quel acteur a reçu l'Oscar pour son interprétation du Joker en 2020 ?", "Joaquin Phoenix", "Heath Ledger", "Jared Leto", "Brad Pitt"],
  ["Quelle actrice française a reçu l'Oscar pour son rôle d'Édith Piaf dans « La Môme » ?", "Marion Cotillard", "Juliette Binoche", "Audrey Tautou", "Isabelle Huppert"],
  ["Quel acteur français a reçu l'Oscar du meilleur acteur pour « The Artist » ?", "Jean Dujardin", "Omar Sy", "Vincent Cassel", "Gérard Depardieu"],
  ["Quelle actrice française a reçu l'Oscar pour « Le Patient anglais » ?", "Juliette Binoche", "Marion Cotillard", "Isabelle Adjani", "Catherine Deneuve"],
  ["Combien de films compte la saga principale de la famille Skywalker dans « Star Wars » ?", "9", "6", "7", "12"],
  ["Comment s'appelle le psychiatre cannibale du « Silence des agneaux » ?", "Hannibal Lecter", "Norman Bates", "Jack Torrance", "Patrick Bateman"],
  ["Quel film de 1939 suit Scarlett O'Hara pendant la guerre de Sécession ?", "Autant en emporte le vent", "Casablanca", "Le Magicien d'Oz", "Ben-Hur"],
  ["Quel film de Charlie Chaplin se moque du travail à la chaîne ?", "Les Temps modernes", "Le Kid", "Le Dictateur", "La Ruée vers l'or"],
  ["Quel réalisateur japonais a tourné « Les Sept Samouraïs » ?", "Akira Kurosawa", "Yasujirō Ozu", "Hayao Miyazaki", "Takeshi Kitano"],
  ["Quel réalisateur italien a tourné « La Dolce Vita » ?", "Federico Fellini", "Roberto Rossellini", "Luchino Visconti", "Sergio Leone"],
  ["Quel réalisateur espagnol a tourné « Tout sur ma mère » et « Volver » ?", "Pedro Almodóvar", "Luis Buñuel", "Alejandro Amenábar", "Carlos Saura"],
  ["Quel cinéaste français a tourné « Le Voyage dans la Lune » en 1902 ?", "Georges Méliès", "Louis Lumière", "Charles Pathé", "Léon Gaumont"],
  ["Quel film de 1927 est considéré comme le premier long métrage parlant ?", "Le Chanteur de jazz", "Metropolis", "Les Lumières de la ville", "Nosferatu"],
  ["Quelle récompense suprême décerne le festival de Berlin ?", "L'Ours d'or", "Le Lion d'or", "La Palme d'or", "La Coquille d'or"],
  ["Quelle récompense suprême décerne la Mostra de Venise ?", "Le Lion d'or", "L'Ours d'or", "La Palme d'or", "Le Léopard d'or"],
  ["Quel réalisateur italien est le maître du western spaghetti ?", "Sergio Leone", "Federico Fellini", "Dario Argento", "Bernardo Bertolucci"],
  ["Quel compositeur a signé les musiques des westerns de Sergio Leone ?", "Ennio Morricone", "John Williams", "Hans Zimmer", "Nino Rota"],
  ["Quel compositeur a écrit les musiques de « Star Wars », « Jaws » et « Indiana Jones » ?", "John Williams", "Hans Zimmer", "Danny Elfman", "Howard Shore"],
  ["Quel compositeur allemand a signé les musiques d'« Inception » et du « Roi lion » ?", "Hans Zimmer", "John Williams", "Alexandre Desplat", "James Horner"],
  ["Quel compositeur a écrit la musique du « Fabuleux Destin d'Amélie Poulain » ?", "Yann Tiersen", "Alexandre Desplat", "Michel Legrand", "Vladimir Cosma"],
  ["Quel film de Jacques Demy est entièrement chanté ?", "Les Parapluies de Cherbourg", "Peau d'âne", "Lola", "Les Demoiselles de Rochefort"],
  ["Quel duo d'acteurs forme le couple Asterix-Obélix dans « Mission Cléopâtre » ?", "Christian Clavier et Gérard Depardieu", "Clovis Cornillac et Gérard Depardieu", "Guillaume Canet et Gilles Lellouche", "Édouard Baer et Jamel Debbouze"],
  ["Quel film de 2011 avec Omar Sy et François Cluzet a réuni plus de 19 millions de spectateurs ?", "Intouchables", "Le Sens de la fête", "Bienvenue chez les Ch'tis", "Qu'est-ce qu'on a fait au Bon Dieu ?"],
  ["Quel film de 1994 suit Andy Dufresne dans la prison de Shawshank ?", "Les Évadés", "La Ligne verte", "Le Prisonnier", "Papillon"],
  ["Quel acteur a remporté l'Oscar en 2016 pour « The Revenant » ?", "Leonardo DiCaprio", "Matthew McConaughey", "Eddie Redmayne", "Tom Hardy"],
];
export const Q3_CINEMA = Q.map(([q, ...choices]) => ({ q, choices, correct: 0 }));
