/* Quiz bank BDMANGA - correct = 0-based index. */
export const Q_BDMANGA = [
  { q: "Qui est le créateur de Tintin ?", choices: ["Hergé", "Franquin", "Uderzo", "Peyo"], correct: 0 },
  { q: "Dans Astérix, quelle est la boisson qui donne une force surhumaine ?", choices: ["L'hydromel", "La cervoise", "La potion magique", "Le vin gaulois"], correct: 2 },
  { q: "Quel est le fidèle chien de Tintin ?", choices: ["Rantanplan", "Milou", "Idéfix", "Bill"], correct: 1 },
  { q: "Comment s'appelle le petit chien d'Astérix et Obélix ?", choices: ["Idéfix", "Milou", "Rantanplan", "Cétautomatix"], correct: 0 },
  { q: "Quel personnage de BD est un cow-boy qui tire plus vite que son ombre ?", choices: ["Blueberry", "Lucky Luke", "Jerry Spring", "Buddy Longway"], correct: 1 },
  { q: "Qui a créé le personnage de Gaston Lagaffe ?", choices: ["Peyo", "Morris", "André Franquin", "Roba"], correct: 2 },
  { q: "Dans quel journal Spirou fait-il ses premières apparitions ?", choices: ["Le Journal de Mickey", "Le journal de Spirou", "Pilote", "Tintin"], correct: 1 },
  { q: "Quel est le métier initial du personnage Spirou ?", choices: ["Détective", "Groom", "Journaliste", "Pilote"], correct: 1 },
  { q: "Qui est l'ami écureuil de Spirou ?", choices: ["Spip", "Marsupilami", "Fantasio", "Pips"], correct: 0 },
  { q: "Comment s'appelle le capitaine ami de Tintin ?", choices: ["Capitaine Crochet", "Capitaine Haddock", "Capitaine Nemo", "Capitaine Flam"], correct: 1 },
  { q: "Quel savant distrait apparaît dans les albums de Tintin ?", choices: ["Professeur Tournesol", "Professeur Calys", "Professeur Mortimer", "Professeur Bergamotte"], correct: 0 },
  { q: "Dans Astérix, quel est le métier d'Obélix ?", choices: ["Forgeron", "Livreur de menhirs", "Poissonnier", "Barde"], correct: 1 },
  { q: "Comment s'appelle le barde du village gaulois d'Astérix ?", choices: ["Assurancetourix", "Abraracourcix", "Ordralfabétix", "Agecanonix"], correct: 0 },
  { q: "Qui est le chef du village gaulois dans Astérix ?", choices: ["Ordralfabétix", "Abraracourcix", "Panoramix", "Agecanonix"], correct: 1 },
  { q: "Comment s'appelle le druide du village d'Astérix ?", choices: ["Panoramix", "Assurancetourix", "Cétautomatix", "Idéfix"], correct: 0 },
  { q: "Quel manga créé par Eiichiro Oda suit un pirate au chapeau de paille ?", choices: ["Naruto", "Bleach", "One Piece", "Dragon Ball"], correct: 2 },
  { q: "Comment s'appelle le héros de One Piece ?", choices: ["Zoro", "Monkey D. Luffy", "Sanji", "Ace"], correct: 1 },
  { q: "Qui est le créateur de Dragon Ball ?", choices: ["Masashi Kishimoto", "Akira Toriyama", "Eiichiro Oda", "Tite Kubo"], correct: 1 },
  { q: "Comment s'appelle le héros principal de Dragon Ball ?", choices: ["Vegeta", "Piccolo", "Son Goku", "Krillin"], correct: 2 },
  { q: "Quel est le nom du héros ninja du manga créé par Masashi Kishimoto ?", choices: ["Sasuke", "Naruto Uzumaki", "Kakashi", "Itachi"], correct: 1 },
  { q: "Quel village est celui de Naruto ?", choices: ["Konoha", "Suna", "Kiri", "Iwa"], correct: 0 },
  { q: "Dans Dragon Ball, quel trésor confère un vœu quand on en réunit sept ?", choices: ["Les Pokéballs", "Les boules de cristal", "Les Dragon Balls", "Les Chaos Emeralds"], correct: 2 },
  { q: "Quel super-héros Marvel est mordu par une araignée radioactive ?", choices: ["Iron Man", "Spider-Man", "Captain America", "Hulk"], correct: 1 },
  { q: "Quelle est l'identité secrète de Spider-Man ?", choices: ["Bruce Wayne", "Peter Parker", "Clark Kent", "Tony Stark"], correct: 1 },
  { q: "Quel milliardaire est l'identité de Iron Man ?", choices: ["Tony Stark", "Bruce Wayne", "Reed Richards", "Charles Xavier"], correct: 0 },
  { q: "Chez DC Comics, quelle est l'identité secrète de Batman ?", choices: ["Clark Kent", "Bruce Wayne", "Hal Jordan", "Barry Allen"], correct: 1 },
  { q: "Quelle est la ville que protège Batman ?", choices: ["Metropolis", "Central City", "Gotham City", "Star City"], correct: 2 },
  { q: "Quelle est la planète d'origine de Superman ?", choices: ["Mars", "Krypton", "Tamaran", "Oa"], correct: 1 },
  { q: "Quel est le point faible de Superman ?", choices: ["L'eau", "La kryptonite", "Le feu", "L'or"], correct: 1 },
  { q: "Quelle est l'identité secrète de Superman ?", choices: ["Clark Kent", "Bruce Wayne", "Barry Allen", "Oliver Queen"], correct: 0 },
  { q: "Quel super-héros Marvel se transforme en géant vert quand il est en colère ?", choices: ["La Chose", "Hulk", "Colossus", "Abomination"], correct: 1 },
  { q: "Quel est le vrai nom de Hulk ?", choices: ["Bruce Banner", "Reed Richards", "Hank Pym", "Norman Osborn"], correct: 0 },
  { q: "Quel super-héros de Marvel manie le marteau Mjöllnir ?", choices: ["Loki", "Thor", "Odin", "Heimdall"], correct: 1 },
  { q: "Quelle équipe de super-héros Marvel comprend Iron Man, Thor et Captain America ?", choices: ["Les X-Men", "Les Vengeurs", "La Ligue des Justiciers", "Les Quatre Fantastiques"], correct: 1 },
  { q: "Chez DC Comics, comment s'appelle l'équipe réunissant Superman, Batman et Wonder Woman ?", choices: ["Les Vengeurs", "La Ligue des Justiciers", "Les Gardiens de la Galaxie", "La Team Titans"], correct: 1 },
  { q: "Quel super-héros porte un bouclier étoilé aux couleurs américaines ?", choices: ["Iron Man", "Captain America", "Hawkeye", "Falcon"], correct: 1 },
  { q: "Quel super-héros DC est surnommé l'homme le plus rapide du monde ?", choices: ["Green Lantern", "Flash", "Aquaman", "Cyborg"], correct: 1 },
  { q: "Comment s'appelle le phacochère dans le dessin animé Le Roi Lion ?", choices: ["Timon", "Pumbaa", "Zazu", "Rafiki"], correct: 1 },
  { q: "Qui a créé les Schtroumpfs ?", choices: ["Peyo", "Franquin", "Morris", "Hergé"], correct: 0 },
  { q: "De quelle couleur sont les Schtroumpfs ?", choices: ["Verts", "Bleus", "Rouges", "Jaunes"], correct: 1 },
  { q: "Quel est l'ennemi juré des Schtroumpfs ?", choices: ["Gargamel", "Azraël", "Le Bourreau", "Cétautomatix"], correct: 0 },
  { q: "Comment s'appelle le chat de Gargamel dans Les Schtroumpfs ?", choices: ["Azraël", "Félix", "Milou", "Grosminet"], correct: 0 },
  { q: "Dans Lucky Luke, comment s'appelle son cheval ?", choices: ["Jolly Jumper", "Tornado", "Fripon", "Docile"], correct: 0 },
  { q: "Quels frères hors-la-loi sont les ennemis récurrents de Lucky Luke ?", choices: ["Les frères Duke", "Les Dalton", "Les James", "Les Younger"], correct: 1 },
  { q: "Comment s'appelle le chien stupide dans l'univers de Lucky Luke ?", choices: ["Rantanplan", "Milou", "Bill", "Idéfix"], correct: 0 },
  { q: "Quel dessinateur a créé Lucky Luke ?", choices: ["Morris", "Goscinny", "Uderzo", "Franquin"], correct: 0 },
  { q: "Quel scénariste a collaboré avec Uderzo sur Astérix et avec Morris sur Lucky Luke ?", choices: ["Hergé", "René Goscinny", "Peyo", "Jacques Martin"], correct: 1 },
  { q: "Dans le manga créé par Tite Kubo, quel adolescent devient un Shinigami ?", choices: ["Ichigo Kurosaki", "Light Yagami", "Eren Jäger", "Natsu"], correct: 0 },
  { q: "Quel manga met en scène des humains luttant contre des géants dévoreurs d'hommes ?", choices: ["Death Note", "L'Attaque des Titans", "Fullmetal Alchemist", "Tokyo Ghoul"], correct: 1 },
  { q: "Comment s'appelle le héros de L'Attaque des Titans ?", choices: ["Eren Jäger", "Armin", "Levi", "Reiner"], correct: 0 },
  { q: "Dans Death Note, quel objet permet de tuer en y inscrivant un nom ?", choices: ["Une épée maudite", "Un cahier", "Un miroir", "Une bague"], correct: 1 },
  { q: "Comment s'appelle le lycéen protagoniste de Death Note ?", choices: ["Light Yagami", "L", "Ryuk", "Misa"], correct: 0 },
  { q: "Quel studio japonais a produit Mon voisin Totoro et Le Voyage de Chihiro ?", choices: ["Studio Ghibli", "Toei Animation", "Madhouse", "Sunrise"], correct: 0 },
  { q: "Qui a réalisé Le Voyage de Chihiro et Princesse Mononoké ?", choices: ["Isao Takahata", "Hayao Miyazaki", "Makoto Shinkai", "Satoshi Kon"], correct: 1 },
  { q: "Dans Mon voisin Totoro, Totoro est une créature qui vit dans...", choices: ["Une grotte", "Un grand arbre", "Une rivière", "Un château"], correct: 1 },
  { q: "Quel manga suit un chasseur nommé Gon à la recherche de son père ?", choices: ["Hunter x Hunter", "Fairy Tail", "Black Clover", "My Hero Academia"], correct: 0 },
  { q: "Dans le manga My Hero Academia, quel est le surnom du héros Izuku Midoriya ?", choices: ["All Might", "Deku", "Bakugo", "Todoroki"], correct: 1 },
  { q: "Quel anime met en scène des Pokémon et un dresseur nommé Sacha ?", choices: ["Digimon", "Pokémon", "Yu-Gi-Oh!", "Beyblade"], correct: 1 },
  { q: "Comment s'appelle le Pokémon jaune emblématique compagnon de Sacha ?", choices: ["Rondoudou", "Salamèche", "Pikachu", "Bulbizarre"], correct: 2 },
  { q: "Quel manga de sport de Takehiko Inoue est centré sur le basket-ball ?", choices: ["Captain Tsubasa", "Slam Dunk", "Haikyu!!", "Ace of Diamond"], correct: 1 },
  { q: "En France, sous quel titre est diffusé l'anime Captain Tsubasa consacré au football ?", choices: ["Olive et Tom", "Nicky Larson", "Ken le Survivant", "Juliette je t'aime"], correct: 0 },
  { q: "Quel personnage de manga, gentleman voleur, est le petit-fils d'Arsène Lupin ?", choices: ["Kaito Kid", "Lupin III", "Jigen", "Goemon"], correct: 1 },
  { q: "Sous quel titre français l'anime City Hunter a-t-il été diffusé ?", choices: ["Nicky Larson", "Olive et Tom", "Cat's Eye", "Max et Compagnie"], correct: 0 },
  { q: "Quelle héroïne magique est associée au col marin et à la lune ?", choices: ["Sakura", "Sailor Moon", "Creamy", "Emi"], correct: 1 },
  { q: "Dans Dragon Ball Z, quelle race guerrière extraterrestre compte Vegeta ?", choices: ["Les Namekiens", "Les Saiyans", "Les Freezas", "Les Tsufuls"], correct: 1 },
  { q: "Que part chercher Astérix à travers le pays dans l'album Le Tour de Gaule ?", choices: ["Des spécialités régionales", "Un bouclier", "Un trésor", "Une potion"], correct: 0 },
  { q: "Dans quel pays se déroule l'album Astérix chez les Bretons ?", choices: ["En Espagne", "En Grande-Bretagne", "En Égypte", "En Grèce"], correct: 1 },
  { q: "Quel est le prénom du chef de bureau exaspéré par Gaston Lagaffe ?", choices: ["Léon Prunelle", "De Mesmaeker", "Fantasio", "Longtarin"], correct: 0 },
  { q: "Quel animal de compagnie insolite possède Gaston Lagaffe ?", choices: ["Une mouette", "Un chat et une mouette rieuse", "Un perroquet", "Un singe"], correct: 1 },
  { q: "Dans Blake et Mortimer, quel est le grand méchant récurrent ?", choices: ["Rastapopoulos", "Olrik", "Gargamel", "Le Sphinx"], correct: 1 },
  { q: "Quel dessinateur français a créé la série de BD Blueberry, un western ?", choices: ["Jean Giraud (Moebius)", "Enki Bilal", "Hermann", "Jijé"], correct: 0 },
  { q: "Quel héros de BD est un aventurier créé par Henri Vernes en roman puis adapté en BD ?", choices: ["Corto Maltese", "Bob Morane", "Ric Hochet", "Alix"], correct: 1 },
  { q: "Quel marin aventurier est le héros créé par Hugo Pratt ?", choices: ["Corto Maltese", "Long John Silver", "Barbe-Rouge", "Cormoran"], correct: 0 },
  { q: "Quel manga de Rumiko Takahashi met en scène un garçon qui se transforme en fille au contact de l'eau froide ?", choices: ["Ranma ½", "Inu-Yasha", "Urusei Yatsura", "Maison Ikkoku"], correct: 0 },
  { q: "Quel anime de robots géants met en scène Amuro Ray pilotant un Mobile Suit ?", choices: ["Evangelion", "Gundam", "Macross", "Voltron"], correct: 1 },
  { q: "Dans Neon Genesis Evangelion, quel adolescent pilote l'EVA-01 ?", choices: ["Shinji Ikari", "Kaworu", "Toji", "Rei"], correct: 0 },
  { q: "Quel super-vilain Marvel, ennemi de Spider-Man, porte un costume vert et une planche volante ?", choices: ["Docteur Octopus", "Le Bouffon Vert", "Venom", "Le Vautour"], correct: 1 },
  { q: "Quel symbiote noir est un ennemi majeur de Spider-Man ?", choices: ["Carnage", "Venom", "Rhino", "Mysterio"], correct: 1 },
  { q: "Quel professeur télépathe dirige les X-Men ?", choices: ["Magnéto", "Charles Xavier", "Fatalis", "Reed Richards"], correct: 1 },
  { q: "Quel mutant des X-Men possède des griffes en adamantium ?", choices: ["Cyclope", "Wolverine", "Diablo", "Fauve"], correct: 1 },
  { q: "Quel super-vilain est l'ennemi juré de Batman et se caractérise par un rire maléfique ?", choices: ["Le Pingouin", "Le Joker", "L'Épouvantail", "Double-Face"], correct: 1 },
  { q: "Quelle héroïne Amazone fait partie de la Trinité DC avec Superman et Batman ?", choices: ["Supergirl", "Wonder Woman", "Batgirl", "Black Canary"], correct: 1 },
];
