/* Quiz — SANTÉ & CORPS HUMAIN, 2e vague. Format compact : [niveau, question, BONNE RÉPONSE,
   leurre ×3] (ordre des choix tiré au hasard à l'affichage).
   Niveau : 1 facile, 2 moyen, 3 expert. */
const Q = [
  [2, "Quel groupe sanguin est le receveur universel ?", "AB positif", "O négatif", "A positif", "B négatif"],
  [2, "Combien de vertèbres cervicales possède un être humain ?", "7", "5", "12", "3"],
  [2, "Quel est le muscle le plus volumineux du corps humain ?", "Le grand fessier", "Le biceps", "Le quadriceps", "Le cœur"],
  [2, "Combien de paires de côtes possède un être humain ?", "12", "10", "14", "24"],
  [2, "Quelle hormone est surnommée « l'hormone du stress » ?", "Le cortisol", "L'insuline", "La mélatonine", "L'ocytocine"],
  [1, "Quelle hormone règle le cycle du sommeil ?", "La mélatonine", "L'adrénaline", "Le cortisol", "La thyroxine"],
  [2, "Quelle hormone, sécrétée lors d'un câlin ou d'un accouchement, est dite « de l'attachement » ?", "L'ocytocine", "La testostérone", "Le cortisol", "L'adrénaline"],
  [1, "Quelle partie colorée de l'œil entoure la pupille ?", "L'iris", "La rétine", "La cornée", "Le cristallin"],
  [1, "Quelle partie du fond de l'œil capte la lumière ?", "La rétine", "L'iris", "La cornée", "La pupille"],
  [1, "Combien de fois par minute le cœur bat-il environ au repos ?", "60 à 80 fois", "20 à 30 fois", "120 à 140 fois", "200 fois"],
  [2, "Combien de saveurs de base distingue-t-on aujourd'hui, umami compris ?", "5", "3", "4", "7"],
  [1, "Quel virus est responsable du sida ?", "Le VIH", "Le VHB", "Le HPV", "Le SRAS"],
  [2, "Quelle maladie a été déclarée éradiquée en 1980 grâce à la vaccination ?", "La variole", "La polio", "La rougeole", "La tuberculose"],
  [3, "Quel médecin anglais a décrit la circulation du sang en 1628 ?", "William Harvey", "Edward Jenner", "Joseph Lister", "Alexander Fleming"],
  [3, "Quel médecin allemand a découvert le bacille de la tuberculose ?", "Robert Koch", "Louis Pasteur", "Rudolf Virchow", "Paul Ehrlich"],
  [2, "Quelle partie du cerveau gère surtout l'équilibre et la coordination ?", "Le cervelet", "L'hippocampe", "Le lobe frontal", "L'hypothalamus"],
  [3, "Quelle structure du cerveau joue un rôle clé dans la mémoire ?", "L'hippocampe", "Le cervelet", "Le bulbe rachidien", "L'hypophyse"],
  [1, "Quelle glande, en forme de papillon, se trouve à la base du cou ?", "La thyroïde", "L'hypophyse", "Le thymus", "La parotide"],
  [1, "Quel liquide la vésicule biliaire stocke-t-elle ?", "La bile", "L'insuline", "Le suc gastrique", "La lymphe"],
  [2, "Où commence la digestion de l'amidon ?", "Dans la bouche", "Dans l'estomac", "Dans l'intestin grêle", "Dans le côlon"],
  [2, "Quelle est la longueur approximative de l'intestin grêle d'un adulte ?", "6 à 7 mètres", "1 mètre", "20 mètres", "50 centimètres"],
  [1, "Quelle carence provoque l'anémie la plus courante ?", "Une carence en fer", "Une carence en calcium", "Une carence en sodium", "Une carence en vitamine D"],
  [1, "Comment appelle-t-on la peur irrationnelle des araignées ?", "L'arachnophobie", "L'agoraphobie", "La claustrophobie", "L'acrophobie"],
  [1, "Comment appelle-t-on la peur des espaces clos ?", "La claustrophobie", "L'agoraphobie", "L'acrophobie", "L'hydrophobie"],
  [2, "Comment appelle-t-on la peur du vide et des hauteurs ?", "L'acrophobie", "La claustrophobie", "L'agoraphobie", "La nyctophobie"],
  // — Expert, 3e vague (2026-10) —
  [3, "Quel est le plus petit muscle du corps humain ?", "Le muscle stapédien, dans l'oreille", "Le muscle orbiculaire de l'œil", "Le muscle masséter", "Le muscle risorius"],
  [3, "Combien d'os forment le crâne et la face d'un adulte ?", "22", "12", "30", "40"],
  [3, "Quelle protéine stocke l'oxygène dans les muscles ?", "La myoglobine", "L'hémoglobine", "La kératine", "Le collagène"],
  [3, "Quel est le nom anatomique actuel de la rotule ?", "La patella", "Le scaphoïde", "L'olécrane", "Le calcanéum"],
  [3, "Quel médecin hongrois a imposé le lavage des mains aux accoucheurs dans les années 1840 ?", "Ignace Semmelweis", "Joseph Lister", "Robert Koch", "Louis Pasteur"],
  [3, "Quel est le nerf le plus long du corps humain ?", "Le nerf sciatique", "Le nerf vague", "Le nerf optique", "Le nerf fémoral"],
  [3, "Quelle quantité de salive un adulte produit-il environ chaque jour ?", "Environ 1 litre", "Environ 10 cl", "Environ 5 litres", "Environ 10 litres"],
  [3, "Quel groupe sanguin est le plus répandu en France ?", "A+", "O+", "B+", "AB+"],
];
export const Q3_SANTE = Q.map(([d, q, ...choices]) => ({ d, q, choices, correct: 0 }));
