/* Quiz bank CINEMA - correct = 0-based index. */
export const Q_CINEMA = [
  { q: "Quel film de James Cameron sorti en 1997 a remporté 11 Oscars ?", choices: ["Avatar", "Titanic", "Aliens", "Terminator 2"], correct: 1 },
  { q: "Qui a réalisé la trilogie du Parrain ?", choices: ["Martin Scorsese", "Francis Ford Coppola", "Brian De Palma", "Sergio Leone"], correct: 1 },
  { q: "Dans Star Wars, qui est le père de Luke Skywalker ?", choices: ["Obi-Wan Kenobi", "Dark Vador", "L'Empereur Palpatine", "Yoda"], correct: 1 },
  { q: "Quel acteur incarne Jack Sparrow dans Pirates des Caraïbes ?", choices: ["Orlando Bloom", "Johnny Depp", "Javier Bardem", "Geoffrey Rush"], correct: 1 },
  { q: "Quel studio a produit le film d'animation Toy Story ?", choices: ["DreamWorks", "Pixar", "Illumination", "Studio Ghibli"], correct: 1 },
  { q: "Quelle réplique célèbre est prononcée dans Autant en emporte le vent ?", choices: ["Franchement ma chère, c'est le cadet de mes soucis", "Je reviendrai", "À nous deux Paris", "Ici, c'est le paradis"], correct: 0 },
  { q: "Qui a réalisé Pulp Fiction ?", choices: ["Quentin Tarantino", "Robert Rodriguez", "Guy Ritchie", "David Fincher"], correct: 0 },
  { q: "Dans quelle saga trouve-t-on l'anneau unique ?", choices: ["Harry Potter", "Le Seigneur des anneaux", "Star Trek", "Narnia"], correct: 1 },
  { q: "Quel acteur a joué James Bond dans Casino Royale (2006) ?", choices: ["Pierce Brosnan", "Daniel Craig", "Roger Moore", "Timothy Dalton"], correct: 1 },
  { q: "Quel film de Steven Spielberg met en scène un requin tueur ?", choices: ["Les Dents de la mer", "Jurassic Park", "E.T.", "Duel"], correct: 0 },
  { q: "Qui interprète le personnage de Forrest Gump ?", choices: ["Tom Cruise", "Tom Hanks", "Kevin Costner", "Robin Williams"], correct: 1 },
  { q: "Quel film d'animation Disney raconte l'histoire d'un lionceau nommé Simba ?", choices: ["Le Livre de la jungle", "Le Roi lion", "Bambi", "Tarzan"], correct: 1 },
  { q: "Quel réalisateur est surnommé le maître du suspense ?", choices: ["Stanley Kubrick", "Alfred Hitchcock", "Orson Welles", "Fritz Lang"], correct: 1 },
  { q: "Dans Le Silence des agneaux, qui incarne Hannibal Lecter ?", choices: ["Al Pacino", "Anthony Hopkins", "Robert De Niro", "Jack Nicholson"], correct: 1 },
  { q: "Quel super-héros Marvel est joué par Robert Downey Jr. ?", choices: ["Captain America", "Iron Man", "Thor", "Hulk"], correct: 1 },
  { q: "Quel film de 1994 réunit deux détenus dans le pénitencier de Shawshank ?", choices: ["La Ligne verte", "Les Évadés", "Midnight Express", "Le Prisonnier d'Alcatraz"], correct: 1 },
  { q: "Qui a réalisé le film Inception ?", choices: ["Christopher Nolan", "Denis Villeneuve", "Ridley Scott", "Zack Snyder"], correct: 0 },
  { q: "Quelle actrice incarne Hermione Granger dans Harry Potter ?", choices: ["Emma Stone", "Emma Watson", "Keira Knightley", "Natalie Portman"], correct: 1 },
  { q: "Quel film Pixar met en scène un rat cuisinier à Paris ?", choices: ["Là-haut", "Ratatouille", "Cars", "Wall-E"], correct: 1 },
  { q: "Dans Terminator 2, quelle réplique Arnold Schwarzenegger rend-il célèbre ?", choices: ["I'll be back", "Hasta la vista, baby", "Show me the money", "Say hello to my little friend"], correct: 1 },
  { q: "Quel réalisateur français a réalisé Le Fabuleux Destin d'Amélie Poulain ?", choices: ["Luc Besson", "Jean-Pierre Jeunet", "Michel Gondry", "Cédric Klapisch"], correct: 1 },
  { q: "Quel film de science-fiction de 1999 popularise le concept de la Matrice ?", choices: ["Blade Runner", "Matrix", "Dark City", "eXistenZ"], correct: 1 },
  { q: "Qui joue le rôle principal dans Gladiator (2000) ?", choices: ["Brad Pitt", "Russell Crowe", "Mel Gibson", "Colin Farrell"], correct: 1 },
  { q: "Quel film d'animation japonais du Studio Ghibli a gagné l'Oscar en 2003 ?", choices: ["Princesse Mononoké", "Le Voyage de Chihiro", "Mon voisin Totoro", "Le Château ambulant"], correct: 1 },
  { q: "Quel acteur incarne le Joker dans The Dark Knight (2008) ?", choices: ["Jack Nicholson", "Heath Ledger", "Joaquin Phoenix", "Jared Leto"], correct: 1 },
  { q: "Combien de films composent la trilogie originale de Star Wars ?", choices: ["Deux", "Trois", "Quatre", "Cinq"], correct: 1 },
  { q: "Qui a réalisé E.T. l'extra-terrestre ?", choices: ["George Lucas", "Steven Spielberg", "Robert Zemeckis", "Ron Howard"], correct: 1 },
  { q: "Quel film raconte l'histoire du naufragé Chuck Noland avec un ballon nommé Wilson ?", choices: ["Life of Pi", "Seul au monde", "Into the Wild", "Robinson Crusoé"], correct: 1 },
  { q: "Quelle actrice a remporté un Oscar pour La La Land ?", choices: ["Jennifer Lawrence", "Emma Stone", "Natalie Portman", "Anne Hathaway"], correct: 1 },
  { q: "Dans quel film entend-on la réplique Que la Force soit avec toi ?", choices: ["Star Trek", "Star Wars", "Dune", "Interstellar"], correct: 1 },
  { q: "Quel réalisateur italien a réalisé Le Bon, la Brute et le Truand ?", choices: ["Federico Fellini", "Sergio Leone", "Dario Argento", "Roberto Benigni"], correct: 1 },
  { q: "Quel film de Bong Joon-ho a remporté l'Oscar du meilleur film en 2020 ?", choices: ["Old Boy", "Parasite", "Memories of Murder", "Snowpiercer"], correct: 1 },
  { q: "Quel acteur incarne Neo dans Matrix ?", choices: ["Keanu Reeves", "Laurence Fishburne", "Hugo Weaving", "Will Smith"], correct: 0 },
  { q: "Quel film Disney met en scène une princesse aux cheveux magiques nommée Raiponce ?", choices: ["La Reine des neiges", "Raiponce", "La Belle au bois dormant", "Vaiana"], correct: 1 },
  { q: "Qui a réalisé Jurassic Park ?", choices: ["James Cameron", "Steven Spielberg", "Roland Emmerich", "Michael Bay"], correct: 1 },
  { q: "Quel personnage prononce Je suis ton père dans Star Wars ?", choices: ["Yoda", "Dark Vador", "Obi-Wan", "Palpatine"], correct: 1 },
  { q: "Dans quel film Marvel Thanos claque-t-il des doigts avec toutes les pierres de l'infini pour la première fois ?", choices: ["Avengers", "Avengers : L'Ère d'Ultron", "Avengers : Infinity War", "Avengers : Endgame"], correct: 2 },
  { q: "Quel personnage Marion Cotillard incarne-t-elle dans La Môme, lui valant un Oscar ?", choices: ["Édith Piaf", "Dalida", "Barbara", "Mistinguett"], correct: 0 },
  { q: "Quel film de Ridley Scott sorti en 1982 est un classique du cyberpunk ?", choices: ["Alien", "Blade Runner", "Total Recall", "Tron"], correct: 1 },
  { q: "Quel acteur incarne Rocky Balboa ?", choices: ["Sylvester Stallone", "Arnold Schwarzenegger", "Dolph Lundgren", "Jean-Claude Van Damme"], correct: 0 },
  { q: "Quel film d'animation Pixar traite des émotions à l'intérieur de la tête d'une fillette ?", choices: ["Coco", "Vice-versa", "Là-haut", "Le Monde de Nemo"], correct: 1 },
  { q: "Qui a réalisé Les Affranchis (Goodfellas) ?", choices: ["Francis Ford Coppola", "Martin Scorsese", "Brian De Palma", "Michael Cimino"], correct: 1 },
  { q: "Quel acteur a joué le rôle-titre dans Edward aux mains d'argent ?", choices: ["Johnny Depp", "Winona Ryder", "Christopher Walken", "Vincent Price"], correct: 0 },
  { q: "Quel film de 1975 de Milos Forman se déroule dans un hôpital psychiatrique ?", choices: ["Shining", "Vol au-dessus d'un nid de coucou", "Rain Man", "Un homme d'exception"], correct: 1 },
  { q: "Dans Le Seigneur des anneaux, qui accompagne Frodon comme fidèle jardinier ?", choices: ["Merry", "Pippin", "Sam", "Bilbon"], correct: 2 },
  { q: "Quel réalisateur a signé Le Labyrinthe de Pan ?", choices: ["Alejandro González Iñárritu", "Guillermo del Toro", "Alfonso Cuarón", "Pedro Almodóvar"], correct: 1 },
  { q: "Quel film de 1972 met en scène la famille Corleone ?", choices: ["Scarface", "Le Parrain", "Casino", "Il était une fois en Amérique"], correct: 1 },
  { q: "Quelle est la couleur du sabre laser de Yoda ?", choices: ["Rouge", "Bleu", "Vert", "Violet"], correct: 2 },
  { q: "Quel acteur incarne Wolverine dans les films X-Men ?", choices: ["Hugh Jackman", "Ryan Reynolds", "Patrick Stewart", "James McAvoy"], correct: 0 },
  { q: "Quel film de Robert Zemeckis fait voyager Marty McFly dans le temps ?", choices: ["L'Effet papillon", "Retour vers le futur", "Bill et Ted", "Interstellar"], correct: 1 },
  { q: "Quelle actrice joue le rôle principal dans Alien, le huitième passager ?", choices: ["Linda Hamilton", "Sigourney Weaver", "Jamie Lee Curtis", "Jodie Foster"], correct: 1 },
  { q: "Quel film d'animation Disney de 2013 met en scène les sœurs Elsa et Anna ?", choices: ["Vaiana", "La Reine des neiges", "Rebelle", "Raya"], correct: 1 },
  { q: "Qui a réalisé Kill Bill ?", choices: ["Robert Rodriguez", "Quentin Tarantino", "John Woo", "Guy Ritchie"], correct: 1 },
  { q: "Quel acteur français a joué dans Léon de Luc Besson aux côtés de Natalie Portman ?", choices: ["Gérard Depardieu", "Jean Reno", "Vincent Cassel", "Daniel Auteuil"], correct: 1 },
  { q: "Dans quel film entend-on Houston, nous avons un problème ?", choices: ["Gravity", "Apollo 13", "Armageddon", "First Man"], correct: 1 },
  { q: "Quel est le vrai nom de Batman ?", choices: ["Bruce Wayne", "Clark Kent", "Peter Parker", "Tony Stark"], correct: 0 },
  { q: "Quel film de Frank Capra est un classique de Noël avec James Stewart ?", choices: ["Miracle sur la 34e rue", "La Vie est belle", "Le Père Noël est une ordure", "L'Étrange Noël de Monsieur Jack"], correct: 1 },
  { q: "Quel réalisateur a signé 2001 : l'Odyssée de l'espace ?", choices: ["Stanley Kubrick", "George Lucas", "Ridley Scott", "Andreï Tarkovski"], correct: 0 },
  { q: "Quel acteur incarne Maximus dans Gladiator ?", choices: ["Joaquin Phoenix", "Russell Crowe", "Richard Harris", "Oliver Reed"], correct: 1 },
  { q: "Quel film Pixar suit un poisson-clown cherchant son fils ?", choices: ["Le Monde de Nemo", "Le Monde de Dory", "Toy Story", "Ratatouille"], correct: 0 },
  { q: "Quelle saga d'espionnage met en scène l'agent 007 ?", choices: ["Mission Impossible", "James Bond", "Jason Bourne", "Kingsman"], correct: 1 },
  { q: "Qui a réalisé Titanic et Avatar ?", choices: ["James Cameron", "Peter Jackson", "Michael Bay", "Roland Emmerich"], correct: 0 },
  { q: "Quel acteur incarne le capitaine Jack dans la saga Pirates des Caraïbes ?", choices: ["Orlando Bloom", "Johnny Depp", "Chow Yun-fat", "Bill Nighy"], correct: 1 },
  { q: "Quel film de 1993 de Spielberg traite de la Shoah en noir et blanc ?", choices: ["Le Pianiste", "La Liste de Schindler", "La Vie est belle", "Au revoir les enfants"], correct: 1 },
  { q: "Quelle actrice incarne Katniss Everdeen dans Hunger Games ?", choices: ["Shailene Woodley", "Jennifer Lawrence", "Kristen Stewart", "Emma Watson"], correct: 1 },
  { q: "Quel réalisateur a créé la saga Alien à l'origine ?", choices: ["James Cameron", "Ridley Scott", "David Fincher", "Jean-Pierre Jeunet"], correct: 1 },
  { q: "Quel film d'animation Pixar de 2017 se déroule pendant la fête des morts mexicaine ?", choices: ["Vice-versa", "Coco", "Luca", "Soul"], correct: 1 },
  { q: "Quel acteur incarne Indiana Jones ?", choices: ["Harrison Ford", "Sean Connery", "Kurt Russell", "Mel Gibson"], correct: 0 },
  { q: "Dans quel film Robin Williams double le Génie chez Disney ?", choices: ["Hercule", "Aladdin", "Peter Pan", "Le Bossu de Notre-Dame"], correct: 1 },
  { q: "Quel réalisateur a signé Reservoir Dogs et Django Unchained ?", choices: ["Quentin Tarantino", "Guy Ritchie", "Robert Rodriguez", "David Fincher"], correct: 0 },
  { q: "Quelle réplique est associée au film Le Parrain ?", choices: ["Je vais lui faire une offre qu'il ne pourra pas refuser", "Yippee ki-yay", "Que la fête commence", "La vie c'est comme une boîte de chocolats"], correct: 0 },
  { q: "Quel film de Peter Jackson clôt la trilogie du Seigneur des anneaux ?", choices: ["La Communauté de l'anneau", "Les Deux Tours", "Le Retour du roi", "La Bataille des cinq armées"], correct: 2 },
  { q: "Quel acteur incarne Captain America dans le MCU ?", choices: ["Chris Evans", "Chris Hemsworth", "Chris Pratt", "Chris Pine"], correct: 0 },
  { q: "Quel film de 1960 d'Hitchcock est célèbre pour sa scène de douche ?", choices: ["Les Oiseaux", "Psychose", "Vertigo", "Fenêtre sur cour"], correct: 1 },
  { q: "Quel studio d'animation a produit Shrek ?", choices: ["Pixar", "DreamWorks", "Blue Sky", "Illumination"], correct: 1 },
  { q: "Quel acteur joue Le Grand Lebowski (The Dude) ?", choices: ["Jeff Bridges", "John Goodman", "Steve Buscemi", "John Turturro"], correct: 0 },
  { q: "Quel film de Chaplin de 1936 critique l'industrialisation ?", choices: ["Le Dictateur", "Les Temps modernes", "Les Lumières de la ville", "La Ruée vers l'or"], correct: 1 },
  { q: "Quelle actrice incarne Trinity dans Matrix ?", choices: ["Carrie-Anne Moss", "Monica Bellucci", "Halle Berry", "Milla Jovovich"], correct: 0 },
  { q: "Quel réalisateur mexicain a remporté l'Oscar pour Gravity et Roma ?", choices: ["Guillermo del Toro", "Alfonso Cuarón", "Alejandro González Iñárritu", "Emmanuel Lubezki"], correct: 1 },
  { q: "Quel film met en scène le personnage de Norman Bates ?", choices: ["Shining", "Psychose", "Halloween", "Seven"], correct: 1 },
  { q: "Quel acteur incarne Thor dans le MCU ?", choices: ["Chris Evans", "Chris Hemsworth", "Tom Hiddleston", "Jeremy Renner"], correct: 1 },
  { q: "Quel film de David Fincher de 1999 met en scène un club de combat clandestin ?", choices: ["Seven", "Fight Club", "Zodiac", "Gone Girl"], correct: 1 },
  { q: "Quel personnage vert et sage forme les Jedi dans Star Wars ?", choices: ["Chewbacca", "Yoda", "Jabba", "Greedo"], correct: 1 },
  { q: "Quel réalisateur canadien a signé Dune (2021) et Blade Runner 2049 ?", choices: ["James Cameron", "Denis Villeneuve", "Christopher Nolan", "Zack Snyder"], correct: 1 },
  { q: "Quel acteur incarne Michael Corleone dans Le Parrain ?", choices: ["Marlon Brando", "Al Pacino", "Robert Duvall", "James Caan"], correct: 1 },
];
