/* Quiz — banque MODE & LUXE (couturiers, maisons, tissus, vêtements, accessoires).
   Format compact : [niveau, question, BONNE RÉPONSE, leurre, leurre, leurre] (ordre des
   choix tiré au hasard à l'affichage).
   Niveau : 1 facile, 2 moyen, 3 expert. */
const Q = [
  [1, "Quelle créatrice a popularisé la « petite robe noire » ?", "Coco Chanel", "Elsa Schiaparelli", "Jeanne Lanvin", "Madeleine Vionnet"],
  [2, "Quel couturier a créé le smoking pour femme en 1966 ?", "Yves Saint Laurent", "Jean Paul Gaultier", "Christian Dior", "Pierre Cardin"],
  [1, "Quel couturier français a fait de la marinière sa signature ?", "Jean Paul Gaultier", "Christian Lacroix", "Pierre Cardin", "Thierry Mugler"],
  [1, "Quel créateur allemand a dirigé la maison Chanel de 1983 à 2019 ?", "Karl Lagerfeld", "Hedi Slimane", "Marc Jacobs", "Tom Ford"],
  [1, "Quelle maison de luxe est connue pour son sac Birkin ?", "Hermès", "Chanel", "Dior", "Louis Vuitton"],
  [1, "Quelle maison italienne a pour logo deux G entrelacés ?", "Gucci", "Givenchy", "Fendi", "Valentino"],
  [1, "Quel créateur est célèbre pour les semelles rouges de ses chaussures ?", "Christian Louboutin", "Manolo Blahník", "Jimmy Choo", "Roger Vivier"],
  [1, "Quel tissu est fabriqué à partir du cocon d'une chenille ?", "La soie", "Le lin", "Le coton", "La laine"],
  [1, "Quelle toile robuste sert à fabriquer les jeans ?", "Le denim", "Le velours", "Le tweed", "Le lin"],
  [1, "Quel commerçant installé à San Francisco a fait breveter le jean à rivets en 1873 ?", "Levi Strauss", "Calvin Klein", "Ralph Lauren", "Tommy Hilfiger"],
  [1, "Quel maillot de bain deux-pièces doit son nom à un atoll du Pacifique ?", "Le bikini", "Le monokini", "Le tankini", "Le trikini"],
  [1, "Quel haut rayé est associé aux marins bretons ?", "La marinière", "Le caban", "Le ciré", "Le kilt"],
  [1, "Quel magazine de mode américain Anna Wintour a-t-elle dirigé à partir de 1988 ?", "Vogue", "Elle", "Harper's Bazaar", "Vanity Fair"],
  [1, "Quelle ville est surnommée la capitale mondiale du parfum ?", "Grasse", "Paris", "Nice", "Florence"],
  [1, "Qu'est-ce qu'un canotier ?", "Un chapeau de paille", "Un nœud papillon", "Une canne", "Un gilet"],
  [2, "Qu'est-ce qu'une lavallière ?", "Un large nœud noué au col", "Un chapeau", "Une ceinture", "Un col roulé"],
  [1, "Comment appelle-t-on un short qui s'arrête au-dessus du genou ?", "Un bermuda", "Un jodhpur", "Un baggy", "Un legging"],
  [1, "Quelle maison horlogère suisse a une couronne pour logo ?", "Rolex", "Omega", "Tag Heuer", "Patek Philippe"],
  [1, "Quelle marque de joaillerie new-yorkaise est célèbre pour sa boîte bleue ?", "Tiffany & Co.", "Cartier", "Harry Winston", "Bulgari"],
  [1, "Quelle actrice a donné son nom au sac Kelly d'Hermès ?", "Grace Kelly", "Jane Birkin", "Audrey Hepburn", "Catherine Deneuve"],
  [2, "Quel joaillier de la place Vendôme est célèbre pour sa panthère et son bracelet Love ?", "Cartier", "Boucheron", "Van Cleef & Arpels", "Chaumet"],
  [2, "Quel couturier a habillé Audrey Hepburn dans « Diamants sur canapé » ?", "Hubert de Givenchy", "Christian Dior", "Yves Saint Laurent", "Valentino"],
  [2, "Quel couturier italien a donné son nom à un rouge éclatant ?", "Valentino", "Giorgio Armani", "Gianni Versace", "Miuccia Prada"],
  [1, "Quelle fibre précieuse provient du duvet d'une chèvre d'Asie centrale ?", "Le cachemire", "Le mohair", "L'alpaga", "L'angora"],
  [2, "De quel animal provient la laine mohair ?", "De la chèvre angora", "Du lapin angora", "Du mouton mérinos", "Du lama"],
  [2, "De quelle ville française la toile denim tirerait-elle son nom ?", "Nîmes", "Lyon", "Gênes", "Roubaix"],
  [3, "Quel couturier japonais est célèbre pour ses plissés permanents ?", "Issey Miyake", "Yohji Yamamoto", "Kenzo Takada", "Rei Kawakubo"],
  [2, "Quel créateur japonais a fondé à Paris, en 1970, la marque qui porte son prénom ?", "Kenzo Takada", "Issey Miyake", "Yohji Yamamoto", "Junya Watanabe"],
  [2, "Quelle maison de luxe française a une calèche pour emblème ?", "Hermès", "Louis Vuitton", "Chanel", "Dior"],
  [1, "Quel groupe de luxe est dirigé par Bernard Arnault ?", "LVMH", "Kering", "Richemont", "Chanel"],
  [2, "Quel groupe de luxe français détient Gucci et Saint Laurent ?", "Kering", "LVMH", "Richemont", "Hermès"],
  [3, "Quelle montre a été la première portée sur la Lune ?", "L'Omega Speedmaster", "La Rolex Submariner", "La Breitling Navitimer", "La Tag Heuer Monaco"],
  [2, "Qu'est-ce qu'un borsalino ?", "Un chapeau de feutre", "Une chaussure", "Un manteau", "Une écharpe"],
  [1, "Qu'est-ce qu'un mocassin ?", "Une chaussure souple sans lacets", "Un gant de cuir", "Une botte de pluie", "Une chaussette épaisse"],
  [1, "Quel motif à carreaux colorés est associé aux clans écossais ?", "Le tartan", "Le pied-de-poule", "Le chevron", "Le liberty"],
  [2, "Quel imprimé à petites fleurs porte le nom d'un grand magasin londonien ?", "Le liberty", "Le paisley", "Le vichy", "La toile de Jouy"],
  [3, "Quel motif en forme de goutte, venu de Perse, porte le nom d'une ville écossaise ?", "Le paisley", "Le liberty", "Le tartan", "Le jacquard"],
  [3, "Quelle actrice a fait du vichy rose une mode en se mariant en 1959 ?", "Brigitte Bardot", "Catherine Deneuve", "Jeanne Moreau", "Marilyn Monroe"],
  [1, "Quel film de 2006, avec Meryl Streep, se moque d'une rédaction de magazine de mode ?", "Le diable s'habille en Prada", "Coco avant Chanel", "Pretty Woman", "Zoolander"],
  [3, "Quelle couturière italienne des années 1930, rivale de Chanel, aimait le rose « shocking » ?", "Elsa Schiaparelli", "Madeleine Vionnet", "Miuccia Prada", "Donatella Versace"],
  [2, "Quel couturier a ouvert la voie à la mode « futuriste » des années 1960, avec ses robes en métal ?", "Paco Rabanne", "Pierre Cardin", "André Courrèges", "Thierry Mugler"],
  [3, "Quel couturier a lancé la minijupe en France au milieu des années 1960 ?", "André Courrèges", "Pierre Cardin", "Paco Rabanne", "Yves Saint Laurent"],
  [3, "Quelle styliste britannique est considérée comme l'inventrice de la minijupe ?", "Mary Quant", "Vivienne Westwood", "Stella McCartney", "Twiggy"],
  [3, "Quelle créatrice britannique a habillé le mouvement punk dans les années 1970 ?", "Vivienne Westwood", "Mary Quant", "Stella McCartney", "Alexander McQueen"],
  [1, "Quel label, protégé par la loi en France, n'est accordé qu'à quelques maisons ?", "Haute couture", "Prêt-à-porter", "Fait main", "Luxe"],
  [3, "Quel couturier a fondé la première maison de haute couture à Paris, vers 1858 ?", "Charles Frederick Worth", "Paul Poiret", "Jeanne Lanvin", "Jacques Doucet"],
  [3, "Quel couturier a libéré les femmes du corset au début du XXe siècle ?", "Paul Poiret", "Charles Frederick Worth", "Christian Dior", "Jacques Fath"],
  [3, "Quelle est la plus ancienne maison de couture parisienne encore en activité ?", "Lanvin", "Chanel", "Dior", "Balenciaga"],
  [2, "Quel couturier espagnol, surnommé « le maître », a inventé la robe sac et la robe ballon ?", "Cristóbal Balenciaga", "Paco Rabanne", "Manuel Pertegaz", "Hubert de Givenchy"],
  [3, "Quel couturier d'origine tunisienne, installé à Paris, était célèbre pour ses robes moulantes ?", "Azzedine Alaïa", "Hedi Slimane", "Olivier Rousteing", "Kenzo Takada"],
  [3, "Quel styliste dirige la création de Balmain depuis 2011 ?", "Olivier Rousteing", "Hedi Slimane", "Simon Porte Jacquemus", "Nicolas Ghesquière"],
  [2, "Quel créateur du Sud de la France a lancé la marque Jacquemus ?", "Simon Porte Jacquemus", "Olivier Rousteing", "Hedi Slimane", "Christian Lacroix"],
  [2, "Quel motif de toile imprimée de scènes champêtres doit son nom à une ville des Yvelines ?", "La toile de Jouy", "Le liberty", "Le vichy", "Le paisley"],
  [1, "Qu'est-ce qu'un « perfecto » ?", "Un blouson de cuir de motard", "Un parfum", "Une chaussure à talon", "Un pantalon de golf"],
  // — Expert, 3e vague (2026-10) —
  [3, "Quelle créatrice japonaise a fondé la marque Comme des Garçons ?", "Rei Kawakubo", "Hanae Mori", "Yohji Yamamoto", "Junya Watanabe"],
  [3, "Quel créateur belge a dirigé la création chez Dior de 2012 à 2015 ?", "Raf Simons", "Dries Van Noten", "Martin Margiela", "Ann Demeulemeester"],
];
export const Q_MODE = Q.map(([d, q, ...choices]) => ({ d, q, choices, correct: 0 }));
