/* Quiz — GASTRONOMIE, 2e vague (fromages, cuisines du monde, desserts, vins, cocktails).
   Format compact : [niveau, question, BONNE RÉPONSE, leurre, leurre, leurre] (ordre des
   choix tiré au hasard à l'affichage).
   Niveau : 1 facile, 2 moyen, 3 expert. */
const Q = [
  [1, "De quelle région le kouign-amann est-il originaire ?", "La Bretagne", "La Normandie", "Le Pays basque", "L'Alsace"],
  [2, "Avec quel lait est fabriqué le crottin de Chavignol ?", "Du lait de chèvre", "Du lait de brebis", "Du lait de vache", "Du lait de jument"],
  [2, "Quel fromage file et s'étire dans l'aligot de l'Aubrac ?", "La tome fraîche", "Le comté", "La raclette", "Le reblochon"],
  [1, "Quel fromage à pâte persillée est italien ?", "Le gorgonzola", "Le roquefort", "Le stilton", "La fourme d'Ambert"],
  [1, "Quel fromage grec en saumure est fait de lait de brebis ?", "La feta", "Le halloumi", "La ricotta", "Le kefalotyri"],
  [3, "De quel pays vient le halloumi, fromage qui se grille ?", "Chypre", "La Grèce", "La Turquie", "Le Liban"],
  [2, "Quel fromage néerlandais est enrobé de cire rouge ?", "L'édam", "Le gouda", "Le leerdammer", "La mimolette"],
  [2, "Quel fromage français à croûte orange est surnommé « boule de Lille » ?", "La mimolette", "Le maroilles", "Le comté", "L'édam"],
  [1, "Quel plat italien de riz crémeux se cuisine en ajoutant du bouillon peu à peu ?", "Le risotto", "La polenta", "Les gnocchis", "L'arancini"],
  [1, "Quelle soupe froide de tomates est andalouse ?", "Le gazpacho", "Le minestrone", "La garbure", "Le bortsch"],
  [2, "Comment appelle-t-on les tranches de poisson cru servies sans riz au Japon ?", "Le sashimi", "Le maki", "Le nigiri", "Le tempura"],
  [2, "Quel plat vietnamien est une soupe de nouilles de riz au bouillon de bœuf ?", "Le phở", "Le bánh mì", "Le ramen", "Le pad thaï"],
  [2, "Quel accompagnement coréen est fait de chou fermenté et pimenté ?", "Le kimchi", "Le bibimbap", "Le bulgogi", "Le tteok"],
  [2, "Quel pain plat indien est cuit contre la paroi d'un four tandoor ?", "Le naan", "Le chapati", "La pita", "La tortilla"],
  [3, "De quelle plante la gousse de vanille est-elle le fruit ?", "D'une orchidée", "D'un arbre à pain", "D'un palmier", "D'une liane de poivre"],
  [2, "Quel pays est le premier producteur mondial de vanille ?", "Madagascar", "Le Mexique", "Tahiti", "L'Inde"],
  [2, "Quel pays est le premier producteur mondial de cacao ?", "La Côte d'Ivoire", "Le Ghana", "Le Brésil", "L'Équateur"],
  [1, "Quel dessert est une crème recouverte d'une fine couche de sucre caramélisé au chalumeau ?", "La crème brûlée", "L'île flottante", "Le flan", "La panna cotta"],
  [2, "Quel gâteau en couronne, garni de crème pralinée, célèbre une course cycliste ?", "Le paris-brest", "Le saint-honoré", "L'opéra", "Le fraisier"],
  [2, "Quel gâteau porte le nom du saint patron des boulangers et des pâtissiers ?", "Le saint-honoré", "Le paris-brest", "Le saint-marc", "La religieuse"],
  [1, "Quel dessert associe choux, glace vanille et sauce chocolat chaude ?", "Les profiteroles", "Les éclairs", "La religieuse", "Le croquembouche"],
  [2, "Comment appelle-t-on les petits restaurants traditionnels de Lyon ?", "Les bouchons", "Les bistrots", "Les estaminets", "Les winstubs"],
  [2, "Quel vin effervescent est produit en Catalogne ?", "Le cava", "Le prosecco", "Le crémant", "Le lambrusco"],
  [3, "Quel vin liquoreux hongrois est surnommé « le vin des rois, le roi des vins » ?", "Le tokaji", "Le porto", "Le sauternes", "Le marsala"],
  [2, "Quel cépage rouge règne sur la Bourgogne ?", "Le pinot noir", "Le merlot", "Le cabernet sauvignon", "La syrah"],
  [3, "Quel cépage blanc donne le chablis ?", "Le chardonnay", "Le sauvignon", "Le riesling", "Le chenin"],
  [3, "Quel cépage domine les vins de Pomerol et de Saint-Émilion ?", "Le merlot", "Le pinot noir", "Le gamay", "Le grenache"],
  [3, "Quel cépage donne le beaujolais ?", "Le gamay", "Le pinot noir", "Le merlot", "La syrah"],
  [1, "Quelle eau-de-vie de pomme est normande ?", "Le calvados", "L'armagnac", "Le kirsch", "La mirabelle"],
  [2, "Quelle eau-de-vie de vin est produite en Gascogne ?", "L'armagnac", "Le cognac", "Le calvados", "Le marc"],
  [1, "Quel cocktail cubain mélange rhum, menthe, citron vert et eau gazeuse ?", "Le mojito", "Le daïquiri", "La piña colada", "Le cuba libre"],
  [2, "Quel cocktail associe champagne et jus d'orange ?", "Le mimosa", "Le bellini", "Le kir royal", "Le spritz"],
  [1, "Quel cocktail associe tequila, liqueur d'orange et citron vert ?", "La margarita", "La caïpirinha", "Le mojito", "Le cosmopolitan"],
  [1, "Quel cocktail brésilien est à base de cachaça et de citron vert ?", "La caïpirinha", "La margarita", "Le mojito", "Le pisco sour"],
  [1, "Quel apéritif italien orange se prépare avec du prosecco et de l'eau gazeuse ?", "Le spritz", "Le negroni", "Le bellini", "L'americano"],
  [1, "De quelle plante est tirée la tequila ?", "De l'agave", "De la canne à sucre", "Du maïs", "Du cactus nopal"],
  [2, "Comment appelle-t-on les bières brassées sous le contrôle de moines ?", "Les trappistes", "Les blanches", "Les lambics", "Les IPA"],
  [1, "Quel chef lyonnais a été élu « cuisinier du siècle » par le Gault et Millau ?", "Paul Bocuse", "Joël Robuchon", "Alain Ducasse", "Michel Guérard"],
  [2, "Quel chef français a cumulé le plus d'étoiles Michelin au monde de son vivant ?", "Joël Robuchon", "Paul Bocuse", "Alain Ducasse", "Pierre Gagnaire"],
  [3, "Comment appelle-t-on des légumes coupés en tout petits dés ?", "Une brunoise", "Une julienne", "Une chiffonnade", "Une mirepoix"],
  [2, "Comment appelle-t-on des légumes taillés en fins bâtonnets ?", "Une julienne", "Une brunoise", "Une jardinière", "Une macédoine"],
  [2, "Quelle sauce chaude associe beurre, jaunes d'œufs, échalote et estragon ?", "La béarnaise", "La hollandaise", "La béchamel", "La mayonnaise"],
  [1, "Quelle sauce blanche est faite de beurre, de farine et de lait ?", "La béchamel", "La béarnaise", "La hollandaise", "La sauce Mornay"],
  [3, "Quelle soupe est traditionnellement servie pour rompre le jeûne du ramadan au Maroc ?", "La harira", "Le gaspacho", "La chorba frik", "Le bortsch"],
  [1, "Quel plat libanais est une purée de pois chiches au tahini ?", "Le houmous", "Le taboulé", "Le falafel", "Le baba ganoush"],
  [1, "Quel plat mexicain est une galette de maïs garnie et pliée ?", "Le taco", "Le burrito", "La quesadilla", "Les nachos"],
  [1, "Quel plat hongrois est un ragoût de bœuf au paprika ?", "Le goulash", "Le bortsch", "Le pörkölt", "Le stroganov"],
  [2, "Quelle soupe d'Europe de l'Est doit sa couleur rouge à la betterave ?", "Le bortsch", "Le goulash", "La soupe au pistou", "Le gazpacho"],
  [1, "Quel plat suisse se partage autour d'un caquelon de fromage fondu ?", "La fondue", "La raclette", "La tartiflette", "Les rösti"],
  [2, "Quel plat écossais est une panse de mouton farcie ?", "Le haggis", "Le black pudding", "Le pie", "Le scotch egg"],
  // — Expert, 3e vague (2026-10) —
  [3, "Quel fromage est surnommé « le roi des fromages et le fromage des rois » ?", "Le brie de Meaux", "Le roquefort", "Le comté", "Le camembert"],
  [3, "Quel vin du Jura vieillit plus de six ans sous un voile de levures avant d'être mis en clavelin ?", "Le vin jaune", "Le vin de paille", "Le macvin", "Le crémant du Jura"],
  [3, "Quelle grande sauce de la cuisine française est à base de fond brun ?", "La sauce espagnole", "La sauce béarnaise", "La sauce gribiche", "La sauce Mornay"],
];
export const Q3_GASTRO = Q.map(([d, q, ...choices]) => ({ d, q, choices, correct: 0 }));
