/* Quiz — NATURE & ANIMAUX, 2e vague (records, petits, cris, plantes, curiosités).
   Format compact : [niveau, question, BONNE RÉPONSE, leurre, leurre, leurre] (ordre des
   choix tiré au hasard à l'affichage).
   Niveau : 1 facile, 2 moyen, 3 expert. */
const Q = [
  [1, "Quel est le seul félin à vivre en groupe ?", "Le lion", "Le tigre", "Le guépard", "Le léopard"],
  [3, "Quel animal possède les plus grands yeux du règne animal ?", "Le calmar colossal", "La baleine bleue", "L'autruche", "Le grand-duc"],
  [1, "Quel poisson se gonfle comme un ballon pour se défendre ?", "Le poisson-globe", "Le poisson-clown", "La rascasse", "Le mérou"],
  [1, "De quoi se nourrit presque exclusivement le panda géant ?", "De bambou", "D'eucalyptus", "De fruits", "De poissons"],
  [1, "De quoi se nourrit le koala ?", "De feuilles d'eucalyptus", "De bambou", "D'insectes", "De baies"],
  [1, "Comment appelle-t-on les mammifères qui portent leur petit dans une poche ?", "Les marsupiaux", "Les monotrèmes", "Les rongeurs", "Les cétacés"],
  [1, "Que fait le cerf quand il pousse son cri ?", "Il brame", "Il barrit", "Il glapit", "Il hennit"],
  [1, "Quel animal barrit ?", "L'éléphant", "Le cerf", "Le renard", "Le sanglier"],
  [2, "Quel animal glapit ?", "Le renard", "Le loup", "Le cerf", "Le hibou"],
  [2, "Comment appelle-t-on le petit du lièvre ?", "Le levraut", "Le lapereau", "Le marcassin", "Le faon"],
  [1, "Comment appelle-t-on le petit du sanglier ?", "Le marcassin", "Le levraut", "Le chevreau", "Le louveteau"],
  [2, "Comment appelle-t-on la femelle du sanglier ?", "La laie", "La hase", "La biche", "La chevrette"],
  [3, "Comment appelle-t-on la femelle du lièvre ?", "La hase", "La laie", "La lapine", "La bréhaigne"],
  [1, "Quel arbre donne les châtaignes ?", "Le châtaignier", "Le marronnier", "Le chêne", "Le noyer"],
  [1, "Quel arbre donne les marrons d'Inde, non comestibles ?", "Le marronnier", "Le châtaignier", "Le platane", "Le tilleul"],
  [1, "Quel arbre est un symbole de paix depuis l'Antiquité ?", "L'olivier", "Le chêne", "Le cyprès", "Le laurier"],
  [3, "Quelle plante parasite produit la plus grande fleur individuelle du monde ?", "La rafflésie", "L'arum titan", "Le nénuphar géant", "Le tournesol"],
  [2, "Quel champignon cause la plupart des intoxications mortelles en Europe ?", "L'amanite phalloïde", "La girolle", "Le cèpe", "La morille"],
  [2, "Quel amphibien mexicain peut régénérer ses membres et même son cœur ?", "L'axolotl", "La salamandre", "Le triton", "La grenouille taureau"],
  [3, "Quelle méduse est capable de rajeunir et est dite « immortelle » ?", "Turritopsis dohrnii", "La méduse lune", "La guêpe de mer", "La méduse à crinière de lion"],
  [1, "Quel cétacé à longue défense torsadée est surnommé « la licorne des mers » ?", "Le narval", "Le béluga", "Le dauphin de Risso", "Le morse"],
  [1, "Quels grands singes sont nos plus proches cousins génétiques ?", "Le chimpanzé et le bonobo", "Le gorille et l'orang-outan", "Le gibbon et le babouin", "Le mandrill et le macaque"],
  [2, "Sur quelles îles vit uniquement l'orang-outan ?", "Bornéo et Sumatra", "Java et Bali", "Madagascar et Maurice", "Les Philippines"],
  [2, "Quel primate de Madagascar a une longue queue annelée noir et blanc ?", "Le lémur catta", "Le tarsier", "Le ouistiti", "Le loris"],
  [3, "Combien de pattes possède le mille-pattes record découvert en Australie en 2021 ?", "1 306", "100", "750", "1 000"],
  [1, "Quel est le plus grand lézard du monde ?", "Le dragon de Komodo", "L'iguane vert", "Le varan du Nil", "Le monstre de Gila"],
  [1, "Comment appelle-t-on un animal actif la nuit ?", "Nocturne", "Diurne", "Crépusculaire", "Hibernant"],
  [1, "Comment appelle-t-on un animal qui mange de tout ?", "Omnivore", "Herbivore", "Carnivore", "Insectivore"],
  [2, "Quel insecte est le principal vecteur du paludisme ?", "Le moustique anophèle", "La mouche tsé-tsé", "La puce", "La tique"],
  [2, "Quel insecte transmet la maladie du sommeil en Afrique ?", "La mouche tsé-tsé", "Le moustique anophèle", "La punaise", "Le taon"],
  [3, "Comment s'appelle la danse des abeilles qui indique où se trouvent les fleurs ?", "La danse frétillante", "La valse des butineuses", "La ronde royale", "Le ballet du pollen"],
  [1, "Quel oiseau pond ses œufs dans le nid d'autres oiseaux ?", "Le coucou", "La pie", "Le merle", "L'hirondelle"],
  [2, "Quel oiseau migrateur parcourt chaque année le plus long trajet, d'un pôle à l'autre ?", "La sterne arctique", "L'hirondelle rustique", "La cigogne blanche", "L'oie cendrée"],
  [2, "Quel oiseau peut tourner la tête à près de 270° ?", "La chouette", "Le perroquet", "L'aigle", "Le pigeon"],
  [2, "Quel mammifère dort le plus, jusqu'à 20 heures par jour ?", "Le koala", "Le chat", "Le paresseux", "L'ours"],
  [3, "Quel animal produit le lait le plus gras ?", "Le phoque à capuchon", "La vache", "La chèvre", "La baleine bleue"],
];
export const Q3_NATURE = Q.map(([d, q, ...choices]) => ({ d, q, choices, correct: 0 }));
