/* Quiz bank LANGUE - correct = 0-based index. */
export const Q_LANGUE = [
  { q: "Que signifie l'expression « tomber dans les pommes » ?", choices: ["S'évanouir", "Se tromper", "Tomber amoureux", "Faire une bêtise"], correct: 0 },
  { q: "Quel est le sens de l'expression « avoir le cafard » ?", choices: ["Être en colère", "Être déprimé", "Être malade", "Être pressé"], correct: 1 },
  { q: "Que veut dire « poser un lapin » à quelqu'un ?", choices: ["Lui faire un cadeau", "Lui mentir", "Ne pas venir au rendez-vous", "Le déranger"], correct: 2 },
  { q: "Que signifie l'expression « couper la poire en deux » ?", choices: ["Se disputer", "Partager équitablement", "Trancher un débat", "Renoncer"], correct: 1 },
  { q: "Que signifie « donner sa langue au chat » ?", choices: ["Renoncer à deviner", "Se taire", "Trahir un secret", "Parler trop"], correct: 0 },
  { q: "Quel est le sens de « il pleut des cordes » ?", choices: ["Il fait du vent", "Il pleut très fort", "Il neige", "Il fait orageux"], correct: 1 },
  { q: "Que veut dire « avoir un chat dans la gorge » ?", choices: ["Avoir faim", "Être enroué", "Avoir peur", "Mentir"], correct: 1 },
  { q: "Que signifie « mettre la charrue avant les bœufs » ?", choices: ["Travailler dur", "Faire les choses dans le désordre", "Aller trop lentement", "Économiser"], correct: 1 },
  { q: "Que veut dire l'expression « prendre ses jambes à son cou » ?", choices: ["Se blesser", "S'enfuir rapidement", "Se cacher", "Danser"], correct: 1 },
  { q: "Que signifie « chercher midi à quatorze heures » ?", choices: ["Compliquer inutilement", "Arriver en retard", "Perdre son temps", "Être en avance"], correct: 0 },
  { q: "Complétez le proverbe : « Petit à petit, l'oiseau fait son... »", choices: ["chant", "nid", "envol", "nom"], correct: 1 },
  { q: "Complétez : « Qui vole un œuf... »", choices: ["vole un bœuf", "perd un ami", "paie deux fois", "gagne un poulet"], correct: 0 },
  { q: "Complétez le proverbe : « L'habit ne fait pas le... »", choices: ["roi", "moine", "tailleur", "printemps"], correct: 1 },
  { q: "Complétez : « Il ne faut pas vendre la peau de l'ours... »", choices: ["avant de l'avoir tué", "sans le prix", "au marché", "en hiver"], correct: 0 },
  { q: "Complétez : « Rien ne sert de courir, il faut... »", choices: ["ralentir", "partir à point", "gagner", "s'arrêter"], correct: 1 },
  { q: "Complétez : « Après la pluie, le... »", choices: ["froid", "beau temps", "vent", "soleil couchant"], correct: 1 },
  { q: "Complétez le proverbe : « La nuit porte... »", choices: ["malheur", "conseil", "chance", "ombre"], correct: 1 },
  { q: "Complétez : « Chat échaudé craint l'eau... »", choices: ["chaude", "froide", "salée", "claire"], correct: 1 },
  { q: "Quelle orthographe est correcte ?", choices: ["Je vous serais gré", "Je vous serais gréé", "Je vous saurais gré", "Je vous saurai gréer"], correct: 2 },
  { q: "Comment écrit-on correctement cette phrase ?", choices: ["Les jours qu'il a passé", "Les jours qu'il a passés", "Les jours qu'ils a passé", "Les jours qu'il à passés"], correct: 1 },
  { q: "Quelle est la bonne orthographe ?", choices: ["Elle s'est permise de partir", "Elle s'est permis de partir", "Elle c'est permis de partir", "Elle s'est permit de partir"], correct: 1 },
  { q: "Choisissez la forme correcte : « Ils se sont... la main. »", choices: ["serré", "serrés", "serrées", "serrée"], correct: 0 },
  { q: "Quelle phrase est correctement orthographiée ?", choices: ["Quoi qu'il en soit", "Quoiqu'il en soit", "Quoi qu'il en soie", "Quoique en soit"], correct: 0 },
  { q: "Comment écrire correctement ce participe ?", choices: ["La lettre que j'ai écris", "La lettre que j'ai écrite", "La lettre que j'ai écrit", "La lettre que j'ai écrient"], correct: 1 },
  { q: "Quel est le pluriel de « cheval » ?", choices: ["Chevals", "Chevaux", "Chevales", "Cheveaux"], correct: 1 },
  { q: "Quel est le pluriel de « un travail » (au sens général) ?", choices: ["Travails", "Travaux", "Travailles", "Travaies"], correct: 1 },
  { q: "Quel est le pluriel de « ciel » (en poésie ou peinture) ?", choices: ["Ciels", "Cieux", "Les deux existent", "Cieles"], correct: 2 },
  { q: "Quel est le pluriel de « un œil » ?", choices: ["Œils", "Yeux", "Oeuils", "Œilles"], correct: 1 },
  { q: "Quel est le pluriel de « un bijou » ?", choices: ["Bijous", "Bijoux", "Bijoues", "Bijoels"], correct: 1 },
  { q: "Quel est le pluriel de « un pneu » ?", choices: ["Pneux", "Pneus", "Pneaux", "Pnels"], correct: 1 },
  { q: "Quel est le pluriel de « un festival » ?", choices: ["Festivaux", "Festivals", "Festivales", "Festiveaux"], correct: 1 },
  { q: "Quel est le pluriel de « madame » ?", choices: ["Madames", "Mesdames", "Madaines", "Mesdemoiselles"], correct: 1 },
  { q: "Quel homophone convient : « Il ... allé au marché » ?", choices: ["est", "et", "ai", "ait"], correct: 0 },
  { q: "Quel homophone convient : « ... voiture est neuve » ?", choices: ["Ta", "Tas", "T'a", "Tà"], correct: 0 },
  { q: "Quel homophone convient : « Je ne sais pas ... il viendra » ?", choices: ["ci", "si", "s'y", "sy"], correct: 1 },
  { q: "Quel homophone convient : « Elle a mangé ... pomme » ?", choices: ["ça", "sa", "çà", "çá"], correct: 1 },
  { q: "Quel homophone convient : « ... vais bien, merci » ?", choices: ["Je", "Jeu", "J'ai", "Geai"], correct: 0 },
  { q: "Quel mot désigne un texte qui se lit de la même façon dans les deux sens ?", choices: ["Anagramme", "Palindrome", "Acronyme", "Pléonasme"], correct: 1 },
  { q: "Comment appelle-t-on un mot formé en réarrangeant les lettres d'un autre ?", choices: ["Anagramme", "Homonyme", "Antonyme", "Paronyme"], correct: 0 },
  { q: "Qu'est-ce qu'un pléonasme ?", choices: ["Une répétition inutile", "Une exagération", "Une comparaison", "Une contradiction"], correct: 0 },
  { q: "Comment appelle-t-on deux mots qui se prononcent pareil mais s'écrivent différemment ?", choices: ["Synonymes", "Homophones", "Antonymes", "Paronymes"], correct: 1 },
  { q: "Comment appelle-t-on des mots proches par la forme mais de sens différents (ex : conjecture/conjoncture) ?", choices: ["Homonymes", "Paronymes", "Synonymes", "Homographes"], correct: 1 },
  { q: "Quelle figure de style consiste à atténuer une idée pour en dire plus (ex : « ce n'est pas mauvais ») ?", choices: ["Hyperbole", "Litote", "Métaphore", "Euphémisme"], correct: 1 },
  { q: "Quelle figure de style exagère la réalité (ex : « mourir de rire ») ?", choices: ["Litote", "Hyperbole", "Métonymie", "Antithèse"], correct: 1 },
  { q: "Quelle figure de style consiste à adoucir une expression désagréable (ex : « disparu » pour mort) ?", choices: ["Euphémisme", "Hyperbole", "Ironie", "Allégorie"], correct: 0 },
  { q: "Comment appelle-t-on une comparaison sans mot de comparaison (ex : « cet homme est un lion ») ?", choices: ["Métaphore", "Comparaison", "Périphrase", "Métonymie"], correct: 0 },
  { q: "Quelle figure de style désigne une chose par un élément lié (ex : « boire un verre ») ?", choices: ["Métaphore", "Métonymie", "Litote", "Anaphore"], correct: 1 },
  { q: "Quelle figure consiste à répéter un mot en début de phrases successives ?", choices: ["Anaphore", "Allitération", "Assonance", "Gradation"], correct: 0 },
  { q: "Comment appelle-t-on la répétition d'un même son consonantique (ex : « pour qui sont ces serpents... ») ?", choices: ["Assonance", "Allitération", "Anaphore", "Paronomase"], correct: 1 },
  { q: "Quelle figure rapproche deux idées opposées dans une même expression (ex : « une obscure clarté ») ?", choices: ["Antithèse", "Oxymore", "Chiasme", "Gradation"], correct: 1 },
  { q: "Quel est le synonyme le plus proche de « véloce » ?", choices: ["Lent", "Rapide", "Fort", "Léger"], correct: 1 },
  { q: "Quel est le synonyme le plus proche de « fallacieux » ?", choices: ["Sincère", "Trompeur", "Utile", "Rare"], correct: 1 },
  { q: "Quel est le synonyme le plus proche de « exhaustif » ?", choices: ["Complet", "Fatigant", "Rapide", "Partiel"], correct: 0 },
  { q: "Quel est le synonyme le plus proche de « laconique » ?", choices: ["Bavard", "Bref", "Confus", "Poli"], correct: 1 },
  { q: "Quel est le contraire de « prolixe » ?", choices: ["Concis", "Généreux", "Long", "Riche"], correct: 0 },
  { q: "Que signifie l'adjectif « ubuesque » ?", choices: ["Grotesque et absurde", "Très ancien", "Luxueux", "Silencieux"], correct: 0 },
  { q: "Que signifie le mot « acrimonie » ?", choices: ["Douceur", "Amertume, aigreur", "Curiosité", "Précision"], correct: 1 },
  { q: "Que signifie « procrastiner » ?", choices: ["Remettre au lendemain", "Se dépêcher", "Insister", "Douter"], correct: 0 },
  { q: "Que signifie le mot « idoine » ?", choices: ["Inutile", "Approprié, convenable", "Étrange", "Ancien"], correct: 1 },
  { q: "Que signifie l'adjectif « pusillanime » ?", choices: ["Courageux", "Craintif, timoré", "Généreux", "Bavard"], correct: 1 },
  { q: "Que signifie le mot « alacrité » ?", choices: ["Vivacité joyeuse", "Lenteur", "Colère", "Tristesse"], correct: 0 },
  { q: "Que désigne le mot « palimpseste » ?", choices: ["Un parchemin réutilisé", "Une erreur d'imprimerie", "Un poème court", "Une signature"], correct: 0 },
  { q: "Que signifie l'adjectif « sibyllin » ?", choices: ["Clair", "Énigmatique, obscur", "Bruyant", "Joyeux"], correct: 1 },
  { q: "De quelle langue vient étymologiquement le mot « algèbre » ?", choices: ["Le grec", "L'arabe", "Le latin", "Le persan"], correct: 1 },
  { q: "D'où vient étymologiquement le mot « salaire » ?", choices: ["Du sel", "De l'or", "Du blé", "Du travail"], correct: 0 },
  { q: "Le mot « robot » a été introduit à partir d'une langue :", choices: ["Anglaise", "Tchèque (slave)", "Japonaise", "Latine"], correct: 1 },
  { q: "Le préfixe « télé- » (télévision, téléphone) signifie :", choices: ["Loin", "Image", "Voix", "Vite"], correct: 0 },
  { q: "Le mot « bureau » vient à l'origine du nom :", choices: ["D'une étoffe (bure)", "D'un meuble italien", "D'un roi", "D'une ville"], correct: 0 },
  { q: "La racine grecque « bio- » signifie :", choices: ["Vie", "Terre", "Livre", "Deux"], correct: 0 },
  { q: "Le mot « pantalon » vient du nom d'un personnage :", choices: ["De la comédie italienne", "Grec", "Biblique", "Espagnol"], correct: 0 },
  { q: "Quel est le sens de l'expression « rendre son tablier » ?", choices: ["Cuisiner", "Démissionner", "Se salir", "S'excuser"], correct: 1 },
  { q: "Que signifie « avoir la main verte » ?", choices: ["Être malade", "Savoir jardiner", "Voler", "Être jaloux"], correct: 1 },
  { q: "Que veut dire « passer une nuit blanche » ?", choices: ["Bien dormir", "Ne pas dormir", "Rêver", "Se réveiller tôt"], correct: 1 },
  { q: "Que signifie l'expression « être dans de beaux draps » ?", choices: ["Être bien reposé", "Être dans une situation difficile", "Être riche", "Être propre"], correct: 1 },
  { q: "Que veut dire « jeter l'éponge » ?", choices: ["Abandonner", "Nettoyer", "Gagner", "Se laver"], correct: 0 },
  { q: "Que signifie « appeler un chat un chat » ?", choices: ["Se répéter", "Dire les choses franchement", "Mentir", "Flatter"], correct: 1 },
  { q: "Quel est le féminin correct de « ambassadeur » ?", choices: ["Ambassadeuse", "Ambassadrice", "Ambassadeure", "Ambassadère"], correct: 1 },
  { q: "Quelle est la bonne conjugaison : « Que je... » (verbe faire, subjonctif présent) ?", choices: ["fasse", "fais", "ferai", "faise"], correct: 0 },
  { q: "Quel est le participe passé du verbe « résoudre » ?", choices: ["Résolu", "Résous", "Résolvé", "Résoudu"], correct: 0 },
  { q: "Quelle est la forme correcte du verbe « mourir » au passé composé ?", choices: ["Il a mouru", "Il est mort", "Il a mort", "Il est mouru"], correct: 1 },
  { q: "Comment écrit-on l'adverbe formé sur « prudent » ?", choices: ["Prudament", "Prudemment", "Prudemant", "Prudément"], correct: 1 },
  { q: "Quel est le sens du mot « acabit » (ex : « du même acabit ») ?", choices: ["Genre, nature", "Village", "Défaut", "Métier"], correct: 0 },
];
