/* Quiz — banque PLANÈTE TERRE (géologie, volcans, océans, climat, météo).
   Format compact : [niveau, question, BONNE RÉPONSE, leurre, leurre, leurre] (ordre des
   choix tiré au hasard à l'affichage).
   Niveau : 1 facile, 2 moyen, 3 expert. */
const Q = [
  [1, "Quelle est la couche la plus externe de la Terre ?", "La croûte", "Le manteau", "Le noyau", "L'asthénosphère"],
  [1, "Comment appelle-t-on la roche en fusion tant qu'elle est sous la surface ?", "Le magma", "La lave", "Le basalte", "Le granite"],
  [1, "Comment s'appellent les grandes plaques mobiles qui forment la surface de la Terre ?", "Les plaques tectoniques", "Les plaques continentales fixes", "Les dorsales", "Les croûtes polaires"],
  [1, "Quel courant marin chaud adoucit le climat de l'Europe de l'Ouest ?", "Le Gulf Stream", "Le courant de Humboldt", "El Niño", "Le courant du Labrador"],
  [1, "Quel vent saisonnier apporte des pluies diluviennes en Inde ?", "La mousson", "Le mistral", "Le sirocco", "L'alizé"],
  [1, "Quel vent froid et violent souffle dans la vallée du Rhône ?", "Le mistral", "Le sirocco", "Le foehn", "Le blizzard"],
  [2, "Quel vent chaud, venu du Sahara, souffle sur la Méditerranée ?", "Le sirocco", "Le mistral", "La bise", "Le blizzard"],
  [1, "Comment appelle-t-on un cyclone tropical de l'Atlantique nord ?", "Un ouragan", "Un typhon", "Une tornade", "Une mousson"],
  [1, "Comment appelle-t-on un cyclone tropical du nord-ouest du Pacifique ?", "Un typhon", "Un ouragan", "Un blizzard", "Un sirocco"],
  [2, "Quel instrument mesure l'humidité de l'air ?", "L'hygromètre", "Le baromètre", "L'anémomètre", "Le pluviomètre"],
  [1, "Quelle est la plus grande calotte glaciaire du monde ?", "Celle de l'Antarctique", "Celle du Groenland", "Celle du Svalbard", "Celle de l'Alaska"],
  [2, "Quelle part de l'eau de la planète est de l'eau douce (environ) ?", "3 %", "30 %", "50 %", "0,1 %"],
  [2, "Quel type de roche forment la craie et le calcaire ?", "Une roche sédimentaire", "Une roche magmatique", "Une roche métamorphique", "Une roche volcanique"],
  [2, "Quel est le minéral le plus tendre de l'échelle de Mohs ?", "Le talc", "Le gypse", "La calcite", "Le quartz"],
  [1, "Comment appelle-t-on les concrétions qui pendent du plafond des grottes ?", "Les stalactites", "Les stalagmites", "Les géodes", "Les fossiles"],
  [1, "Comment s'appelle le triangle de bras multiples formé par certains fleuves à leur embouchure ?", "Un delta", "Un estuaire", "Un méandre", "Une lagune"],
  [1, "Comment appelle-t-on une longue vallée glaciaire envahie par la mer, en Norvège ?", "Un fjord", "Un atoll", "Un lagon", "Un canyon"],
  [1, "Comment s'appelle une île corallienne en forme d'anneau ?", "Un atoll", "Un fjord", "Un delta", "Un isthme"],
  [1, "Comment appelle-t-on la glace de mer qui flotte sur l'océan ?", "La banquise", "L'iceberg", "L'inlandsis", "Le névé"],
  [2, "De quoi le noyau terrestre est-il principalement composé ?", "De fer et de nickel", "De silicium et d'oxygène", "De carbone", "De granite"],
  [2, "Quel est le plus haut volcan actif d'Europe continentale et de ses îles méditerranéennes ?", "L'Etna", "Le Vésuve", "Le Stromboli", "Le Santorin"],
  [2, "Quel volcan islandais a paralysé le trafic aérien européen en 2010 ?", "L'Eyjafjallajökull", "L'Hekla", "Le Katla", "Le Grímsvötn"],
  [2, "Comment s'appelle l'arc de volcans et de séismes qui borde le Pacifique ?", "La ceinture de feu", "La dorsale atlantique", "Le rift africain", "La chaîne d'Hawaï"],
  [3, "Quel scientifique allemand a proposé la dérive des continents en 1912 ?", "Alfred Wegener", "Charles Lyell", "James Hutton", "Arthur Holmes"],
  [2, "Comment s'appelait le supercontinent qui réunissait toutes les terres il y a environ 300 millions d'années ?", "La Pangée", "Le Gondwana", "La Laurasia", "L'Atlantide"],
  [2, "Quelle est la profondeur approximative de la fosse des Mariannes ?", "Environ 11 000 m", "Environ 5 000 m", "Environ 8 800 m", "Environ 20 000 m"],
  [1, "Comment s'appelle le réchauffement périodique des eaux du Pacifique qui bouleverse la météo mondiale ?", "El Niño", "La Niña", "Le Gulf Stream", "La mousson"],
  [3, "Quelle échelle classe les ouragans de 1 à 5 ?", "L'échelle de Saffir-Simpson", "L'échelle de Richter", "L'échelle de Beaufort", "L'échelle de Fujita"],
  [3, "Quelle échelle mesure l'intensité des tornades ?", "L'échelle de Fujita", "L'échelle de Saffir-Simpson", "L'échelle de Beaufort", "L'échelle de Mercalli"],
  [1, "Quel organisme de l'ONU publie des rapports de référence sur le climat ?", "Le GIEC", "L'OMS", "L'Unesco", "Le FMI"],
  [2, "Dans quelle couche de l'atmosphère se forment presque tous les nuages ?", "La troposphère", "La stratosphère", "La mésosphère", "L'exosphère"],
  [3, "Le marbre est une roche… ?", "Métamorphique", "Sédimentaire", "Volcanique", "Organique"],
  [2, "Comment appelle-t-on une roche formée par le refroidissement du magma ?", "Une roche magmatique", "Une roche sédimentaire", "Une roche métamorphique", "Une roche calcaire"],
  [2, "Où se trouvent les plus fortes marées d'Europe continentale ?", "Dans la baie du Mont-Saint-Michel", "Dans le golfe de Gascogne", "En mer du Nord", "Dans le golfe du Lion"],
  [3, "Où trouve-t-on les plus grandes marées du monde ?", "Dans la baie de Fundy, au Canada", "Dans la baie du Mont-Saint-Michel", "En mer Rouge", "Dans le golfe du Bengale"],
  [2, "Quel est le point le plus bas des terres émergées ?", "Les rives de la mer Morte", "La vallée de la Mort", "La dépression de Qattara", "Le lac Assal"],
  [2, "Qu'est-ce que le pergélisol (permafrost) ?", "Un sol gelé en permanence", "Un glacier de montagne", "Un vent polaire", "Une banquise côtière"],
  [1, "D'où proviennent les icebergs ?", "Des glaciers et des calottes", "De la banquise", "De la pluie gelée", "Des nuages polaires"],
  [2, "Quels nuages fins et filamenteux se forment très haut dans le ciel ?", "Les cirrus", "Les cumulus", "Les stratus", "Les nimbostratus"],
  [3, "Quelle est la température la plus basse mesurée à la surface de la Terre (environ) ?", "−89 °C", "−50 °C", "−120 °C", "−273 °C"],
  [2, "Où a-t-on officiellement mesuré la température de l'air la plus élevée, 56,7 °C ?", "Dans la vallée de la Mort", "Dans le Sahara algérien", "Au Koweït", "En Australie"],
  [1, "Comment appelle-t-on un tremblement de terre qui suit le séisme principal ?", "Une réplique", "Un précurseur", "Un épicentre", "Un hypocentre"],
  [1, "Comment s'appelle le point de la surface situé à la verticale du foyer d'un séisme ?", "L'épicentre", "L'hypocentre", "La faille", "Le cratère"],
  [1, "Comment s'appelle la grande faille qui traverse la Californie ?", "La faille de San Andreas", "La faille de Hayward", "Le rift de l'Afar", "La faille du Levant"],
  [3, "Quelle est la limite entre la croûte et le manteau terrestres ?", "Le Moho (discontinuité de Mohorovičić)", "La discontinuité de Gutenberg", "La dorsale", "La zone de subduction"],
  [2, "Comment appelle-t-on l'enfoncement d'une plaque tectonique sous une autre ?", "La subduction", "L'obduction", "La convection", "L'érosion"],
  [2, "Quelle fracture géante est en train de couper l'Afrique de l'Est en deux ?", "Le grand rift est-africain", "La faille de San Andreas", "La dorsale atlantique", "La ceinture de feu"],
  [3, "Quel volcan indonésien a provoqué en 1815 la plus grande éruption des temps historiques ?", "Le Tambora", "Le Krakatoa", "Le Pinatubo", "Le Merapi"],
  [3, "Quelle « année sans été » a suivi l'éruption du Tambora ?", "1816", "1789", "1883", "1912"],
  [2, "Quel volcan de la Martinique a rasé Saint-Pierre en 1902 ?", "La montagne Pelée", "La Soufrière", "Le piton de la Fournaise", "Le Karthala"],
  [1, "Quel volcan de La Réunion est l'un des plus actifs du monde ?", "Le piton de la Fournaise", "Le piton des Neiges", "La montagne Pelée", "La Soufrière"],
  [2, "Quelle chaîne de volcans endormis se trouve en Auvergne ?", "La chaîne des Puys", "Le massif des Écrins", "Les Vosges", "Le massif de l'Esterel"],
  [2, "Quel est le point culminant de la chaîne des Puys ?", "Le puy de Dôme", "Le puy de Sancy", "Le Plomb du Cantal", "Le puy Mary"],
  [1, "Comment appelle-t-on une zone de basse pression atmosphérique ?", "Une dépression", "Un anticyclone", "Un front chaud", "Une isobare"],
  [1, "Comment appelle-t-on l'anticyclone qui commande souvent l'été en France ?", "L'anticyclone des Açores", "L'anticyclone de Sibérie", "La dépression d'Islande", "L'anticyclone du Groenland"],
  [1, "Quel gaz à effet de serre les ruminants rejettent-ils en grande quantité ?", "Le méthane", "L'ozone", "L'azote", "L'argon"],
  [1, "Quel mot désigne une période où les glaciers recouvraient une grande partie de l'Europe ?", "Une glaciation", "Une transgression", "Une orogenèse", "Une éruption"],
  [3, "Quand s'est achevée la dernière glaciation (environ) ?", "Il y a 12 000 ans", "Il y a 1 200 ans", "Il y a 120 000 ans", "Il y a 1,2 million d'années"],
  // — Expert, 3e vague (2026-10) —
  [3, "Quelle est l'épaisseur moyenne de la croûte océanique ?", "Environ 7 km", "Environ 35 km", "Environ 100 km", "Environ 1 km"],
  [3, "Quel minéral occupe le 9e rang de l'échelle de Mohs, juste avant le diamant ?", "Le corindon", "La topaze", "Le quartz", "L'orthose"],
  [3, "Quelle couche de l'atmosphère s'étend d'environ 50 à 85 km d'altitude ?", "La mésosphère", "La stratosphère", "La thermosphère", "L'exosphère"],
  [3, "Quelle échelle classe de I à XII l'intensité ressentie d'un séisme ?", "L'échelle de Mercalli", "L'échelle de Richter", "L'échelle de Beaufort", "L'échelle de Fujita"],
  [3, "À quelle profondeur environ se trouve le centre de la Terre ?", "Environ 6 370 km", "Environ 1 200 km", "Environ 12 700 km", "Environ 40 000 km"],
  [3, "Quel sommet est le point de la surface terrestre le plus éloigné du centre de la Terre ?", "Le Chimborazo", "L'Everest", "Le Kilimandjaro", "Le Mauna Kea"],
  [3, "Quel courant froid longe la côte ouest de l'Amérique du Sud ?", "Le courant de Humboldt", "Le Kuroshio", "Le courant des Canaries", "Le courant du Labrador"],
];
export const Q_TERRE = Q.map(([d, q, ...choices]) => ({ d, q, choices, correct: 0 }));
