/* Quiz bank GASTRO - correct = 0-based index. */
export const Q_GASTRO = [
  { q: "De quel pays la paella est-elle originaire ?", choices: ["Italie", "Espagne", "Portugal", "Grèce"], correct: 1 },
  { q: "Quel ingrédient donne sa couleur jaune caractéristique à la paella ?", choices: ["Curcuma", "Safran", "Paprika", "Curry"], correct: 1 },
  { q: "Le sushi est un plat emblématique de quel pays ?", choices: ["Chine", "Corée", "Japon", "Thaïlande"], correct: 2 },
  { q: "Quel fromage italien est traditionnellement utilisé dans le tiramisu ?", choices: ["Ricotta", "Mozzarella", "Mascarpone", "Gorgonzola"], correct: 2 },
  { q: "De quelle région le couscous est-il originaire ?", choices: ["Maghreb", "Turquie", "Liban", "Égypte"], correct: 0 },
  { q: "Quelle boisson alcoolisée est produite à partir d'agave ?", choices: ["Rhum", "Tequila", "Vodka", "Gin"], correct: 1 },
  { q: "Le fromage feta est traditionnellement associé à quel pays ?", choices: ["Italie", "Grèce", "Bulgarie", "Turquie"], correct: 1 },
  { q: "Quel plat japonais consiste en des nouilles servies dans un bouillon ?", choices: ["Ramen", "Tempura", "Sashimi", "Gyoza"], correct: 0 },
  { q: "De quel pays le goulasch est-il un plat traditionnel ?", choices: ["Pologne", "Hongrie", "Autriche", "Roumanie"], correct: 1 },
  { q: "Quelle épice est surnommée l'or rouge en raison de son prix élevé ?", choices: ["Paprika", "Safran", "Cannelle", "Poivre"], correct: 1 },
  { q: "Le guacamole est principalement à base de quel ingrédient ?", choices: ["Tomate", "Poivron", "Avocat", "Courgette"], correct: 2 },
  { q: "Quel alcool est la base du cocktail Mojito ?", choices: ["Rhum", "Gin", "Vodka", "Whisky"], correct: 0 },
  { q: "De quel pays les tacos sont-ils originaires ?", choices: ["Espagne", "Mexique", "Pérou", "Brésil"], correct: 1 },
  { q: "Quel fromage bleu français est affiné dans les caves de Roquefort-sur-Soulzon ?", choices: ["Bleu d'Auvergne", "Roquefort", "Fourme d'Ambert", "Gorgonzola"], correct: 1 },
  { q: "Le kimchi est un plat fermenté typique de quel pays ?", choices: ["Japon", "Chine", "Corée", "Vietnam"], correct: 2 },
  { q: "Quelle pâtisserie française est faite de deux coques et d'une ganache ?", choices: ["Éclair", "Macaron", "Financier", "Madeleine"], correct: 1 },
  { q: "De quel pays le fish and chips est-il un plat emblématique ?", choices: ["Irlande", "Royaume-Uni", "Australie", "Canada"], correct: 1 },
  { q: "Quel type de pâtes a la forme de petits tubes courts et striés ?", choices: ["Penne", "Spaghetti", "Farfalle", "Tagliatelle"], correct: 0 },
  { q: "Le champagne est produit dans quelle région française ?", choices: ["Bourgogne", "Champagne", "Alsace", "Provence"], correct: 1 },
  { q: "De quel pays le hummus est-il originaire ?", choices: ["Grèce", "Moyen-Orient", "Inde", "Espagne"], correct: 1 },
  { q: "Quel alcool japonais est fabriqué à partir de riz fermenté ?", choices: ["Soju", "Saké", "Baijiu", "Shochu"], correct: 1 },
  { q: "Quelle est la base du plat italien risotto ?", choices: ["Pâtes", "Riz", "Semoule", "Polenta"], correct: 1 },
  { q: "Le fromage emmental est reconnaissable à quelle caractéristique ?", choices: ["Sa croûte rouge", "Ses trous", "Sa moisissure bleue", "Sa forme ronde"], correct: 1 },
  { q: "De quel pays le pad thaï est-il originaire ?", choices: ["Vietnam", "Thaïlande", "Cambodge", "Malaisie"], correct: 1 },
  { q: "Quel condiment est associé à la ville de Modène en Italie ?", choices: ["Prosecco", "Vinaigre balsamique", "Limoncello", "Grappa"], correct: 1 },
  { q: "Quel dessert français est une crème caramélisée au sucre brûlé ?", choices: ["Crème brûlée", "Panna cotta", "Flan", "Mousse au chocolat"], correct: 0 },
  { q: "Le bortsch est une soupe traditionnelle de quelle région ?", choices: ["Scandinavie", "Europe de l'Est", "Balkans", "Caucase"], correct: 1 },
  { q: "Quelle épice provient de l'écorce séchée d'un arbre ?", choices: ["Muscade", "Cannelle", "Gingembre", "Cardamome"], correct: 1 },
  { q: "Quel cocktail est composé de vodka et de jus de tomate ?", choices: ["Bloody Mary", "Cosmopolitan", "Margarita", "Daiquiri"], correct: 0 },
  { q: "De quel pays le ceviche est-il un plat emblématique ?", choices: ["Mexique", "Pérou", "Chili", "Argentine"], correct: 1 },
  { q: "Quel fromage italien à pâte filée est utilisé sur la pizza ?", choices: ["Parmesan", "Mozzarella", "Pecorino", "Provolone"], correct: 1 },
  { q: "La choucroute est un plat traditionnel de quelle région française ?", choices: ["Bretagne", "Alsace", "Normandie", "Savoie"], correct: 1 },
  { q: "Quel est l'ingrédient principal du falafel ?", choices: ["Lentilles", "Pois chiches", "Haricots rouges", "Fèves de soja"], correct: 1 },
  { q: "Le tabasco est une sauce à base de quel ingrédient ?", choices: ["Tomate", "Piment", "Moutarde", "Ail"], correct: 1 },
  { q: "Quel cépage rouge est emblématique de la région de Bordeaux ?", choices: ["Pinot noir", "Merlot", "Gamay", "Syrah"], correct: 1 },
  { q: "De quelle région le baklava est-il une pâtisserie traditionnelle ?", choices: ["Grèce et Turquie", "Italie", "Espagne", "France"], correct: 0 },
  { q: "Quelle technique culinaire consiste à cuire lentement dans un sac hermétique à basse température ?", choices: ["Braiser", "Sous vide", "Pocher", "Rôtir"], correct: 1 },
  { q: "Le wasabi accompagne traditionnellement quel type de plat ?", choices: ["Pâtes", "Sushi", "Curry", "Tapas"], correct: 1 },
  { q: "Quel alcool écossais est vieilli en fût de chêne ?", choices: ["Bourbon", "Whisky", "Cognac", "Armagnac"], correct: 1 },
  { q: "De quel pays la moussaka est-elle un plat traditionnel ?", choices: ["Italie", "Grèce", "Espagne", "Liban"], correct: 1 },
  { q: "Quel fromage suisse est traditionnellement utilisé pour la fondue ?", choices: ["Gruyère", "Cheddar", "Brie", "Camembert"], correct: 0 },
  { q: "Quelle pâtisserie viennoise est un feuilleté aux pommes ?", choices: ["Strudel", "Sachertorte", "Croissant", "Kouign-amann"], correct: 0 },
  { q: "Le nuoc-mâm est une sauce typique de quelle cuisine ?", choices: ["Chinoise", "Vietnamienne", "Coréenne", "Japonaise"], correct: 1 },
  { q: "Quel cocktail classique associe gin et vermouth ?", choices: ["Martini", "Manhattan", "Negroni", "Old Fashioned"], correct: 0 },
  { q: "De quel pays le chorizo est-il une charcuterie traditionnelle ?", choices: ["Italie", "Espagne", "Allemagne", "Grèce"], correct: 1 },
  { q: "Quelle est la principale céréale utilisée pour faire la bière ?", choices: ["Blé", "Orge", "Maïs", "Riz"], correct: 1 },
  { q: "Le dim sum est une tradition culinaire de quel pays ?", choices: ["Japon", "Chine", "Thaïlande", "Corée"], correct: 1 },
  { q: "Quel plat italien consiste en de fines tranches de bœuf cru ?", choices: ["Carpaccio", "Bresaola", "Prosciutto", "Vitello tonnato"], correct: 0 },
  { q: "Quelle épice est extraite du pistil de la fleur de crocus ?", choices: ["Curcuma", "Safran", "Paprika", "Cumin"], correct: 1 },
  { q: "De quel pays le pho est-il une soupe emblématique ?", choices: ["Thaïlande", "Vietnam", "Cambodge", "Laos"], correct: 1 },
  { q: "Quel alcool français est distillé à partir de vin dans la région de Cognac ?", choices: ["Armagnac", "Cognac", "Calvados", "Marc"], correct: 1 },
  { q: "Quel fromage italien dur est traditionnellement râpé sur les pâtes ?", choices: ["Mozzarella", "Parmesan", "Burrata", "Ricotta"], correct: 1 },
  { q: "La sangria est une boisson traditionnelle de quel pays ?", choices: ["Italie", "Espagne", "Portugal", "Grèce"], correct: 1 },
  { q: "Quel plat marocain est cuit dans un récipient en terre cuite conique ?", choices: ["Couscous", "Tajine", "Pastilla", "Harira"], correct: 1 },
  { q: "De quel pays la poutine est-elle un plat emblématique ?", choices: ["États-Unis", "Canada", "Belgique", "France"], correct: 1 },
  { q: "Quelle boisson alcoolisée mexicaine est distillée à partir de l'agave bleue ?", choices: ["Mezcal", "Tequila", "Pulque", "Pisco"], correct: 1 },
  { q: "Quel dessert italien signifie littéralement remonte-moi le moral ?", choices: ["Panna cotta", "Tiramisu", "Cannoli", "Gelato"], correct: 1 },
  { q: "Quelle herbe aromatique est l'ingrédient principal du pesto genovese ?", choices: ["Persil", "Basilic", "Coriandre", "Menthe"], correct: 1 },
  { q: "De quel pays le biryani est-il un plat de riz épicé traditionnel ?", choices: ["Thaïlande", "Inde", "Chine", "Iran"], correct: 1 },
  { q: "Quel café italien est un expresso avec de la mousse de lait ?", choices: ["Ristretto", "Cappuccino", "Macchiato", "Americano"], correct: 1 },
  { q: "Le haggis est un plat traditionnel de quel pays ?", choices: ["Irlande", "Écosse", "Pays de Galles", "Angleterre"], correct: 1 },
  { q: "Quel piment est considéré comme l'un des plus forts au monde ?", choices: ["Jalapeño", "Carolina Reaper", "Piment d'Espelette", "Poivron"], correct: 1 },
  { q: "De quelles régions les empanadas sont-elles originaires ?", choices: ["Amérique latine et Espagne", "Italie", "Grèce", "Inde"], correct: 0 },
  { q: "Quel cocktail cubain associe rhum, citron vert et sucre ?", choices: ["Mojito", "Daiquiri", "Piña colada", "Cuba libre"], correct: 1 },
  { q: "Quelle est la base de la sauce béchamel ?", choices: ["Œufs et beurre", "Lait, beurre et farine", "Crème et vin", "Tomate et oignon"], correct: 1 },
  { q: "De quelle région le gravlax est-il une spécialité de saumon ?", choices: ["Écosse", "Scandinavie", "Russie", "Canada"], correct: 1 },
  { q: "Quel fromage frais indien est utilisé dans de nombreux currys ?", choices: ["Halloumi", "Paneer", "Feta", "Ricotta"], correct: 1 },
  { q: "Quelle liqueur italienne est parfumée au citron ?", choices: ["Amaretto", "Limoncello", "Sambuca", "Campari"], correct: 1 },
  { q: "Le kebab est un plat de viande grillée originaire de quelle région ?", choices: ["Inde", "Moyen-Orient", "Afrique du Nord", "Asie du Sud-Est"], correct: 1 },
  { q: "Quelle technique culinaire consiste à saisir rapidement à feu vif en remuant ?", choices: ["Sauté au wok", "Confire", "Blanchir", "Mijoter"], correct: 0 },
  { q: "De quel pays le gaspacho est-il une soupe froide traditionnelle ?", choices: ["Italie", "Espagne", "Portugal", "Grèce"], correct: 1 },
  { q: "Quel dessert français est une pâte à choux allongée garnie de crème ?", choices: ["Millefeuille", "Éclair", "Tarte Tatin", "Clafoutis"], correct: 1 },
  { q: "Quelle graine est utilisée pour fabriquer le tofu ?", choices: ["Pois chiche", "Soja", "Lentille", "Haricot rouge"], correct: 1 },
  { q: "De quel pays le rendang est-il un plat de viande mijotée originaire ?", choices: ["Thaïlande", "Indonésie", "Philippines", "Japon"], correct: 1 },
  { q: "Quel vin blanc pétillant italien est produit en Vénétie ?", choices: ["Prosecco", "Chianti", "Barolo", "Lambrusco"], correct: 0 },
  { q: "Quel condiment japonais est une pâte de soja fermentée ?", choices: ["Wasabi", "Miso", "Ponzu", "Mirin"], correct: 1 },
  { q: "De quel pays les bretzels sont-ils originaires ?", choices: ["Allemagne", "Autriche", "Suisse", "Pays-Bas"], correct: 0 },
  { q: "Quelle épice donne sa couleur jaune caractéristique au curry en poudre ?", choices: ["Safran", "Curcuma", "Paprika", "Cumin"], correct: 1 },
  { q: "Quel plat suisse consiste à faire fondre une meule de fromage et à le racler sur des pommes de terre ?", choices: ["Fondue", "Raclette", "Rösti", "Tartiflette"], correct: 1 },
  { q: "De quel pays le pisco sour est-il un cocktail emblématique ?", choices: ["Mexique", "Pérou", "Brésil", "Colombie"], correct: 1 },
  { q: "Quel fromage à pâte molle est célèbre pour sa croûte fleurie blanche ?", choices: ["Camembert", "Roquefort", "Comté", "Cantal"], correct: 0 },
  { q: "Quelle technique consiste à plonger brièvement des aliments dans l'eau bouillante ?", choices: ["Braiser", "Blanchir", "Rôtir", "Griller"], correct: 1 },
  { q: "Quelle liqueur à l'anis est traditionnellement bue en apéritif dans le sud de la France ?", choices: ["Pastis", "Absinthe", "Chartreuse", "Cointreau"], correct: 0 },
];
