/* Quiz bank TECHWEB - correct = 0-based index. */
export const Q_TECHWEB = [
  { q: "Que signifie l'acronyme HTML ?", choices: ["HyperText Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyperlink Text Management Logic"], correct: 0 },
  { q: "Qui a cofondé Microsoft avec Paul Allen ?", choices: ["Steve Jobs", "Bill Gates", "Larry Page", "Mark Zuckerberg"], correct: 1 },
  { q: "En quelle année Facebook a-t-il été lancé ?", choices: ["2000", "2002", "2004", "2007"], correct: 2 },
  { q: "Que signifie 'URL' ?", choices: ["Universal Reading Link", "User Reference Locator", "Unified Resource Line", "Uniform Resource Locator"], correct: 3 },
  { q: "Quelle entreprise a créé l'iPhone ?", choices: ["Apple", "Samsung", "Nokia", "Sony"], correct: 0 },
  { q: "Combien de bits contient un octet ?", choices: ["4", "8", "16", "32"], correct: 1 },
  { q: "Quel format d'image est réputé pour ses animations en boucle ?", choices: ["PNG", "JPEG", "BMP", "GIF"], correct: 3 },
  { q: "Quelle application de messagerie a été rachetée par Facebook en 2014 ?", choices: ["Telegram", "WhatsApp", "Signal", "Snapchat"], correct: 1 },
  { q: "Que désigne communément le terme 'Wi-Fi' ?", choices: ["Un type de câble", "Un logiciel", "Un réseau sans fil", "Un microprocesseur"], correct: 2 },
  { q: "Qui a cofondé Apple avec Steve Jobs et Ronald Wayne ?", choices: ["Steve Ballmer", "Sergey Brin", "Jack Dorsey", "Steve Wozniak"], correct: 3 },
  { q: "Quel réseau social est symbolisé par un petit oiseau à l'origine ?", choices: ["Twitter", "Instagram", "LinkedIn", "Pinterest"], correct: 0 },
  { q: "Que signifie 'CPU' en informatique ?", choices: ["Central Power Unit", "Central Processing Unit", "Computer Personal Unit", "Core Processing Utility"], correct: 1 },
  { q: "Quelle société a développé le système d'exploitation Android ?", choices: ["Apple", "Microsoft", "Google", "Samsung"], correct: 2 },
  { q: "Qui a cofondé Google avec Larry Page ?", choices: ["Eric Schmidt", "Bill Gates", "Steve Jobs", "Sergey Brin"], correct: 3 },
  { q: "Quelle unité est la plus grande ?", choices: ["Téraoctet", "Gigaoctet", "Mégaoctet", "Kilooctet"], correct: 0 },
  { q: "Quel navigateur web est développé par Mozilla ?", choices: ["Chrome", "Firefox", "Safari", "Edge"], correct: 1 },
  { q: "Que signifie l'acronyme 'PDF' ?", choices: ["Public Document Form", "Personal Data File", "Portable Document Format", "Print Document Frame"], correct: 2 },
  { q: "Quel réseau social professionnel a été racheté par Microsoft ?", choices: ["Facebook", "Xing", "Viadeo", "LinkedIn"], correct: 3 },
  { q: "Quelle entreprise est connue pour la boutique en ligne et le service AWS ?", choices: ["Amazon", "eBay", "Alibaba", "Rakuten"], correct: 0 },
  { q: "Que signifie 'RAM' ?", choices: ["Rapid Access Memory", "Random Access Memory", "Read Access Module", "Remote Applied Memory"], correct: 1 },
  { q: "Quel agent conversationnel a été lancé par OpenAI fin 2022 ?", choices: ["Bard", "Copilot", "ChatGPT", "Alexa"], correct: 2 },
  { q: "Quel est le protocole sécurisé de navigation web ?", choices: ["HTTPS", "FTP", "SMTP", "POP3"], correct: 0 },
  { q: "Quelle application permet de partager des photos et fut rachetée par Facebook en 2012 ?", choices: ["TikTok", "Instagram", "Flickr", "Snapchat"], correct: 1 },
  { q: "Que signifie 'USB' ?", choices: ["Universal System Bus", "United Serial Board", "Universal Serial Bus", "User Standard Bus"], correct: 2 },
  { q: "Qui a fondé Amazon ?", choices: ["Elon Musk", "Bill Gates", "Larry Ellison", "Jeff Bezos"], correct: 3 },
  { q: "Quel composant est considéré comme le 'cerveau' de l'ordinateur ?", choices: ["Le processeur", "Le disque dur", "La carte graphique", "L'écran"], correct: 0 },
  { q: "Quel réseau social basé sur des vidéos courtes appartient à ByteDance ?", choices: ["Vine", "TikTok", "Snapchat", "Triller"], correct: 1 },
  { q: "Que signifie 'IA' ?", choices: ["Information Automatique", "Interface Active", "Intelligence Artificielle", "Innovation Analytique"], correct: 2 },
  { q: "Quel géant informatique a créé le système d'exploitation Windows ?", choices: ["Apple", "IBM", "Google", "Microsoft"], correct: 3 },
  { q: "Quelle mémoire conserve les données même sans alimentation ?", choices: ["Le disque dur", "La RAM", "Le cache", "Les registres"], correct: 0 },
  { q: "Qui a créé le World Wide Web en 1989-1991 ?", choices: ["Vint Cerf", "Tim Berners-Lee", "Alan Turing", "Steve Jobs"], correct: 1 },
  { q: "Quelle entreprise fabrique les puces graphiques GeForce ?", choices: ["Intel", "AMD", "Nvidia", "Qualcomm"], correct: 2 },
  { q: "Que signifie 'ROM' ?", choices: ["Rapid Output Memory", "Remote Online Memory", "Random Output Module", "Read Only Memory"], correct: 3 },
  { q: "Quelle application de visioconférence a explosé en popularité en 2020 ?", choices: ["Zoom", "MSN", "ICQ", "Periscope"], correct: 0 },
  { q: "Quel est le langage de programmation nommé d'après un serpent ?", choices: ["Java", "Python", "Ruby", "Cobra"], correct: 1 },
  { q: "Que désigne le terme 'cookie' sur internet ?", choices: ["Un virus", "Un moteur de recherche", "Un petit fichier de données", "Un type d'écran"], correct: 2 },
  { q: "Quel système d'exploitation mobile équipe les iPhone ?", choices: ["Android", "Windows Phone", "Symbian", "iOS"], correct: 3 },
  { q: "Quel service de streaming vidéo appartient à Google ?", choices: ["YouTube", "Netflix", "Dailymotion", "Vimeo"], correct: 0 },
  { q: "Que signifie 'PC' ?", choices: ["Public Computer", "Personal Computer", "Portable Console", "Private Core"], correct: 1 },
  { q: "Quel réseau social a été créé par Evan Spiegel avec des messages éphémères ?", choices: ["Instagram", "WhatsApp", "Snapchat", "Telegram"], correct: 2 },
  { q: "Quelle société a créé le processeur Core i7 ?", choices: ["AMD", "Nvidia", "ARM", "Intel"], correct: 3 },
  { q: "Que signifie 'GPS' ?", choices: ["Global Positioning System", "General Position Software", "Global Personal Service", "Geo Public System"], correct: 0 },
  { q: "Quel est le nom de l'assistant vocal d'Apple ?", choices: ["Alexa", "Siri", "Cortana", "Bixby"], correct: 1 },
  { q: "Quelle entreprise a lancé le lecteur MP3 iPod ?", choices: ["Sony", "Samsung", "Apple", "Creative"], correct: 2 },
  { q: "Que signifie 'FAQ' sur un site web ?", choices: ["Fast Answer Query", "Free Access Question", "File Access Queue", "Foire Aux Questions"], correct: 3 },
  { q: "Quel réseau social a été racheté par Elon Musk en 2022 ?", choices: ["Twitter", "Facebook", "Reddit", "LinkedIn"], correct: 0 },
  { q: "Que mesure-t-on en 'pixels' ?", choices: ["La vitesse du réseau", "La résolution d'une image", "La capacité mémoire", "La fréquence du processeur"], correct: 1 },
  { q: "Quel navigateur est développé par Apple ?", choices: ["Chrome", "Edge", "Safari", "Opera"], correct: 2 },
  { q: "Que signifie 'LOL' dans le langage internet ?", choices: ["Lots Of Love", "Look Online Later", "Live On Location", "Laughing Out Loud"], correct: 3 },
  { q: "Quel est l'assistant vocal d'Amazon ?", choices: ["Alexa", "Siri", "Google Assistant", "Cortana"], correct: 0 },
  { q: "Quelle société a créé le réseau social Instagram avant son rachat ?", choices: ["Google", "Burbn (Systrom et Krieger)", "Yahoo", "Twitter"], correct: 1 },
  { q: "Que signifie 'VPN' ?", choices: ["Virtual Public Network", "Verified Private Node", "Virtual Private Network", "Variable Protocol Network"], correct: 2 },
  { q: "Quel composant stocke temporairement les données en cours d'utilisation ?", choices: ["Le disque dur", "Le processeur", "La carte mère", "La mémoire vive"], correct: 3 },
  { q: "Quelle entreprise a développé la console PlayStation ?", choices: ["Sony", "Microsoft", "Nintendo", "Sega"], correct: 0 },
  { q: "Que signifie 'email' littéralement ?", choices: ["Electric mailbox", "Electronic mail", "External mail", "Encrypted mail"], correct: 1 },
  { q: "Quel géant chinois est connu pour le commerce en ligne et son fondateur Jack Ma ?", choices: ["Tencent", "Baidu", "Alibaba", "Huawei"], correct: 2 },
  { q: "Que signifie 'IoT' ?", choices: ["Input Output Terminal", "Internal Online Transfer", "Interface Of Tools", "Internet of Things"], correct: 3 },
  { q: "Quel réseau social est centré sur le partage d'images à épingler ?", choices: ["Pinterest", "Reddit", "Tumblr", "Flickr"], correct: 0 },
  { q: "Quelle société édite le logiciel Photoshop ?", choices: ["Corel", "Adobe", "Microsoft", "Autodesk"], correct: 1 },
  { q: "Que signifie 'DNS' ?", choices: ["Data Network Service", "Digital Name Server", "Domain Name System", "Direct Node Service"], correct: 2 },
  { q: "Quel est le premier réseau ancêtre d'internet ?", choices: ["Minitel", "Ethernet", "Usenet", "ARPANET"], correct: 3 },
  { q: "Quelle entreprise fabrique les processeurs Ryzen ?", choices: ["AMD", "Intel", "Nvidia", "IBM"], correct: 0 },
  { q: "Que signifie 'app' dans le contexte des smartphones ?", choices: ["Appareil", "Application", "Appel", "Apparence"], correct: 1 },
  { q: "Quel réseau social favorise les discussions par forums appelés 'subreddits' ?", choices: ["Discord", "Quora", "Reddit", "4chan"], correct: 2 },
  { q: "Que signifie 'HTTP' ?", choices: ["High Transfer Text Protocol", "Hyper Tool Transfer Path", "Home Text Transfer Process", "HyperText Transfer Protocol"], correct: 3 },
  { q: "Quel service de messagerie électronique appartient à Google ?", choices: ["Gmail", "Outlook", "Yahoo Mail", "ProtonMail"], correct: 0 },
  { q: "Quelle unité mesure la fréquence d'un processeur ?", choices: ["Le watt", "Le hertz (gigahertz)", "L'octet", "Le pixel"], correct: 1 },
  { q: "Qui a fondé Facebook en 2004 ?", choices: ["Jack Dorsey", "Kevin Systrom", "Mark Zuckerberg", "Reid Hoffman"], correct: 2 },
  { q: "Que signifie 'SMS' ?", choices: ["System Message Service", "Simple Mobile Send", "Secure Mail System", "Short Message Service"], correct: 3 },
  { q: "Quel système d'exploitation libre est symbolisé par un manchot nommé Tux ?", choices: ["Linux", "Windows", "macOS", "Unix"], correct: 0 },
  { q: "Quelle société fabrique les smartphones Galaxy ?", choices: ["Apple", "Samsung", "Xiaomi", "Huawei"], correct: 1 },
  { q: "Que signifie 'CC' dans un email ?", choices: ["Correct Copy", "Central Contact", "Copie Carbone", "Confidential Contact"], correct: 2 },
  { q: "Quel format audio compressé est très répandu pour la musique ?", choices: ["WAV", "FLAC", "AAC", "MP3"], correct: 3 },
  { q: "Quelle entreprise a créé le moteur de recherche Bing ?", choices: ["Microsoft", "Google", "Yahoo", "Amazon"], correct: 0 },
  { q: "Que signifie 'FTP' ?", choices: ["Fast Transfer Path", "File Transfer Protocol", "Free Text Provider", "Full Transmission Port"], correct: 1 },
  { q: "Quel langage est principalement utilisé pour styliser les pages web ?", choices: ["PHP", "SQL", "CSS", "XML"], correct: 2 },
  { q: "Quelle société a racheté YouTube en 2006 ?", choices: ["Yahoo", "Microsoft", "Facebook", "Google"], correct: 3 },
  { q: "Que signifie 'GHz' ?", choices: ["Gigahertz", "Gigaoctet", "Graphique haute zone", "Grande hauteur"], correct: 0 },
  { q: "Quel protocole envoie les emails vers un serveur ?", choices: ["POP3", "SMTP", "IMAP", "HTTP"], correct: 1 },
  { q: "Quelle plateforme de code collaboratif a été rachetée par Microsoft en 2018 ?", choices: ["GitLab", "Bitbucket", "GitHub", "SourceForge"], correct: 2 },
  { q: "Que signifie le 'www' d'une adresse web ?", choices: ["World Wide Web dupliqué", "Web Working World", "Wide Web Wire", "World Wide Web"], correct: 3 },
];
