/* Quiz — banque CULTURES DU MONDE (fêtes, traditions, vêtements, langues, coutumes).
   Format compact : [niveau, question, BONNE RÉPONSE, leurre, leurre, leurre] (ordre des
   choix tiré au hasard à l'affichage).
   Niveau : 1 facile, 2 moyen, 3 expert. */
const Q = [
  [2, "Quelle fête hindoue est surnommée « la fête des lumières » ?", "Diwali", "Holi", "Ganesh Chaturthi", "Raksha Bandhan"],
  [2, "Comment appelle-t-on aussi le Nouvel An chinois ?", "La fête du Printemps", "La fête de la Lune", "La fête des Bateaux-Dragons", "Le Têt"],
  [1, "Dans quel pays fête-t-on Thanksgiving le quatrième jeudi de novembre ?", "Les États-Unis", "Le Royaume-Uni", "L'Australie", "L'Irlande"],
  [1, "Quel saint irlandais est fêté en vert le 17 mars ?", "Saint Patrick", "Saint Georges", "Saint André", "Saint David"],
  [1, "Quel jour célèbre-t-on l'Épiphanie, avec la galette des rois ?", "Le 6 janvier", "Le 1er janvier", "Le 2 février", "Le 25 décembre"],
  [1, "Dans quel pays se déroule la Tomatina, une gigantesque bataille de tomates ?", "L'Espagne", "L'Italie", "Le Mexique", "Le Portugal"],
  [1, "Quelle ville italienne est célèbre pour son carnaval masqué ?", "Venise", "Rome", "Naples", "Milan"],
  [1, "Quelle fête lyonnaise illumine la ville autour du 8 décembre ?", "La fête des Lumières", "La fête de la Musique", "Les Nuits sonores", "La Saint-Nicolas"],
  [1, "Quel jour a lieu la Fête de la musique ?", "Le 21 juin", "Le 14 juillet", "Le 1er mai", "Le 15 août"],
  [2, "Quel art japonais consiste à composer des bouquets de fleurs ?", "L'ikebana", "L'origami", "Le bonsaï", "Le kintsugi"],
  [1, "Quel art japonais consiste à plier du papier sans le couper ?", "L'origami", "L'ikebana", "Le furoshiki", "Le sumi-e"],
  [1, "Quel vêtement traditionnel japonais se ferme avec une large ceinture, l'obi ?", "Le kimono", "Le sari", "Le hanbok", "Le qipao"],
  [1, "Comment s'appelle le long drapé traditionnel des femmes indiennes ?", "Le sari", "Le kimono", "Le boubou", "Le hanbok"],
  [3, "Quel est le costume traditionnel coréen ?", "Le hanbok", "Le kimono", "Le qipao", "L'ao dai"],
  [1, "De quel pays la samba est-elle la danse emblématique ?", "Le Brésil", "L'Argentine", "Cuba", "Le Mexique"],
  [1, "Quel instrument des Aborigènes d'Australie est un long tube de bois ?", "Le didgeridoo", "Le djembé", "Le cor des Alpes", "La kora"],
  [1, "De quel continent le djembé est-il originaire ?", "L'Afrique", "L'Asie", "L'Amérique du Sud", "L'Océanie"],
  [1, "Comment dit-on « merci » en japonais ?", "Arigatō", "Konnichiwa", "Sayōnara", "Kanpai"],
  [1, "Quel mot lance-t-on en trinquant en Allemagne ?", "Prost !", "Skål !", "Salud !", "Kanpai !"],
  [1, "Dans quel pays le thé à la menthe est-il une institution ?", "Le Maroc", "La Turquie", "L'Inde", "Le Japon"],
  [1, "Quel bain de vapeur est une tradition de la Finlande ?", "Le sauna", "Le hammam", "Le jacuzzi", "L'onsen"],
  [1, "Quelle tradition mexicaine consiste à casser une figurine remplie de bonbons ?", "La piñata", "La quinceañera", "La posada", "Le mariachi"],
  [1, "En Chine, quelle couleur porte bonheur, notamment au Nouvel An ?", "Le rouge", "Le blanc", "Le vert", "Le noir"],
  [1, "Combien d'animaux compte le zodiaque chinois ?", "12", "10", "8", "13"],
  [2, "Quel animal ouvre le cycle du zodiaque chinois ?", "Le rat", "Le dragon", "Le tigre", "Le buffle"],
  [2, "Quelle ville française fête le citron chaque mois de février ?", "Menton", "Nice", "Antibes", "Cannes"],
  [1, "Quel ministre a créé la Fête de la musique en 1982 ?", "Jack Lang", "André Malraux", "Frédéric Mitterrand", "Jacques Toubon"],
  [2, "Quel art japonais répare les céramiques cassées avec de l'or ?", "Le kintsugi", "L'ikebana", "Le raku", "Le sumi-e"],
  [3, "Quel instrument à cordes est emblématique des griots d'Afrique de l'Ouest ?", "La kora", "Le sitar", "Le koto", "Le oud"],
  [2, "Quel instrument indien Ravi Shankar a-t-il fait connaître dans le monde entier ?", "Le sitar", "La kora", "Le koto", "Le bouzouki"],
  [2, "Quel instrument grec résonne dans la musique du film « Zorba le Grec » ?", "Le bouzouki", "La mandoline", "Le oud", "Le sitar"],
  [2, "Comment dit-on « santé » en trinquant en Suède ou au Danemark ?", "Skål !", "Prost !", "Salud !", "Na zdrowie !"],
  [1, "Quelle est la langue la plus parlée au monde en comptant ceux qui l'ont apprise ?", "L'anglais", "Le mandarin", "L'espagnol", "L'hindi"],
  [2, "Quelle langue construite, inventée par Zamenhof en 1887, se voulait universelle ?", "L'espéranto", "Le volapük", "Le latin", "Le sanskrit"],
  [3, "Dans combien de pays le français est-il langue officielle (environ) ?", "29", "9", "49", "79"],
  [1, "Quelle organisation rassemble les pays ayant le français en partage ?", "L'Organisation internationale de la francophonie", "Le Commonwealth", "L'Union latine", "La Ligue arabe"],
  [1, "Quelle organisation réunit le Royaume-Uni et la plupart de ses anciennes colonies ?", "Le Commonwealth", "L'OTAN", "L'ASEAN", "L'OCDE"],
  [3, "Comment s'appelle la cérémonie du thé japonaise ?", "Le chanoyu", "L'ikebana", "Le hanami", "Le matsuri"],
  [2, "Quelle tradition japonaise consiste à admirer les cerisiers en fleurs ?", "Le hanami", "Le chanoyu", "L'ikebana", "L'onsen"],
  [2, "Comment appelle-t-on les bains thermaux naturels du Japon ?", "Les onsen", "Les hammams", "Les ryokan", "Les izakaya"],
  [2, "À quel âge les jeunes filles d'Amérique latine fêtent-elles traditionnellement la quinceañera ?", "15 ans", "13 ans", "16 ans", "18 ans"],
  [1, "Comment s'appelle la cérémonie juive de la majorité religieuse d'un garçon, à 13 ans ?", "La bar-mitsva", "Le shabbat", "Hanoucca", "Souccot"],
  [2, "Quelle couleur porte traditionnellement la mariée en Inde ?", "Le rouge", "Le blanc", "Le noir", "Le bleu"],
  [2, "Quel nombre porte malheur au Japon et en Chine, parce qu'il se prononce comme le mot « mort » ?", "4", "13", "7", "9"],
  [2, "Quel nombre porte chance en Chine, parce qu'il évoque la prospérité ?", "8", "4", "13", "6"],
  [2, "Quel animal du zodiaque chinois correspond à l'année qui a commencé en 2024 ?", "Le dragon", "Le lapin", "Le serpent", "Le tigre"],
  [2, "Quel animal du zodiaque chinois correspond à l'année qui a commencé en 2026 ?", "Le cheval", "Le serpent", "La chèvre", "Le dragon"],
  [3, "Comment s'appelle le salut thaïlandais, mains jointes et tête inclinée ?", "Le wai", "L'ojigi", "Le hongi", "Le salam"],
  [3, "Quel salut maori consiste à presser son nez et son front contre ceux de l'autre ?", "Le hongi", "Le haka", "Le wai", "Le namasté"],
  [2, "Dans quel pays la « fika », pause café et pâtisserie, est-elle une institution ?", "La Suède", "La Norvège", "Le Danemark", "Les Pays-Bas"],
  [2, "Quel mot danois désigne un art de vivre douillet et chaleureux ?", "Le hygge", "La fika", "Le lagom", "Le sisu"],
  [2, "Quelle fête chinoise célèbre la pleine lune d'automne avec des gâteaux de lune ?", "La fête de la Mi-Automne", "La fête du Printemps", "La fête des Lanternes", "La fête de Qingming"],
  [2, "De quelle fête celtique Halloween tire-t-il son origine ?", "Samain", "Beltaine", "Imbolc", "Lughnasadh"],
  [2, "Quel vêtement d'homme d'Afrique de l'Ouest est une longue tunique ample ?", "Le boubou", "Le sari", "Le poncho", "Le kimono"],
  [1, "De quel pays d'Amérique du Sud le poncho et la flûte de Pan sont-ils emblématiques ?", "Du Pérou", "Du Brésil", "Du Venezuela", "De la Colombie"],
  [1, "Quelle danse traditionnelle est associée à l'Andalousie, avec castagnettes et talons ?", "Le flamenco", "Le paso doble", "La salsa", "La sardane"],
  [3, "Quelle danse catalane se danse en rond, les mains jointes levées ?", "La sardane", "Le flamenco", "La jota", "La muñeira"],
  [3, "Quel mot finlandais désigne la ténacité face à l'adversité ?", "Le sisu", "Le hygge", "La fika", "Le lagom"],
  [3, "Quel mot suédois désigne la juste mesure, « ni trop ni trop peu » ?", "Le lagom", "Le hygge", "Le sisu", "La fika"],
  [3, "Quel mot japonais désigne la mort par excès de travail ?", "Le karōshi", "Le hikikomori", "L'ikigai", "Le wabi-sabi"],
  [2, "Quel concept japonais désigne la « raison d'être » qui fait se lever le matin ?", "L'ikigai", "Le karōshi", "Le kaizen", "Le wabi-sabi"],
  [3, "Quelle philosophie japonaise trouve la beauté dans l'imperfection et l'éphémère ?", "Le wabi-sabi", "L'ikigai", "Le kaizen", "Le bushido"],
  [3, "Quelle fête chinoise rend hommage aux ancêtres en nettoyant leurs tombes, au printemps ?", "Qingming", "La fête des Lanternes", "La Mi-Automne", "La fête des Bateaux-Dragons"],
  [3, "Quelle fête japonaise du 3 mars est consacrée aux petites filles et à leurs poupées ?", "Hina matsuri", "Tanabata", "Obon", "Shichi-go-san"],
  [3, "Quelle fête japonaise de l'été accueille les esprits des ancêtres ?", "Obon", "Hanami", "Tanabata", "Setsubun"],
  [1, "Dans quel pays le Día de los Muertos est-il inscrit au patrimoine immatériel de l'Unesco ?", "Le Mexique", "L'Espagne", "Le Pérou", "La Colombie"],
  [1, "Quelle langue a le plus de locuteurs natifs en Inde ?", "L'hindi", "Le bengali", "Le tamoul", "L'ourdou"],
  [2, "Quelle langue est la plus parlée en Afrique comme langue véhiculaire de l'Est ?", "Le swahili", "Le zoulou", "L'amharique", "Le haoussa"],
  [3, "Combien de langues officielles l'Afrique du Sud reconnaît-elle depuis 2023 ?", "12", "2", "5", "20"],
  [2, "Quelle langue est parlée au Groenland par les Inuits, à côté du danois ?", "Le groenlandais (kalaallisut)", "Le same", "Le féroïen", "L'islandais"],
  [1, "Quelle langue celtique est encore parlée en Bretagne ?", "Le breton", "Le gallo", "Le basque", "L'occitan"],
  [1, "Quelle langue, sans parenté connue avec ses voisines, est parlée au Pays basque ?", "Le basque (euskara)", "Le béarnais", "Le catalan", "Le gascon"],
];
export const Q_MONDE = Q.map(([d, q, ...choices]) => ({ d, q, choices, correct: 0 }));
