/* Quiz — FRANCE, 2e vague (territoire, villes, outre-mer, institutions).
   Format compact : [niveau, question, BONNE RÉPONSE, leurre ×3] (ordre des choix tiré au
   hasard à l'affichage).
   Niveau : 1 facile, 2 moyen, 3 expert. */
const Q = [
  [2, "Quelle est la plus grande région de France métropolitaine ?", "La Nouvelle-Aquitaine", "L'Occitanie", "Auvergne-Rhône-Alpes", "Le Grand Est"],
  [3, "Quel est le département le plus peuplé de France ?", "Le Nord", "Paris", "Les Bouches-du-Rhône", "Le Rhône"],
  [2, "Quel code porte le département de la Corse-du-Sud ?", "2A", "20", "2B", "96"],
  [1, "Quelle ville est surnommée « la cité des Papes » ?", "Avignon", "Rome", "Reims", "Arles"],
  [2, "Dans quelle ville se trouve la Cité de l'espace ?", "Toulouse", "Bordeaux", "Kourou", "Marseille"],
  [1, "Près de quelle ville se trouve le parc du Futuroscope ?", "Poitiers", "Tours", "Limoges", "Angers"],
  [1, "Dans quel département se trouve le Puy du Fou ?", "La Vendée", "La Loire-Atlantique", "Les Deux-Sèvres", "Le Maine-et-Loire"],
  [1, "Quel est le parc de loisirs le plus visité d'Europe ?", "Disneyland Paris", "Europa-Park", "Le Puy du Fou", "Port Aventura"],
  [1, "Quelle est l'altitude du mont Blanc (environ) ?", "4 806 m", "4 478 m", "4 102 m", "5 642 m"],
  [2, "Lequel de ces territoires est un département d'outre-mer ?", "Mayotte", "La Polynésie française", "La Nouvelle-Calédonie", "Wallis-et-Futuna"],
  [1, "Quelle collectivité française se trouve au large du Canada ?", "Saint-Pierre-et-Miquelon", "Saint-Barthélemy", "Clipperton", "Wallis-et-Futuna"],
  [3, "Quel est le chef-lieu de la Guadeloupe ?", "Basse-Terre", "Pointe-à-Pitre", "Les Abymes", "Le Gosier"],
  [2, "Quel est le chef-lieu de la Martinique ?", "Fort-de-France", "Saint-Pierre", "Le Lamentin", "Schœlcher"],
  [1, "Quel est le chef-lieu de la Nouvelle-Calédonie ?", "Nouméa", "Papeete", "Mamoudzou", "Mata-Utu"],
  [3, "Quel est le chef-lieu de Mayotte ?", "Mamoudzou", "Dzaoudzi", "Moroni", "Saint-Denis"],
  [3, "Combien de présidents a eus la Ve République jusqu'à Emmanuel Macron inclus ?", "8", "6", "7", "10"],
  [2, "Quel fort du Var sert de résidence d'été officielle au président ?", "Le fort de Brégançon", "Le fort Boyard", "Le fort Saint-Jean", "Le château d'If"],
  [2, "Dans quel palais siège l'Assemblée nationale ?", "Le palais Bourbon", "Le palais du Luxembourg", "Le palais de l'Élysée", "Le palais Royal"],
  [1, "Dans quel hôtel parisien réside et travaille le Premier ministre ?", "L'hôtel de Matignon", "L'hôtel de Brienne", "L'hôtel de Lassay", "L'hôtel de Beauvau"],
  [2, "Quel ministère occupe l'hôtel de Beauvau ?", "Le ministère de l'Intérieur", "Le ministère des Armées", "Le ministère de la Justice", "Le ministère de la Culture"],
  [2, "Dans quel département se trouve la dune du Pilat, la plus haute d'Europe ?", "La Gironde", "Les Landes", "La Charente-Maritime", "Les Pyrénées-Atlantiques"],
  [2, "Quelles gorges de Provence sont surnommées « le Grand Canyon de l'Europe » ?", "Les gorges du Verdon", "Les gorges du Tarn", "Les gorges de l'Ardèche", "Les gorges du Gardon"],
  [3, "Quel cirque des Pyrénées est classé au patrimoine mondial avec sa grande cascade ?", "Le cirque de Gavarnie", "Le cirque de Troumouse", "Le cirque de Mafate", "Le cirque d'Estaubé"],
  [2, "Quelle île de l'Atlantique est la plus grande de France métropolitaine après la Corse ?", "L'île d'Oléron", "L'île de Ré", "Belle-Île-en-Mer", "Noirmoutier"],
  [1, "Quelle ville est la préfecture de la région Bretagne ?", "Rennes", "Brest", "Nantes", "Quimper"],
  [1, "Quelle ville est la préfecture de la région Occitanie ?", "Toulouse", "Montpellier", "Nîmes", "Perpignan"],
  [1, "Quelle ville est la préfecture de la région Hauts-de-France ?", "Lille", "Amiens", "Arras", "Calais"],
  [2, "Quelle ville est la préfecture de la région Normandie ?", "Rouen", "Caen", "Le Havre", "Cherbourg"],
  [2, "Quelle ville est la préfecture de la région Bourgogne-Franche-Comté ?", "Dijon", "Besançon", "Auxerre", "Mâcon"],
  [2, "Quelle ville est la préfecture de la région Centre-Val de Loire ?", "Orléans", "Tours", "Bourges", "Blois"],
  [2, "Quel département porte le numéro 01 ?", "L'Ain", "L'Aisne", "L'Allier", "Les Ardennes"],
  // — Expert, 3e vague (2026-10) —
  [3, "Quel est le plus haut sommet des Pyrénées françaises ?", "Le Vignemale", "Le pic du Midi de Bigorre", "Le Canigou", "L'Aneto"],
  [3, "Quelle ville est la préfecture de l'Aveyron ?", "Rodez", "Millau", "Villefranche-de-Rouergue", "Albi"],
  [3, "Quelle est la plus petite commune de France par la superficie ?", "Castelmoron-d'Albret", "Rochefourchat", "Le Mont-Saint-Michel", "Saint-Martin-de-Ré"],
  [3, "Quel est le département le moins peuplé de France ?", "La Lozère", "La Creuse", "Le Cantal", "Les Hautes-Alpes"],
  [3, "Combien de communes compte la France, environ ?", "35 000", "12 000", "22 000", "52 000"],
  [3, "De quelles anciennes régions est née l'Occitanie en 2016 ?", "Languedoc-Roussillon et Midi-Pyrénées", "Provence et Languedoc-Roussillon", "Aquitaine et Midi-Pyrénées", "Auvergne et Limousin"],
];
export const Q3_FRANCE = Q.map(([d, q, ...choices]) => ({ d, q, choices, correct: 0 }));
