/* Quiz culture générale. correct = index de la bonne réponse (0-based).
   Banque rédigée à la main (90). Les gages sont centralisés dans src/gages.js. */
export const QUESTIONS = [
  { q: "Quelle est la capitale de l'Australie ?", choices: ["Sydney", "Canberra", "Melbourne", "Perth"], correct: 1 },
  { q: "Combien de côtés a un hexagone ?", choices: ["5", "6", "7", "8"], correct: 1 },
  { q: "Qui a peint la Joconde ?", choices: ["Michel-Ange", "Raphaël", "Léonard de Vinci", "Botticelli"], correct: 2 },
  { q: "Quel est l'élément chimique O ?", choices: ["Or", "Osmium", "Oxygène", "Oganesson"], correct: 2 },
  { q: "En quelle année a eu lieu la chute du mur de Berlin ?", choices: ["1987", "1989", "1991", "1993"], correct: 1 },
  { q: "Quel océan est le plus grand ?", choices: ["Atlantique", "Indien", "Arctique", "Pacifique"], correct: 3 },
  { q: "Combien de joueurs dans une équipe de foot sur le terrain ?", choices: ["9", "10", "11", "12"], correct: 2 },
  { q: "Quelle planète est la plus proche du Soleil ?", choices: ["Vénus", "Mercure", "Mars", "Terre"], correct: 1 },
  { q: "Qui a écrit « Les Misérables » ?", choices: ["Zola", "Balzac", "Hugo", "Flaubert"], correct: 2 },
  { q: "Quel pays a gagné la Coupe du monde 2018 ?", choices: ["Croatie", "France", "Allemagne", "Brésil"], correct: 1 },
  { q: "Quelle est la capitale du Canada ?", choices: ["Toronto", "Vancouver", "Ottawa", "Montréal"], correct: 2 },
  { q: "Combien y a-t-il de continents ?", choices: ["5", "6", "7", "8"], correct: 2 },
  { q: "Quel fleuve traverse Paris ?", choices: ["La Loire", "Le Rhône", "La Seine", "La Garonne"], correct: 2 },
  { q: "Quel est le plus long fleuve du monde ?", choices: ["L'Amazone", "Le Nil", "Le Mississippi", "Le Yangzi"], correct: 1 },
  { q: "Dans quel pays se trouve le Machu Picchu ?", choices: ["Mexique", "Bolivie", "Pérou", "Chili"], correct: 2 },
  { q: "Quelle mer borde Marseille ?", choices: ["Mer du Nord", "Méditerranée", "Atlantique", "Mer Noire"], correct: 1 },
  { q: "Quel désert est le plus grand désert chaud du monde ?", choices: ["Gobi", "Kalahari", "Sahara", "Atacama"], correct: 2 },
  { q: "Combien d'états composent les États-Unis ?", choices: ["48", "50", "52", "54"], correct: 1 },
  { q: "Quelle est la monnaie du Japon ?", choices: ["Le won", "Le yuan", "Le yen", "Le baht"], correct: 2 },
  { q: "Quel pays a la forme d'une botte ?", choices: ["Espagne", "Grèce", "Italie", "Portugal"], correct: 2 },
  { q: "Quelle est la plus haute montagne du monde ?", choices: ["K2", "Mont Blanc", "Everest", "Kilimandjaro"], correct: 2 },
  { q: "En quelle année l'homme a-t-il marché sur la Lune pour la première fois ?", choices: ["1965", "1969", "1971", "1975"], correct: 1 },
  { q: "Qui était surnommé le Roi-Soleil ?", choices: ["Louis XIV", "Louis XVI", "Napoléon", "François Ier"], correct: 0 },
  { q: "En quelle année a commencé la Première Guerre mondiale ?", choices: ["1912", "1914", "1916", "1918"], correct: 1 },
  { q: "Qui a découvert l'Amérique en 1492 ?", choices: ["Magellan", "Vasco de Gama", "Christophe Colomb", "Marco Polo"], correct: 2 },
  { q: "Quelle reine d'Égypte a séduit César ?", choices: ["Néfertiti", "Cléopâtre", "Hatchepsout", "Isis"], correct: 1 },
  { q: "Quel monument parisien a été construit pour l'Exposition de 1889 ?", choices: ["L'Arc de Triomphe", "Le Louvre", "La tour Eiffel", "Le Panthéon"], correct: 2 },
  { q: "Quelle civilisation a construit les pyramides de Gizeh ?", choices: ["Les Mayas", "Les Égyptiens", "Les Aztèques", "Les Grecs"], correct: 1 },
  { q: "En quelle année la Révolution française a-t-elle éclaté ?", choices: ["1789", "1792", "1799", "1804"], correct: 0 },
  { q: "Quel navire « insubmersible » a coulé en 1912 ?", choices: ["Le Lusitania", "Le Britannic", "Le Titanic", "Le Queen Mary"], correct: 2 },
  { q: "Combien d'os compte environ le corps humain adulte ?", choices: ["106", "206", "306", "406"], correct: 1 },
  { q: "Quelle est la vitesse de la lumière (environ) ?", choices: ["300 km/s", "3 000 km/s", "300 000 km/s", "3 millions km/s"], correct: 2 },
  { q: "Quel gaz les plantes absorbent-elles ?", choices: ["Oxygène", "Azote", "CO2", "Hydrogène"], correct: 2 },
  { q: "Combien de cœurs possède une pieuvre ?", choices: ["1", "2", "3", "4"], correct: 2 },
  { q: "Quelle planète est surnommée la planète rouge ?", choices: ["Vénus", "Jupiter", "Mars", "Saturne"], correct: 2 },
  { q: "Quel est l'organe le plus lourd du corps humain ?", choices: ["Le cerveau", "Le foie", "La peau", "Les poumons"], correct: 2 },
  { q: "À quelle température l'eau bout-elle au niveau de la mer ?", choices: ["90 °C", "95 °C", "100 °C", "110 °C"], correct: 2 },
  { q: "Quel animal est le plus rapide au monde en course ?", choices: ["Le lion", "Le guépard", "L'antilope", "Le lévrier"], correct: 1 },
  { q: "Combien de pattes a une araignée ?", choices: ["6", "8", "10", "12"], correct: 1 },
  { q: "Quel est le plus grand mammifère du monde ?", choices: ["L'éléphant", "Le rorqual bleu", "L'orque", "La girafe"], correct: 1 },
  { q: "Les dauphins sont des… ?", choices: ["Poissons", "Mammifères", "Reptiles", "Amphibiens"], correct: 1 },
  { q: "Quel métal est liquide à température ambiante ?", choices: ["Le plomb", "Le mercure", "L'étain", "Le zinc"], correct: 1 },
  { q: "Combien de dents a un adulte (avec les dents de sagesse) ?", choices: ["28", "30", "32", "36"], correct: 2 },
  { q: "Quelle est la formule chimique de l'eau ?", choices: ["CO2", "H2O", "O2", "NaCl"], correct: 1 },
  { q: "Quel sport pratique Teddy Riner ?", choices: ["La boxe", "Le judo", "La lutte", "Le karaté"], correct: 1 },
  { q: "Combien de temps dure un match de foot (hors arrêts de jeu) ?", choices: ["80 min", "90 min", "100 min", "120 min"], correct: 1 },
  { q: "Dans quel sport parle-t-on de « grand chelem » ?", choices: ["Le golf", "Le tennis", "L'escrime", "Le cyclisme"], correct: 1 },
  { q: "Combien d'anneaux sur le drapeau olympique ?", choices: ["4", "5", "6", "7"], correct: 1 },
  { q: "Quelle course cycliste se termine sur les Champs-Élysées ?", choices: ["Paris-Roubaix", "Le Giro", "Le Tour de France", "La Vuelta"], correct: 2 },
  { q: "Au basket, combien de points vaut un panier derrière la ligne ?", choices: ["1", "2", "3", "4"], correct: 2 },
  { q: "Quel pays a inventé le judo ?", choices: ["Chine", "Corée", "Japon", "Thaïlande"], correct: 2 },
  { q: "Combien de joueurs dans une équipe de volley sur le terrain ?", choices: ["5", "6", "7", "8"], correct: 1 },
  { q: "Quelle nage est la plus lente en compétition ?", choices: ["Le crawl", "Le dos", "La brasse", "Le papillon"], correct: 2 },
  { q: "Où se déroule le tournoi de Roland-Garros ?", choices: ["Londres", "New York", "Paris", "Melbourne"], correct: 2 },
  { q: "Qui a chanté « Thriller » ?", choices: ["Prince", "Michael Jackson", "Stevie Wonder", "Lionel Richie"], correct: 1 },
  { q: "Quel groupe a composé « Bohemian Rhapsody » ?", choices: ["The Beatles", "Queen", "Pink Floyd", "The Rolling Stones"], correct: 1 },
  { q: "Quel instrument a 88 touches ?", choices: ["L'orgue", "Le piano", "L'accordéon", "Le clavecin"], correct: 1 },
  { q: "Qui interprète « Alors on danse » ?", choices: ["Maître Gims", "Stromae", "Soprano", "Black M"], correct: 1 },
  { q: "Combien de cordes a une guitare classique ?", choices: ["4", "5", "6", "7"], correct: 2 },
  { q: "Quel film détient le record du box-office mondial ?", choices: ["Titanic", "Avatar", "Avengers: Endgame", "Star Wars VII"], correct: 1 },
  { q: "Qui joue Jack dans « Titanic » ?", choices: ["Brad Pitt", "Johnny Depp", "Leonardo DiCaprio", "Matt Damon"], correct: 2 },
  { q: "Dans « Star Wars », qui est le père de Luke ?", choices: ["Obi-Wan", "Yoda", "Dark Vador", "Palpatine"], correct: 2 },
  { q: "Quel studio a créé « Toy Story » ?", choices: ["DreamWorks", "Pixar", "Ghibli", "Illumination"], correct: 1 },
  { q: "Dans « Harry Potter », quelle est la maison de Harry ?", choices: ["Serpentard", "Poufsouffle", "Gryffondor", "Serdaigle"], correct: 2 },
  { q: "Quel super-héros vient de la planète Krypton ?", choices: ["Batman", "Superman", "Thor", "Flash"], correct: 1 },
  { q: "Combien de saisons compte « Friends » ?", choices: ["8", "9", "10", "12"], correct: 2 },
  { q: "Quel personnage habite dans un ananas sous la mer ?", choices: ["Nemo", "Bob l'éponge", "Dory", "Patrick"], correct: 1 },
  { q: "De quel pays vient la paella ?", choices: ["Italie", "Portugal", "Espagne", "Mexique"], correct: 2 },
  { q: "Quel fromage est traditionnellement utilisé pour la raclette ?", choices: ["Comté", "Raclette", "Reblochon", "Emmental"], correct: 1 },
  { q: "Le sushi est originaire de quel pays ?", choices: ["Chine", "Japon", "Corée", "Vietnam"], correct: 1 },
  { q: "Quel alcool sert de base au mojito ?", choices: ["Vodka", "Rhum", "Gin", "Tequila"], correct: 1 },
  { q: "De quelle région vient le champagne ?", choices: ["Bourgogne", "Champagne", "Alsace", "Provence"], correct: 1 },
  { q: "Qu'est-ce que le guacamole ?", choices: ["Une sauce tomate", "Une purée d'avocat", "Une crème de maïs", "Un fromage fondu"], correct: 1 },
  { q: "Quel est l'ingrédient principal du houmous ?", choices: ["Lentilles", "Pois chiches", "Haricots", "Fèves"], correct: 1 },
  { q: "La tarte Tatin est une tarte… ?", choices: ["Au citron", "Renversée aux pommes", "Au chocolat", "Aux noix"], correct: 1 },
  { q: "Combien de lettres dans l'alphabet français ?", choices: ["24", "25", "26", "27"], correct: 2 },
  { q: "Quelle langue compte le plus de locuteurs natifs ?", choices: ["Anglais", "Espagnol", "Mandarin", "Hindi"], correct: 2 },
  { q: "Que signifie « www » ?", choices: ["World Wide Web", "World Web Wide", "Wide World Web", "Web World Wide"], correct: 0 },
  { q: "Quel réseau social a un fantôme pour logo ?", choices: ["TikTok", "Snapchat", "Twitch", "Discord"], correct: 1 },
  { q: "Qui a fondé Tesla et SpaceX ?", choices: ["Jeff Bezos", "Elon Musk", "Bill Gates", "Steve Jobs"], correct: 1 },
  { q: "Combien font 7 × 8 ?", choices: ["54", "56", "58", "64"], correct: 1 },
  { q: "Quel est le chiffre romain pour 50 ?", choices: ["C", "D", "L", "M"], correct: 2 },
  { q: "Combien de minutes dans une journée ?", choices: ["1 240", "1 440", "1 640", "2 440"], correct: 1 },
  { q: "Quel animal figure sur le logo de Lacoste ?", choices: ["Un requin", "Un crocodile", "Un lézard", "Un serpent"], correct: 1 },
  { q: "De quelle couleur est la boîte noire d'un avion ?", choices: ["Noire", "Orange", "Rouge", "Jaune"], correct: 1 },
  { q: "Quel pays est célèbre pour ses champs de tulipes et ses moulins ?", choices: ["France", "Pays-Bas", "Belgique", "Danemark"], correct: 1 },
  { q: "Combien de zéros dans un million ?", choices: ["5", "6", "7", "9"], correct: 1 },
  { q: "Quelle est la devise de la France ?", choices: ["Unité, Progrès, Justice", "Liberté, Égalité, Fraternité", "Dieu et mon droit", "Paix et Travail"], correct: 1 },
  { q: "Le Colisée se trouve dans quelle ville ?", choices: ["Athènes", "Rome", "Naples", "Milan"], correct: 1 },
];
