/* Quiz bank SANTE - correct = 0-based index. */
export const Q_SANTE = [
  { q: "Quelle vitamine est produite par la peau sous l'effet du soleil ?", choices: ["Vitamine C", "Vitamine D", "Vitamine B12", "Vitamine K"], correct: 1 },
  { q: "Quel organe produit l'insuline ?", choices: ["Le foie", "Les reins", "Le pancréas", "La rate"], correct: 2 },
  { q: "Le scorbut est causé par une carence en quelle vitamine ?", choices: ["Vitamine C", "Vitamine A", "Vitamine D", "Vitamine E"], correct: 0 },
  { q: "Combien de temps dure environ un cycle de sommeil complet chez l'adulte ?", choices: ["30 minutes", "90 minutes", "3 heures", "20 minutes"], correct: 1 },
  { q: "Quel numéro appelle-t-on pour les urgences médicales (SAMU) en France ?", choices: ["17", "18", "15", "119"], correct: 2 },
  { q: "Quelle est la température corporelle normale moyenne d'un adulte ?", choices: ["35 °C", "37 °C", "39 °C", "41 °C"], correct: 1 },
  { q: "Quel nutriment est la principale source d'énergie rapide pour l'organisme ?", choices: ["Les lipides", "Les protéines", "Les glucides", "Les fibres"], correct: 2 },
  { q: "Que signifie le sigle IMC en santé ?", choices: ["Indice de masse corporelle", "Index métabolique cellulaire", "Indice musculaire corporel", "Indicateur de masse calorique"], correct: 0 },
  { q: "Quelle maladie est provoquée par un manque d'iode et affecte la thyroïde ?", choices: ["Le diabète", "Le goitre", "L'anémie", "Le rachitisme"], correct: 1 },
  { q: "Quel geste de premiers secours est utilisé en cas d'étouffement ?", choices: ["Le bouche-à-bouche", "La manœuvre de Heimlich", "La position latérale de sécurité", "Le massage cardiaque"], correct: 1 },
  { q: "Quel minéral est essentiel pour la solidité des os et des dents ?", choices: ["Le fer", "Le calcium", "Le zinc", "Le sodium"], correct: 1 },
  { q: "Quelle carence provoque principalement l'anémie la plus courante ?", choices: ["Manque de fer", "Manque de calcium", "Manque de vitamine D", "Manque de potassium"], correct: 0 },
  { q: "Combien de dents compte en moyenne un adulte (dents de sagesse incluses) ?", choices: ["28", "30", "32", "36"], correct: 2 },
  { q: "Quel est le rôle principal des globules rouges ?", choices: ["Combattre les infections", "Transporter l'oxygène", "Coaguler le sang", "Digérer les graisses"], correct: 1 },
  { q: "Quelle vitamine est essentielle à la coagulation du sang ?", choices: ["Vitamine C", "Vitamine K", "Vitamine B6", "Vitamine A"], correct: 1 },
  { q: "Quel type de microbe est responsable de la grippe ?", choices: ["Une bactérie", "Un virus", "Un champignon", "Un parasite"], correct: 1 },
  { q: "Contre quel type de microbe les antibiotiques sont-ils efficaces ?", choices: ["Les virus", "Les bactéries", "Les champignons uniquement", "Tous les microbes"], correct: 1 },
  { q: "Quel organe filtre le sang et produit l'urine ?", choices: ["Le foie", "La rate", "Les reins", "Le pancréas"], correct: 2 },
  { q: "Combien de litres de sang contient environ le corps d'un adulte ?", choices: ["2 à 3 litres", "5 à 6 litres", "9 à 10 litres", "12 à 14 litres"], correct: 1 },
  { q: "Quel aliment est particulièrement riche en vitamine C ?", choices: ["Le pain", "L'orange", "Le beurre", "Le riz"], correct: 1 },
  { q: "Que mesure un tensiomètre ?", choices: ["La glycémie", "La température", "La pression artérielle", "Le taux d'oxygène"], correct: 2 },
  { q: "Comment appelle-t-on le trouble caractérisé par une difficulté persistante à dormir ?", choices: ["Apnée", "Insomnie", "Narcolepsie", "Somnambulisme"], correct: 1 },
  { q: "Quel est le plus grand organe du corps humain ?", choices: ["Le foie", "Les poumons", "La peau", "L'intestin"], correct: 2 },
  { q: "Quelle boisson est recommandée pour bien s'hydrater au quotidien ?", choices: ["Les sodas", "L'eau", "Le café", "Les jus sucrés"], correct: 1 },
  { q: "Que faut-il faire en priorité sur une brûlure légère ?", choices: ["Appliquer du beurre", "La refroidir à l'eau courante fraîche", "Percer la cloque", "Appliquer de la glace directement"], correct: 1 },
  { q: "Quel sens est associé à la cochlée dans l'oreille ?", choices: ["L'équilibre", "L'audition", "Le goût", "L'odorat"], correct: 1 },
  { q: "Quelle est la principale cause du diabète de type 2 ?", choices: ["Une infection virale", "Une résistance à l'insuline", "Un manque de vitamine C", "Une carence en fer"], correct: 1 },
  { q: "Quel nutriment participe surtout à la construction des muscles ?", choices: ["Les glucides", "Les lipides", "Les protéines", "Les fibres"], correct: 2 },
  { q: "Que provoque une carence sévère en vitamine D chez l'enfant ?", choices: ["Le scorbut", "Le rachitisme", "La pellagre", "Le béribéri"], correct: 1 },
  { q: "Quel organe est atteint par l'hépatite ?", choices: ["Le cœur", "Le foie", "Les reins", "Les poumons"], correct: 1 },
  { q: "Combien d'heures de sommeil sont recommandées en moyenne pour un adulte ?", choices: ["3 à 4 heures", "7 à 9 heures", "10 à 12 heures", "5 heures maximum"], correct: 1 },
  { q: "Quel muscle est le plus sollicité pour pomper le sang ?", choices: ["Le diaphragme", "Le cœur", "Le biceps", "Les abdominaux"], correct: 1 },
  { q: "Quelle partie de l'œil contient les cellules sensibles à la lumière ?", choices: ["La cornée", "La rétine", "L'iris", "Le cristallin"], correct: 1 },
  { q: "Comment appelle-t-on un médecin spécialiste de la peau ?", choices: ["Cardiologue", "Dermatologue", "Neurologue", "Ophtalmologue"], correct: 1 },
  { q: "Quel fluide est produit par les glandes sudoripares ?", choices: ["Le sébum", "La sueur", "La salive", "Les larmes"], correct: 1 },
  { q: "Quelle vitamine est particulièrement importante pour la vision nocturne ?", choices: ["Vitamine A", "Vitamine C", "Vitamine D", "Vitamine K"], correct: 0 },
  { q: "Que faut-il faire face à une personne inconsciente qui respire ?", choices: ["Massage cardiaque", "Position latérale de sécurité", "Bouche-à-bouche", "La faire boire"], correct: 1 },
  { q: "Quel type de fibres favorise le bon transit intestinal ?", choices: ["Les fibres alimentaires", "Les fibres musculaires", "Les fibres nerveuses", "Les fibres optiques"], correct: 0 },
  { q: "Quel gaz respirons-nous et est vital pour nos cellules ?", choices: ["L'azote", "L'oxygène", "Le dioxyde de carbone", "L'hydrogène"], correct: 1 },
  { q: "Comment s'appelle le spécialiste des dents ?", choices: ["Podologue", "Dentiste", "Orthophoniste", "Kinésithérapeute"], correct: 1 },
  { q: "Quelle habitude est la plus efficace pour prévenir la propagation des microbes ?", choices: ["Se laver les mains", "Manger épicé", "Boire du thé", "Faire du sport"], correct: 0 },
  { q: "Quel organe stocke la bile produite par le foie ?", choices: ["L'estomac", "La vésicule biliaire", "Le pancréas", "La rate"], correct: 1 },
  { q: "Que signifie être à jeun avant une prise de sang courante ?", choices: ["Ne pas dormir", "Ne pas manger depuis plusieurs heures", "Ne pas parler", "Ne pas bouger"], correct: 1 },
  { q: "Quelle est la fréquence cardiaque normale au repos chez l'adulte ?", choices: ["20 à 40 battements/min", "60 à 100 battements/min", "120 à 150 battements/min", "150 à 180 battements/min"], correct: 1 },
  { q: "Quel élément le fluor renforce-t-il principalement ?", choices: ["Les cheveux", "L'émail des dents", "Les ongles", "La peau"], correct: 1 },
  { q: "Quelle maladie est causée par une glycémie chroniquement élevée ?", choices: ["L'asthme", "Le diabète", "L'arthrose", "La migraine"], correct: 1 },
  { q: "Quel organe permet les échanges gazeux avec le sang ?", choices: ["Le cœur", "Les poumons", "L'estomac", "Le foie"], correct: 1 },
  { q: "Comment appelle-t-on l'inflammation des articulations ?", choices: ["La gastrite", "L'arthrite", "La bronchite", "La cystite"], correct: 1 },
  { q: "Quel nutriment apporte le plus de calories par gramme ?", choices: ["Les glucides", "Les protéines", "Les lipides", "Les fibres"], correct: 2 },
  { q: "Quelle vitamine du groupe B, absente des végétaux, est surtout d'origine animale ?", choices: ["Vitamine B12", "Vitamine C", "Vitamine D", "Vitamine E"], correct: 0 },
  { q: "Quel est le principal symptôme de la déshydratation ?", choices: ["La faim", "La soif intense", "Les frissons", "Les éternuements"], correct: 1 },
  { q: "Comment appelle-t-on la pratique de prendre soin de sa santé mentale et physique globale ?", choices: ["Le bien-être", "La chirurgie", "La radiologie", "La pharmacologie"], correct: 0 },
  { q: "Quel organe du système immunitaire filtre le sang et détruit les vieux globules rouges ?", choices: ["Le foie", "La rate", "Le pancréas", "La vessie"], correct: 1 },
  { q: "Quelle est la fonction principale des poumons ?", choices: ["Digérer", "Respirer", "Filtrer l'urine", "Produire du sang"], correct: 1 },
  { q: "Comment appelle-t-on l'intolérance sévère au gluten d'origine auto-immune ?", choices: ["Intolérance au lactose", "Maladie cœliaque", "Allergie aux arachides", "Allergie au pollen"], correct: 1 },
  { q: "Quel organe produit la bile ?", choices: ["Le foie", "L'estomac", "Les reins", "Le cœur"], correct: 0 },
  { q: "Quelle vitamine est un puissant antioxydant présent dans les huiles végétales ?", choices: ["Vitamine E", "Vitamine K", "Vitamine B1", "Vitamine C"], correct: 0 },
  { q: "Comment appelle-t-on le rythme biologique interne sur 24 heures ?", choices: ["Le rythme circadien", "Le rythme cardiaque", "Le métabolisme", "La respiration"], correct: 0 },
  { q: "Quel geste aide une personne en arrêt cardiaque en attendant les secours ?", choices: ["La lui donner à boire", "Le massage cardiaque", "La position assise", "Le repos"], correct: 1 },
  { q: "Quel appareil délivre un choc électrique pour relancer le cœur ?", choices: ["Le stéthoscope", "Le défibrillateur", "Le tensiomètre", "L'électrocardiographe"], correct: 1 },
  { q: "La carence en quelle vitamine provoque la maladie du béribéri ?", choices: ["Vitamine B1 (thiamine)", "Vitamine C", "Vitamine D", "Vitamine A"], correct: 0 },
  { q: "Quel organe est le principal siège de la digestion des aliments après l'estomac ?", choices: ["Le côlon", "L'intestin grêle", "Le foie", "L'œsophage"], correct: 1 },
  { q: "Quelle est la principale fonction des globules blancs ?", choices: ["Transporter l'oxygène", "Défendre contre les infections", "Coaguler le sang", "Digérer les graisses"], correct: 1 },
  { q: "Quel type de gras est généralement considéré comme bénéfique pour le cœur ?", choices: ["Les graisses trans", "Les graisses saturées", "Les graisses insaturées", "Le cholestérol"], correct: 2 },
  { q: "Comment appelle-t-on la perte partielle ou totale de l'audition ?", choices: ["La cécité", "La surdité", "L'aphasie", "L'amnésie"], correct: 1 },
  { q: "Quelle structure du cerveau régule la température corporelle et de nombreuses hormones ?", choices: ["Le cervelet", "L'hypothalamus", "Le bulbe", "Le cortex visuel"], correct: 1 },
  { q: "Quel moyen médical a permis d'éradiquer la variole ?", choices: ["La vaccination", "Les antibiotiques", "La vitamine C", "L'homéopathie"], correct: 0 },
  { q: "Quel médecin britannique a introduit la vaccination contre la variole au 18e siècle ?", choices: ["Louis Pasteur", "Edward Jenner", "Alexander Fleming", "Robert Koch"], correct: 1 },
  { q: "Qui a découvert la pénicilline en 1928 ?", choices: ["Louis Pasteur", "Alexander Fleming", "Marie Curie", "Robert Koch"], correct: 1 },
  { q: "Quel scientifique français a mis au point le vaccin contre la rage ?", choices: ["Louis Pasteur", "Claude Bernard", "René Laennec", "Ambroise Paré"], correct: 0 },
  { q: "Quel aliment fermenté contient naturellement des probiotiques ?", choices: ["Le pain blanc", "Le yaourt", "Le sucre", "L'huile"], correct: 1 },
  { q: "Quelles structures de la langue et du nez perçoivent les saveurs et les arômes ?", choices: ["Les papilles et récepteurs olfactifs", "Les cordes vocales", "Les amygdales", "La luette"], correct: 0 },
  { q: "Quel est l'effet principal de la caféine sur l'organisme ?", choices: ["Elle endort", "Elle stimule la vigilance", "Elle hydrate", "Elle nourrit"], correct: 1 },
  { q: "Comment appelle-t-on l'arrêt momentané de la respiration pendant le sommeil ?", choices: ["L'insomnie", "L'apnée du sommeil", "La narcolepsie", "Le bruxisme"], correct: 1 },
  { q: "Quel organe produit les hormones thyroïdiennes ?", choices: ["Le pancréas", "La thyroïde", "Les surrénales", "L'hypophyse"], correct: 1 },
  { q: "Quelle mesure d'hygiène réduit le risque de caries dentaires ?", choices: ["Manger sucré le soir", "Se brosser les dents régulièrement", "Boire des sodas", "Grignoter souvent"], correct: 1 },
  { q: "Quel nutriment est indispensable au transport de l'oxygène dans l'hémoglobine ?", choices: ["Le fer", "Le magnésium", "Le sodium", "Le phosphore"], correct: 0 },
  { q: "Quelle affection cutanée courante est liée à un excès de sébum chez l'adolescent ?", choices: ["L'eczéma", "L'acné", "Le psoriasis", "L'urticaire"], correct: 1 },
  { q: "Quel est le rôle des plaquettes sanguines ?", choices: ["Transporter l'oxygène", "Aider à la coagulation", "Combattre les virus", "Produire des hormones"], correct: 1 },
  { q: "Quelle vitamine du groupe B est cruciale avant et pendant la grossesse ?", choices: ["Vitamine B9 (folate)", "Vitamine C", "Vitamine E", "Vitamine K"], correct: 0 },
  { q: "Quel type d'exercice est le meilleur pour la santé cardiovasculaire ?", choices: ["L'exercice d'endurance", "L'immobilité", "Le sommeil", "La lecture"], correct: 0 },
  { q: "Comment appelle-t-on une élévation anormale de la température corporelle ?", choices: ["L'hypothermie", "La fièvre", "L'anémie", "La déshydratation"], correct: 1 },
  { q: "Quel organe contient les alvéoles où l'oxygène passe dans le sang ?", choices: ["Le cœur", "Les poumons", "Le foie", "Les reins"], correct: 1 },
  { q: "Quelle vitamine est synthétisée avec l'aide des bactéries de l'intestin ?", choices: ["Vitamine C", "Vitamine K", "Vitamine A", "Vitamine D"], correct: 1 },
  { q: "Quel excès alimentaire est le plus associé à l'hypertension artérielle ?", choices: ["Le sel", "Le sucre", "Les fibres", "Le calcium"], correct: 0 },
  { q: "Quel professionnel de santé traite les troubles du mouvement par des exercices ?", choices: ["Le pharmacien", "Le kinésithérapeute", "Le radiologue", "L'anesthésiste"], correct: 1 },
];
