/* Données « Action ou Vérité ».
   Base : action_verite_1000.json (nettoyée : suffixes de génération retirés,
   doublons éliminés, familles répétitives plafonnées à 8 variantes) + cartes originales.
   Trois niveaux EXCLUSIFS (voir src/levels.js) : soft · soiree · x18. Enrichis librement. */

export const VERITES = {
  soft: [
    "Quelle application de ton téléphone mérite d'être supprimée depuis des mois ?",
    "Montre le nombre exact de photos dans ta galerie.",
    "Quel est ton emoji le plus utilisé ? Vérifie et montre.",
    "Raconte ta pire honte en public.",
    "Quel objet gardes-tu précieusement alors qu'il ne sert absolument à rien ?",
    "Quelle série as-tu regardée en entier alors qu'elle était objectivement nulle ?",
    "Quel achat regrettes-tu le plus de ta vie ?",
    "Quelle odeur bizarre aimes-tu secrètement ?",
    "Quel est ton avis impopulaire le plus assumé ?",
    "As-tu déjà fait semblant de reconnaître quelqu'un qui te disait bonjour ? Raconte.",
    "Quel est le message le plus gênant que tu aies envoyé à la mauvaise personne ?",
    "Montre ton temps d'écran de la semaine, sans commentaire.",
    "Quelle chanson connais-tu par cœur sans jamais l'avoir voulu ?",
    "As-tu déjà pleuré au travail ou en cours ? Pourquoi ?",
    "Quel aliment refuses-tu catégoriquement de goûter ?",
    "Quelle est la chose la plus enfantine que tu fais encore régulièrement ?",
    "Quel mot es-tu incapable de prononcer correctement ?",
    "As-tu déjà triché à un examen ? Comment ?",
    "Quel est ton record de retard le plus honteux ?",
    "Quelle célébrité adorée de tous te laisse complètement froid ?",
    "As-tu déjà eu un fou rire dans un moment très grave ? Raconte.",
    "Quel âge mental as-tu réellement, honnêtement ?",
    "Quelle photo d'identité assumes-tu le moins ? Montre-la si tu l'as.",
    "As-tu déjà mangé quelque chose tombé par terre en public ?",
    "Quel bruit corporel t'échappe le plus souvent au pire moment ?",
    "Quelle habitude d'hygiène douteuse as-tu (eue) ? Sois honnête.",
    "Quel super-pouvoir totalement inutile aimerais-tu avoir ?",
    "Tu gagnes au loto ce soir : quel est ton premier achat absurde ?",
    "Quel métier serais-tu absolument incapable de faire ?",
    "Quelle matière détestais-tu le plus à l'école, et à cause de qui ?",
    "As-tu déjà bouché les toilettes chez quelqu'un ? Raconte la gestion de crise.",
    "Quel surnom donnes-tu en secret à quelqu'un que tout le monde connaît ?",
    "Quelle appli utilises-tu en cachette ?",
    "Quel programme télé est ton plaisir coupable assumé ?",
    "Raconte la dernière fois où tu t'es perdu alors que c'était impossible.",
    "As-tu déjà oublié le prénom de quelqu'un en le présentant ? Raconte.",
    "Quel plat rates-tu systématiquement alors qu'il est simple ?",
    "Quelle peur d'enfance traîne encore chez toi aujourd'hui ?",
    "Quel est le compliment le plus étrange qu'on t'ait fait ?",
    "Quelle chose fais-tu mieux que tout le monde ici, sans preuve possible ?",
    "Combien de fois par jour te regardes-tu dans un miroir, honnêtement ?",
    "Quel personnage de fiction est secrètement ton modèle de vie ?",
    "As-tu déjà parlé tout seul à voix haute en public ? De quoi ?",
    "Quel est ton record de jours sans sortir de chez toi ?",
    "Quelle tendance mode as-tu suivie et regrettes-tu amèrement ?",
    "Si on fouillait ton sac ou tes poches maintenant, quelle serait la découverte la plus étrange ?",
    "Quelle excuse bidon utilises-tu le plus pour annuler un plan ?",
    "Quel film culte n'as-tu jamais vu, sans jamais oser l'avouer ?",
    "Quelle chose interdite as-tu déjà faite dans un magasin ?",
    "As-tu déjà porté un vêtement avec l'étiquette pour le rendre ensuite ?",
    "Quel talent as-tu perdu avec le temps ?",
    "Raconte ton pire moment de gêne avec un prof ou un patron.",
    "Quelle théorie du complot te fait quand même un peu douter ?",
    "Quel jouet d'enfance as-tu toujours, ou rêverais-tu de récupérer ?",
    "Quel est le truc le plus cher que tu aies perdu ?",
    "As-tu déjà fait semblant d'être au téléphone pour éviter quelqu'un ?",
    "Quelle règle de tes parents enfreignais-tu systématiquement ?",
    "Quel bruit ou tic des autres te rend absolument fou ?",
    "Quelle est ta plus grande fierté totalement dérisoire ?",
    "Si tu devais changer de prénom, lequel choisirais-tu ?",
    "Quel animal te correspond le mieux selon toi ? La table valide ou corrige.",
    "Quelle chanson passerait à ton enterrement si tu devais choisir ce soir ?",
    "As-tu déjà re-offert un cadeau reçu ? À qui ?",
    "Quel mensonge de tes parents as-tu cru bien trop longtemps ?",
    "Quelle victoire à un jeu de société t'a rendu insupportable ?",
    "Raconte ta pire expérience chez le coiffeur, le dentiste ou le médecin.",
    "Quel est ton record d'heures de sommeil d'affilée ?",
    "Quelle appli de ton téléphone révélerait le plus de choses gênantes sur toi ?",
    "As-tu déjà écouté une conversation qui ne te concernait pas ? Qu'as-tu appris ?",
    "Quel est le pire pseudo internet que tu aies eu ?",
    "Quelle photo de toi enfant tes parents adorent-ils montrer pour te faire honte ?",
    "Quelle chose as-tu apprise incroyablement tard dans ta vie ?",
    "Quel achat fais-tu toujours en cachette ?",
    "Quel est ton record de messages ou mails non lus ? Montre.",
    "Quelle habitude alimentaire bizarre assumes-tu totalement ?",
    "As-tu déjà chanté ou dansé en pensant être seul… et quelqu'un t'a vu ?",
    "Quelle invitation as-tu acceptée en priant pour qu'elle soit annulée ?",
    "Quel truc de « vieux » fais-tu déjà ?",
    "Quelle est la pire chose que tu aies dite à voix haute en pensant chuchoter ?",
    "Quelle compétence tout le monde possède-t-il sauf toi ?",
    "As-tu déjà pleuré devant une publicité ? Laquelle ?",
    "Quelle promesse de nouvel an n'as-tu jamais tenue plus de trois jours ?",
    "Qui de la table survivrait le mieux à une apocalypse zombie, et pourquoi pas toi ?",
    "Quelle question détestes-tu qu'on te pose en famille ?",
    "Raconte une fois où tu as totalement fait semblant de comprendre une conversation.",
    "Quelle est la chose la plus étrange que tu aies déjà mangée par curiosité ?",
    "Quel bruit bizarre fait ton corps que tu ne peux pas contrôler ?",
    "Quelle application as-tu téléchargée puis oubliée immédiatement ?",
    "Quel est le pire compliment que tu aies reçu, genre vraiment raté ?",
    "Quelle chanson te met immédiatement de bonne humeur, sans exception ?",
    "As-tu déjà fait semblant d'aimer un cadeau ? Pour qui ?",
    "Quel est ton pire souvenir de piscine publique ?",
    "Quelle règle absurde respectais-tu enfant sans jamais la remettre en question ?",
    "Quel est le mensonge le plus long que tu aies entretenu ?",
    "As-tu un rituel bizarre avant de dormir ? Lequel ?",
    "Quelle est la pire chose que tu aies dite en pensant chuchoter ?",
    "Quel est ton plus grand regret culinaire de la semaine ?",
    "As-tu déjà pleuré pour un animal qui n'était pas le tien ?",
    "Quelle est la chose la plus chère que tu aies achetée sur un coup de tête ?",
    "Quel super-héros ferais-tu vraiment mal, selon toi ?",
    "Quel mensonge racontes-tu encore aujourd'hui pour éviter une conversation ?",
    "Montre la photo la plus gênante de ta galerie et raconte son histoire.",
    "Quelle habitude bizarre as-tu uniquement quand tu es seul·e chez toi ?",
    "Quel message n'as-tu jamais osé envoyer, et à qui ?",
    "Quelle est la chose la plus chère que tu aies cassée sans jamais l'avouer ?",
    "Quel talent parfaitement inutile maîtrises-tu ? Démonstration obligatoire.",
    "Quelle recherche Internet récente aurais-tu honte de montrer à la table ?",
    "Quel surnom ridicule t'a-t-on donné dans ta famille ?",
    "Si ta vie était une téléréalité, quel serait son titre ?",
    "Quelle célébrité es-tu secrètement convaincu·e de pouvoir séduire ?",
    "Quel plat adores-tu alors que tout le monde le trouve dégoûtant ?",
    "Quel est le tout dernier mensonge que tu as dit — et à qui ?",
  ],
  soiree: [
    "Qui de la table draguerais-tu si tu étais célibataire, et pourquoi cette personne ?",
    "Décris ton type précis ; la table dit qui y correspond le plus ici.",
    "Ton pire râteau : raconte tout.",
    "Le pire message de drague que tu aies reçu ? Montre-le si possible.",
    "Et le pire message de drague que TU aies envoyé ?",
    "As-tu déjà ghosté quelqu'un qui ne le méritait pas ? Il attend peut-être encore.",
    "As-tu déjà été ghosté ? Combien de temps as-tu espéré ?",
    "Combien de fois es-tu vraiment tombé amoureux ?",
    "Qu'est-ce qui te fait craquer instantanément chez quelqu'un ?",
    "Qu'est-ce qui te refroidit instantanément, même chez quelqu'un de canon ?",
    "As-tu déjà embrassé quelqu'un pour rendre jaloux quelqu'un d'autre ?",
    "Ta technique de drague la plus honteuse qui a réellement fonctionné ?",
    "As-tu déjà menti sur ton âge ou ton métier pour séduire ?",
    "Le rendez-vous le plus catastrophique que TU as fait vivre à quelqu'un ?",
    "Quel ex défendais-tu bec et ongles à l'époque ? Qu'est-ce que tu refusais de voir ?",
    "Quelle chanson te ramène immédiatement à un ex ?",
    "As-tu déjà eu un crush sur un prof, un patron ou un collègue ? Développe.",
    "Le plus grand écart d'âge avec quelqu'un que tu as fréquenté ?",
    "As-tu déjà été le plan B de quelqu'un en le sachant parfaitement ?",
    "As-tu déjà eu deux crushs en même temps ? Comment ça s'est terminé ?",
    "Ton pire vocal envoyé en état d'ébriété : à qui, et que disait-il ?",
    "Quelle est la pire chose que tu aies faite en soirée et jamais avouée à personne ici ?",
    "T'es-tu déjà endormi en pleine soirée ? Où t'es-tu réveillé ?",
    "Ton record de verres en une soirée, et comment ça s'est terminé ?",
    "As-tu déjà vomi dans un endroit vraiment problématique ? Raconte.",
    "Qui ici ferait le pire témoin de mariage, et pourquoi ?",
    "Tu donnes un cours de séduction à quelqu'un de la table : à qui, et quel est le chapitre 1 ?",
    "Quel membre de la table connaît ton plus gros secret ? Sans dire le secret.",
    "Quelle rumeur a circulé sur toi, vraie ou fausse ?",
    "As-tu déjà lu par-dessus une épaule un message qui t'a appris quelque chose ?",
    "Ton crush actuel sait-il qu'il est ton crush ?",
    "Quelle est la plus grosse folie que tu aies faite par amour ?",
    "As-tu déjà accepté un rencard juste pour le restaurant ?",
    "Ta pire anecdote d'appli de rencontre ?",
    "Décris ton rencard idéal ; la table juge si c'est crédible.",
    "As-tu déjà supprimé une photo parce qu'elle ne faisait pas assez de likes ?",
    "As-tu déjà flirté pour obtenir quelque chose ? Quoi exactement ?",
    "Ton pire réveil après une soirée : où, comment, avec qui ?",
    "As-tu déjà embrassé deux personnes différentes dans la même soirée ?",
    "As-tu déjà regretté d'avoir présenté deux personnes l'une à l'autre ?",
    "De 1 à 10, à quel point es-tu jaloux ? Exemple vécu à l'appui.",
    "Quelle est la chose la plus mesquine que tu aies faite à un ex ?",
    "Et la plus mesquine qu'un ex t'ait faite ?",
    "As-tu déjà stalké quelqu'un au point de connaître son emploi du temps ?",
    "Quel mensonge as-tu dit ce mois-ci à quelqu'un de présent dans cette pièce ?",
    "Qui appellerais-tu à 4h du matin pour enterrer un corps, métaphoriquement ?",
    "Le pire surnom amoureux qu'on t'ait donné ?",
    "Cite les trois premiers critères de ta liste rédhibitoire.",
    "Combien de temps après une rupture peut-on sortir avec l'ami d'un ex ? Assume ta réponse.",
    "As-tu déjà fait semblant d'adorer un cadeau de ton partenaire ? Lequel ?",
    "Quelle habitude d'un ex as-tu gardée sans t'en rendre compte ?",
    "Ta pire rencontre avec des beaux-parents ?",
    "As-tu déjà dit « je t'aime » sans le penser ?",
    "10 000 € pour ne plus jamais reparler à ton crush : tu signes ?",
    "Qui ici a le rire le plus séduisant ? Et le plus terrifiant ?",
    "Ton profil de rencontre en trois mots honnêtes, ce serait quoi ?",
    "Quel message as-tu supprimé en priant qu'il n'ait pas été lu ? Que disait-il ?",
    "Quelle personne de ton passé voudrais-tu recroiser une seule soirée ?",
    "Quelle urgence as-tu inventée pour fuir un rencard ennuyeux ?",
    "Quelle petite infraction as-tu déjà commise en soirée ?",
    "L'astrologie en drague : argument valable ou signal d'alarme ? Défends-toi.",
    "La personne la plus connue que tu aies approchée ou draguée ?",
    "As-tu déjà pris un râteau devant témoins ? Qui a ri le plus fort ?",
    "Quelle est ta pire photo de soirée encore en ligne quelque part ?",
    "De 1 à 10, à quel point ton historique de likes est-il compromettant ?",
    "Qui de la table survivrait le moins longtemps au célibat ?",
    "Ton ex te recontacte ce soir « pour parler » : tu réponds quoi, honnêtement ?",
    "As-tu déjà utilisé une réplique de film pour draguer ? Laquelle ?",
    "La limite entre « attentionné » et « lourd » : donne un exemple vécu.",
    "As-tu déjà friendzoné quelqu'un tout en profitant de ses attentions ?",
    "Quel bad boy ou quelle bad girl t'a fait perdre tout bon sens ?",
    "Témoin d'une infidélité : tu as fait quoi, et tu referais pareil ?",
    "Tricher en pensée, c'est déjà tricher ? Tranche et assume.",
    "As-tu déjà eu honte de présenter quelqu'un à tes amis ? Pourquoi ?",
    "Quelle qualité surestimée tout le monde cherche-t-il en amour ?",
    "Ton plus long crush non réciproque : combien de temps ?",
    "As-tu déjà dragué le serveur ou la serveuse devant tes amis ?",
    "À quel signe précis sais-tu que tu es en train de craquer pour quelqu'un ?",
    "À quel moment précis as-tu su que ton ex était une erreur ?",
    "Qu'est-ce qu'on trouverait de plus surprenant dans tes conversations archivées ?",
    "Le lendemain de ta pire soirée : qu'as-tu dû réparer ou te faire pardonner ?",
    "As-tu déjà pleuré pour quelqu'un qui n'en valait objectivement pas la peine ?",
    "La chose la plus romantique que tu aies faite — et la plus romantique reçue ?",
    "Un crush de vacances t'attend encore quelque part : où, et depuis quand ?",
    "Que penserait ton ex en te voyant ce soir ?",
    "Qui ici mentirait le mieux face à un détecteur de mensonges ?",
    "As-tu déjà commencé une soirée en détestant quelqu'un et fini très proche de lui ?",
    "Quel red flag es-TU pour les autres ? Sois honnête.",
    "On ouvre les « souvenirs d'il y a 5 ans » de ton téléphone : on y trouve quoi ?",
    "As-tu déjà fait croire à quelqu'un que tu l'aimais bien plus que la réalité ?",
    "Quelle est la pire chose que tu aies dite à un ex sous le coup de la colère ?",
    "As-tu déjà accepté un date uniquement parce que tu étais seul un vendredi soir ?",
    "Quel est ton pire souvenir de soirée où tu as trop parlé de ton ex ?",
    "As-tu déjà simulé un coup de foudre pour rendre service à un ami ?",
    "Quelle est la chose la plus embarrassante que quelqu'un t'ait vu faire en soirée ?",
    "As-tu déjà changé de tenue en pleine soirée pour plaire à quelqu'un d'arrivé plus tard ?",
    "Quel est ton pire souvenir lié à un slow ?",
    "As-tu déjà inventé un mensonge élaboré pour éviter de croiser un ex en soirée ?",
    "Quelle est la dernière chose stupide que tu as faite pour impressionner quelqu'un ?",
    "As-tu déjà eu le cœur brisé par quelqu'un que tu connaissais depuis moins d'une semaine ?",
    "Quel est le pire surnom que quelqu'un t'ait donné en soirée ?",
    "As-tu déjà fait un pas vers quelqu'un puis regretté immédiatement ?",
    "Quelle est la chose la plus folle que tu aies faite pour te faire pardonner après une soirée ?",
    "As-tu déjà eu un coup de foudre pour quelqu'un que tu détestais avant ?",
    "As-tu déjà regretté un baiser ? Raconte, sans donner le nom.",
    "Quelle est la pire excuse que tu aies utilisée pour annuler un rendez-vous amoureux ?",
    "As-tu déjà stalké l'ex de ton ou ta partenaire ? Jusqu'où ?",
    "Quel red flag ignores-tu volontairement quand quelqu'un te plaît ?",
    "As-tu déjà écrit à ton ex en pleine soirée ? Que disait le message ?",
    "Classe trois personnes de cette pièce par charisme. Et assume.",
    "Quelle est la chose la plus folle que tu aies faite pour attirer l'attention de quelqu'un ?",
    "As-tu déjà menti sur ton nombre d'ex ? Dans quel sens ?",
    "Quel crush totalement improbable as-tu eu, que personne ici ne soupçonne ?",
    "Quelle soirée voudrais-tu revivre — ou effacer à jamais — et pourquoi ?",
    "Si tu devais matcher deux personnes de cette pièce sur une appli de rencontre, qui — et pourquoi ?",
  ],
  x18: [
    "Douche à deux : logistique de génie ou piège inconfortable ? Argumente avec vécu.",
    "Ton record sur 24 heures ?",
    "Le câlin du réveil : pour ou contre, et pourquoi ?",
    "As-tu déjà envoyé un sexto à la mauvaise personne ? Conséquences ?",
    "Lumière allumée ou éteinte ? Défends ton camp.",
    "Quelle est la chose la plus étrange qui t'ait déjà excité ?",
    "Y a-t-il un mot ou un son qui te fait de l'effet ? Lequel ?",
    "Ton pire fou rire en plein moment intime : raconte.",
    "As-tu déjà été surpris en pleine action ? Par qui ?",
    "Sieste ou sexe : choix définitif pour un dimanche pluvieux ?",
    "Quelle partie de ton corps préfères-tu qu'on embrasse ?",
    "As-tu déjà vécu — ou refusé — un plan à trois ?",
    "Ta plus longue conversation coquine par messages a duré combien de temps ?",
    "As-tu déjà noté un partenaire dans ta tête ? Quelle note ?",
    "Le premier soir : validé, risqué ou stratégique ? Vécu à l'appui.",
    "Dans quel lieu rêves-tu de le faire sans avoir jamais osé ?",
    "As-tu déjà utilisé une appli uniquement pour un plan d'un soir ?",
    "Quelle zone sensible chez toi presque personne ne connaît ?",
    "Le pire « dirty talk » que tu aies entendu — mot pour mot si tu l'oses.",
    "As-tu déjà regretté immédiatement après ? Pourquoi ?",
    "Combien de partenaires as-tu eus ? La fourchette est acceptée.",
    "As-tu déjà fait semblant de dormir pour éviter un câlin ?",
    "Un fantasme impliquant un uniforme ? Lequel ?",
    "Qu'est-ce qu'un partenaire a fait de mieux, que tu recherches depuis ?",
    "Plutôt matin ou soir ? Réponse motivée.",
    "As-tu déjà eu une aventure au travail ou en cours ?",
    "Le compliment le plus torride qu'on t'ait fait dans l'intimité ?",
    "As-tu déjà été attiré par quelqu'un de beaucoup plus âgé ou plus jeune ?",
    "Musique pendant l'amour : playlist, silence, ou improvisation sonore ?",
    "As-tu déjà quitté quelqu'un pour une raison purement sexuelle ?",
    "Aventures sans lendemain ou relation longue : ton camp naturel ?",
    "Quel accessoire t'intrigue sans que tu l'aies encore testé ?",
    "As-tu déjà menti sur tes performances ? Dans quel sens ?",
    "Raconte la fois où le décor s'est retourné contre vous : meuble, voisins, alarme…",
    "Ta pire crampe ou blessure en pleine action ?",
    "Photos ou vidéos intimes : déjà fait ? Des regrets ?",
    "Décris ton scénario de rêve : lieu, ambiance, partenaire — sans donner de nom.",
    "Ton plus grand complexe au lit — et qui t'a aidé à le dépasser ?",
    "Qu'est-ce qui rend quelqu'un inoubliable au lit, d'après ton expérience ?",
    "Une amitié qui a basculé une seule nuit : et après ?",
    "Le sexe de réconciliation : mythe surcoté ou meilleure invention du monde ?",
    "Ta première fois : à quel âge, et que changerais-tu ?",
    "As-tu déjà compté les fois sur un mois ? Record assumé ?",
    "Quelle phrase tue instantanément l'ambiance ? Vécu obligatoire.",
    "As-tu déjà eu envie de quelqu'un au pire moment possible ? Raconte.",
    "Sous-vêtements du soir : description… ou preuve, au choix.",
    "As-tu déjà fait durer exprès trop longtemps ? Pourquoi ?",
    "Ton rythme idéal par semaine, en toute honnêteté ?",
    "As-tu déjà pleuré pendant ou après ? Explique si tu veux.",
    "Qu'as-tu découvert sur toi grâce à un partenaire ?",
    "Parler pendant : indispensable, gênant, ou selon la personne ?",
    "As-tu déjà simulé une urgence pour partir juste après ?",
    "La douche : avant, après, ou les deux ? Débat assumé.",
    "Ton pire timing de libido : raconte.",
    "As-tu déjà eu un sex friend ? Combien de temps ça a tenu ?",
    "Quelle scène de film t'a durablement marqué ?",
    "Spontané ou planifié ? Le meilleur des deux mondes existe-t-il ?",
    "Qu'est-ce que tu n'oses jamais demander ?",
    "As-tu déjà été jaloux du passé de quelqu'un ? Jusqu'où ?",
    "Ton niveau d'endurance honnête sur 10, validé par l'expérience ?",
    "As-tu déjà assumé une relation 100 % physique des deux côtés ?",
    "La position la plus surcotée selon toi ? Argumente.",
    "Et la plus sous-cotée ?",
    "As-tu déjà ri de quelque chose qu'il ne fallait surtout pas ? Quoi ?",
    "Qu'est-ce qui te met dans l'ambiance à coup sûr ?",
    "As-tu déjà envoyé une photo coquine ? Avec le visage ?",
    "Avis tranché : les préliminaires sont-ils le plat principal ?",
    "Un crush purement physique sur quelqu'un d'incompatible : raconte.",
    "La chose la plus douce qu'on t'ait dite dans l'intimité ?",
    "Pourquoi le sexe en vacances est-il toujours mieux — ou pas ?",
    "As-tu déjà tenté un jeu de rôle ? Lequel ?",
    "Qu'est-ce qui t'a le plus surpris chez un partenaire ?",
    "As-tu une règle des trois rendez-vous, ou aucune règle ?",
    "Ton niveau sonore, de bibliothèque à stade de foot ?",
    "Une panne de désir en couple : comment c'est revenu ?",
    "Quelle est la limite que tu ne franchiras jamais ?",
    "As-tu déjà dit le mauvais prénom ? Comment t'en es-tu sorti ?",
    "L'endroit le plus inconfortable testé : verdict ?",
    "Qu'est-ce qui vieillit le mieux : la passion ou la complicité ? Vécu.",
    "Une expérience à l'étranger où la barrière de la langue faisait partie du charme ?",
    "Ta pièce de lingerie ou ton boxer fétiche : description.",
    "Réveiller les voisins : déjà arrivé ? Comment le sais-tu ?",
    "As-tu déjà eu un coup de cœur pour une voix avant le physique ?",
    "Entre la rencontre et la première fois : ton record le plus court et le plus long ?",
    "Si ta vie intime était un titre de film, ce serait quoi ?",
    "Quelle est la dernière fois où tu as dû improviser un mensonge après une nuit torride ?",
    "As-tu déjà eu un fantasme concernant un lieu totalement improbable ?",
    "Quel est le compliment le plus cru que tu aies reçu au lit ?",
    "As-tu déjà fait quelque chose que tu regrettes… juste un peu ?",
    "Quelle est ta plus grande audace amoureuse récente ?",
    "As-tu un mot ou une phrase qui te met immédiatement dans l'ambiance ?",
    "Quelle est la chose la plus osée que tu aies faite pour surprendre un partenaire ?",
    "As-tu déjà eu une aventure que tu n'as jamais racontée à personne ici présent ?",
    "Quel est ton meilleur souvenir intime en extérieur ?",
    "As-tu déjà comparé deux partenaires à voix haute, ou au moins dans ta tête ?",
    "Quelle est la limite que tu ne franchirais jamais, même dans un fantasme ?",
    "As-tu déjà eu recours à un petit mensonge pour prolonger une soirée arrosée… et intime ?",
    "Quel est ton meilleur souvenir d'un message qui a mal, ou très bien, fini ?",
    "As-tu déjà eu un coup de foudre purement physique et instantané ?",
    "Quelle est la question que tu redoutes le plus dans ce genre de jeu ?",
    "Quel fantasme n'as-tu jamais réalisé — et qu'est-ce qui te retient ?",
    "As-tu déjà simulé ? Raconte la fois la plus théâtrale.",
    "Sextos : plutôt émetteur ou récepteur ? Raconte le dernier en date.",
    "Quelle est la chose la plus audacieuse que tu aies faite au lit ?",
    "Y a-t-il quelqu'un dans cette pièce avec qui tu passerais la nuit sans hésiter ?",
    "Dans quel endroit public as-tu failli te faire surprendre ?",
    "Quel est ton plus gros turn-off, celui qui coupe absolument tout ?",
    "As-tu déjà craqué pour le ou la partenaire d'un·e ami·e ? Développe.",
    "Ta plus longue période d'abstinence — et la plus courte entre deux fois ?",
    "Quelle expérience aimerais-tu tenter sans jamais avoir osé la proposer ?",
    "Quelle est la panne ou le fail le plus gênant que tu aies vécu au lit ?",
    "Quelle célébrité rejoindrait ta liste « permis de tromper » sans la moindre hésitation ?",
  ],
};

export const ACTIONS = {
  soft: [
    "Tiens un débat passionné de 30 secondes contre toi-même, en changeant de voix.",
    "Fais l'influenceur qui présente un objet banal de la pièce comme révolutionnaire.",
    "Vends la chaussure de ton voisin façon téléachat pendant 30 secondes.",
    "Récite l'alphabet à l'envers ; chaque erreur se paie d'une gorgée.",
    "Parle en gardant la langue collée au palais jusqu'à ton prochain tour.",
    "Fais 10 squats en comptant dans une langue inventée, avec conviction.",
    "Laisse ton voisin de gauche te recoiffer comme il veut ; garde la coiffure un tour.",
    "Dessine les yeux fermés le portrait de la personne en face ; elle garde le dessin.",
    "Appelle la 7e personne de tes contacts et demande-lui un conseil de cuisine urgent.",
    "Envoie « je t'expliquerai » à un membre de ta famille, sans aucune explication.",
    "Imite le rire de chaque personne de la table ; la table note sur 10.",
    "Rejoue une publicité culte à fond, produits imaginaires compris.",
    "Marche comme un crabe jusqu'à la porte et reviens comme un flamant rose.",
    "Compose un haïku sur la soirée en cours et déclame-le solennellement.",
    "Pendant un tour, réponds à tout uniquement par des questions.",
    "Adopte l'accent de ton choix jusqu'à ton prochain tour ; si tu le perds, bois.",
    "Va remplir les verres de tout le monde avec la classe d'un grand sommelier.",
    "Mime ton trajet du matin, du lit à la porte, en accéléré.",
    "Chante « Joyeux anniversaire » à la personne dont l'anniversaire est le plus lointain.",
    "Invente une minute de yoga en donnant des noms absurdes aux postures.",
    "Invente un secret ridicule et défends-le comme une confession bouleversante.",
    "Imite un serveur snob qui refuse de servir la table.",
    "Danse 20 secondes sur une musique que toi seul entends.",
    "Prononce un discours de ministre pour inaugurer… la table basse.",
    "Fais deviner un métier uniquement avec des bruits.",
    "Ta prochaine phrase doit contenir exactement douze mots ; la table recompte.",
    "Décris ton plat préféré comme un critique gastronomique insupportable.",
    "Imite la personne à ta droite en train de conduire, selon toi.",
    "Improvise une berceuse contenant le prénom de chaque joueur.",
    "Fais semblant de recevoir un appel bouleversant et joue la scène, sans dire de qui il s'agit.",
    "Chuchote pendant tout ton prochain tour, quoi qu'il arrive.",
    "Deviens l'arbitre : siffle chaque fois que quelqu'un boit, pendant un tour complet.",
    "Épelle ton prénom avec ton corps, lettre par lettre.",
    "Fais un discours d'Oscar pour ta victoire de « meilleure personne de la soirée ».",
    "Joue le touriste perdu qui ne parle pas la langue et demande ton chemin à la table.",
    "Tente un tour de magie improvisé avec les objets de la table.",
    "Raconte ta journée comme un conte de fées : « Il était une fois… ».",
    "Fais dix pompes ; toutes les trois pompes, crie un compliment à quelqu'un.",
    "Déguste ta prochaine gorgée comme si c'était le meilleur breuvage de l'histoire, commentaire à l'appui.",
    "Parle de toi à la troisième personne jusqu'à ton prochain tour.",
    "Invente et exécute une poignée de main secrète avec chaque personne de la table.",
    "Concours de grimaces contre toi-même : si personne ne rit, tu bois.",
    "Improvise un exposé de 30 secondes sur un sujet tiré au hasard par la table.",
    "Lis à voix haute une conversation WhatsApp de ton choix avec des intonations de théâtre.",
    "Imite un GPS qui recalcule sans arrêt pendant que quelqu'un te fait marcher dans la pièce.",
    "Souffle une bougie imaginaire placée à l'autre bout de la pièce, avec tout l'effort nécessaire.",
    "Applaudis chaque phrase prononcée à la table pendant deux minutes.",
    "Essaie de lécher ton coude avec une conviction absolue pendant 15 secondes.",
    "Mannequin challenge : fige-toi 30 secondes pendant que la table continue de vivre.",
    "Invente une langue et tiens une conversation d'une minute avec ton voisin, qui doit répondre pareil.",
    "Note la prochaine prise de parole comme un juré de télé-crochet, panneau imaginaire compris.",
    "Réalise l'« unboxing » théâtral du premier objet qu'on te tend.",
    "Imite successivement un politicien, un coach sportif et un vendeur de marché ; la table devine.",
    "Prends la pose la plus héroïque possible et tiens-la pendant qu'on te photographie.",
    "Fais ta demande en mariage la plus émouvante… à ton verre.",
    "Décris la pièce comme un agent immobilier qui veut absolument conclure.",
    "Danse le slow le plus dramatique du monde avec un balai ou un coussin.",
    "Parle comme un pirate jusqu'à ton prochain tour, moussaillon.",
    "Battle de regard avec ton reflet en mode selfie, 20 secondes sans rire.",
    "Commente ce que fait la personne en face comme un documentaire animalier, 30 secondes.",
    "Éternue de la façon la plus élégante possible, puis la plus catastrophique.",
    "Compose le refrain de l'hymne officiel de cette soirée ; tout le monde doit le reprendre.",
    "Compte jusqu'à 10 dans trois langues différentes ; les langues inventées sont acceptées mais assumées.",
    "Fais tenir le plus d'objets possible sur ta tête pendant 20 secondes.",
    "Joue une scène de film d'horreur où le monstre est… une chaussette.",
    "Trace un cercle parfait à main levée ; la table juge, échec = gorgée.",
    "Fais la statue : la table te place dans la pose de son choix, tiens 30 secondes.",
    "Présente ton voisin de droite comme un candidat de télé-réalité, punchline obligatoire.",
    "Réponds « oui chef ! » à tout ce qu'on te dit jusqu'à ton prochain tour.",
    "Mime la montée de 10 étages en ascenseur, musique d'ascenseur chantée comprise.",
    "Fais un tuto beauté imaginaire face caméra en 30 secondes.",
    "Tiens ton verre comme la royauté et parle comme elle pendant un tour.",
    "Improvise un slam sur le thème « la soif ».",
    "Réagis de façon exagérément bouleversée à la prochaine chose qu'on te dira.",
    "Le sol est de la lave : va toucher le mur le plus éloigné sans le toucher.",
    "Récite la fiche Wikipédia imaginaire d'un joueur de la table, de mémoire.",
    "Chante tes phrases au lieu de les dire jusqu'à ton prochain tour, opéra ou rap au choix.",
    "Pierre-feuille-ciseaux en cinq manches avec la personne de ton choix ; le perdant boit.",
    "Laisse la personne à ta gauche programmer une alarme surprise sur ton téléphone pour cette nuit.",
    "Ouvre un paquet ou épluche un fruit sans utiliser les pouces.",
    "Fais ton autoportrait en trois défauts et une seule qualité.",
    "Organise une minute de silence solennelle « pour les verres tombés au combat ».",
    "Tente une roulade ou un équilibre (en sécurité) ; refus = deux gorgées.",
    "Double la voix de la personne en face : elle articule en silence, tu parles pour elle, 30 secondes.",
    "Lève-toi de ta chaise en ralenti de film d'action, explosion imaginaire dans le dos.",
    "Invente une superstition et convaincs la table de la respecter pendant une heure.",
    "Fais un high-five à distance avec chaque joueur, bruitages compris.",
    "Raconte une blague ; si personne ne rit, bois deux gorgées.",
    "Deviens le majordome de la table pendant un tour ; on t'appelle d'une clochette imaginaire.",
    "La personne désignée par une bouteille qui tourne choisit ton fond d'écran pour la semaine.",
    "Chante le générique d'une série culte a cappella jusqu'à ce que quelqu'un trouve.",
    "Prends un selfie de groupe le plus raté possible ; il doit rester dans ta galerie.",
    "Récite une recette de cuisine comme un poème d'amour tragique.",
    "Imite un présentateur météo annonçant une invasion de licornes.",
    "Fais deviner ton dessert préféré uniquement avec des bruits de bouche.",
    "Raconte les 30 dernières secondes comme un commentateur de course hippique.",
    "Mime un réveil qui n'arrive pas à sonner malgré tous ses efforts.",
    "Fais un discours de 20 secondes pour te présenter à la mairie du village.",
    "Imite quelqu'un qui essaie d'ouvrir une porte qui pousse alors qu'il tire.",
    "Chante les règles du jeu sur l'air d'un hymne national.",
    "Fais deviner un objet de la maison en le décrivant comme un critique d'art.",
    "Mime une plante qui pousse en accéléré, du germe à la fleur.",
    "Improvise 15 secondes de commentaire sportif sur le fait de boire un verre.",
    "Fais semblant de recevoir une médaille pour « la personne la plus calme de la table ».",
    "Raconte ta liste de courses comme si c'était un poème dramatique.",
    "Imite un robot qui tombe en panne au milieu d'une phrase.",
    "Fais un générique de fin façon cérémonie des Oscars pour cette soirée.",
    "Mime la préparation d'un plat gastronomique avec des ingrédients imaginaires ridicules.",
    "Pendant 2 minutes, commente tout ce qui se passe autour de toi comme un commentateur sportif.",
    "Invente un slogan publicitaire pour la personne en face de toi et déclame-le fièrement.",
    "Jusqu'à ton prochain tour, termine chaque phrase par « …et c'est pour ça qu'on m'adore ».",
    "Fais deviner un film uniquement en mimant ses trois scènes clés.",
    "Échange de place avec la personne en face et imite sa façon de s'asseoir et de parler.",
    "Raconte le dernier film que tu as vu comme s'il s'agissait d'un scandale d'État.",
    "Fais le tour de la pièce en marchant comme sur un podium de haute couture.",
    "Improvise un rap de quatre phrases sur la personne à ta gauche.",
    "Laisse la table choisir un mot que tu devras placer discrètement trois fois avant ton prochain tour.",
    "Bois ta prochaine gorgée en portant un toast solennel à un objet de la pièce.",
    "Imite chaque personne de la table à tour de rôle jusqu'à ce que quelqu'un se reconnaisse.",
  ],
  soiree: [
    "Trinque les yeux dans les yeux avec chaque personne, sans jamais rompre le regard.",
    "Fais un compliment sincère et précis à chaque personne de la table.",
    "Rejoue ton pire rencard en jouant les deux rôles.",
    "Lis ta bio de rencontre à la table — ou écris-la en direct si tu n'en as pas.",
    "Recrée la photo de profil de la personne en face ; elle pose pour comparer.",
    "Chaque joueur regarde UNE photo au hasard de ta galerie… ou bois trois gorgées.",
    "Appelle un ami et demande très sérieusement comment enlever une tache de vin sur un chat.",
    "Envoie un vocal de compliments exagérés à la dernière personne qui t'a écrit.",
    "Slow avec la personne désignée par la table… sur une musique de film d'horreur.",
    "Susurre « tu me rends fou » à ton voisin, le plus crédible possible.",
    "Déclare ta flamme façon comédie romantique sous la pluie ; quelqu'un mime la pluie.",
    "Genoux contre genoux avec la personne de ton choix : soutenez-vous du regard 30 secondes.",
    "Refais le brief de sécurité d'un avion… version boîte de nuit.",
    "Improvise le discours de témoin pour le mariage imaginaire de deux personnes de la table.",
    "Décris ton crush idéal en portrait chinois ; la table devine si ça correspond à quelqu'un ici.",
    "Shooting photo de 30 secondes : tu es le photographe de mode insupportable, choisis ton modèle.",
    "Apprends une chorégraphie de 10 secondes à la table ; les ratés boivent.",
    "Choisis quelqu'un : conversation entière en vouvoiement aristocratique.",
    "Mime ton pire réveil de lendemain de soirée.",
    "Rejoue la scène de la proue du Titanic avec la personne de ton choix.",
    "Bras de fer avec la personne de ton choix ; le perdant boit.",
    "Regarde ton voisin droit dans les yeux et dis « je sais ce que tu as fait » sans rire.",
    "Envoie « j'ai un truc à te dire depuis longtemps » au contact choisi par la table… ou trois gorgées.",
    "Danse comme si tu étais seul en boîte à 3h du matin, 20 secondes.",
    "Imite la façon de danser de chaque personne de la table.",
    "Dispute violente et absurde avec la personne de ton choix : le sujet est « le houmous ».",
    "Susurre le menu de ton dernier repas comme un poème sulfureux.",
    "Porte un toast « sans rancune » à ton ex, discours de 20 secondes.",
    "Serre la main de chaque personne avec un style différent : mafieux, politicien, coach…",
    "Chute de confiance dans les bras de la personne de ton choix.",
    "Lis les lignes de la main de ton voisin et invente son avenir amoureux avec aplomb.",
    "Rejoue votre première rencontre avec la personne que tu connais depuis le plus longtemps ici.",
    "Prononce l'éloge funèbre humoristique du célibat de quelqu'un ici.",
    "Anime un « rencard express » de 30 secondes entre deux personnes de la table.",
    "Chante une chanson d'amour en remplaçant le prénom par celui de quelqu'un ici.",
    "La table choisit ta photo la moins flatteuse : fond d'écran jusqu'à demain.",
    "Enregistre un vocal de drague destiné à un numéro imaginaire ; la table écoute.",
    "Fais le storytime exagéré de ta soirée jusqu'ici, façon influenceur.",
    "Imite la façon de draguer de chaque personne de la table, selon toi.",
    "Sommelier : fais déguster sa propre boisson à ton voisin avec un discours pompeux.",
    "Attribue un surnom de célébrité à chaque personne de la table.",
    "Traverse la pièce sur un tapis rouge imaginaire pendant que la table crie ton nom.",
    "Fais ta demande solennelle de colocation à la personne de ton choix, avec arguments.",
    "La table choisit un mot interdit pour toi ; chaque oubli se paie d'une gorgée.",
    "Décris votre lune de miel imaginaire à la personne à ta gauche, en 20 secondes.",
    "Les yeux fermés, reconnais ton voisin parmi trois personnes… uniquement à l'odeur.",
    "Concours de regards de braise avec la personne en face ; la table départage.",
    "Rejoue au ralenti l'accolade la plus dramatique avec la personne en face.",
    "Lis la composition d'un paquet de chips avec la voix la plus sensuelle possible.",
    "Improvise une scène de jalousie à la personne de ton choix : elle a regardé quelqu'un d'autre.",
    "Fais tourner une bouteille : compliment appuyé obligatoire à la personne désignée.",
    "Debout sur une jambe, récite ton numéro à l'envers ; échec = gorgée.",
    "Duo musical : la personne de ton choix chante, tu fais les chœurs à fond.",
    "Échange ton téléphone avec un volontaire pendant 5 minutes… ou buvez tous les deux.",
    "À genoux, fais une cour à l'ancienne (poème compris) à la personne désignée par la table.",
    "Décris sans rire la personne en face comme la huitième merveille du monde.",
    "Rencontre ton voisin « pour la première fois » dans un bar imaginaire et lance la conversation.",
    "Organise l'élection de la personne la mieux habillée, discours de remise de prix compris.",
    "Appelle quelqu'un et dis-lui simplement « je pensais à toi »… ou trois gorgées.",
    "Danse dos à dos avec la personne de ton choix jusqu'à la fin du morceau.",
    "Refais la scène de Dirty Dancing ; le porté est optionnel, la conviction non.",
    "Envoie ta localisation à un contact au hasard avec « rejoins-moi »… ou deux gorgées.",
    "Complimente la personne que tu connais le moins sur un détail que personne n'a remarqué.",
    "Coup de foudre soudain pour un objet de la pièce : présente-le comme ton +1.",
    "Interview croisée : trois questions indiscrètes chacun avec la personne de ton choix.",
    "Fais voter la table sur ton meilleur profil : face, gauche ou droite ? Défilé obligatoire.",
    "Désigne un duo : compliment mutuel, les yeux dans les yeux.",
    "Raconte un souvenir commun avec quelqu'un ici comme le plus beau jour de ta vie.",
    "DJ d'office : impose une chanson maintenant, refrain a cappella si pas d'enceinte.",
    "Coiffe ou décoiffe la personne volontaire de ton choix pour lui créer « son meilleur look ».",
    "Rejoue la pire dispute de couple imaginaire avec ton verre comme partenaire.",
    "Fixe la personne de ton choix jusqu'à ce qu'elle demande pourquoi ; réponds « tu le sais très bien ».",
    "Rap de séduction de 20 secondes pour la personne désignée par la table.",
    "Choisis quelqu'un : décrivez-vous mutuellement en trois emojis, envoyés pour de vrai.",
    "Reconstitue ton pire moment de danse de mariage.",
    "Retrouvailles d'aéroport au ralenti avec la personne en face, musique intérieure comprise.",
    "Dresse le portrait-robot du partenaire idéal de ton voisin ; il valide ou corrige.",
    "Déclare ta flamme à la personne de ton choix uniquement avec des titres de chansons.",
    "Écris un vrai compliment à quelqu'un de la table… qu'il sera le seul à lire.",
    "Nomme un garde du corps pour la soirée et briefe-le très sérieusement sur les menaces.",
    "Rejoue la demande en mariage la plus ratée de l'histoire avec un volontaire.",
    "Traverse la pièce façon « retour de soirée à 6h du matin », chaussures à la main.",
    "Improvise 15 secondes de claquettes ; les chaussettes comptent.",
    "Devine la boisson préférée de chaque personne ; chaque erreur = gorgée.",
    "Pitch de 20 secondes pour vendre la personne à ta droite sur une appli de rencontre.",
    "Désigne le futur marié de l'année dans la table et improvise le discours.",
    "Chuchote ta pire blague à la personne de ton choix ; celui qui rit boit.",
    "Les yeux fermés, la table te déplace : devine devant qui tu es, au son de sa voix.",
    "Adopte le prénom de ton voisin de droite jusqu'à ton prochain tour ; ne réponds qu'à ce prénom.",
    "Fais deviner un souvenir de soirée commun uniquement par gestes.",
    "Porte un toast personnalisé à chaque joueur, sans jamais te répéter.",
    "Fais une demande en mariage exagérée à la personne assise en face de toi.",
    "Chuchote un scénario de rencontre improbable à l'oreille de ton voisin.",
    "Improvise un slow romantique avec la chaise la plus proche.",
    "Fais une déclaration façon télé-réalité à la caméra imaginaire, sujet : ton crush.",
    "Choisis quelqu'un et raconte votre « premier rendez-vous idéal » comme si c'était vrai.",
    "Envoie un compliment vocal exagéré à quelqu'un dans tes contacts.",
    "Danse un tango improvisé de 15 secondes avec la personne de ton choix.",
    "Fais deviner ton crush de lycée par des mimes uniquement.",
    "Récite un poème d'amour improvisé pour ton verre.",
    "Mets-toi à genoux et déclare ta flamme à un objet du salon.",
    "Fais un strip-tease… version manteau et écharpe uniquement.",
    "Chante « je t'aime » sur trois musiques différentes en 20 secondes.",
    "Raconte le pire râteau que tu as pris, avec effets sonores.",
    "Improvise un slam sur le thème « cœur brisé ».",
    "Choisis un partenaire de danse et fais un dos-à-dos romantique pendant 10 secondes.",
    "Slow de 30 secondes avec la personne de ton choix, regard dans les yeux obligatoire.",
    "Envoie « devine quoi ! » à un contact au hasard et lis sa réponse à voix haute.",
    "Laisse la table écrire un message de drague envoyé depuis ton téléphone… ou bois trois gorgées.",
    "Duel de regards avec la personne en face : le premier qui rit boit.",
    "Fais deviner ton crush de jeunesse uniquement par des mimes.",
    "Assieds-toi sur les genoux de la personne de ton choix jusqu'à ton prochain tour.",
    "Rejoue la scène de rupture la plus dramatique possible avec la personne à ta droite.",
    "Prononce le prénom de chaque personne de la table de la façon la plus sensuelle possible.",
    "Danse collé-serré 20 secondes avec la personne désignée par la table.",
    "Appelle un ami, annonce-lui que tu as un énorme secret à lui avouer… puis raccroche.",
    "Fais une déclaration théâtrale enflammée à la personne de la pièce que tu connais le moins.",
    "Improvise 20 secondes de stand-up sur la personne de ton choix (gentiment… ou pas).",
  ],
  x18: [
    "Masse les mains d'un volontaire avec une application déconcertante, 30 secondes.",
    "Embrasse le poignet d'un volontaire en le regardant droit dans les yeux.",
    "Raconte ton dernier rêve torride ; s'il n'existe pas, improvises-en un crédible.",
    "Montre ton meilleur « regard d'après » ; la table devine de quoi il s'agit.",
    "Apprends un pas de bachata très rapproché à un volontaire.",
    "Susurre trois mots doux inavouables à ton verre, micro imaginaire à l'appui.",
    "Enlève lentement un accessoire (montre, bijou, ceinture) en soutenant le regard de quelqu'un.",
    "Complimente la bouche de la personne de ton choix sans détourner le regard.",
    "Décris ta position préférée uniquement avec les mains, sans un mot.",
    "20 secondes de slow ultra rapproché, joue contre joue, avec un volontaire.",
    "Enregistre (sans envoyer) un message vocal torride destiné à ton crush.",
    "Trace un mot du doigt dans le dos d'un volontaire ; il doit le deviner.",
    "Baisemain interminable à chaque personne volontaire de la table.",
    "Raconte une expérience vécue en remplaçant tous les mots explicites par des noms de légumes.",
    "Fais deviner un fantasme en le dessinant ; interdiction d'écrire des mots.",
    "Duel de regards avec la personne de ton choix : le premier qui rit retire un accessoire.",
    "Fais le bruit que tu essaies de ne PAS faire dans l'intimité.",
    "Dos à dos avec un volontaire : décrivez chacun votre soirée idéale à deux.",
    "Improvise 15 secondes de dirty talk adressé à un objet du salon.",
    "La table choisit la personne à qui tu dois faire ton compliment le plus torride.",
    "Montre ta technique de baiser… sur ta propre main, avec le plus grand sérieux.",
    "Démonstration : « comment enlever un t-shirt de façon sexy » — le retirer vraiment est optionnel.",
    "Chuchote ton surnom d'oreiller à ton voisin ; il doit le répéter à voix haute.",
    "Glaçon en bouche, dépose un baiser sur la joue d'un volontaire.",
    "Rejoue une scène culte au ralenti en version sensuelle ; la table choisit le film.",
    "Danse 20 secondes assis sur ta chaise, haut du corps seulement, regard braqué sur quelqu'un.",
    "Adresse ton meilleur appel du regard à chaque personne de la table, une par une.",
    "Remonte du bout des doigts le bras d'un volontaire, du poignet à l'épaule, lentement.",
    "Simule la pire technique de baiser du monde sur le dos de ta main ; la table note.",
    "Réponds pendant tout ton prochain tour d'une voix suave et légèrement essoufflée.",
    "Fais un compliment anatomique élégant à trois personnes différentes.",
    "Retire ta ceinture ou un lacet le plus lentement possible en fixant quelqu'un.",
    "Petite cuillère 15 secondes avec un volontaire, conversation banale obligatoire.",
    "Embrasse l'épaule d'un volontaire à travers le vêtement.",
    "Décris ta tenue actuelle comme l'inventaire d'un film pour adultes.",
    "Invente une pub pour un produit pour adultes imaginaire, jingle compris.",
    "Fais admirer tes abdos, réels ou imaginaires, avec un discours de coach sportif.",
    "Fais glisser un glaçon le long de ton propre cou sans broncher.",
    "Prends la pose la plus suggestive possible sur ta chaise ; photo interdite.",
    "Choisis quelqu'un : décrivez-vous mutuellement « au réveil » avec un maximum de charme.",
    "Mordille l'épaule (vêtue) d'un volontaire… sinon cul sec.",
    "Envoie « tu me manques » à ton dernier match ou crush… ou trois gorgées.",
    "Double un dessin animé muet en version très suggestive pendant 20 secondes.",
    "Les yeux bandés, devine qui vient de te toucher la joue parmi trois volontaires.",
    "Susurre l'alphabet comme s'il était interdit aux mineurs, jusqu'à ce que quelqu'un craque.",
    "Complimente un volontaire des pieds à la tête, sans aucune vulgarité : c'est ça, le défi.",
    "10 secondes de respiration synchronisée, front contre front, avec un volontaire.",
    "Mime « la douche » comme dans un clip des années 2000.",
    "Explique ta technique de séduction ultime en la mimant intégralement.",
    "Un volontaire te fait manger une bouchée avec une lenteur exagérée.",
    "Dépose un baiser sur la nuque d'un volontaire.",
    "Improvise un poème torride de quatre vers sur la personne désignée par la table.",
    "Fixe un volontaire 60 secondes en silence total, sans sourire.",
    "Simule l'appel « reviens, c'était incroyable » à un ex imaginaire.",
    "Fais deviner un objet coquin uniquement par des mimes.",
    "Danse une lambada de 15 secondes avec un volontaire.",
    "Retire le bijou ou l'accessoire d'un volontaire d'une seule main, lentement.",
    "Énumère à voix haute ce que tu ferais « si on était seuls »… en regardant ton verre.",
    "Refais la scène de poterie de Ghost avec un volontaire et un objet de la table.",
    "Murmure une phrase dans une langue étrangère (réelle ou inventée) à l'oreille de quelqu'un, l'air grave.",
    "Ta main devient un micro : interviewe quelqu'un sur « sa nuit idéale », questions incisives.",
    "Décris un baiser parfait, étape par étape, en expert passionné.",
    "Paume contre paume avec un volontaire, 15 secondes de silence en se regardant.",
    "Casting de film romantique : la table te donne la réplique, embrasse ta main pour la scène finale.",
    "Coiffe-toi « sortie de lit » et assume le look pendant un tour complet.",
    "Enregistre ta voix de répondeur « spécial adultes » pour la table.",
    "Duel de compliments torrides en alternance avec un volontaire ; le premier à court boit.",
    "Effleure la joue d'un volontaire du revers de la main pendant que la table chante une musique dramatique.",
    "Rejoue ton « oh pardon » le plus faussement innocent après un frôlement calculé.",
    "Décris ton partenaire idéal uniquement par des textures et des odeurs.",
    "Test gourmand à l'aveugle : yeux fermés, devine ce qu'on te fait goûter.",
    "Joue à voix haute ton monologue intérieur à la fin d'un rencard parfait, devant ta porte.",
    "Craque tes doigts, roule des épaules, annonce « maintenant c'est sérieux » — et assume ton prochain gage.",
    "Susurre « approche » à la personne la plus éloignée jusqu'à ce qu'elle vienne.",
    "Décris les trois premières minutes de ta nuit idéale, minute par minute.",
    "Improvise le slow le plus gênant possible avec un volontaire, SANS jamais vous toucher.",
    "Envoie un emoji unique et ambigu au contact choisi par la table… ou deux gorgées.",
    "Joue l'avant/après : toi très sage au travail, puis toi à 2h du matin en soirée.",
    "Prends une gorgée et livre ton bruit d'appréciation le plus indécent.",
    "15 secondes de regard avec sourire en coin face à un volontaire ; le premier qui parle boit.",
    "Refais ta tête de « je fais semblant d'écouter mais je pense à autre chose de très précis ».",
    "Fais glisser ta veste d'une épaule avec un clin d'œil ; sans veste, improvise avec une écharpe.",
    "Marionnettiste : place-toi derrière un volontaire et guide ses bras pour « draguer » la table.",
    "Termine par un baiser soufflé personnalisé à chaque personne, prénom compris.",
    "Chuchote une invitation osée à l'oreille d'un·e volontaire.",
    "Mime ton meilleur souvenir intime, sans un mot, pendant 10 secondes.",
    "Retire un vêtement de ton choix en gardant le contact visuel avec la table.",
    "Fais un compliment très cru mais élégant à la personne en face.",
    "Danse un slow ultra collé avec un·e volontaire, 15 secondes minimum.",
    "Raconte ton fantasme le plus fou en le mimant discrètement.",
    "Embrasse la main d'un·e volontaire en remontant lentement jusqu'au coude.",
    "Simule un appel très embarrassant vers un ex, façon glamour.",
    "Fais deviner ta pratique préférée uniquement par des gestes suggestifs.",
    "Susurre le menu de ta soirée idéale à l'oreille de quelqu'un.",
    "Laisse un·e volontaire choisir où poser un baiser sur ta main ou ton bras.",
    "Décris à voix haute ton partenaire de rêve, physique compris, sans filtre.",
    "Fais un effeuillage lent d'un accessoire (montre, ceinture, écharpe).",
    "Mime ta réaction si ton crush te proposait « un dernier verre chez lui ».",
    "Raconte, en chuchotant, le message le plus osé que tu n'as jamais envoyé.",
    "Mordille doucement l'oreille d'un·e volontaire pendant 5 secondes.",
    "Retire un vêtement de ton choix jusqu'à la fin de la partie.",
    "Embrasse la personne volontaire de ton choix… là où elle le décide.",
    "Yeux fermés, décris à voix haute ta scène torride idéale avec ton crush.",
    "Laisse ton voisin dessiner au feutre où il veut sur ta peau (zone visible ou non, à toi de choisir).",
    "Simule un orgasme le plus crédible possible ; la table note sur 10.",
    "Assieds-toi à califourchon sur la personne volontaire de ton choix et tiens une conversation parfaitement banale pendant une minute.",
    "Strip-tease de 20 secondes : au moins un vêtement doit tomber.",
    "Susurre à l'oreille de ton voisin la chose la plus osée que tu oserais lui proposer.",
    "Fais un body shot sur la personne volontaire de ton choix.",
    "Masse lentement les cuisses d'un·e volontaire pendant 30 secondes, regard assumé.",
    "Colle-toi dos à dos contre un·e volontaire et ondulez en rythme pendant 15 secondes de musique.",
  ],
};

