/* Données « Action ou Vérité ».
   Base : action_verite_1000.json (nettoyée : suffixes de génération retirés,
   doublons éliminés, familles répétitives plafonnées à 8 variantes) + cartes originales.
   Trois niveaux EXCLUSIFS (voir src/levels.js) : soft · soiree · x18. Enrichis librement. */

export const VERITES = {
  soft: [
    "Quel est ton plus vieux souvenir d'enfance dont tu es absolument certain ?",
    "Quelle est ta plus grande phobie irrationnelle ou ridicule ?",
    "Quelle est ta plus grande manie inconsciente quand tu es stressé ?",
    "Si tu devais manger un seul aliment jusqu'à la fin de tes jours, ce serait quoi ?",
    "Raconte le pire mensonge que tu as dit à tes parents quand tu étais adolescent.",
    "Quel était ton dessin animé ou ta série préférée quand tu avais 8 ans ?",
    "Quel est le pire cadeau d'anniversaire ou de Noël que tu as reçu de ta vie ?",
    "As-tu un talent caché complètement inutile à nous montrer ou nous décrire ?",
    "Quel est le rêve le plus étrange ou absurde dont tu te souviennes encore ?",
    "Quelle chanson honteuse adores-tu écouter à fond quand tu es seul en voiture ?",
    "Quel est le film ou la scène de cinéma qui te tire une larme à chaque fois ?",
    "Qui était ton tout premier coup de foudre parmi les célébrités ou personnages de fiction ?",
    "Quelle est la chose la plus stupide que tu as faite uniquement parce que tu t'ennuyais ?",
    "Y a-t-il une superstition ridicule à laquelle tu crois secrètement ?",
    "Quel est ton pire défaut selon les membres de ta propre famille ?",
    "Quel est le vêtement le plus ringard ou improbable qui dort dans ton armoire ?",
    "Quelle est la pire note ou la pire appréciation de prof que tu as eue à l'école ?",
    "Quel animal pourtant inoffensif te dégoûte ou te terrifie le plus ?",
    "Quelle est la plus grosse bêtise que tu as commise avant tes 10 ans ?",
    "Quel métier farfelu voulais-tu faire quand tu étais très jeune ?",
    "Quel est l'endroit le plus insolite ou inconfortable où tu t'es endormi ?",
    "Quelle est ta pire expérience de cuisine ratée que tu as dû jeter ?",
    "Quelle ancienne coupe de cheveux regrettes-tu profondément aujourd'hui ?",
    "Quel est ton péché mignon ou plaisir coupable inavouable du moment ?",
    "Combien de temps es-tu déjà resté sans te doucher ou te laver par pure flemme ?",
    "Quel mensonge racontes-tu encore aujourd'hui pour éviter une conversation ?",
    "Montre la photo la plus gênante de ta galerie et raconte son histoire.",
    "Quelle habitude bizarre as-tu uniquement quand tu es seul·e chez toi ?",
    "Quel message n'as-tu jamais osé envoyer, et à qui ?",
    "Quelle est la chose la plus chère que tu aies cassée sans jamais l'avouer ?",
    "Quel talent parfaitement inutile maîtrises-tu ? Démonstration obligatoire.",
    "Quelle recherche Internet récente aurais-tu honte de montrer à la table ?",
    "Quel surnom ridicule t'a-t-on donné dans ta famille ?",
    "Si ta vie était une téléréalité, quel serait son titre ?",
    "Quelle célébrité es-tu secrètement convaincu·e de pouvoir séduire ?",
  ],
  soiree: [
    "Qui dans cette pièce trouves-tu le plus séduisant ou charismatique à première vue ?",
    "Quelle a été ta pire expérience absolue de premier rendez-vous amoureux ?",
    "As-tu déjà eu un coup d'un soir avec une connaissance commune ou quelqu'un ici ?",
    "Quel est le plus grand mensonge que tu as dit à ton partenaire actuel ou à ton ex ?",
    "Quelle est ta pire habitude ou ton plus grand défaut quand tu es un peu éméché ?",
    "As-tu déjà fouillé discrètement dans les tiroirs ou placards de quelqu'un par pure curiosité ?",
    "Quel est le secret le plus croustillant ou surprenant qu'on t'ait confié récemment ?",
    "Qui autour de cette table possède selon toi le plus grand potentiel de manipulateur ?",
    "As-tu déjà développé un crush secret sur le ou la partenaire d'un de tes amis ?",
    "Quel a été le moment de solitude le plus embarrassant que tu as vécu lors d'une fête ?",
    "As-tu déjà regretté un baiser ? Raconte, sans donner le nom.",
    "Quelle est la pire excuse que tu aies utilisée pour annuler un rendez-vous amoureux ?",
    "As-tu déjà stalké l'ex de ton ou ta partenaire ? Jusqu'où ?",
    "Quel red flag ignores-tu volontairement quand quelqu'un te plaît ?",
    "As-tu déjà écrit à ton ex en pleine soirée ? Que disait le message ?",
    "Classe trois personnes de cette pièce par charisme. Et assume.",
    "Quelle est la chose la plus folle que tu aies faite pour attirer l'attention de quelqu'un ?",
    "As-tu déjà menti sur ton nombre d'ex ? Dans quel sens ?",
    "Quel crush totalement improbable as-tu eu, que personne ici ne soupçonne ?",
    "Quelle soirée voudrais-tu revivre — ou effacer à jamais — et pourquoi ?",
  ],
  x18: [
    "Quelle est ta position sexuelle préférée et décris pourquoi elle te procure le plus de plaisir ?",
    "Où se trouve l'endroit le plus insolite, risqué ou interdit où tu as déjà fait l'amour ?",
    "Quel est ton fantasme sexuel le plus fou, inavoué ou excentrique à ce jour ?",
    "As-tu déjà eu une expérience ou une attirance intime avec une personne du même sexe ?",
    "Quelle est la phrase ou la demande la plus cochonne ou surprenante qu'on t'ait dite au lit ?",
    "Quel fantasme n'as-tu jamais réalisé — et qu'est-ce qui te retient ?",
    "As-tu déjà simulé ? Raconte la fois la plus théâtrale.",
    "Sextos : plutôt émetteur ou récepteur ? Raconte le dernier en date.",
    "Quelle est la chose la plus audacieuse que tu aies faite au lit ?",
    "Y a-t-il quelqu'un dans cette pièce avec qui tu passerais la nuit sans hésiter ?",
    "Dans quel endroit public as-tu failli te faire surprendre ?",
    "Quel est ton plus gros turn-off, celui qui coupe absolument tout ?",
    "As-tu déjà craqué pour le ou la partenaire d'un·e ami·e ? Développe.",
    "Ta plus longue période d'abstinence — et la plus courte entre deux fois ?",
    "Quelle expérience aimerais-tu tenter sans jamais avoir osé la proposer ?",
  ],
};

export const ACTIONS = {
  soft: [
    "Fais une imitation d'un dinosaure en colère en faisant le tour de la table.",
    "Mime sans un mot un chat qui a une peur bleue de l'eau.",
    "Raconte les deux prochaines minutes du jeu comme un commentateur sportif épuisé.",
    "Chante tes excuses à la pièce sur l'air d'un opéra ultra dramatique.",
    "Mime une poule qui essaie péniblement de pondre un œuf gigantesque.",
    "Parle et déplace-toi comme un robot en panne de batterie pendant un tour.",
    "Fais un bulletin météo catastrophique en simulant une tempête imaginaire.",
    "Imite un bébé qui refuse catégoriquement de manger sa purée de légumes.",
    "Prends la posture d'un professeur d'école extrêmement sévère et gronde la pièce.",
    "Mime un guerrier ninja d'élite mais d'une maladresse absolue.",
    "Fais semblant de marcher sur la lune en apesanteur tout autour de la pièce.",
    "Imite la démarche d'un pingouin qui glisse maladroitement sur une plaque de verglas.",
    "Mime un super-héros qui a perdu ses lunettes de vue en pleine mission.",
    "Fais semblant d'être un chien surexcité qui tenta d'attraper sa propre queue.",
    "Raconte une histoire courte en prenant l'attitude d'un lion devenu végétarien.",
    "Pendant 2 minutes, commente tout ce qui se passe autour de toi comme un commentateur sportif.",
    "Invente un slogan publicitaire pour la personne en face de toi et déclame-le fièrement.",
    "Jusqu'à ton prochain tour, termine chaque phrase par « …et c'est pour ça qu'on m'adore ».",
    "Fais deviner un film uniquement en mimant ses trois scènes clés.",
    "Échange de place avec la personne en face et imite sa façon de s'asseoir et de parler.",
    "Raconte le dernier film que tu as vu comme s'il s'agissait d'un scandale d'État.",
    "Fais le tour de la pièce en marchant comme sur un podium de haute couture.",
    "Improvise un rap de quatre phrases sur la personne à ta gauche.",
    "Laisse la table choisir un mot que tu devras placer discrètement trois fois avant ton prochain tour.",
    "Bois ta prochaine gorgée en portant un toast solennel à un objet de la pièce.",
  ],
  soiree: [
    "Fais une danse de séduction totalement parodique et exagérée devant la personne de ton choix.",
    "Chuchote un secret piquant ou une confession audacieuse à l'oreille de ton voisin de gauche.",
    "Fais un massage des épaules de 2 minutes à la personne assise directement en face de toi.",
    "Échange un vêtement léger (veste, montre, bague, chaussures) avec ton voisin de droite pour le reste du jeu.",
    "Regarde la personne de ton choix dans les yeux pendant 1 minute complète sans ciller ni rire.",
    "Réalise une déclaration d'amour digne d'un grand drame théâtral à un coussin ou à une chaise.",
    "Slow de 30 secondes avec la personne de ton choix, regard dans les yeux obligatoire.",
    "Envoie « devine quoi ! » à un contact au hasard et lis sa réponse à voix haute.",
    "Laisse la table écrire un message de drague envoyé depuis ton téléphone… ou bois trois gorgées.",
    "Duel de regards avec la personne en face : le premier qui rit boit.",
    "Fais deviner ton crush de jeunesse uniquement par des mimes.",
    "Assieds-toi sur les genoux de la personne de ton choix jusqu'à ton prochain tour.",
    "Rejoue la scène de rupture la plus dramatique possible avec la personne à ta droite.",
    "Prononce le prénom de chaque personne de la table de la façon la plus sensuelle possible.",
    "Danse collé-serré 20 secondes avec la personne désignée par la table.",
    "Appelle un ami, annonce-lui que tu as un énorme secret à lui avouer… puis raccroche.",
  ],
  x18: [
    "Fais un lap dance sensuel et rythmé d'une minute sur les genoux de la personne de ton choix.",
    "Embrasse langoureusement avec la langue la personne que tu trouves la plus séduisante de la pièce.",
    "Retire immédiatement trois vêtements ou accessoires visibles sur toi (hors sous-vêtements).",
    "Donne un baiser langoureux et chaud dans le cou de ton voisin ou ta voisine de droite.",
    "Laisse la personne de ton choix te bander les yeux avec un t-shirt et te caresser le cou pendant une minute.",
    "Mordille doucement l'oreille d'un·e volontaire pendant 5 secondes.",
    "Retire un vêtement de ton choix jusqu'à la fin de la partie.",
    "Embrasse la personne volontaire de ton choix… là où elle le décide.",
    "Yeux fermés, décris à voix haute ta scène torride idéale avec ton crush.",
    "Laisse ton voisin dessiner au feutre où il veut sur ta peau (zone visible ou non, à toi de choisir).",
    "Simule un orgasme le plus crédible possible ; la table note sur 10.",
    "Assieds-toi à califourchon sur la personne volontaire de ton choix et tiens une conversation parfaitement banale pendant une minute.",
    "Strip-tease de 20 secondes : au moins un vêtement doit tomber.",
    "Susurre à l'oreille de ton voisin la chose la plus osée que tu oserais lui proposer.",
    "Fais un body shot sur la personne volontaire de ton choix.",
  ],
};

