/* Missions secrètes à glisser dans la conversation sans se faire repérer.
   Banque rédigée à la main (100). Une mission = une idée. */
export const MISSIONS = [
  "Place le mot « aubergine » dans la conversation.",
  "Fais dire « c'est vrai ça » à quelqu'un.",
  "Compare quelque chose à un dauphin.",
  "Cite une ville de plus de 3 syllabes naturellement.",
  "Fais parler quelqu'un de son enfance.",
  "Utilise l'expression « à l'ancienne ».",
  "Place une réplique de film sans que ça se voie.",
  "Fais rire au moins deux personnes avec une seule phrase.",
  "Amène le sujet des extraterrestres.",
  "Complimente discrètement les chaussures de quelqu'un.",
  "Place le mot « stratégie » deux fois.",
  "Fais dire un chiffre supérieur à 100 à quelqu'un.",
  "Parle de la météo comme si c'était dramatique.",
  "Glisse le mot « fromage » sans parler de nourriture.",
  "Fais deviner que tu détestes le lundi.",
  "Termine une phrase par « … enfin bref ».",
  "Place le mot « pyramide » dans la conversation.",
  "Fais dire « ah bon ?! » à quelqu'un.",
  "Utilise trois fois le prénom de la même personne en cinq minutes.",
  "Baille discrètement jusqu'à faire bailler quelqu'un d'autre.",
  "Fais parler quelqu'un de ses vacances.",
  "Place l'expression « ça ne s'invente pas ».",
  "Glisse une rime volontaire dans une phrase banale.",
  "Amène le sujet des dinosaures.",
  "Fais dire à quelqu'un le nom d'un pays d'Amérique du Sud.",
  "Complimente la coiffure de quelqu'un sans que ce soit louche.",
  "Place le mot « hélicoptère ».",
  "Raconte un souvenir totalement inventé comme s'il était vrai.",
  "Fais deviner que tu as faim sans jamais le dire.",
  "Utilise l'expression « au jour d'aujourd'hui ».",
  "Fais répéter la même personne deux fois.",
  "Place le mot « marmotte » dans une phrase crédible.",
  "Obtiens un high-five de quelqu'un.",
  "Fais dire « moi aussi » à trois personnes différentes.",
  "Lance un débat sur un sujet totalement futile.",
  "Place l'expression « c'est un métier ».",
  "Cite deux couleurs dans la même phrase sans que ça se remarque.",
  "Amène quelqu'un à parler de son premier téléphone.",
  "Utilise le mot « bio » trois fois.",
  "Fais croire que tu connais quelqu'un de célèbre.",
  "Place le mot « igloo ».",
  "Fais dire « t'es sérieux ?! » à quelqu'un.",
  "Propose un toast sans raison particulière.",
  "Fais parler quelqu'un de son plat préféré.",
  "Place l'expression « comme dirait ma grand-mère ».",
  "Utilise un mot anglais avec un accent exagéré.",
  "Fais dire à quelqu'un un mot de plus de quatre syllabes.",
  "Amène le sujet de l'astrologie.",
  "Place le mot « catapulte » dans une phrase.",
  "Fais deviner que tu as froid sans le dire.",
  "Raconte une anecdote qui commence par « une fois, en soirée… ».",
  "Fais dire « non ?! » à quelqu'un avec un vrai étonnement.",
  "Place l'expression « en vrai » cinq fois.",
  "Complimente le prénom de quelqu'un.",
  "Fais parler quelqu'un de son travail sans poser de question directe.",
  "Place le mot « flamant rose ».",
  "Imite discrètement la posture de ton voisin pendant deux minutes.",
  "Fais dire « ça me rappelle » à quelqu'un.",
  "Amène le sujet des rêves bizarres.",
  "Utilise l'expression « petit mais costaud ».",
  "Place le mot « sous-marin » naturellement.",
  "Fais rire quelqu'un sans faire de blague (regard, mimique…).",
  "Cite un proverbe légèrement déformé sans te faire corriger.",
  "Fais parler quelqu'un d'un film qu'il a détesté.",
  "Place le mot « moustache ».",
  "Obtiens que quelqu'un te passe un objet sans le demander directement.",
  "Utilise l'expression « c'était mieux avant » avec conviction.",
  "Place le mot « trampoline » dans la conversation.",
  "Fais dire « exactement ! » à quelqu'un.",
  "Amène le sujet d'un talent caché.",
  "Fais croire que tu as déjà fait un sport extrême.",
  "Place l'expression « entre nous »… puis change de sujet.",
  "Cite trois fruits dans la même phrase.",
  "Fais deviner que tu es fatigué sans jamais le dire.",
  "Place le mot « boomerang ».",
  "Demande l'heure alors que tu as une montre ou ton téléphone en main.",
  "Fais parler quelqu'un de sa série du moment.",
  "Utilise l'expression « à la base » trois fois.",
  "Place le mot « chorizo » hors sujet nourriture.",
  "Fais dire « j'avoue » à deux personnes différentes.",
  "Raconte un fait divers inventé de façon crédible.",
  "Amène quelqu'un à te proposer à boire.",
  "Place le mot « autruche ».",
  "Termine trois phrases de suite par un mot interrogatif.",
  "Fais parler quelqu'un de ses grands-parents.",
  "Place l'expression « c'est tout un art ».",
  "Utilise le mot « vintage » pour un objet récent.",
  "Fais deviner que tu adores cette chanson sans le dire.",
  "Place le mot « périscope » dans une phrase plausible.",
  "Obtiens un compliment de quelqu'un sans le demander.",
  "Fais dire « on l'a tous fait » à quelqu'un.",
  "Amène le sujet des fantômes ou du paranormal.",
  "Place l'expression « ni vu ni connu ».",
  "Cite l'année de ta naissance sans raison apparente.",
  "Fais croire que tu comprends une langue que tu ne parles pas.",
  "Place le mot « gondole » (le bateau ou le rayon, au choix).",
  "Fais te resservir quelqu'un sans formuler de demande.",
  "Utilise l'expression « ça, c'est fait » après une banalité.",
  "Fais applaudir au moins une personne pour n'importe quelle raison.",

  // --- lot 2 ---
  "Place le mot « kangourou » dans une phrase crédible.",
  "Place le mot « tornade » sans parler de météo.",
  "Place le mot « spaghetti » hors sujet nourriture.",
  "Utilise le mot « diplomate » pour décrire quelqu'un de la table.",
  "Place le mot « origami » dans la conversation.",
  "Fais dire « c'est fou non ? » à quelqu'un.",
  "Place le mot « cactus » naturellement.",
  "Amène le sujet d'un talent que tu n'as jamais avoué avoir.",
  "Place le mot « tsunami » de façon plausible.",
  "Fais dire à quelqu'un le nom d'une capitale européenne.",
  "Utilise l'expression « c'est pas faux » deux fois.",
  "Place le mot « escalator » dans une anecdote.",
  "Fais fredonner quelqu'un sans qu'il s'en rende compte.",
  "Place le mot « koala » dans la conversation.",
  "Amène quelqu'un à vérifier son téléphone alors qu'il n'a pas vibré.",
  "Utilise l'expression « à mon époque » avec le plus grand sérieux.",
  "Place le mot « météorite » dans une phrase banale.",
  "Fais dire « c'est dingue » à trois personnes différentes.",
  "Place le mot « labyrinthe » sans parler de jeu.",
  "Raconte une anecdote sur un animal de compagnie que tu n'as jamais eu.",
  "Place le mot « silhouette » dans la conversation.",
  "Fais lever quelqu'un de sa chaise sans lui demander directement.",
  "Utilise l'expression « pour la petite histoire » avant un mensonge évident.",
  "Place le mot « tournesol » naturellement.",
  "Fais chuchoter quelqu'un sans raison apparente.",
  "Place le mot « chihuahua » dans une phrase sérieuse.",
  "Amène le sujet d'un rêve prémonitoire que tu n'as jamais eu.",
  "Utilise le mot « carambar » sans parler de bonbon.",
  "Place le mot « tiramisu » hors contexte dessert.",
  "Fais dire un chiffre entre 1 et 10 à quelqu'un, puis note-le mentalement.",
  "Place le mot « yeti » dans la conversation avec sérieux.",
  "Amène quelqu'un à te tendre la main pour un check improbable.",
  "Utilise l'expression « c'est un signe » après un événement banal.",
  "Place le mot « goudron » naturellement.",
  "Fais deviner ton animal totem sans jamais le nommer.",
  "Place le mot « harmonica » dans une phrase plausible.",
  "Raconte un souvenir de colonie de vacances totalement inventé.",
  "Place le mot « praline » hors sujet nourriture.",
  "Fais dire « exactement pareil » à quelqu'un.",
  "Amène quelqu'un à imiter un accent sans lui demander directement.",
  "Utilise l'expression « je te jure » sur un fait totalement anodin.",
  "Place le mot « tapenade » dans une conversation sérieuse.",
  "Fais dire à quelqu'un le prénom d'un membre de sa famille.",
  "Raconte une anecdote de voyage inventée avec des détails précis.",
  "Place le mot « paravent » naturellement.",
  "Fais deviner ton film préféré uniquement par élimination.",
  "Utilise l'expression « c'est mathématique » sur un sujet qui ne l'est pas.",
  "Place le mot « narval » dans une phrase crédible.",
  "Amène quelqu'un à te demander l'heure alors que tu n'as pas de montre.",
  "Fais dire « ça se tient » à quelqu'un après une théorie absurde.",
  "Place le mot « samovar » sans que personne ne remarque le mot.",
  "Raconte que tu as déjà croisé une célébrité, sans donner de nom précis.",
  "Utilise l'expression « statistiquement parlant » sur un sujet léger.",
  "Place le mot « tamanoir » dans la conversation.",
  "Fais deviner une saison uniquement par gestes.",
  "Amène quelqu'un à parler de son horoscope sans lui demander directement.",
  "Place le mot « vinaigrette » hors contexte cuisine.",
  "Fais applaudir toute la table sans donner de raison claire.",
  "Utilise l'expression « ça sent le vécu » après une anecdote de quelqu'un.",
  "Place le mot « clepsydre » dans une phrase plausible.",
  "Raconte que tu as un vague lien de parenté avec quelqu'un de célèbre.",
  "Fais dire « c'est top » à deux personnes différentes.",
  "Place le mot « ricochet » naturellement.",
  "Amène quelqu'un à sortir son téléphone pour vérifier un fait inventé.",
  "Utilise l'expression « ça ne date pas d'hier » sur un sujet récent.",
  "Place le mot « paludier » dans une conversation sérieuse.",
  "Fais deviner un pays uniquement en citant des plats typiques.",
  "Raconte une anecdote sur un exploit sportif totalement inventé.",
  "Place le mot « gargouille » dans la conversation.",
  "Fais dire « je confirme » à quelqu'un qui n'était pas concerné.",
  "Utilise l'expression « à ce stade » pour dramatiser une phrase banale.",
  "Place le mot « anachronisme » sans que ça sonne bizarre.",
  "Amène quelqu'un à te proposer son aide pour un faux problème.",
  "Fais dire un prénom de célébrité à quelqu'un sans lui demander directement.",
  "Place le mot « brouillard » sans parler de météo.",
  "Raconte que tu as failli devenir professionnel dans un sport improbable.",
  "Utilise l'expression « rien d'anormal » après un événement bizarre.",
  "Place le mot « obélisque » dans une phrase plausible.",
  "Fais deviner une profession uniquement par les objets qu'elle utilise.",
  "Amène quelqu'un à réciter un extrait de chanson sans le vouloir.",
  "Place le mot « archipel » hors contexte géographie.",
  "Raconte un souvenir d'école inventé avec un professeur au nom absurde.",
  "Fais dire « ça m'est déjà arrivé » à quelqu'un sur un sujet inventé.",
  "Utilise l'expression « pour info » avant une fausse information amusante.",
  "Place le mot « clavicule » sans parler de médecine.",
  "Fais deviner ta boisson préférée uniquement par mimes.",
  "Amène quelqu'un à te complimenter sur un vêtement que tu ne portes pas.",
  "Place le mot « embruns » dans une phrase crédible.",
  "Raconte que tu as un talent de sourcier ou de voyance, avec sérieux.",
  "Fais dire « intéressant » à quelqu'un sur un sujet volontairement plat.",
];
