/* Missions secrètes à glisser dans la conversation sans se faire repérer.
   Banque rédigée à la main (100). Une mission = une idée. */
export const MISSIONS = [
  "Place le mot « aubergine » dans la conversation.",
  "Fais dire « c'est vrai ça » à quelqu'un.",
  "Compare quelque chose à un dauphin.",
  "Cite une ville de plus de 3 syllabes naturellement.",
  "Fais parler quelqu'un de son enfance.",
  "Utilise l'expression « à l'ancienne ».",
  "Place une réplique de film sans que ça se voie.",
  "Fais rire au moins deux personnes avec une seule phrase.",
  "Amène le sujet des extraterrestres.",
  "Complimente discrètement les chaussures de quelqu'un.",
  "Place le mot « stratégie » deux fois.",
  "Fais dire un chiffre supérieur à 100 à quelqu'un.",
  "Parle de la météo comme si c'était dramatique.",
  "Glisse le mot « fromage » sans parler de nourriture.",
  "Fais deviner que tu détestes le lundi.",
  "Termine une phrase par « … enfin bref ».",
  "Place le mot « pyramide » dans la conversation.",
  "Fais dire « ah bon ?! » à quelqu'un.",
  "Utilise trois fois le prénom de la même personne en cinq minutes.",
  "Baille discrètement jusqu'à faire bailler quelqu'un d'autre.",
  "Fais parler quelqu'un de ses vacances.",
  "Place l'expression « ça ne s'invente pas ».",
  "Glisse une rime volontaire dans une phrase banale.",
  "Amène le sujet des dinosaures.",
  "Fais dire à quelqu'un le nom d'un pays d'Amérique du Sud.",
  "Complimente la coiffure de quelqu'un sans que ce soit louche.",
  "Place le mot « hélicoptère ».",
  "Raconte un souvenir totalement inventé comme s'il était vrai.",
  "Fais deviner que tu as faim sans jamais le dire.",
  "Utilise l'expression « au jour d'aujourd'hui ».",
  "Fais répéter la même personne deux fois.",
  "Place le mot « marmotte » dans une phrase crédible.",
  "Obtiens un high-five de quelqu'un.",
  "Fais dire « moi aussi » à trois personnes différentes.",
  "Lance un débat sur un sujet totalement futile.",
  "Place l'expression « c'est un métier ».",
  "Cite deux couleurs dans la même phrase sans que ça se remarque.",
  "Amène quelqu'un à parler de son premier téléphone.",
  "Utilise le mot « bio » trois fois.",
  "Fais croire que tu connais quelqu'un de célèbre.",
  "Place le mot « igloo ».",
  "Fais dire « t'es sérieux ?! » à quelqu'un.",
  "Propose un toast sans raison particulière.",
  "Fais parler quelqu'un de son plat préféré.",
  "Place l'expression « comme dirait ma grand-mère ».",
  "Utilise un mot anglais avec un accent exagéré.",
  "Fais dire à quelqu'un un mot de plus de quatre syllabes.",
  "Amène le sujet de l'astrologie.",
  "Place le mot « catapulte » dans une phrase.",
  "Fais deviner que tu as froid sans le dire.",
  "Raconte une anecdote qui commence par « une fois, en soirée… ».",
  "Fais dire « non ?! » à quelqu'un avec un vrai étonnement.",
  "Place l'expression « en vrai » cinq fois.",
  "Complimente le prénom de quelqu'un.",
  "Fais parler quelqu'un de son travail sans poser de question directe.",
  "Place le mot « flamant rose ».",
  "Imite discrètement la posture de ton voisin pendant deux minutes.",
  "Fais dire « ça me rappelle » à quelqu'un.",
  "Amène le sujet des rêves bizarres.",
  "Utilise l'expression « petit mais costaud ».",
  "Place le mot « sous-marin » naturellement.",
  "Fais rire quelqu'un sans faire de blague (regard, mimique…).",
  "Cite un proverbe légèrement déformé sans te faire corriger.",
  "Fais parler quelqu'un d'un film qu'il a détesté.",
  "Place le mot « moustache ».",
  "Obtiens que quelqu'un te passe un objet sans le demander directement.",
  "Utilise l'expression « c'était mieux avant » avec conviction.",
  "Place le mot « trampoline » dans la conversation.",
  "Fais dire « exactement ! » à quelqu'un.",
  "Amène le sujet d'un talent caché.",
  "Fais croire que tu as déjà fait un sport extrême.",
  "Place l'expression « entre nous »… puis change de sujet.",
  "Cite trois fruits dans la même phrase.",
  "Fais deviner que tu es fatigué sans jamais le dire.",
  "Place le mot « boomerang ».",
  "Demande l'heure alors que tu as une montre ou ton téléphone en main.",
  "Fais parler quelqu'un de sa série du moment.",
  "Utilise l'expression « à la base » trois fois.",
  "Place le mot « chorizo » hors sujet nourriture.",
  "Fais dire « j'avoue » à deux personnes différentes.",
  "Raconte un fait divers inventé de façon crédible.",
  "Amène quelqu'un à te proposer à boire.",
  "Place le mot « autruche ».",
  "Termine trois phrases de suite par un mot interrogatif.",
  "Fais parler quelqu'un de ses grands-parents.",
  "Place l'expression « c'est tout un art ».",
  "Utilise le mot « vintage » pour un objet récent.",
  "Fais deviner que tu adores cette chanson sans le dire.",
  "Place le mot « périscope » dans une phrase plausible.",
  "Obtiens un compliment de quelqu'un sans le demander.",
  "Fais dire « on l'a tous fait » à quelqu'un.",
  "Amène le sujet des fantômes ou du paranormal.",
  "Place l'expression « ni vu ni connu ».",
  "Cite l'année de ta naissance sans raison apparente.",
  "Fais croire que tu comprends une langue que tu ne parles pas.",
  "Place le mot « gondole » (le bateau ou le rayon, au choix).",
  "Fais te resservir quelqu'un sans formuler de demande.",
  "Utilise l'expression « ça, c'est fait » après une banalité.",
  "Fais applaudir au moins une personne pour n'importe quelle raison.",
];
