/* Affirmations « Qui est le plus susceptible de… ». Une carte = une idée.
   Banque rédigée à la main (150). Enrichis librement. */
export const AFFIRMATIONS = [
  "finir la soirée en dansant sur une table.",
  "oublier son téléphone quelque part ce soir.",
  "envoyer un message qu'il regrettera demain.",
  "tomber amoureux en vacances.",
  "devenir célèbre un jour.",
  "pleurer devant une pub.",
  "se perdre même avec un GPS.",
  "manger le dernier morceau sans demander.",
  "faire une grasse mat' jusqu'à 15h.",
  "adopter dix chats.",
  "raconter la même histoire trois fois dans la soirée.",
  "craquer et rappeler son ex.",
  "gagner à un jeu télévisé.",
  "être en retard à son propre mariage.",
  "devenir millionnaire… puis tout perdre en un an.",
  "se marier à Las Vegas sur un coup de tête.",
  "partir vivre à l'étranger sans prévenir personne.",
  "pleurer à un mariage avant même la cérémonie.",
  "oublier l'anniversaire de son meilleur ami.",
  "se disputer avec un GPS à voix haute.",
  "passer une nuit au poste pour une bêtise absurde.",
  "devenir influenceur par accident.",
  "croire à une arnaque par téléphone.",
  "envoyer un vocal de 10 minutes pour dire un truc simple.",
  "arriver en pyjama à un rendez-vous important.",
  "s'endormir au cinéma… à la séance de 14h.",
  "draguer le serveur ou la serveuse ce soir.",
  "finir la soirée à raconter sa vie à un inconnu.",
  "organiser des vacances de groupe et tout annuler.",
  "avoir un compte secret sur un réseau social.",
  "se resservir trois fois avant que tout le monde soit servi.",
  "chanter en karaoké sans connaître les paroles.",
  "tomber dans les escaliers en soirée.",
  "être le premier à pleurer devant un film triste.",
  "faire semblant de travailler toute une journée.",
  "répondre à son patron un samedi à minuit.",
  "avoir 47 alarmes le matin.",
  "poser un lapin sans s'en rendre compte.",
  "dépenser son salaire en une semaine.",
  "connaître les paroles de chansons d'il y a 20 ans par cœur.",
  "finir dans une téléréalité.",
  "acheter un truc inutile à 3h du matin.",
  "prendre la défense d'un inconnu dans la rue.",
  "faire ami-ami avec le chien plutôt qu'avec les invités.",
  "avoir déjà stalké tout le monde dans cette pièce.",
  "envoyer « je t'aime » à la mauvaise personne.",
  "devenir prof de yoga après un seul cours.",
  "se lancer dans un business douteux avec conviction.",
  "faire un discours gênant au mariage de quelqu'un ici.",
  "oublier où il a garé sa voiture.",
  "manger un plat entier à 4h du matin.",
  "se faire virer d'un musée pour avoir touché une œuvre.",
  "rire au pire moment possible.",
  "se tromper de groupe et envoyer un message compromettant.",
  "croire encore à son horoscope.",
  "négocier au marché comme si sa vie en dépendait.",
  "avoir un plan B, C et D pour tout.",
  "ne rien préparer et improviser brillamment.",
  "arriver premier à une soirée… avant les hôtes.",
  "adopter un animal sur un coup de tête.",
  "finir bénévole d'une cause dont il ignorait tout hier.",
  "pleurer de rire au point d'inquiéter les gens.",
  "s'incruster à un mariage inconnu.",
  "prendre un accent en parlant à un étranger.",
  "faire la bise à quelqu'un qui tendait la main.",
  "raconter un secret qu'on lui a confié il y a une heure.",
  "confondre les prénoms de ses propres amis.",
  "gagner un pari stupide au prix de sa dignité.",
  "faire un régime qui dure exactement un repas.",
  "s'acheter un cadeau « de la part de » quelqu'un d'autre.",
  "applaudir seul à la fin d'un film.",
  "se porter volontaire sans savoir pour quoi.",
  "dormir 14 heures et se plaindre d'être fatigué.",
  "connaître tous les potins avant tout le monde.",
  "transformer une anecdote banale en épopée.",
  "finir la soirée pieds nus.",
  "perdre son billet d'avion à l'aéroport.",
  "draguer en utilisant des jeux de mots terribles.",
  "avoir une playlist secrète très honteuse.",
  "envoyer un texto à la personne assise juste à côté.",
  "refuser de demander son chemin par fierté.",
  "commander « comme d'habitude » partout où il va.",
  "se faire adopter par la famille de quelqu'un d'autre.",
  "prendre 400 photos de son assiette avant de manger.",
  "annuler un plan pour rester avec son animal.",
  "battre tout le monde à un jeu qu'il découvre.",
  "tricher à un jeu de société familial.",
  "se vexer pour une carte Uno.",
  "faire tomber son téléphone sur son visage au lit.",
  "connaître le prénom de tous les serveurs du quartier.",
  "devenir maire de son village.",
  "se réveiller dans une autre ville après une soirée.",
  "lancer une mode sans le vouloir.",
  "être recruté par les services secrets… pour son bagout.",
  "survivre le plus longtemps à une apocalypse zombie.",
  "être éliminé en premier dans un film d'horreur.",
  "vendre du sable dans le désert.",
  "oublier son propre âge en le disant.",
  "se faire avoir deux fois par la même blague.",
  "finir sur un panneau publicitaire.",
  "écrire un livre sur sa vie.",
  "avoir une double vie très bien cachée.",
  "faire fortune avec une idée ridicule.",
  "passer à la télé pour un micro-trottoir.",
  "devenir le sosie officiel d'une célébrité.",
  "être en couple sans que personne ne le sache.",
  "célibataire, officier le mariage de tous ses amis.",
  "pleurer en vendant sa vieille voiture.",
  "garder un ticket de loterie perdant « au cas où ».",
  "parler aux plantes pour qu'elles poussent.",
  "faire une crise pour un wifi trop lent.",
  "partir en week-end et revenir avec un tatouage.",
  "prendre parti dans une dispute qui ne le concerne pas.",
  "se faire bannir d'un groupe WhatsApp.",
  "créer un groupe WhatsApp pour tout et n'importe quoi.",
  "répondre « on verra » et ne jamais voir.",
  "arriver à un barbecue avec une salade et repartir avec les restes.",
  "finir la soirée en organisant la prochaine.",
  "connaître par cœur les répliques d'un film entier.",
  "faire un road trip sans itinéraire.",
  "tomber en panne d'essence à 500 mètres d'une station.",
  "acheter des places de concert sans regarder la date.",
  "s'endormir pendant son propre anniversaire.",
  "défendre une théorie absurde jusqu'au bout de la nuit.",
  "changer de coiffure après une rupture.",
  "envoyer des messages à son animal via la caméra du salon.",
  "être fiché VIP dans un kebab.",
  "faire semblant de comprendre le vin au restaurant.",
  "réserver des vacances pendant une réunion.",
  "porter des lunettes de soleil en boîte.",
  "gagner un concours de danse improvisé.",
  "perdre ses clés en les tenant dans la main.",
  "faire un footing pour aller à la boulangerie.",
  "prendre le petit-déjeuner à 15h.",
  "connaître le menu McDo par cœur mais pas son code de carte bleue.",
  "faire une liste de courses et l'oublier chez lui.",
  "devenir la mascotte d'un bar.",
  "être le dernier au courant de son propre anniversaire surprise.",
  "quitter son travail sur un coup de tête pour ouvrir un food truck.",
  "avoir un jour une statue à son effigie.",
  "être le premier à proposer un jeu à boire.",
  "être le dernier debout ce soir.",
  "partir le premier ce soir « parce que demain je bosse ».",
  "casser quelque chose dans cette pièce avant la fin de la soirée.",
  "convaincre tout le monde de faire un after.",
  "raconter cette soirée pendant les dix prochaines années.",
];
