/* Affirmations « Qui est le plus susceptible de… ». Une carte = une idée.
   Banque rédigée à la main (150). Enrichis librement. */
export const AFFIRMATIONS = [
  "finir la soirée en dansant sur une table.",
  "oublier son téléphone quelque part ce soir.",
  "envoyer un message qu'il regrettera demain.",
  "tomber amoureux en vacances.",
  "devenir célèbre un jour.",
  "pleurer devant une pub.",
  "se perdre même avec un GPS.",
  "manger le dernier morceau sans demander.",
  "faire une grasse mat' jusqu'à 15h.",
  "adopter dix chats.",
  "raconter la même histoire trois fois dans la soirée.",
  "craquer et rappeler son ex.",
  "gagner à un jeu télévisé.",
  "être en retard à son propre mariage.",
  "devenir millionnaire… puis tout perdre en un an.",
  "se marier à Las Vegas sur un coup de tête.",
  "partir vivre à l'étranger sans prévenir personne.",
  "pleurer à un mariage avant même la cérémonie.",
  "oublier l'anniversaire de son meilleur ami.",
  "se disputer avec un GPS à voix haute.",
  "passer une nuit au poste pour une bêtise absurde.",
  "devenir influenceur par accident.",
  "croire à une arnaque par téléphone.",
  "envoyer un vocal de 10 minutes pour dire un truc simple.",
  "arriver en pyjama à un rendez-vous important.",
  "s'endormir au cinéma… à la séance de 14h.",
  "draguer le serveur ou la serveuse ce soir.",
  "finir la soirée à raconter sa vie à un inconnu.",
  "organiser des vacances de groupe et tout annuler.",
  "avoir un compte secret sur un réseau social.",
  "se resservir trois fois avant que tout le monde soit servi.",
  "chanter en karaoké sans connaître les paroles.",
  "tomber dans les escaliers en soirée.",
  "être le premier à pleurer devant un film triste.",
  "faire semblant de travailler toute une journée.",
  "répondre à son patron un samedi à minuit.",
  "avoir 47 alarmes le matin.",
  "poser un lapin sans s'en rendre compte.",
  "dépenser son salaire en une semaine.",
  "connaître les paroles de chansons d'il y a 20 ans par cœur.",
  "finir dans une téléréalité.",
  "acheter un truc inutile à 3h du matin.",
  "prendre la défense d'un inconnu dans la rue.",
  "faire ami-ami avec le chien plutôt qu'avec les invités.",
  "avoir déjà stalké tout le monde dans cette pièce.",
  "envoyer « je t'aime » à la mauvaise personne.",
  "devenir prof de yoga après un seul cours.",
  "se lancer dans un business douteux avec conviction.",
  "faire un discours gênant au mariage de quelqu'un ici.",
  "oublier où il a garé sa voiture.",
  "manger un plat entier à 4h du matin.",
  "se faire virer d'un musée pour avoir touché une œuvre.",
  "rire au pire moment possible.",
  "se tromper de groupe et envoyer un message compromettant.",
  "croire encore à son horoscope.",
  "négocier au marché comme si sa vie en dépendait.",
  "avoir un plan B, C et D pour tout.",
  "ne rien préparer et improviser brillamment.",
  "arriver premier à une soirée… avant les hôtes.",
  "adopter un animal sur un coup de tête.",
  "finir bénévole d'une cause dont il ignorait tout hier.",
  "pleurer de rire au point d'inquiéter les gens.",
  "s'incruster à un mariage inconnu.",
  "prendre un accent en parlant à un étranger.",
  "faire la bise à quelqu'un qui tendait la main.",
  "raconter un secret qu'on lui a confié il y a une heure.",
  "confondre les prénoms de ses propres amis.",
  "gagner un pari stupide au prix de sa dignité.",
  "faire un régime qui dure exactement un repas.",
  "s'acheter un cadeau « de la part de » quelqu'un d'autre.",
  "applaudir seul à la fin d'un film.",
  "se porter volontaire sans savoir pour quoi.",
  "dormir 14 heures et se plaindre d'être fatigué.",
  "connaître tous les potins avant tout le monde.",
  "transformer une anecdote banale en épopée.",
  "finir la soirée pieds nus.",
  "perdre son billet d'avion à l'aéroport.",
  "draguer en utilisant des jeux de mots terribles.",
  "avoir une playlist secrète très honteuse.",
  "envoyer un texto à la personne assise juste à côté.",
  "refuser de demander son chemin par fierté.",
  "commander « comme d'habitude » partout où il va.",
  "se faire adopter par la famille de quelqu'un d'autre.",
  "prendre 400 photos de son assiette avant de manger.",
  "annuler un plan pour rester avec son animal.",
  "battre tout le monde à un jeu qu'il découvre.",
  "tricher à un jeu de société familial.",
  "se vexer pour une carte Uno.",
  "faire tomber son téléphone sur son visage au lit.",
  "connaître le prénom de tous les serveurs du quartier.",
  "devenir maire de son village.",
  "se réveiller dans une autre ville après une soirée.",
  "lancer une mode sans le vouloir.",
  "être recruté par les services secrets… pour son bagout.",
  "survivre le plus longtemps à une apocalypse zombie.",
  "être éliminé en premier dans un film d'horreur.",
  "vendre du sable dans le désert.",
  "oublier son propre âge en le disant.",
  "se faire avoir deux fois par la même blague.",
  "finir sur un panneau publicitaire.",
  "écrire un livre sur sa vie.",
  "avoir une double vie très bien cachée.",
  "faire fortune avec une idée ridicule.",
  "passer à la télé pour un micro-trottoir.",
  "devenir le sosie officiel d'une célébrité.",
  "être en couple sans que personne ne le sache.",
  "célibataire, officier le mariage de tous ses amis.",
  "pleurer en vendant sa vieille voiture.",
  "garder un ticket de loterie perdant « au cas où ».",
  "parler aux plantes pour qu'elles poussent.",
  "faire une crise pour un wifi trop lent.",
  "partir en week-end et revenir avec un tatouage.",
  "prendre parti dans une dispute qui ne le concerne pas.",
  "se faire bannir d'un groupe WhatsApp.",
  "créer un groupe WhatsApp pour tout et n'importe quoi.",
  "répondre « on verra » et ne jamais voir.",
  "arriver à un barbecue avec une salade et repartir avec les restes.",
  "finir la soirée en organisant la prochaine.",
  "connaître par cœur les répliques d'un film entier.",
  "faire un road trip sans itinéraire.",
  "tomber en panne d'essence à 500 mètres d'une station.",
  "acheter des places de concert sans regarder la date.",
  "s'endormir pendant son propre anniversaire.",
  "défendre une théorie absurde jusqu'au bout de la nuit.",
  "changer de coiffure après une rupture.",
  "envoyer des messages à son animal via la caméra du salon.",
  "être fiché VIP dans un kebab.",
  "faire semblant de comprendre le vin au restaurant.",
  "réserver des vacances pendant une réunion.",
  "porter des lunettes de soleil en boîte.",
  "gagner un concours de danse improvisé.",
  "perdre ses clés en les tenant dans la main.",
  "faire un footing pour aller à la boulangerie.",
  "prendre le petit-déjeuner à 15h.",
  "connaître le menu McDo par cœur mais pas son code de carte bleue.",
  "faire une liste de courses et l'oublier chez lui.",
  "devenir la mascotte d'un bar.",
  "être le dernier au courant de son propre anniversaire surprise.",
  "quitter son travail sur un coup de tête pour ouvrir un food truck.",
  "avoir un jour une statue à son effigie.",
  "être le premier à proposer un jeu à boire.",
  "être le dernier debout ce soir.",
  "partir le premier ce soir « parce que demain je bosse ».",
  "casser quelque chose dans cette pièce avant la fin de la soirée.",
  "convaincre tout le monde de faire un after.",
  "raconter cette soirée pendant les dix prochaines années.",

  // --- lot 2 ---
  "devenir accro à une série qu'il détestait au départ.",
  "manger des céréales pour le dîner trois soirs de suite.",
  "envoyer un CV avec une faute dans son propre prénom.",
  "s'endormir en pleine conversation téléphonique.",
  "acheter un vélo d'appartement qui finit porte-manteau.",
  "pleurer en regardant une pub d'assurance.",
  "confondre deux prénoms toute une soirée sans s'en rendre compte.",
  "gagner un débat en citant Wikipédia comme source ultime.",
  "faire un créneau parfait devant un public nombreux.",
  "rater totalement le même créneau devant le même public.",
  "adopter l'accent du pays visité après trois jours de vacances.",
  "raconter un rêve avec plus de détails qu'un vrai souvenir.",
  "se faire des amis dans une salle d'attente.",
  "négocier le prix d'un article déjà en solde.",
  "avoir un avis tranché sur un sujet qu'il découvre à l'instant.",
  "pleurer de rire tout seul en repensant à une blague de la semaine dernière.",
  "convaincre tout le monde qu'un mensonge évident est vrai.",
  "perdre à pierre-feuille-ciseaux dix fois de suite.",
  "faire un discours de mariage improvisé et bouleversant.",
  "s'incruster dans une photo de famille qui n'est pas la sienne.",
  "connaître par cœur le générique d'une émission des années 90.",
  "prétendre avoir déjà vu un film pour éviter les spoilers ratés.",
  "se réveiller avec un tatouage dont il ne se souvient pas avoir discuté.",
  "être invité à un mariage d'un inconnu par erreur et y rester.",
  "gagner à la loterie et le claquer en une semaine.",
  "défendre un signe astrologique avec une passion suspecte.",
  "reconnaître une chanson dès la première seconde, toujours.",
  "être incapable de siffler malgré des années d'entraînement.",
  "raconter ses rêves au petit-déjeuner comme des exploits.",
  "faire du bruit en mangeant sans jamais le remarquer.",
  "avoir un plan d'évacuation pour chaque restaurant visité.",
  "réussir à dormir debout dans les transports.",
  "collectionner des objets totalement inutiles avec fierté.",
  "prendre une photo de son plat avant même que la table soit servie.",
  "réciter un poème appris à l'école il y a vingt ans, sans une faute.",
  "s'endormir avant la fin d'un film qu'il adore.",
  "changer d'avis trois fois avant de commander au restaurant.",
  "faire un tableau Excel pour organiser des vacances entre amis.",
  "convaincre un enfant que les légumes sont un super-pouvoir.",
  "réparer un objet avec du ruban adhésif « en attendant ».",
  "raconter une blague vue sur Internet comme si elle lui était arrivée.",
  "s'improviser DJ à une soirée sans qu'on le lui demande.",
  "connaître le nom de toutes les plantes… sauf les siennes, mortes.",
  "confondre un rendez-vous professionnel avec un rendez-vous amical.",
  "faire trembler la table en tapant du pied sans le savoir.",
  "être le seul à applaudir à la fin d'un spectacle moyen.",
  "avoir déjà pleuré devant un jeu télévisé.",
  "réussir à perdre ses clés alors qu'elles sont dans sa main.",
  "prendre des résolutions de nouvel an dès le 2 janvier abandonnées.",
  "raconter un souvenir d'enfance de plus en plus exagéré à chaque fois.",
  "envoyer un mail professionnel signé par erreur « bisous ».",
  "faire semblant de connaître un plat exotique au restaurant.",
  "être le premier debout à un concert assis.",
  "réussir à casser un objet juste en le regardant.",
  "convaincre la table qu'une théorie farfelue est scientifiquement prouvée.",
  "manger la dernière part sans en avoir vraiment envie, juste par principe.",
  "faire une sieste de trois heures en pensant faire vingt minutes.",
  "être fan d'un sport dont il ne connaît pas les règles.",
  "confier un secret à la mauvaise personne au pire moment.",
  "réciter une réplique de pub avec plus de conviction qu'un acteur.",
  "avoir un talent caché découvert uniquement en soirée.",
  "prétendre adorer un cadeau visiblement raté.",
  "changer de file d'attente juste avant que la sienne n'avance.",
  "se perdre dans son propre quartier de nuit.",
  "raconter une anecdote que tout le monde a déjà entendue trois fois.",
  "être convaincu d'avoir raison même face à des preuves contraires.",
  "faire un pas de danse en pleine réunion sérieuse par réflexe.",
  "oublier le prénom de son propre animal sous le coup de la surprise.",
  "réussir à faire fondre la glace de son cocktail en la fixant trop longtemps.",
  "s'endormir avec la télévision allumée et le son au maximum.",
  "improviser un discours de remerciement pour un prix qu'il n'a pas gagné.",
  "prendre 20 minutes pour choisir un émoji.",
  "convaincre un inconnu qu'ils se sont déjà rencontrés.",
  "être le seul à comprendre une blague qu'il vient d'inventer.",
  "acheter un objet uniquement parce que le vendeur avait l'air triste.",
  "raconter une dispute en donnant systématiquement raison à l'autre camp.",
  "réussir à se faire mal en bâillant.",
  "prétendre être fatigué pour éviter de danser, puis danser toute la nuit.",
  "avoir un avis politique tranché sur un sujet totalement inventé.",
  "confondre deux applications de messagerie et envoyer au mauvais endroit.",
  "gagner un jeu de société en trichant si discrètement que personne ne le voit.",
  "être capable de dormir n'importe où sauf dans son propre lit.",
  "raconter les règles d'un jeu de façon plus compliquée qu'elles ne le sont.",
  "avoir déjà applaudi un train qui arrive à l'heure.",
  "s'improviser expert en vin après un seul verre.",
  "faire un discours passionné sur un sujet qu'il vient de découvrir sur Internet.",
  "confondre l'heure d'été et l'heure d'hiver chaque année.",
  "réussir à perdre au memory contre un enfant de 6 ans.",
  "prendre plus de photos d'un plat que de ses propres vacances.",
  "avoir un rituel bizarre avant chaque examen ou entretien.",
  "réussir à faire une allergie à quelque chose qu'il adore.",
  "raconter sa vie à un chauffeur de taxi en dix minutes chrono.",
  "être persuadé que son animal comprend le français couramment.",
  "improviser un plan B, C et D avant même que le plan A échoue.",
  "s'endormir pendant sa propre fête surprise.",
  "réussir à faire rire toute la table sans le vouloir.",
  "confier ses mots de passe à son animal de compagnie « au cas où ».",
  "raconter un film entier à quelqu'un qui ne l'a pas demandé.",
  "gagner un pari absurde grâce à une chance insolente.",
];
