/* Questions « Qui a dit ça ? ». Chacun y répond en secret, puis la table
   devine qui a écrit quoi : une bonne question appelle une réponse COURTE
   et PERSONNELLE, assez typique de quelqu'un pour qu'on puisse la lui
   attribuer… ou se tromper. Trois niveaux EXCLUSIFS (voir src/levels.js). */

export const QUESTIONS = {
  soft: [
    "Ton talent caché ?",
    "Le métier dont tu rêvais enfant ?",
    "Ton plat signature quand tu reçois ?",
    "La chanson que tu chantes sous la douche ?",
    "Ta phobie la plus ridicule ?",
    "La dernière chose que tu as cherchée sur Internet ?",
    "Ton plaisir coupable à la télé ?",
    "Le surnom que tu avais à l'école ?",
    "Ce que tu emporterais sur une île déserte ?",
    "Ton excuse préférée pour arriver en retard ?",
    "Le super-pouvoir que tu choisirais ?",
    "Le pire cadeau que tu aies reçu ?",
    "Ta pire coupe de cheveux ?",
    "Le film que tu peux revoir cent fois ?",
    "Ton petit-déjeuner idéal ?",
    "La célébrité avec qui tu aimerais dîner ?",
    "Le pays où tu partirais demain matin ?",
    "Ta manie la plus bizarre ?",
    "Ce que tu collectionnais enfant ?",
    "Ton jeu de société préféré ?",
    "La dernière chose qui t'a fait pleurer de rire ?",
    "Le prénom que tu donnerais à un perroquet ?",
    "Ce que tu ferais d'un jour de congé surprise ?",
    "Ton émoji le plus utilisé ?",
    "Le plat que tout le monde adore et que tu détestes ?",
    "Le pire petit boulot que tu aies fait ?",
    "Ta série du moment ?",
    "La matière qui te faisait souffrir à l'école ?",
    "Ton dessin animé d'enfance préféré ?",
    "Le bruit qui t'énerve le plus ?",
    "La première chose que tu fais le matin ?",
    "Ton dernier achat inutile ?",
    "Le personnage historique que tu aimerais rencontrer ?",
    "Le sport que tu ne pratiqueras jamais ?",
    "Ta boisson préférée en terrasse ?",
    "Le dernier rêve bizarre dont tu te souviens ?",
    "Ton animal totem ?",
    "Le mot que tu dis beaucoup trop souvent ?",
    "Ce qui te met de bonne humeur à coup sûr ?",
    "L'artiste que tu écoutes en cachette ?",
    "Ce que tu commandes toujours au resto ?",
    "Ta technique pour t'endormir ?",
    "Le premier concert de ta vie ?",
    "L'objet dont tu ne te sépares jamais ?",
    "Ton record personnel le plus inutile ?",
    "Le jouet que tu as le plus aimé ?",
    "Ce que tu ferais si tu étais invisible une journée ?",
    "La phrase que tes parents te répétaient tout le temps ?",
    "Ton péché mignon sucré ?",
    "La compétence que tu voudrais maîtriser d'un claquement de doigts ?",
    "Le dernier livre que tu as lu (ou abandonné) ?",
    "L'époque où tu aurais aimé vivre ?",
    "Le personnage de fiction qui te ressemble le plus ?",
    "Ta façon de te détendre après une sale journée ?",
    "Le pire nom de wifi que tu puisses imaginer ?",
    "L'odeur qui te rappelle ton enfance ?",
    "Ce que tu achèterais en premier en gagnant au loto ?",
    "Ta spécialité au barbecue ?",
  ],
  soiree: [
    "Ta pire gueule de bois, en trois mots ?",
    "Le texto que tu regrettes d'avoir envoyé ?",
    "Ton pire rencard, en une phrase ?",
    "Le mensonge à tes parents qui tient toujours ?",
    "Ce que tu ferais d'un million d'euros demain ?",
    "Ta technique de drague, si on peut appeler ça comme ça ?",
    "Ton cocktail de l'extrême ?",
    "Le pire endroit où tu as piqué un somme ?",
    "Ta chanson de karaoké imparable ?",
    "La chose la plus folle que tu aies faite pour impressionner quelqu'un ?",
    "Ton excuse pour fuir une soirée qui t'ennuie ?",
    "Le pire cadeau que tu aies offert ?",
    "La rumeur la plus folle qui a couru sur toi ?",
    "Ce que ton historique de recherche dirait de toi ?",
    "L'épitaphe sur ta tombe ?",
    "Le surnom que tu donnes en secret à ton boss (ou à un prof) ?",
    "La plus grosse bêtise que tu aies faite en vacances ?",
    "Ton pire achat après quelques verres ?",
    "Le pire conseil qu'on t'ait donné ?",
    "Le conseil que tu donnerais à tes 15 ans ?",
    "Ce que tu fais quand personne ne te regarde ?",
    "Ton pire moment de honte en public ?",
    "Le défi le plus bête que tu aies relevé ?",
    "Le nom de ton futur groupe de rock ?",
    "Ton plan pour survivre à une invasion de zombies ?",
    "La loi absurde que tu voterais si tu dirigeais le pays ?",
    "Le pire prénom que tu pourrais donner à un enfant ?",
    "La pire chose que tu aies mangée pour un pari ?",
    "Le titre de ton autobiographie ?",
    "Ton talent inutile qui fait sensation en soirée ?",
    "Ton pire souvenir de colo ou de voyage scolaire ?",
    "La bêtise la plus « hors-la-loi » que tu aies faite ?",
    "La phrase qui résume ta vie amoureuse ?",
    "Ton premier réflexe en te réveillant après une grosse soirée ?",
    "Ton rôle si tu participais à une téléréalité ?",
    "La pire excuse que tu aies donnée pour ne pas aller travailler ?",
    "Ce que tu cacherais en premier si la police fouillait chez toi ?",
    "Le tatouage que tu regretterais à coup sûr ?",
    "La photo la plus gênante de ta galerie ?",
    "Ce que tu ferais si tu échangeais ton corps avec quelqu'un ici ?",
    "Le pire endroit pour un premier rendez-vous ?",
    "Ton crush inavouable chez les célébrités ?",
    "Ta danse signature en soirée ?",
    "Le plat que tu ne peux plus voir depuis une indigestion ?",
    "La pire phrase de rupture que tu aies entendue (ou dite) ?",
    "Le métier que tu ferais si l'argent n'existait pas ?",
    "Un secret que personne ici ne connaît, en trois mots ?",
    "Le slogan de ta campagne présidentielle ?",
    "Le message que tu enverrais à ton ex ce soir ?",
    "Ta plus grosse dépense regrettée ?",
    "L'appli de ton téléphone dont tu as un peu honte ?",
    "La pire chose que tu aies dite à un inconnu ?",
    "Ta pire tenue de soirée ?",
    "Le mot de passe que tout le monde devinerait pour toi ?",
    "Ta réplique culte quand tu as trop bu ?",
    "La personne ici avec qui tu partirais en road trip ?",
    "Le plus gros fou rire au mauvais moment de ta vie ?",
  ],
  x18: [
    "Ton fantasme le plus avouable ?",
    "L'endroit le plus insolite où tu l'as fait ?",
    "Ton pire moment au lit, en trois mots ?",
    "La partie du corps qui te fait craquer ?",
    "Ta pire expérience sur une appli de rencontre ?",
    "Le message coquin le plus raté que tu aies envoyé ?",
    "Ce que tu as fait pour séduire et que tu regrettes ?",
    "La célébrité qui hante tes rêves les plus chauds ?",
    "Le pire endroit où tu t'es fait surprendre en plein câlin ?",
    "Ta position préférée, en un mot ?",
    "Le surnom le plus gênant qu'on t'ait donné au lit ?",
    "Ta première fois, en trois mots ?",
    "Le lieu de rêve pour une nuit torride ?",
    "Le jeu coquin que tu aimerais essayer ?",
    "La plus grosse honte d'un lendemain de soirée ?",
    "Le pire mensonge que tu aies dit à un partenaire ?",
    "Ta tenue qui ne rate jamais son effet ?",
    "La chose la plus osée que tu aies faite en public ?",
    "Ce qui te refroidit en une seconde ?",
    "Le message que tu enverrais à ton crush si tu n'avais rien à perdre ?",
    "Le film qui t'a donné des idées ?",
    "Ton pire baiser, en trois mots ?",
    "La musique idéale pour une nuit chaude ?",
    "Le lieu le plus risqué où tu as embrassé quelqu'un ?",
    "Ce que tu ne ferais jamais au lit… sauf peut-être une fois ?",
    "Le compliment qui te fait fondre ?",
    "Ton pire plan d'un soir, en une phrase ?",
    "Le déguisement qui te ferait craquer ?",
    "Ce que ton ex dirait de toi au lit ?",
    "La chose la plus bizarre qui t'excite ?",
    "Ton pire réveil chez quelqu'un ?",
    "Ta phrase d'approche la plus culottée ?",
    "Le moment le plus gênant d'un rendez-vous coquin ?",
    "Ce que tu regardes en premier chez quelqu'un ?",
    "Ton record : combien de temps sans câlin ?",
    "Le pire endroit où tu as eu un coup de foudre ?",
    "Ton fantasme de vacances ?",
    "La chose que tu n'oserais jamais demander à ton partenaire ?",
    "Ta pire bourde en plein flirt ?",
    "Le petit nom que tu donnes à ton crush ?",
  ],
};
