/* Paires de mots pour Undercover : { civils, imposteur } — deux mots proches.
   Les civils reçoivent le 1er, l'imposteur le 2nd. Banque rédigée à la main (120). */
export const PAIRES = [
  { civils: "Chat", imposteur: "Tigre" },
  { civils: "Café", imposteur: "Thé" },
  { civils: "Plage", imposteur: "Piscine" },
  { civils: "Pizza", imposteur: "Quiche" },
  { civils: "Guitare", imposteur: "Violon" },
  { civils: "Neige", imposteur: "Sable" },
  { civils: "Docteur", imposteur: "Vétérinaire" },
  { civils: "Métro", imposteur: "Bus" },
  { civils: "Vin", imposteur: "Bière" },
  { civils: "Roman", imposteur: "Journal" },
  { civils: "Football", imposteur: "Rugby" },
  { civils: "Lune", imposteur: "Soleil" },
  { civils: "Téléphone", imposteur: "Talkie-walkie" },
  { civils: "Château", imposteur: "Palais" },
  { civils: "Croissant", imposteur: "Pain au chocolat" },
  { civils: "Ski", imposteur: "Snowboard" },
  { civils: "Frites", imposteur: "Chips" },
  { civils: "Burger", imposteur: "Kebab" },
  { civils: "Sushi", imposteur: "Poke bowl" },
  { civils: "Crêpe", imposteur: "Gaufre" },
  { civils: "Moutarde", imposteur: "Mayonnaise" },
  { civils: "Champagne", imposteur: "Cidre" },
  { civils: "Mojito", imposteur: "Piña colada" },
  { civils: "Baguette", imposteur: "Brioche" },
  { civils: "Fourchette", imposteur: "Baguettes chinoises" },
  { civils: "Barbecue", imposteur: "Raclette" },
  { civils: "Glace", imposteur: "Sorbet" },
  { civils: "Miel", imposteur: "Confiture" },
  { civils: "Chien", imposteur: "Loup" },
  { civils: "Poule", imposteur: "Canard" },
  { civils: "Abeille", imposteur: "Guêpe" },
  { civils: "Dauphin", imposteur: "Requin" },
  { civils: "Tortue", imposteur: "Escargot" },
  { civils: "Cheval", imposteur: "Âne" },
  { civils: "Papillon", imposteur: "Libellule" },
  { civils: "Pingouin", imposteur: "Autruche" },
  { civils: "Hamster", imposteur: "Lapin" },
  { civils: "Serpent", imposteur: "Lézard" },
  { civils: "Aigle", imposteur: "Corbeau" },
  { civils: "Fourmi", imposteur: "Cafard" },
  { civils: "Avion", imposteur: "Hélicoptère" },
  { civils: "Vélo", imposteur: "Trottinette" },
  { civils: "Train", imposteur: "Tramway" },
  { civils: "Voiture", imposteur: "Moto" },
  { civils: "Bateau", imposteur: "Sous-marin" },
  { civils: "Taxi", imposteur: "Ambulance" },
  { civils: "Fusée", imposteur: "Montgolfière" },
  { civils: "Paris", imposteur: "Lyon" },
  { civils: "Rome", imposteur: "Athènes" },
  { civils: "New York", imposteur: "Londres" },
  { civils: "Désert", imposteur: "Jungle" },
  { civils: "Montagne", imposteur: "Volcan" },
  { civils: "Rivière", imposteur: "Canal" },
  { civils: "Île", imposteur: "Presqu'île" },
  { civils: "Camping", imposteur: "Hôtel" },
  { civils: "Tente", imposteur: "Caravane" },
  { civils: "Boulanger", imposteur: "Pâtissier" },
  { civils: "Pompier", imposteur: "Policier" },
  { civils: "Avocat", imposteur: "Notaire" },
  { civils: "Professeur", imposteur: "Moniteur d'auto-école" },
  { civils: "Coiffeur", imposteur: "Barbier" },
  { civils: "Serveur", imposteur: "Barman" },
  { civils: "Chanteur", imposteur: "Rappeur" },
  { civils: "Acteur", imposteur: "Cascadeur" },
  { civils: "Peintre", imposteur: "Sculpteur" },
  { civils: "Journaliste", imposteur: "Paparazzi" },
  { civils: "Pilote", imposteur: "Capitaine" },
  { civils: "Astronaute", imposteur: "Plongeur" },
  { civils: "Magicien", imposteur: "Clown" },
  { civils: "Arbitre", imposteur: "Entraîneur" },
  { civils: "Tennis", imposteur: "Badminton" },
  { civils: "Boxe", imposteur: "Judo" },
  { civils: "Marathon", imposteur: "Triathlon" },
  { civils: "Yoga", imposteur: "Pilates" },
  { civils: "Pétanque", imposteur: "Bowling" },
  { civils: "Échecs", imposteur: "Dames" },
  { civils: "Poker", imposteur: "Tarot" },
  { civils: "Piscine", imposteur: "Jacuzzi" },
  { civils: "Basket", imposteur: "Handball" },
  { civils: "Salle de sport", imposteur: "Dojo" },
  { civils: "Lit", imposteur: "Hamac" },
  { civils: "Canapé", imposteur: "Fauteuil" },
  { civils: "Douche", imposteur: "Baignoire" },
  { civils: "Miroir", imposteur: "Vitre" },
  { civils: "Bougie", imposteur: "Lampe" },
  { civils: "Escalier", imposteur: "Ascenseur" },
  { civils: "Balcon", imposteur: "Terrasse" },
  { civils: "Cave", imposteur: "Grenier" },
  { civils: "Clé", imposteur: "Badge" },
  { civils: "Portefeuille", imposteur: "Sac à main" },
  { civils: "Montre", imposteur: "Bracelet" },
  { civils: "Lunettes", imposteur: "Lentilles" },
  { civils: "Parapluie", imposteur: "Parasol" },
  { civils: "Écharpe", imposteur: "Cravate" },
  { civils: "Chaussettes", imposteur: "Gants" },
  { civils: "Pyjama", imposteur: "Maillot de bain" },
  { civils: "Baskets", imposteur: "Talons" },
  { civils: "Jean", imposteur: "Jogging" },
  { civils: "Noël", imposteur: "Nouvel An" },
  { civils: "Halloween", imposteur: "Carnaval" },
  { civils: "Mariage", imposteur: "Baptême" },
  { civils: "Anniversaire", imposteur: "Crémaillère" },
  { civils: "Concert", imposteur: "Festival" },
  { civils: "Cinéma", imposteur: "Théâtre" },
  { civils: "Musée", imposteur: "Bibliothèque" },
  { civils: "Zoo", imposteur: "Aquarium" },
  { civils: "Cirque", imposteur: "Fête foraine" },
  { civils: "Boîte de nuit", imposteur: "Bar" },
  { civils: "Karaoké", imposteur: "Blind test" },
  { civils: "Selfie", imposteur: "Portrait" },
  { civils: "Story", imposteur: "Tweet" },
  { civils: "Emoji", imposteur: "Sticker" },
  { civils: "Wifi", imposteur: "Bluetooth" },
  { civils: "Netflix", imposteur: "YouTube" },
  { civils: "Licorne", imposteur: "Dragon" },
  { civils: "Fantôme", imposteur: "Vampire" },
  { civils: "Sorcière", imposteur: "Fée" },
  { civils: "Pirate", imposteur: "Viking" },
  { civils: "Robot", imposteur: "Zombie" },
];
