/* Paires de mots pour Undercover : { civils, imposteur } — deux mots proches.
   Les civils reçoivent le 1er, l'imposteur le 2nd. Banque rédigée à la main (120). */
export const PAIRES = [
  { civils: "Chat", imposteur: "Tigre" },
  { civils: "Café", imposteur: "Thé" },
  { civils: "Plage", imposteur: "Piscine" },
  { civils: "Pizza", imposteur: "Quiche" },
  { civils: "Guitare", imposteur: "Violon" },
  { civils: "Neige", imposteur: "Sable" },
  { civils: "Docteur", imposteur: "Vétérinaire" },
  { civils: "Métro", imposteur: "Bus" },
  { civils: "Vin", imposteur: "Bière" },
  { civils: "Roman", imposteur: "Journal" },
  { civils: "Football", imposteur: "Rugby" },
  { civils: "Lune", imposteur: "Soleil" },
  { civils: "Téléphone", imposteur: "Talkie-walkie" },
  { civils: "Château", imposteur: "Palais" },
  { civils: "Croissant", imposteur: "Pain au chocolat" },
  { civils: "Ski", imposteur: "Snowboard" },
  { civils: "Frites", imposteur: "Chips" },
  { civils: "Burger", imposteur: "Kebab" },
  { civils: "Sushi", imposteur: "Poke bowl" },
  { civils: "Crêpe", imposteur: "Gaufre" },
  { civils: "Moutarde", imposteur: "Mayonnaise" },
  { civils: "Champagne", imposteur: "Cidre" },
  { civils: "Mojito", imposteur: "Piña colada" },
  { civils: "Baguette", imposteur: "Brioche" },
  { civils: "Fourchette", imposteur: "Baguettes chinoises" },
  { civils: "Barbecue", imposteur: "Raclette" },
  { civils: "Glace", imposteur: "Sorbet" },
  { civils: "Miel", imposteur: "Confiture" },
  { civils: "Chien", imposteur: "Loup" },
  { civils: "Poule", imposteur: "Canard" },
  { civils: "Abeille", imposteur: "Guêpe" },
  { civils: "Dauphin", imposteur: "Requin" },
  { civils: "Tortue", imposteur: "Escargot" },
  { civils: "Cheval", imposteur: "Âne" },
  { civils: "Papillon", imposteur: "Libellule" },
  { civils: "Pingouin", imposteur: "Autruche" },
  { civils: "Hamster", imposteur: "Lapin" },
  { civils: "Serpent", imposteur: "Lézard" },
  { civils: "Aigle", imposteur: "Corbeau" },
  { civils: "Fourmi", imposteur: "Cafard" },
  { civils: "Avion", imposteur: "Hélicoptère" },
  { civils: "Vélo", imposteur: "Trottinette" },
  { civils: "Train", imposteur: "Tramway" },
  { civils: "Voiture", imposteur: "Moto" },
  { civils: "Bateau", imposteur: "Sous-marin" },
  { civils: "Taxi", imposteur: "Ambulance" },
  { civils: "Fusée", imposteur: "Montgolfière" },
  { civils: "Paris", imposteur: "Lyon" },
  { civils: "Rome", imposteur: "Athènes" },
  { civils: "New York", imposteur: "Londres" },
  { civils: "Désert", imposteur: "Jungle" },
  { civils: "Montagne", imposteur: "Volcan" },
  { civils: "Rivière", imposteur: "Canal" },
  { civils: "Île", imposteur: "Presqu'île" },
  { civils: "Camping", imposteur: "Hôtel" },
  { civils: "Tente", imposteur: "Caravane" },
  { civils: "Boulanger", imposteur: "Pâtissier" },
  { civils: "Pompier", imposteur: "Policier" },
  { civils: "Avocat", imposteur: "Notaire" },
  { civils: "Professeur", imposteur: "Moniteur d'auto-école" },
  { civils: "Coiffeur", imposteur: "Barbier" },
  { civils: "Serveur", imposteur: "Barman" },
  { civils: "Chanteur", imposteur: "Rappeur" },
  { civils: "Acteur", imposteur: "Cascadeur" },
  { civils: "Peintre", imposteur: "Sculpteur" },
  { civils: "Journaliste", imposteur: "Paparazzi" },
  { civils: "Pilote", imposteur: "Capitaine" },
  { civils: "Astronaute", imposteur: "Plongeur" },
  { civils: "Magicien", imposteur: "Clown" },
  { civils: "Arbitre", imposteur: "Entraîneur" },
  { civils: "Tennis", imposteur: "Badminton" },
  { civils: "Boxe", imposteur: "Judo" },
  { civils: "Marathon", imposteur: "Triathlon" },
  { civils: "Yoga", imposteur: "Pilates" },
  { civils: "Pétanque", imposteur: "Bowling" },
  { civils: "Échecs", imposteur: "Dames" },
  { civils: "Poker", imposteur: "Tarot" },
  { civils: "Piscine", imposteur: "Jacuzzi" },
  { civils: "Basket", imposteur: "Handball" },
  { civils: "Salle de sport", imposteur: "Dojo" },
  { civils: "Lit", imposteur: "Hamac" },
  { civils: "Canapé", imposteur: "Fauteuil" },
  { civils: "Douche", imposteur: "Baignoire" },
  { civils: "Miroir", imposteur: "Vitre" },
  { civils: "Bougie", imposteur: "Lampe" },
  { civils: "Escalier", imposteur: "Ascenseur" },
  { civils: "Balcon", imposteur: "Terrasse" },
  { civils: "Cave", imposteur: "Grenier" },
  { civils: "Clé", imposteur: "Badge" },
  { civils: "Portefeuille", imposteur: "Sac à main" },
  { civils: "Montre", imposteur: "Bracelet" },
  { civils: "Lunettes", imposteur: "Lentilles" },
  { civils: "Parapluie", imposteur: "Parasol" },
  { civils: "Écharpe", imposteur: "Cravate" },
  { civils: "Chaussettes", imposteur: "Gants" },
  { civils: "Pyjama", imposteur: "Maillot de bain" },
  { civils: "Baskets", imposteur: "Talons" },
  { civils: "Jean", imposteur: "Jogging" },
  { civils: "Noël", imposteur: "Nouvel An" },
  { civils: "Halloween", imposteur: "Carnaval" },
  { civils: "Mariage", imposteur: "Baptême" },
  { civils: "Anniversaire", imposteur: "Crémaillère" },
  { civils: "Concert", imposteur: "Festival" },
  { civils: "Cinéma", imposteur: "Théâtre" },
  { civils: "Musée", imposteur: "Bibliothèque" },
  { civils: "Zoo", imposteur: "Aquarium" },
  { civils: "Cirque", imposteur: "Fête foraine" },
  { civils: "Boîte de nuit", imposteur: "Bar" },
  { civils: "Karaoké", imposteur: "Blind test" },
  { civils: "Selfie", imposteur: "Portrait" },
  { civils: "Story", imposteur: "Tweet" },
  { civils: "Emoji", imposteur: "Sticker" },
  { civils: "Wifi", imposteur: "Bluetooth" },
  { civils: "Netflix", imposteur: "YouTube" },
  { civils: "Licorne", imposteur: "Dragon" },
  { civils: "Fantôme", imposteur: "Vampire" },
  { civils: "Sorcière", imposteur: "Fée" },
  { civils: "Pirate", imposteur: "Viking" },
  { civils: "Robot", imposteur: "Zombie" },

  // --- lot 2 ---
  { civils: "Citron", imposteur: "Orange" },
  { civils: "Fraise", imposteur: "Framboise" },
  { civils: "Ananas", imposteur: "Mangue" },
  { civils: "Poire", imposteur: "Pêche" },
  { civils: "Carotte", imposteur: "Panais" },
  { civils: "Aubergine", imposteur: "Courgette" },
  { civils: "Radis", imposteur: "Navet" },
  { civils: "Whisky", imposteur: "Rhum" },
  { civils: "Jus d'orange", imposteur: "Smoothie" },
  { civils: "Limonade", imposteur: "Soda" },
  { civils: "Cocktail", imposteur: "Punch" },
  { civils: "Ketchup", imposteur: "Sauce barbecue" },
  { civils: "Lasagnes", imposteur: "Cannellonis" },
  { civils: "Couscous", imposteur: "Tajine" },
  { civils: "Ramen", imposteur: "Nouilles sautées" },
  { civils: "Tacos", imposteur: "Burritos" },
  { civils: "Falafel", imposteur: "Nems" },
  { civils: "Tiramisu", imposteur: "Panna cotta" },
  { civils: "Cookie", imposteur: "Brownie" },
  { civils: "Macaron", imposteur: "Meringue" },
  { civils: "Tarte", imposteur: "Clafoutis" },
  { civils: "Girafe", imposteur: "Zèbre" },
  { civils: "Ours", imposteur: "Panda" },
  { civils: "Loutre", imposteur: "Castor" },
  { civils: "Renard", imposteur: "Blaireau" },
  { civils: "Hibou", imposteur: "Chouette" },
  { civils: "Perroquet", imposteur: "Toucan" },
  { civils: "Baleine", imposteur: "Cachalot" },
  { civils: "Méduse", imposteur: "Anémone" },
  { civils: "Crabe", imposteur: "Homard" },
  { civils: "Scorpion", imposteur: "Mygale" },
  { civils: "Kangourou", imposteur: "Wallaby" },
  { civils: "Koala", imposteur: "Paresseux" },
  { civils: "Dentiste", imposteur: "Orthodontiste" },
  { civils: "Architecte", imposteur: "Ingénieur" },
  { civils: "Chef cuisinier", imposteur: "Sommelier" },
  { civils: "Comédien", imposteur: "Humoriste" },
  { civils: "Traducteur", imposteur: "Interprète" },
  { civils: "Photographe", imposteur: "Vidéaste" },
  { civils: "Facteur", imposteur: "Livreur" },
  { civils: "Menuisier", imposteur: "Charpentier" },
  { civils: "Électricien", imposteur: "Plombier" },
  { civils: "Forêt", imposteur: "Clairière" },
  { civils: "Plaine", imposteur: "Vallée" },
  { civils: "Falaise", imposteur: "Crique" },
  { civils: "Geyser", imposteur: "Source chaude" },
  { civils: "Grotte", imposteur: "Caverne" },
  { civils: "Marseille", imposteur: "Nice" },
  { civils: "Barcelone", imposteur: "Madrid" },
  { civils: "Berlin", imposteur: "Munich" },
  { civils: "Tokyo", imposteur: "Séoul" },
  { civils: "Golf", imposteur: "Mini-golf" },
  { civils: "Escalade", imposteur: "Alpinisme" },
  { civils: "Surf", imposteur: "Paddle" },
  { civils: "Patinage", imposteur: "Ski de fond" },
  { civils: "Volleyball", imposteur: "Beach-volley" },
  { civils: "Cricket", imposteur: "Baseball" },
  { civils: "Fléchettes", imposteur: "Billard" },
  { civils: "Aspirateur", imposteur: "Balai" },
  { civils: "Frigo", imposteur: "Congélateur" },
  { civils: "Four", imposteur: "Micro-ondes" },
  { civils: "Grille-pain", imposteur: "Bouilloire" },
  { civils: "Coussin", imposteur: "Plaid" },
  { civils: "Tapis", imposteur: "Moquette" },
  { civils: "Ordinateur", imposteur: "Tablette" },
  { civils: "Souris", imposteur: "Clavier" },
  { civils: "Casque audio", imposteur: "Écouteurs" },
  { civils: "Imprimante", imposteur: "Scanner" },
  { civils: "Pâques", imposteur: "Épiphanie" },
  { civils: "Saint-Valentin", imposteur: "Fête des mères" },
  { civils: "Kermesse", imposteur: "Vide-grenier" },
  { civils: "Piano", imposteur: "Clavecin" },
  { civils: "Batterie", imposteur: "Percussions" },
  { civils: "Trompette", imposteur: "Trombone" },
  { civils: "Flûte", imposteur: "Clarinette" },
  { civils: "Harpe", imposteur: "Lyre" },
  { civils: "Camion", imposteur: "Camionnette" },
  { civils: "Scooter", imposteur: "Mobylette" },
  { civils: "Tracteur", imposteur: "Quad" },
  { civils: "Voilier", imposteur: "Yacht" },
  { civils: "Elfe", imposteur: "Nain" },
  { civils: "Ange", imposteur: "Démon" },
  { civils: "Géant", imposteur: "Titan" },
  { civils: "Ninja", imposteur: "Samouraï" },
  { civils: "Martien", imposteur: "Extraterrestre" },
  { civils: "Chapeau", imposteur: "Casquette" },
  { civils: "Gants", imposteur: "Moufles" },
  { civils: "Manteau", imposteur: "Blouson" },
  { civils: "Dominos", imposteur: "Puzzle" },
  { civils: "Loto", imposteur: "Bingo" },
  { civils: "Orage", imposteur: "Tempête" },
  { civils: "Arc-en-ciel", imposteur: "Aurore boréale" },
  { civils: "Éclipse", imposteur: "Comète" },
  { civils: "Cantine", imposteur: "Cafétéria" },
];
