/* Cadavre exquis : amorces structurées.
   OUVERTURES = début d'histoire (1re contribution), CLOTURES = fin (dernière),
   AMORCES = connecteurs de milieu (toutes les autres). L'éditeur « Mes amorces »
   enrichit le pool du milieu. */

export const OUVERTURES = [
  "Il était une fois…",
  "Tout a commencé un mardi, vers 23h47, quand",
  "Personne n'aurait parié que",
  "Au fin fond d'un royaume oublié,",
  "Le jour de son anniversaire,",
  "Dans un futur pas si lointain,",
  "La légende raconte que",
  "C'était la soirée la plus banale du monde, jusqu'à ce que",
  "Au réveil, avec un mal de tête suspect,",
  "Sur une petite île déserte,",
  "Le premier jour de son nouveau travail,",
  "Alors que la pluie tombait sur la ville,",
  "Ce matin-là, rien ne laissait présager que",
  "Dans une galaxie pas si lointaine,",
  "Il aura fallu attendre le troisième café pour que",
  "Sous le regard suspicieux du chat,",
  "À l'aube du grand jour,",
  "Loin, très loin de la civilisation,",
  "Un simple coup de vent suffit à déclencher",
  "Personne n'osait le dire tout haut, mais",
  "Dans les couloirs silencieux de l'immeuble,",
  "Ce soir-là, les étoiles semblaient annoncer",
  "Au beau milieu du marché,",
  "Tout aurait pu s'arrêter là, si seulement",
  "Derrière la porte close du numéro 7,",
  "Il n'y avait pourtant rien d'extraordinaire jusqu'à ce que",
  "Bien avant que quiconque s'en aperçoive,",
];

export const AMORCES = [
  "Soudain,",
  "Mais personne ne s'attendait à ce que",
  "C'est alors que",
  "Au même moment, à l'autre bout de la ville,",
  "Malheureusement,",
  "Contre toute attente,",
  "Pendant ce temps, dans l'ombre,",
  "Sans prévenir,",
  "Comme par magie,",
  "Et là, catastrophe :",
  "Ce que personne ne savait, c'est que",
  "Par un heureux hasard,",
  "Dans un fracas épouvantable,",
  "Le plus discrètement possible,",
  "À la surprise générale,",
  "Après trois jours de silence,",
  "Au moment précis où tout semblait perdu,",
  "Avec un aplomb incroyable,",
  "Juste avant minuit,",
  "Dans un dernier effort,",
  "Alors, évidemment,",
  "Sans aucune raison valable,",
  "Le téléphone sonna et",
  "Quelqu'un cria que",
  "En ouvrant la porte,",
  "Sous les applaudissements,",
  "Trempé de la tête aux pieds,",
  "Avec l'énergie du désespoir,",
  "Comme dans un rêve,",
  "Aussitôt dit, aussitôt fait :",
  "Contre l'avis de tout le monde,",
  "Dans le plus grand secret,",
  "Le lendemain matin,",
  "À des kilomètres de là,",
  "Étrangement,",
  "Pour couronner le tout,",
  "Sur un malentendu,",
  "Avec la grâce d'un flamant rose,",
  "Le destin en décida autrement :",
  "En chuchotant très fort,",
  "Par vengeance,",
  "Dans un élan de courage inexpliqué,",
  "Alors que plus personne n'y croyait,",
  "Une odeur de fromage flottait quand",
  "Comble de l'ironie,",
  "En un clin d'œil,",
  "L'instant d'après,",
  "Sans que personne ne s'en aperçoive,",
  "À voix basse, on murmurait que",
  "Le silence retomba avant que",
  "D'un geste théâtral,",
  "En coulisses,",
  "Ni une ni deux,",
  "Comme prévu, mais pour de mauvaises raisons,",
  "Au détour d'un couloir,",
  "Le hasard voulut que",
  "Un détail avait échappé à tout le monde :",
  "En un rien de temps,",
  "Ce fut le début d'une longue série d'ennuis quand",
  "Sans crier gare,",
  "Prise d'une inspiration soudaine,",
  "Le cœur battant,",
  "Un peu plus loin,",
  "Contre toute logique,",
  "Il fallait s'y attendre :",
  "Fidèle à son habitude,",
  "Personne ne remarqua que",
  "En apparence seulement,",
  "Dans un sursaut d'orgueil,",
  "Il suffisait pourtant d'un mot pour que",
  "Comme un signe du destin,",
  "L'ambiance changea du tout au tout lorsque",
  "Au fond de la salle,",
  "Une petite voix chuchota que",
  "Rien ne se déroula comme prévu, car",
  "En dépit du bon sens,",
  "L'horloge sonna au moment précis où",
  "Sur la pointe des pieds,",
  "D'un commun accord,",
  "Il ne fallut qu'une seconde pour que",
  "Envers et contre tout,",
  "Ce fut plus fort qu'eux :",
  "Une ombre passa et",
  "Sans un mot de plus,",
  "Le vent tourna, littéralement, quand",
  "À bout de souffle,",
  "D'un pas décidé,",
  "Comme toujours au pire moment,",
  "Le hasard fit qu'au même instant,",
  "L'un dans l'autre,",
  "Pour ne pas perdre la face,",
  "Il n'en fallait pas plus pour que",
  "Coup de théâtre :",
  "En dernier recours,",
  "L'histoire aurait pu s'arrêter là, mais",
];

/* Thèmes d'histoire : consigne d'écriture + ouvertures/clôtures dédiées.
   Les connecteurs de milieu (AMORCES) restent communs à tous les thèmes. */
export const THEMES = [
  { id: "libre", label: "🎲 Libre" },
  {
    id: "horreur", label: "👻 Horreur",
    consigne: "Ambiance frissons : nuit, craquements, ombres, cave humide…",
    ouvertures: [
      "La nuit où le vent s'est tu d'un coup,",
      "Personne ne retournait jamais dans la maison du 13, et pourtant",
      "Le miroir de l'entrée renvoyait un reflet de trop quand",
    ],
    clotures: [
      "On n'a jamais retrouvé que ses chaussures, et encore,",
      "Depuis, chaque nuit à 3h33 précises,",
      "La police a classé l'affaire, mais les voisins jurent que",
    ],
  },
  {
    id: "romance", label: "💘 Romance",
    consigne: "Cœurs qui battent, regards appuyés, quiproquos amoureux…",
    ouvertures: [
      "Leurs mains se sont frôlées au rayon surgelés quand",
      "Le mariage devait être parfait, jusqu'au moment où",
      "Trois ans qu'ils se croisaient dans l'ascenseur sans oser, mais ce matin-là",
    ],
    clotures: [
      "Et c'est ainsi qu'ils s'aimèrent, malgré",
      "Le faire-part précisait simplement que",
      "On raconte qu'ils se disputent encore pour savoir qui a embrassé l'autre en premier, car",
    ],
  },
  {
    id: "bureau", label: "💼 Bureau",
    consigne: "Open space, réunions absurdes, machine à café, mails « urgents »…",
    ouvertures: [
      "La réunion de 9h aurait dû durer quinze minutes, mais",
      "Le stagiaire cliqua sur « Répondre à tous » et",
      "Le jour de l'audit, la photocopieuse choisit de",
    ],
    clotures: [
      "Le compte-rendu officiel mentionne seulement que",
      "Depuis, la machine à café est sous surveillance, parce que",
      "Les RH ont créé une nouvelle règle spécialement pour que",
    ],
  },
  {
    id: "sf", label: "🚀 Science-fiction",
    consigne: "Vaisseaux, robots, planètes étranges, paradoxes temporels…",
    ouvertures: [
      "L'an 3042 commença comme les autres, jusqu'à ce que le vaisseau",
      "Le robot domestique afficha une émotion non répertoriée quand",
      "À l'ouverture du portail temporel,",
    ],
    clotures: [
      "L'humanité décida d'un commun accord que",
      "Le rapport intergalactique conclut sobrement que",
      "Et c'est pour ça que, depuis, les robots ont interdiction de",
    ],
  },
  {
    id: "polar", label: "🕵️ Polar",
    consigne: "Enquête, suspects, indices douteux, imperméable et pluie…",
    ouvertures: [
      "Le corps du règlement intérieur avait disparu quand l'inspecteur",
      "Il pleuvait sur la ville, comme toujours, quand le téléphone",
      "Trois suspects, deux alibis, un seul cendrier plein :",
    ],
    clotures: [
      "Le coupable était donc, depuis le début,",
      "L'inspecteur ralluma une cigarette en concluant que",
      "L'affaire fut close, même si personne n'expliqua jamais",
    ],
  },
];

export const CLOTURES = [
  "Et pour finir,",
  "Et c'est ainsi que",
  "Moralité :",
  "Depuis ce jour,",
  "Finalement, contre toute attente,",
  "Et ils vécurent, tant bien que mal,",
  "Le rapport de police conclura simplement que",
  "Aujourd'hui encore, on raconte que",
  "En guise de happy end,",
  "Tout ça pour dire que",
  "Et voilà comment tout s'est terminé :",
  "La suite, personne ne l'a jamais racontée, sauf que",
  "Bien des années plus tard, on se souviendra que",
  "Pour la petite histoire,",
  "Et si vous ne me croyez pas,",
  "Sur ce, le rideau tombe :",
  "En conclusion de cette folle soirée,",
  "Personne n'a jamais retrouvé",
  "Et c'est ainsi que la légende raconte que",
  "Épilogue :",
  "Le mot de la fin revient à celui qui dira que",
  "Longtemps après, il en restait",
  "Comme dans tout bon conte,",
  "Et la morale de cette histoire, s'il y en a une, c'est que",
  "FIN. Ou presque, car",
];
