/* Données « Je n'ai jamais ». Chaque phrase commence implicitement par
   « Je n'ai jamais… ». Trois niveaux EXCLUSIFS (voir src/levels.js) :
   soft · soiree · x18. Banque rédigée à la main, une phrase = une idée. */

export const PHRASES = {
  soft: [
    "séché les cours.",
    "menti sur mon âge.",
    "chanté sous la douche à tue-tête.",
    "mangé quelque chose tombé par terre.",
    "fait semblant d'être malade pour éviter un truc.",
    "envoyé un message à la mauvaise personne.",
    "pleuré devant un film d'animation.",
    "oublié le prénom de quelqu'un juste après les présentations.",
    "fait un fou rire au pire moment possible.",
    "gardé un objet emprunté sans jamais le rendre.",
    "redoublé une classe.",
    "copié sur mon voisin pendant un contrôle.",
    "imité la signature de mes parents.",
    "fait l'école buissonnière avec un mot d'excuse inventé.",
    "été collé un samedi matin.",
    "pleuré à cause d'une note.",
    "eu le béguin pour un prof.",
    "mangé de la colle ou du papier à l'école.",
    "cassé des lunettes en chahutant.",
    "oublié mon sac ou mon cartable à la maison.",
    "triché contre un enfant pour gagner à un jeu.",
    "cru au Père Noël après mes 10 ans.",
    "fait un exposé sans avoir rien préparé.",
    "appelé un prof « maman » ou « papa ».",
    "été délégué de classe.",
    "fait semblant de comprendre en cours pendant tout un trimestre.",
    "rendu une copie quasiment blanche.",
    "écrit sur les tables ou les murs de l'école.",
    "gagné un concours ou un tournoi scolaire.",
    "fait tomber mon téléphone dans les toilettes.",
    "envoyé un vocal de plus de trois minutes.",
    "stalké quelqu'un jusqu'à ses photos d'il y a cinq ans.",
    "liké par accident une vieille photo en stalkant.",
    "supprimé une publication parce qu'elle ne faisait pas assez de likes.",
    "eu plus de 100 messages non lus.",
    "fait semblant de ne pas avoir vu un message pendant des jours.",
    "répondu « oui oui » sans avoir lu le message.",
    "passé une nuit blanche à scroller.",
    "cassé deux écrans de téléphone dans le même mois.",
    "publié une story supprimée dans les cinq minutes.",
    "envoyé un message entièrement dicté par quelqu'un d'autre.",
    "oublié mon téléphone dans un taxi, un bus ou un train.",
    "créé un faux compte pour regarder le profil de quelqu'un.",
    "googlé mon propre nom.",
    "répondu au téléphone en imitant quelqu'un d'autre.",
    "laissé sonner exprès pour pouvoir rappeler « plus tard ».",
    "filmé un concert entier sans jamais regarder la vidéo ensuite.",
    "utilisé le mode avion pour éviter quelqu'un.",
    "passé un appel vidéo depuis les toilettes.",
    "envoyé « je suis en route » sans être parti.",
    "mis quelqu'un en haut-parleur sans le prévenir.",
    "archivé une conversation pour ne plus jamais l'ouvrir.",
    "eu honte de mon historique YouTube.",
    "mangé un aliment périmé en toute connaissance de cause.",
    "commandé le même plat trois soirs de suite.",
    "fini un pot de pâte à tartiner à la cuillère.",
    "menti en disant « c'est fait maison ».",
    "recraché discrètement un plat chez quelqu'un.",
    "mangé au fast-food deux fois dans la même journée.",
    "bu le jus du pot de cornichons.",
    "mis du ketchup sur un plat gastronomique.",
    "fait semblant d'aimer un plat par politesse pendant des années.",
    "mangé la part de quelqu'un d'autre dans un frigo commun.",
    "commandé une pizza entière pour moi tout seul.",
    "goûté la nourriture pour animaux.",
    "caché des légumes pour ne pas les manger, même adulte.",
    "mangé un dessert en cachette avant le repas.",
    "inventé une allergie pour éviter un aliment.",
    "fait brûler une casserole en faisant bouillir de l'eau.",
    "mangé froid un plat prévu chaud, par pure flemme.",
    "passé une journée entière à ne manger que des snacks.",
    "léché l'assiette quand personne ne regardait.",
    "fait un repas entier à la cuillère à café faute de vaisselle propre.",
    "bu directement à la bouteille du frigo commun.",
    "remis un emballage presque vide dans le placard.",
    "envoyé un « répondre à tous » catastrophique.",
    "poussé avec insistance une porte marquée « tirer ».",
    "salué quelqu'un qui saluait en fait la personne derrière moi.",
    "marché dans une crotte de chien en tongs.",
    "glissé devant tout le monde sans me blesser… sauf l'ego.",
    "cassé un objet chez quelqu'un et l'avoir légèrement déplacé pour cacher les dégâts.",
    "laissé un caddie rouler jusqu'à une voiture.",
    "claqué la porte avec les clés à l'intérieur.",
    "pris le mauvais bus ou train et assumé jusqu'au bout.",
    "perdu mes clés trois fois dans le même mois.",
    "raté mon arrêt en dormant dans les transports.",
    "porté un vêtement à l'envers toute une journée.",
    "porté deux chaussettes différentes à un rendez-vous important.",
    "offert un cadeau à la mauvaise personne.",
    "confondu le sel et le sucre, avec conséquences.",
    "fait un créneau en dix-sept manœuvres avec du public.",
    "répondu « toi aussi » à un serveur qui me souhaitait bon appétit.",
    "oublié pourquoi j'entrais dans une pièce, deux fois de suite.",
    "passé l'aspirateur autour d'un objet pendant des mois au lieu de le ramasser.",
    "fait tomber mon plateau devant tout un self.",
    "déclenché une alarme sans le vouloir.",
    "arrosé une plante en plastique.",
    "attendu devant la mauvaise voiture en croyant que c'était la mienne.",
    "fait semblant d'avoir vu un film pour éviter qu'on me le raconte.",
    "dit « j'arrive dans 5 minutes » en étant encore sous la douche.",
    "inventé un rendez-vous pour partir plus tôt.",
    "fait semblant d'être très occupé au travail en tapant n'importe quoi.",
    "félicité quelqu'un pour une grossesse inexistante.",
    "raconté l'anecdote de quelqu'un d'autre comme si c'était la mienne.",
    "fait semblant de me souvenir d'une personne pendant toute une conversation.",
    "accepté une invitation en espérant qu'elle serait annulée.",
    "dit « c'est trop drôle » sans avoir compris la blague.",
    "prétendu avoir lu un livre à peine ouvert.",
    "embelli mon CV au-delà du raisonnable.",
    "fait passer un plat acheté pour du fait maison chez des invités.",
    "dit « on se refait ça vite » sans aucune intention.",
    "fait semblant de dormir pour éviter une discussion.",
    "applaudi sans savoir pourquoi tout le monde applaudissait.",
    "fait semblant de connaître une chanson en marmonnant les paroles.",
    "souhaité un anniversaire uniquement grâce à la notification.",
    "prétendu être malade pour rester au lit sans raison.",
    "exposé un cadeau moche uniquement quand la personne vient à la maison.",
    "exagéré une anecdote jusqu'à ne plus reconnaître la vérité.",
    "payé une grosse somme en centimes.",
    "oublié de rembourser un ami — qui est peut-être ici.",
    "acheté un truc inutile juste parce que le vendeur était sympa.",
    "rendu un article après l'avoir porté une fois.",
    "gardé la monnaie quand on m'en a trop rendu.",
    "fait semblant de chercher mon portefeuille au moment de l'addition.",
    "dormi au travail ou en cours sans me faire prendre.",
    "fait une sieste dans les toilettes du bureau.",
    "postulé à un poste dont je ne comprenais pas l'intitulé.",
    "utilisé l'imprimante du travail pour des documents très personnels.",
    "fait les courses en pyjama à peine dissimulé.",
    "signé une pétition sans la lire.",
    "payé un abonnement inutilisé pendant plus d'un an.",
    "négocié âprement pour cinquante centimes au marché.",
    "pleuré à cause d'une démarche administrative.",
    "prétendu faire du sport « régulièrement » chez le médecin.",
    "pris un abonnement de sport utilisé moins de cinq fois.",
    "eu des courbatures après un effort ridicule.",
    "simulé une blessure pour éviter un match.",
    "pris l'ascenseur pour un seul étage en pleine forme.",
    "couru après un bus devant témoins… et l'avoir raté.",
    "fait du sport uniquement pour la photo d'après.",
    "battu un enfant à un jeu sans le laisser gagner.",
    "suivi un tuto de fitness sans dépasser l'échauffement.",
    "dansé au point de me blesser.",
    "raconté le même exploit sportif en l'exagérant à chaque fois.",
    "raté un avion ou un train par ma seule faute.",
    "fait ma valise le matin même du départ.",
    "oublié un indispensable (chargeur, brosse à dents, maillot) en voyage.",
    "hoché la tête à l'étranger sans rien comprendre à la conversation.",
    "pris un coup de soleil avec des marques ridicules.",
    "suivi un GPS jusque dans une impasse absurde.",
    "ramené des souvenirs jamais offerts.",
    "visité un musée au pas de course juste pour dire « je l'ai fait ».",
    "dormi dans un aéroport.",
    "envoyé une carte postale arrivée après mon retour.",
    "fait semblant d'être un local pour éviter les vendeurs.",
    "pris 400 photos du même monument.",
    "pleuré devant une comédie romantique que je critique en public.",
    "chanté des paroles fausses pendant des années avec une conviction totale.",
    "dormi au cinéma.",
    "spoilé une fin par accident et fait comme si de rien n'était.",
    "regardé une série entière en un seul week-end.",
    "écouté la même chanson plus de vingt fois dans la journée.",
    "dansé seul devant le miroir avec chorégraphie complète.",
    "fait une playlist pour quelqu'un qui ne l'a jamais écoutée.",
    "menti sur mes goûts musicaux pour paraître cool.",
    "pleuré à un concert.",
    "refusé de sortir pour finir une série.",
    "lu la fin d'un livre avant d'arriver au milieu.",
    "oublié l'anniversaire d'un très proche.",
    "appelé quelqu'un par le prénom de mon animal.",
    "écouté aux portes chez mes parents.",
    "lu le journal intime ou les notes privées de quelqu'un.",
    "profité d'un cadeau commun sans avoir participé financièrement.",
    "inventé une urgence pour quitter un repas de famille.",
    "gardé un secret de famille plus de dix ans.",
    "perdu temporairement l'animal que je gardais.",
    "dit à deux amis différents qu'ils étaient mon « meilleur ami ».",
    "oublié d'aller chercher quelqu'un que je devais récupérer.",
    "utilisé le compte de streaming de quelqu'un sans son accord.",
    "parlé à mes plantes ou à mes objets.",
    "donné un prénom à ma voiture ou à mon téléphone.",
    "gardé des boîtes vides « au cas où ».",
    "senti un vêtement pour décider s'il était encore propre.",
    "dormi avec une peluche après mes 18 ans.",
    "vérifié sous le lit ou derrière la porte après un film d'horreur.",
    "répété une conversation importante devant le miroir.",
    "rejoué mentalement un débat perdu des années après, avec la réplique parfaite.",
    "fait un discours de remerciement imaginaire sous la douche.",
    "mangé debout au-dessus de l'évier comme un raton laveur.",
    "remis l'alarme « encore 5 minutes » plus de trois fois.",
    "porté le même jean une semaine entière.",
    "fixé mon téléphone pour éviter de parler à un voisin.",
    "fait coucou à quelqu'un qui ne me faisait pas coucou.",
    "ri si fort que tout un lieu public s'est retourné.",
    "eu un fou rire pendant un moment solennel.",
    "trébuché en marchant sur absolument rien.",
    "chanté à voix haute avec des écouteurs sans m'en rendre compte.",
    "parlé dix minutes à quelqu'un avec un truc entre les dents.",
    "découvert ma braguette ouverte après une présentation.",
    "éternué dans un silence total avec un bruit improbable.",
    "tendu la main pour un high-five resté sans réponse.",
    "appelé un inconnu « chef » ou « champion » faute de prénom.",
    "fait tomber mon téléphone sur mon visage au lit.",
    "dit « au revoir » puis marché dans la même direction que la personne.",
    "raté une marche devant un public nombreux.",
    "eu le hoquet pendant un moment très sérieux.",
    "pris un inconnu par l'épaule en le confondant avec un ami.",
    "rage-quitté un jeu vidéo.",
    "failli casser une manette de rage.",
    "joué toute une nuit jusqu'au lever du jour.",
    "accusé le lag pour masquer mon niveau.",
    "fait une pause « cinq minutes » de trois heures.",
    "crié sur un écran comme s'il pouvait m'entendre.",
    "perdu contre quelqu'un qui découvrait le jeu.",
    "dépensé de l'argent réel dans un jeu gratuit.",
    "tout perdu pour avoir oublié de sauvegarder.",
    "prétendu avoir laissé gagner quelqu'un alors que j'avais vraiment perdu.",
    "installé et désinstallé le même jeu trois fois.",
    "regardé quelqu'un jouer pendant des heures, avec plaisir.",
    "dormi plus de 14 heures d'affilée.",
    "répondu à un message à moitié endormi, sans aucun souvenir ensuite.",
    "raté un événement important à cause d'une sieste.",
    "dormi tout habillé, chaussures comprises.",
    "fait la tête au réveil à cause d'une dispute rêvée.",
    "parlé en dormant — et on me l'a répété.",
    "mis trois alarmes et raté la journée quand même.",
    "somnolé pendant un appel vidéo.",
    "fait une nuit blanche pour rien de spécial.",
    "confondu un rêve avec un souvenir devant témoin.",
    "coupé ma frange moi-même, avec regret immédiat.",
    "porté des lunettes sans correction pour le style.",
    "suivi une mode qui ne me va objectivement pas.",
    "gardé un vêtement troué par pur attachement.",
    "mis une heure à choisir une tenue pour finir en jogging.",
    "tenté une coloration qui a mal tourné.",
    "gardé des chaussures douloureuses toute une soirée par fierté.",
    "pris 40 selfies pour un rendu « naturel ».",
    "utilisé un filtre pendant une visio professionnelle.",
    "découvert trop tard l'étiquette restée sur un vêtement neuf.",
    "parlé à un animal avec une voix spéciale devant témoins.",
    "préféré la compagnie de l'animal à celle des invités.",
    "montré 50 photos de mon animal à quelqu'un de simplement poli.",
    "créé un album photo ou un compte dédié à un animal.",
    "été trahi par un animal que je gardais : fugue, bêtise ou destruction.",
    "pleuré devant une vidéo d'animaux.",
    "cédé ma place dans le lit à un animal.",
    "déclenché le détecteur de fumée en cuisinant.",
    "mangé des pâtes cinq soirs d'affilée.",
    "entassé le désordre dans une seule pièce avant une visite.",
    "nettoyé uniquement les zones visibles avant l'arrivée d'invités.",
    "laissé la vaisselle « tremper » trois jours.",
    "repassé un vêtement avec un lisseur à cheveux.",
    "utilisé un t-shirt comme taie d'oreiller faute de linge propre.",
    "monté un meuble avec des vis en trop à la fin.",
    "recollé un objet cassé en espérant que personne ne remarque.",
    "tué une plante réputée increvable en une semaine.",
    "chanté à tue-tête au feu rouge, fenêtre ouverte, sans le savoir.",
    "calé au démarrage devant un public.",
    "klaxonné par erreur et regardé ailleurs.",
    "suivi une voiture en croyant que c'était celle d'un ami.",
    "raté une sortie et improvisé un « raccourci » de 40 minutes.",
    "conduit jusqu'au travail un jour férié.",
    "cherché ma voiture sur un parking plus de 20 minutes.",
    "roulé plusieurs jours avec le voyant d'essence allumé.",
    "mis les essuie-glaces au lieu du clignotant.",
    "gagné quelque chose à une tombola ou à un jeu à gratter.",
    "fait un vœu en voyant une étoile filante.",
    "écrit une lettre à mon moi du futur.",
    "partagé une fake news en y croyant dur comme fer.",
    "participé à un karaoké ou un flash mob public.",
    "fait la queue pour un truc gratuit dont je n'avais pas besoin.",
    "gardé un ticket de concert ou de cinéma en souvenir pendant des années.",
    "testé tous les parfums d'un magasin jusqu'au mal de tête.",
    "pris un accent au téléphone sans aucune raison.",
    "répondu avec mon « allô » professionnel un dimanche.",
    "écrit une liste de tâches juste pour barrer des choses déjà faites.",
    "applaudi à l'atterrissage d'un avion.",
    "gardé le chargeur d'un appareil que je n'ai plus.",
    "souri à un bébé qui s'est immédiatement mis à pleurer.",
    "perdu cinq fois de suite à pierre-feuille-ciseaux.",
    "dit « dernière vidéo et je dors » plus de trois fois la même nuit.",
    "fait semblant de connaître les règles pendant toute une partie.",
    "juré de ne plus jamais boire… un dimanche matin.",
    "organisé un événement et failli ne pas y aller.",
    "oublié le prénom de quelqu'un que je connais depuis des années.",
    "fait un discours improvisé beaucoup trop long.",
    "gardé le même fond d'écran par flemme pendant des années.",
    "demandé « quoi de neuf ? » sans écouter la réponse.",
    "fini une soirée jeux fâché pour de vrai.",
    "gagné un débat en citant une étude inventée.",
    "prétendu savoir siffler, claquer des doigts ou faire un clin d'œil.",
    "répondu à une question de quiz avec un aplomb total… et eu tout faux.",
    "gardé un fou rire pour moi pendant une visio en coupant ma caméra.",
    "mimé une conversation téléphonique dans la rue pour avoir l'air attendu.",
    "fait semblant d'être pressé pour marcher plus vite qu'un inconnu.",
    "triché à un jeu de société de famille et gagné.",
    "caché un aliment pour ne pas avoir à le partager.",
    "répondu « présent » à l'appel pour un ami absent.",
    "raconté un rêve en direct à quelqu'un qui s'en fichait visiblement.",
    "changé de trottoir pour éviter une connaissance.",
    "porté un pyjama toute la journée un jour de semaine.",
    "menti sur mon film préféré pour paraître plus cultivé.",
    "acheté un gadget de cuisine jamais utilisé.",
    "chanté du karaoké complètement faux avec assurance.",
    "fait semblant de comprendre une blague en anglais.",
    "gardé un ticket de caisse pendant plus d'un an.",
    "porté des chaussures neuves qui font horriblement mal, par fierté.",
    "menti sur mon âge pour une réduction.",
    "raté une recette simple en suivant scrupuleusement les instructions.",
    "regardé un tuto pour finalement ne rien faire.",
    "acheté un abonnement de sport « pour de bon cette fois ».",
    "cru dur comme fer à une fake news partagée par un proche.",
    "utilisé le mot « littéralement » alors que ce n'était pas littéral du tout.",
    "oublié d'éteindre le four en partant.",
    "fait un créneau catastrophique devant mon propre voisin.",
    "raconté un rêve avec plus de suspense qu'un film.",
    "gardé une plante en plastique en pensant qu'elle était vraie, un instant.",
    "porté deux parfums différents en même temps par erreur.",
    "menti sur le nombre de livres lus cette année.",
    "fait semblant d'écrire un message important pour éviter une conversation.",
    "raté une marche ou un trottoir en plein jour, sans obstacle visible.",
    "eu peur d'un film soi-disant « pour enfants ».",
    "acheté un objet uniquement pour sa couleur.",
    "chanté une pub à la place d'une vraie chanson par réflexe.",
    "confondu deux séries au point de spoiler la mauvaise à quelqu'un.",
    "gardé un vieux téléphone cassé « juste au cas où ».",
    "tenté un créneau en trois points… qui a fini en dix.",
    "mangé un yaourt après la date de péremption en fermant les yeux.",
    "cru reconnaître quelqu'un de célèbre et m'être trompé complètement.",
    "porté un vêtement encore plié, marques du pliage bien visibles.",
    "envoyé un email professionnel avec une faute dans l'objet.",
    "fait semblant d'être malade pour rater un cours de sport.",
    "raconté une blague que personne n'a comprise, deux fois de suite.",
    "acheté un jeu de société jamais sorti de sa boîte.",
    "confondu le nom de deux collègues pendant des mois.",
    "cru qu'un aliment était périmé alors que la date était encore bonne.",
    "regardé la météo dix fois dans la même journée par angoisse.",
    "raté un rendez-vous en le confondant avec le lendemain.",
    "fait semblant de ne pas entendre pour éviter de répondre.",
    "chanté la mauvaise chanson à un karaoké en pensant que c'était la bonne.",
    "collectionné des sacs plastiques « juste au cas où ».",
    "oublié le mot de passe de mon propre téléphone.",
    "porté des lunettes de vue à la place de mes lunettes de soleil, ou l'inverse.",
    "fait tomber un objet en essayant de prouver que je ne l'avais pas fait tomber.",
    "menti sur ma taille de vêtement pour éviter la honte au magasin.",
    "cru comprendre les règles d'un jeu avant de perdre lamentablement.",
    "utilisé un mot que je ne comprenais pas vraiment pour paraître intelligent.",
    "fait semblant de reconnaître une odeur de cuisine pour flatter le cuisinier.",
    "regardé mon reflet dans une vitrine en pensant que personne ne me voyait faire.",
    "raté une blague pourtant très simple à raconter.",
    "acheté un aliment exotique jamais cuisiné, encore au fond du placard.",
    "porté un masque de sommeil en plein jour par flemme de le ranger.",
    "confondu deux applications de banque et paniqué inutilement.",
    "raté un high five devant tout le monde.",
    "utilisé un GPS pour un trajet que je connais par cœur.",
    "cru avoir perdu mon téléphone en le tenant dans l'autre main.",
    "gardé un post-it « urgent » collé pendant six mois.",
    "regardé un épisode déjà vu en pensant découvrir la suite.",
    "porté un t-shirt à l'envers toute une réunion sans que personne ne le dise.",
    "fait semblant de connaître un jeu vidéo pour ne pas passer pour largué.",
  ],
  soiree: [
    "embrassé quelqu'un dans cette pièce.",
    "eu un crush sur un·e ami·e de mes potes.",
    "fait un date via une appli.",
    "menti sur le nombre de mes ex.",
    "envoyé une photo que j'ai regrettée.",
    "flirté pour obtenir quelque chose.",
    "mélangé les alcools en connaissant parfaitement les conséquences.",
    "perdu mon téléphone en soirée et l'avoir retrouvé dans un endroit absurde.",
    "dansé sur une table ou un bar.",
    "pleuré en soirée pour une raison oubliée le lendemain.",
    "déclaré mon amour à tout le monde après deux verres.",
    "juré « c'est mon dernier verre » plus de trois fois la même nuit.",
    "fini une soirée en parlant philosophie dans une cuisine.",
    "dormi dans une baignoire, un jardin ou un couloir.",
    "perdu au moins un vêtement en soirée.",
    "payé une tournée générale sur un coup de tête.",
    "confondu la porte des toilettes avec un placard.",
    "appelé mes parents en rentrant de soirée en croyant appeler quelqu'un d'autre.",
    "eu un trou noir de plus de deux heures.",
    "promis une amitié éternelle à un inconnu de soirée.",
    "vomi dans un endroit non prévu à cet effet.",
    "caché mon état à mes parents avec un aplomb remarquable.",
    "bu un fond de verre qui n'était pas le mien.",
    "inventé un cocktail avec les fonds de bouteilles.",
    "été le premier à partir d'une soirée… vers 23h.",
    "aidé à ranger juste pour rester plus longtemps.",
    "perdu mes clés en soirée et dormi ailleurs que prévu.",
    "fait un karaoké dont il existe des preuves vidéo.",
    "refusé de donner mon téléphone « pour mon bien ».",
    "dansé avec un inconnu comme si on se connaissait depuis dix ans.",
    "juré qu'un kebab à 4h du matin était le meilleur repas de ma vie.",
    "lancé en soirée un projet de vie abandonné au réveil.",
    "envoyé un vocal de cinq minutes en état d'ébriété.",
    "perdu un pari stupide en soirée et payé le prix fort.",
    "réveillé toute une rue en chantant.",
    "oublié le prénom de la personne avec qui je dansais.",
    "terminé une soirée pieds nus sans explication.",
    "simulé la sobriété devant un agent de sécurité.",
    "bu pour oublier… puis raconté à tout le monde ce que je voulais oublier.",
    "organisé une soirée qui a laissé des traces sur les murs.",
    "sympathisé dans une file d'attente de toilettes.",
    "pris la cuite la plus chère de ma vie.",
    "juré de détester quelqu'un puis fini la soirée à rire avec lui.",
    "fait un before qui a duré plus longtemps que la soirée.",
    "raté un événement le lendemain à cause d'une soirée.",
    "retrouvé au réveil des photos inconnues dans mon téléphone.",
    "embrassé quelqu'un dont je ne connaissais pas le prénom.",
    "embrassé plus d'une personne dans la même soirée.",
    "dragué avec une phrase toute faite trouvée sur internet.",
    "donné un faux numéro.",
    "reçu un faux numéro — et vérifié.",
    "dragué le meilleur ami ou la meilleure amie de mon ex.",
    "embrassé quelqu'un pour gagner un pari.",
    "regretté un bisou dans la seconde qui a suivi.",
    "flirté avec deux personnes en même temps dans la même pièce.",
    "utilisé un ami comme excuse pour aborder quelqu'un.",
    "fait semblant d'aimer une passion que je déteste pour séduire.",
    "invité exprès la mauvaise personne pour un slow.",
    "écrit un poème ou une chanson pour séduire.",
    "envoyé un message de drague à 3h du matin.",
    "parlé d'un crush pendant des semaines après un seul regard.",
    "détourné la tradition du gui ou du Nouvel An pour embrasser quelqu'un.",
    "dragué dans une salle d'attente ou un lieu totalement improbable.",
    "utilisé mon animal comme aimant à rencontres.",
    "prétendu fêter quelque chose pour engager la conversation.",
    "demandé à un ami de tester la fidélité de quelqu'un.",
    "annulé un rencard parce que le précédent s'était trop bien passé.",
    "eu deux rencards le même jour.",
    "oublié le prénom de mon rencard pendant le rencard.",
    "croisé un rencard raté en soirée et fait semblant de ne pas le voir.",
    "accepté un deuxième rendez-vous juste par politesse.",
    "embrassé un ou une collègue à une fête de travail.",
    "écrit des messages de drague pour quelqu'un d'autre, façon Cyrano.",
    "laissé traîner un objet chez quelqu'un pour avoir une raison de revenir.",
    "dit « je ne cherche rien de sérieux » en pensant exactement le contraire.",
    "ghosté quelqu'un après un seul rendez-vous.",
    "été ghosté après un rendez-vous que je croyais parfait.",
    "rejoué mentalement un râteau pendant des années.",
    "fait le premier pas alors que je jurais ne jamais le faire.",
    "dragué quelqu'un devant son ou sa partenaire, sans le savoir.",
    "rougi au point que toute la pièce l'a remarqué.",
    "inventé un passé plus intéressant en rendez-vous.",
    "envoyé une capture d'écran à la personne dont on parlait.",
    "découvert que mes amis m'avaient organisé un rencard sans me prévenir.",
    "comparé tous mes rencards à un ex.",
    "gardé des photos d'un ex « pour les souvenirs ».",
    "rendu visite à un ex « juste pour discuter ».",
    "rompu par message.",
    "été largué par message — ou pire, par un intermédiaire.",
    "fait un break qui n'a jamais repris.",
    "caché une relation à mes parents.",
    "présenté quelqu'un comme « un ami » alors que c'était bien plus.",
    "espionné le nouveau ou la nouvelle de mon ex.",
    "gardé un vêtement d'un ex que je porte encore.",
    "recontacté un ex après minuit.",
    "répondu à un ex après minuit — ce qui est pire.",
    "dit « c'est fini » sans le penser, juste pour tester.",
    "pleuré une relation qui n'a jamais officiellement existé.",
    "été jaloux d'un personnage de série préféré de mon ou ma partenaire.",
    "fouillé le téléphone d'un ou une partenaire.",
    "su que mon téléphone avait été fouillé et rien dit.",
    "menti sur l'endroit où j'étais.",
    "inventé une sortie « entre potes » pour couvrir un rendez-vous.",
    "aimé en secret quelqu'un de pris.",
    "appris des années après que j'étais le crush secret de quelqu'un.",
    "refusé une déclaration et regretté ensuite.",
    "fait une déclaration refusée devant témoins.",
    "repris avec un ex en sachant que c'était une erreur.",
    "oublié un anniversaire de couple.",
    "offert le même cadeau à deux partenaires différents.",
    "fait semblant d'être célibataire en soirée.",
    "pensé à quelqu'un d'autre pendant un rendez-vous.",
    "écrit une lettre jamais envoyée.",
    "mal vécu d'apprendre par les réseaux que mon ex était recasé.",
    "demandé à un ami de bloquer quelqu'un à ma place.",
    "rompu juste avant les fêtes pour éviter le cadeau.",
    "eu une relation « secrète » que tout le monde connaissait.",
    "redemandé en couple le jour même de la rupture.",
    "assisté au mariage d'un ex.",
    "envoyé « je t'aime » à la mauvaise personne.",
    "supprimé au réveil un message de soirée… trop tard.",
    "laissé quelqu'un lire un message compromettant par-dessus mon épaule.",
    "répondu dans le mauvais groupe de discussion.",
    "critiqué quelqu'un dans un message envoyé… à cette personne.",
    "publié une story que mes collègues n'auraient jamais dû voir.",
    "oublié que ma story était publique.",
    "menti sur ma localisation avec une photo d'archive.",
    "utilisé le compte d'un ami pour voir un profil qui m'avait bloqué.",
    "lancé une rumeur sans en mesurer les conséquences.",
    "révélé en soirée un secret qui ne m'appartenait pas.",
    "joué à un jeu à boire qui a fini en vraie dispute.",
    "été retiré (temporairement) d'un groupe de discussion.",
    "organisé une soirée surprise qui a capoté.",
    "découvert une soirée organisée sans moi.",
    "fait une crise en soirée pour une raison minuscule.",
    "quitté une soirée sans dire au revoir à personne.",
    "annoncé mon départ… puis été encore là deux heures plus tard.",
    "été raccompagné par quelqu'un rencontré le soir même.",
    "raconté ma vie entière à un inconnu dans un bar.",
    "pris parti dans une dispute de soirée qui ne me concernait pas.",
    "fini habillé dans une piscine.",
    "perdu une amitié à cause d'une soirée.",
    "gagné une amitié grâce à une dispute.",
    "conclu un pacte de soirée toujours en vigueur aujourd'hui.",
    "fait un gage si gênant que le groupe en parle encore.",
    "couvert l'état d'un ami devant ses parents.",
    "fourni un alibi inventé à un ami.",
    "inventé un couvre-feu pour partir tôt.",
    "fait semblant d'avoir froid pour obtenir une veste ou un câlin.",
    "choisi une tenue stratégique pour obtenir quelque chose.",
    "rentré le ventre pendant toute une soirée.",
    "fait des pompes ou du gainage juste avant un rendez-vous.",
    "changé de tenue quatre fois avant de sortir.",
    "forcé sur le parfum pour marquer les esprits.",
    "pris vingt essais pour une photo « spontanée ».",
    "accepté un plan que je détestais juste pour voir quelqu'un.",
    "appris une danse pour impressionner en soirée.",
    "prétendu savoir jouer au billard pour approcher quelqu'un.",
    "perdu exprès à un jeu pour flatter quelqu'un.",
    "gagné exprès pour impressionner quelqu'un.",
    "fait mine de partir pour voir si on me retiendrait.",
    "attendu à côté de mon téléphone après avoir envoyé « on se voit quand ? ».",
    "relu une conversation entière avant de répondre « ok ».",
    "préparé des sujets de conversation avant une soirée.",
    "demandé l'avis du groupe pour répondre à UN message.",
    "rédigé un message à plusieurs mains en soirée.",
    "espéré qu'une soirée soit annulée pour rester avec quelqu'un.",
    "fait un détour absurde pour croiser quelqu'un « par hasard ».",
    "liké puis retiré un like en priant que la notification ne soit pas partie.",
    "laissé exprès un « vu » sans réponse pour marquer un point.",
    "doublé mon temps de réponse pour ne pas paraître pressé.",
    "imaginé un mariage entier avec un crush d'un soir.",
    "gardé le ticket ou le sous-verre d'une rencontre.",
    "fait semblant d'adorer danser alors que je déteste ça.",
    "fini une soirée à regarder le lever du soleil avec quelqu'un.",
    "tenu une main « par accident » un peu trop longtemps.",
    "inventé une passion commune de toutes pièces.",
    "fait un compliment si raté qu'il est devenu une insulte.",
    "confondu la gentillesse avec de la drague — dans les deux sens.",
    "envoyé un ami en éclaireur pour savoir si je plaisais.",
    "reçu un râteau par personne interposée.",
    "transformé une bise hésitante en moment légendaire de gêne.",
    "calculé mon départ pour partager le trajet de quelqu'un.",
    "prêté ma veste et eu froid toute la nuit avec le sourire.",
    "proposé « un dernier verre » sans arrière-pensée officielle.",
    "accepté « un dernier verre » sans y croire moi-même.",
    "annulé un rencard pour un meilleur plan, en mentant sur la raison.",
    "accepté d'être le plan de secours d'une soirée.",
    "dansé collé-serré avec la mauvaise personne aux yeux de quelqu'un.",
    "joué les entremetteurs et déclenché une vraie histoire.",
    "parié sur le futur couple de la soirée — et gagné.",
    "vu un couple se former à cause d'un de mes gages.",
    "reçu une déclaration à laquelle je ne m'attendais pas du tout.",
    "fait une promesse de vacances ensemble jamais tenue.",
    "perdu le numéro de quelqu'un noté sur un bout de papier.",
    "chanté une chanson d'amour en pensant très fort à quelqu'un de précis.",
    "testé ma limite d'alcool par pure curiosité scientifique.",
    "pris un taxi ou un VTC de moins de 500 mètres en soirée.",
    "échangé mon verre contre celui de quelqu'un sans qu'il le sache.",
    "promis à quelqu'un de le raccompagner puis oublié complètement.",
    "avoué un secret que je ne voulais révéler à personne, en soirée.",
    "dansé sur une chanson que je déteste, avec une énergie totale.",
    "dit à quelqu'un que je le trouvais séduisant sans le penser vraiment.",
    "profité d'un jeu à boire pour révéler quelque chose de gênant sur moi-même.",
    "embrassé quelqu'un juste pour voir la réaction d'un tiers.",
    "menti sur mon statut relationnel pour éviter une drague insistante.",
    "fait croire que j'avais un rencard urgent pour partir plus tôt.",
    "raconté une anecdote inventée pour paraître plus intéressant en soirée.",
    "regretté un compliment fait à quelqu'un en pleine soirée.",
    "dit à quelqu'un « on devrait sortir un jour » sans intention réelle.",
    "fait semblant d'apprécier la musique choisie par l'hôte de la soirée.",
    "flirté avec quelqu'un uniquement pour obtenir la dernière part de pizza.",
    "raconté ma vie amoureuse à un inconnu croisé au bar.",
    "menti sur mon nombre de verres pour paraître plus raisonnable.",
    "dragué quelqu'un en citant une réplique de film sans le dire.",
    "fait exprès de perdre à un jeu à boire pour boire plus.",
    "envoyé un message doux à quelqu'un juste après ma propre rupture.",
    "évité quelqu'un toute une soirée pour ne pas avoir à m'expliquer.",
    "raconté à un·e inconnu·e un secret que même mes amis ne connaissent pas.",
    "accepté de « juste discuter » en sachant très bien où ça allait mener.",
    "fait un compliment calculé pour obtenir une faveur en soirée.",
    "changé de sujet brutalement pour éviter de parler de mon ex.",
    "menti sur mon travail pour paraître plus impressionnant en rencard.",
    "profité de l'obscurité d'une soirée pour observer quelqu'un sans être vu.",
    "raconté une rupture comme si c'était totalement de la faute de l'autre.",
    "accepté un compliment que je savais faux, juste pour le plaisir.",
    "dragué quelqu'un uniquement parce que mes amis m'avaient mis au défi.",
    "fait croire à un·e ami·e que son crush s'intéressait à lui pour l'encourager.",
    "menti sur l'heure à laquelle je suis rentré d'une soirée.",
    "accepté un « dernier verre » qui a duré jusqu'au petit matin.",
    "envoyé un selfie flatteur en pleine soirée pour impressionner quelqu'un.",
    "raconté un souvenir de soirée en changeant discrètement les détails gênants.",
    "profité d'un jeu pour poser une question que je n'osais pas poser autrement.",
    "menti sur avoir « juste un peu bu » alors que c'était clairement plus.",
    "fait semblant d'être surpris par une nouvelle que je connaissais déjà.",
    "accepté de danser avec quelqu'un juste pour éviter un moment gênant.",
    "raconté une blague vulgaire en soirée en le regrettant immédiatement.",
    "profité de l'ambiance d'une fête pour dire un « je t'aime bien » maladroit.",
    "fait exprès de rater mon chemin retour pour prolonger une conversation.",
    "menti sur le nombre de fois où j'ai recroisé un ex « par hasard ».",
  ],
  x18: [
    "fait des choses dans un lieu public.",
    "passé une nuit blanche pour de très bonnes raisons.",
    "fait l'amour dans une voiture.",
    "fait l'amour en extérieur.",
    "fait l'amour chez mes parents pendant qu'ils étaient là.",
    "fait l'amour chez les parents de l'autre.",
    "été surpris en pleine action par un colocataire.",
    "fait croire au téléphone que j'étais seul·e alors que non.",
    "envoyé un sexto pendant une réunion ou un repas de famille.",
    "reçu un sexto au pire moment et souri bêtement.",
    "eu un plan d'un soir devenu une relation.",
    "eu une relation devenue plan d'un soir.",
    "embrassé quelqu'un du même sexe.",
    "eu un rêve torride sur quelqu'un de cette pièce.",
    "eu un rêve torride sur un·e collègue et été gêné·e le lendemain.",
    "fait l'amour le premier soir.",
    "quitté discrètement un lit au milieu de la nuit.",
    "fait le mur pour un rendez-vous nocturne.",
    "menti sur mon nombre de partenaires.",
    "oublié le prénom de la personne au réveil.",
    "fait semblant de dormir au réveil pour éviter la conversation.",
    "pratiqué le « friends with benefits ».",
    "eu une histoire avec quelqu'un de mon travail.",
    "eu une histoire avec un voisin ou une voisine.",
    "assumé un coup de cœur purement physique.",
    "fait l'amour en gardant mes chaussettes.",
    "ri en plein milieu de l'action.",
    "eu une crampe au pire moment possible.",
    "cassé un meuble ou un objet pendant l'action.",
    "été interrompu par un animal de compagnie.",
    "été interrompu par un appel des parents.",
    "mis de la musique pour couvrir le bruit.",
    "monté le son de la télé à cause des voisins.",
    "été le voisin qu'on entend.",
    "proposé « un film » avec un programme très différent en tête.",
    "proposé « un massage » avec un plan précis.",
    "accepté un massage en connaissant parfaitement la suite.",
    "dormi dans le même lit « sans rien faire »… vraiment rien.",
    "dormi dans le même lit « sans rien faire »… au début seulement.",
    "fait l'amour dans l'eau — mer, piscine ou douche.",
    "testé les sextos vocaux.",
    "relu mes propres sextos et eu honte.",
    "envoyé une photo coquine.",
    "reçu une photo coquine non sollicitée.",
    "supprimé des photos en urgence avant de prêter mon téléphone.",
    "eu un dossier caché dans mon téléphone.",
    "fait des choses dans un train, un avion ou un bus.",
    "fait des choses dans les toilettes d'un bar ou d'une boîte.",
    "fait des choses sur un lieu de travail.",
    "fait des choses dans une pièce avec vue directe sur la rue.",
    "eu une aventure de vacances dont j'ignore encore le nom complet.",
    "eu une aventure avec la même personne qu'un ami — pas en même temps.",
    "participé à un jeu qui a fini en strip.",
    "perdu un pari dont le gage était coquin.",
    "utilisé une appli de rencontre en mode incognito.",
    "matché avec quelqu'un de cette pièce.",
    "matché avec quelqu'un de pris et l'avoir appris après.",
    "eu un ou une partenaire beaucoup plus expérimenté·e.",
    "été de loin le ou la plus expérimenté·e des deux.",
    "raconté ma propre expérience en la déguisant en « un ami à moi ».",
    "comparé mentalement deux partenaires.",
    "eu une abstinence de plus d'un an, choisie ou subie.",
    "rattrapé une longue abstinence en un seul week-end.",
    "fait l'amour plus de trois fois en une journée.",
    "fait l'amour moins de dix minutes après avoir passé la porte.",
    "organisé un rendez-vous uniquement pour ça, sans dîner ni cinéma.",
    "appelé un ex « pour parler » en sachant très bien comment ça finirait.",
    "regretté d'avoir dit non un soir précis.",
    "regretté d'avoir dit oui un soir précis.",
    "vécu — ou failli vivre — un plan à trois.",
    "embrassé deux personnes le même week-end sans qu'elles le sachent.",
    "eu un sex friend dont je suis tombé·e amoureux·se.",
    "gardé un secret intime que même mes proches ignorent.",
    "avoué avoir simulé.",
    "été félicité·e pour une performance… moyenne de mon point de vue.",
    "menti sur ma première fois.",
    "sorti une réplique de film au lit, volontairement ou non.",
    "dit « je t'aime » pendant, sans le penser une seconde après.",
    "pensé à quelqu'un d'autre pendant.",
    "eu du mal à regarder quelqu'un en face le lendemain d'un rêve.",
    "pris une douche à deux qui a fini en fou rire logistique.",
    "testé un accessoire.",
    "offert ou reçu un accessoire en cadeau.",
    "rougi en écoutant les autres répondre à ce jeu.",
    "fait des choses dans un ascenseur.",
    "laissé une trace visible le lundi au travail.",
    "porté une écharpe en plein été pour cacher un suçon.",
    "vécu une histoire dont le récit intégral choquerait cette table.",
    "fait l'amour sur une plage — et regretté le sable.",
    "réglé un coup de foudre physique le soir même.",
    "attendu que tout le monde dorme en soirée pour rejoindre quelqu'un.",
    "vécu une histoire secrète pendant un séjour de groupe sans éveiller de soupçons.",
    "assumé au réveil un message coquin dicté par l'alcool.",
    "consigné une expérience dans un journal ou une note de téléphone.",
    "eu un fou rire nerveux en retirant un vêtement récalcitrant.",
    "été bloqué·e par une fermeture éclair au pire moment.",
    "fait une pause snack en pleine nuit torride.",
    "réservé un hôtel juste pour quelques heures.",
    "fait l'amour avec des invités dans la pièce d'à côté.",
    "juré de ne jamais recommencer avec quelqu'un… et recommencé le week-end suivant.",
    "fait quelque chose que je n'aurais jamais imaginé faire un jour.",
    "utilisé un objet du quotidien à des fins totalement différentes.",
    "eu une conversation coquine en pleine réunion de famille par message.",
    "improvisé un scénario romantique complètement inventé sur le moment.",
    "eu une attirance immédiate pour quelqu'un de très différent de mon type habituel.",
    "gardé un souvenir « spécial » d'une rencontre d'un soir.",
    "testé quelque chose de nouveau uniquement par curiosité, sans regret.",
    "eu une conversation très explicite avec quelqu'un que je viens à peine de rencontrer.",
    "improvisé un jeu de rôle inattendu avec un·e partenaire.",
    "ressenti une attirance forte pour la voix de quelqu'un avant même de le voir.",
    "eu une expérience marquante que je n'ai racontée qu'à une seule personne.",
    "utilisé la musique pour mettre volontairement de l'ambiance.",
    "eu une aventure qui a commencé par un simple regard insistant.",
    "improvisé un compliment très osé qui a fonctionné au-delà de mes espérances.",
    "eu une expérience dans un endroit clairement pas prévu pour ça.",
    "gardé un vêtement d'une nuit mémorable en souvenir, sans le dire à personne.",
    "eu une discussion très frontale sur les préférences intimes avec un·e partenaire.",
    "ressenti le besoin de tout raconter à un·e ami·e le lendemain, dans les moindres détails.",
    "eu un coup de foudre purement physique qui ne s'est jamais reproduit avec la même intensité.",
    "improvisé une excuse bancale pour disparaître discrètement le matin.",
  ],
};
