/* Dilemmes « Tu préfères… ». Chaque entrée = { a, b }. Une carte = une idée.
   Banque rédigée à la main (120). Enrichis librement. */
export const DILEMMES = [
  { a: "Ne plus jamais manger de fromage", b: "Ne plus jamais manger de chocolat" },
  { a: "Pouvoir voler", b: "Être invisible" },
  { a: "Savoir quand tu vas mourir", b: "Savoir comment tu vas mourir" },
  { a: "Avoir toujours trop chaud", b: "Avoir toujours trop froid" },
  { a: "Lire dans les pensées", b: "Prédire l'avenir" },
  { a: "Ne plus jamais utiliser ton téléphone", b: "Ne plus jamais regarder d'écran (TV, ciné…)" },
  { a: "Être célèbre mais fauché", b: "Être riche mais anonyme" },
  { a: "Perdre la mémoire tous les 10 ans", b: "Ne jamais rien pouvoir oublier" },
  { a: "Vivre sans musique", b: "Vivre sans films et séries" },
  { a: "Toujours dire la vérité", b: "Ne plus jamais pouvoir parler de toi" },
  { a: "Avoir des mains à la place des pieds", b: "Avoir des pieds à la place des mains" },
  { a: "Être bloqué sur une île déserte seul", b: "Être bloqué avec quelqu'un que tu détestes" },
  { a: "Parler toutes les langues", b: "Savoir jouer de tous les instruments" },
  { a: "Revivre la même journée parfaite en boucle", b: "Vivre des journées inconnues, bonnes ou mauvaises" },
  { a: "Ne dormir que 2 heures par nuit sans fatigue", b: "Devoir dormir 12 heures obligatoires" },
  { a: "Gagner 5 000 € par mois à vie sans travailler", b: "Gagner 20 000 € par mois avec un travail détesté" },
  { a: "Avoir toujours raison mais personne ne te croit", b: "Avoir souvent tort mais tout le monde te suit" },
  { a: "Sentir le poisson en permanence sans le savoir", b: "Sentir le poisson et le savoir, sans solution" },
  { a: "Rire à chaque phrase qu'on te dit", b: "Pleurer à chaque compliment reçu" },
  { a: "Éternuer à chaque fois que tu mens", b: "Rougir à chaque fois que tu penses à ton crush" },
  { a: "Vivre 100 ans dans le passé", b: "Vivre 100 ans dans le futur" },
  { a: "Ne boire que de l'eau à vie", b: "Ne plus jamais boire d'eau pure" },
  { a: "Manger ton plat préféré tous les jours à vie", b: "Ne plus jamais y goûter mais varier à l'infini" },
  { a: "Avoir un rire de dessin animé", b: "Avoir une démarche de pingouin" },
  { a: "Chanter tout ce que tu dis", b: "Danser partout où tu marches" },
  { a: "Connaître la date de fin du monde", b: "Vivre sans jamais le savoir" },
  { a: "Être un génie incompris", b: "Être moyen mais adoré" },
  { a: "Perdre tous tes souvenirs de vacances", b: "Ne plus jamais partir en vacances" },
  { a: "Avoir un bouton pause pour la vie", b: "Avoir un bouton retour de 10 secondes" },
  { a: "Parler aux animaux", b: "Parler couramment 10 langues" },
  { a: "Toujours arriver 2 heures en avance", b: "Toujours arriver 20 minutes en retard" },
  { a: "Ne plus jamais faire la vaisselle", b: "Ne plus jamais faire la lessive" },
  { a: "Vivre sans réseaux sociaux", b: "Vivre sans musique dans les écouteurs" },
  { a: "Que ton historique de recherche soit public", b: "Que tes messages privés soient publics" },
  { a: "Avoir un sosie qui fait des bêtises en ton nom", b: "Être le sosie de quelqu'un de détesté" },
  { a: "Gagner à tous les jeux de société", b: "Gagner à tous les paris sportifs" },
  { a: "Un dimanche éternel", b: "Un vendredi soir éternel" },
  { a: "Ne manger que sucré", b: "Ne manger que salé" },
  { a: "Pizza sans fromage à vie", b: "Burger sans pain à vie" },
  { a: "Boire ton café/thé toujours froid", b: "Boire ton soda toujours chaud" },
  { a: "Avoir du wifi parfait partout", b: "Ne plus jamais payer l'essence ou les transports" },
  { a: "Être pote avec ton acteur préféré", b: "Que ton acteur préféré joue ta vie au cinéma" },
  { a: "Revoir ton film préféré comme la première fois", b: "Découvrir 10 nouveaux films excellents" },
  { a: "Vivre dans un film d'horreur", b: "Vivre dans une téléréalité 24h/24" },
  { a: "Avoir la bande-son de ta vie audible par tous", b: "Que tes pensées s'affichent au-dessus de ta tête 1 min par jour" },
  { a: "Te téléporter mais arriver tout nu", b: "Voler mais seulement à 30 cm du sol" },
  { a: "Être ultra fort mais très lent", b: "Être ultra rapide mais très faible" },
  { a: "Connaître toutes les réponses de quiz", b: "Être imbattable à tous les jeux d'adresse" },
  { a: "Dormir chaque nuit dans un endroit différent", b: "Ne plus jamais quitter ta ville" },
  { a: "Vivre à la montagne sans mer à vie", b: "Vivre à la mer sans montagne à vie" },
  { a: "Été éternel à 35 degrés", b: "Hiver éternel à -5 degrés" },
  { a: "Voyager gratuitement mais toujours seul", b: "Voyager accompagné mais hors de prix" },
  { a: "Refaire ta vie dans un pays au hasard", b: "Rester ici pour toujours" },
  { a: "Un billet d'avion gratuit chaque mois", b: "Un restaurant gastronomique gratuit chaque semaine" },
  { a: "Croiser ton ex à chaque soirée", b: "Croiser ton patron à chaque soirée" },
  { a: "Que tes parents lisent tes messages", b: "Que tes amis lisent ton journal intime" },
  { a: "Un partenaire qui ronfle très fort", b: "Un partenaire qui vole la couette" },
  { a: "Tomber amoureux de ton meilleur ami", b: "Que ton meilleur ami tombe amoureux de toi" },
  { a: "Un grand amour qui dure 5 ans", b: "Dix belles histoires d'un an" },
  { a: "Savoir qui t'aime en secret", b: "Savoir qui te critique en secret" },
  { a: "Être le plus drôle de la pièce", b: "Être le plus intelligent de la pièce" },
  { a: "Ne plus jamais faire la bise", b: "Faire la bise à absolument tout le monde" },
  { a: "Avoir un an de vacances mais injoignable", b: "Travailler un an sans un seul jour off, payé double" },
  { a: "Choisir ton apparence à vie", b: "Choisir ton intelligence à vie" },
  { a: "Retourner à 10 ans avec tes souvenirs", b: "Avancer à 60 ans avec ta santé actuelle" },
  { a: "Que tout le monde oublie ton anniversaire", b: "Qu'on te le souhaite tous les jours" },
  { a: "Porter les mêmes vêtements toute l'année", b: "Changer de coiffure imposée chaque mois" },
  { a: "Chausser du 30", b: "Chausser du 55" },
  { a: "Avoir des sourcils qui repoussent en 1 heure", b: "Ne plus jamais avoir de sourcils" },
  { a: "Sentir bon mais avoir l'air négligé", b: "Être impeccable mais sentir le renfermé" },
  { a: "Un tatouage raté visible", b: "Un tatouage magnifique que personne ne voit jamais" },
  { a: "Ne plus jamais te couper les cheveux", b: "Te raser la tête tous les mois" },
  { a: "Manger un insecte par semaine", b: "Ne plus jamais manger de dessert" },
  { a: "Boire un smoothie mystère chaque matin", b: "Manger exactement la même chose chaque midi" },
  { a: "Goûter à tout sans jamais être rassasié", b: "Être rassasié d'un seul plat pour la journée" },
  { a: "Cuisiner comme un chef sans pouvoir goûter", b: "Goûter les meilleurs plats sans jamais savoir cuisiner" },
  { a: "Ne plus jamais manger de pain", b: "Ne plus jamais manger de pâtes" },
  { a: "Café gratuit à vie", b: "Apéro gratuit tous les vendredis" },
  { a: "Reprendre les études 5 ans", b: "Travailler 5 ans sans vacances" },
  { a: "Un travail passionnant payé au SMIC", b: "Un travail ennuyeux payé une fortune" },
  { a: "Être ton propre patron débordé", b: "Être salarié tranquille" },
  { a: "Faire un discours devant 1 000 personnes", b: "Chanter devant ta famille entière" },
  { a: "Que ton téléphone sonne en réunion", b: "Que ton ventre gargouille en entretien" },
  { a: "Travailler dans le noir", b: "Travailler dans le bruit" },
  { a: "Savoir démasquer tous les mensonges", b: "Pouvoir mentir sans jamais être démasqué" },
  { a: "Être aimé mais jamais respecté", b: "Être respecté mais jamais aimé" },
  { a: "Recevoir un compliment par jour d'un inconnu", b: "Un compliment par an de la personne que tu admires" },
  { a: "Vivre sans mentir une année entière", b: "Mentir librement mais chaque mensonge coûte 10 €" },
  { a: "Connaître l'avis de tous sur toi", b: "Rester dans un doute confortable" },
  { a: "Avoir la maison de tes rêves dans un endroit moche", b: "Une maison moche dans le lieu de tes rêves" },
  { a: "Vivre en colocation avec tes meilleurs amis à vie", b: "Vivre seul dans un manoir isolé" },
  { a: "Ne plus jamais faire le ménage", b: "Ne plus jamais faire les courses" },
  { a: "Un voisin qui fait la fête tous les soirs", b: "Un voisin qui t'espionne en silence" },
  { a: "Perdre tes photos", b: "Perdre tes contacts" },
  { a: "Un téléphone qui a toujours 10 % de batterie", b: "Un téléphone qui met 1 minute à tout ouvrir" },
  { a: "Écrire sans fautes mais lentement", b: "Écrire vite avec des fautes énormes" },
  { a: "Être une star du rire malgré toi", b: "Être sérieux et jamais écouté" },
  { a: "Un super-pouvoir aléatoire chaque jour", b: "Un pouvoir moyen mais permanent" },
  { a: "Revivre ta meilleure soirée chaque samedi", b: "Découvrir une soirée inconnue chaque samedi" },
  { a: "Être DJ de toutes les soirées", b: "Être le VIP de toutes les soirées" },
  { a: "Danser comme un dieu une seule nuit par an", b: "Danser correctement tous les jours" },
  { a: "Gagner tous tes paris pendant un an", b: "Ne plus jamais perdre aux jeux à boire" },
  { a: "Boire un verre avec une légende disparue", b: "Un week-end avec ta star vivante préférée" },
  { a: "Savoir exactement quoi dire, une fois par jour", b: "Être naturellement charmant sans le contrôler" },
  { a: "Un rewind de 24 heures utilisable une fois par an", b: "Une avance rapide de 24 heures illimitée" },
  { a: "Toujours gagner à pierre-feuille-ciseaux", b: "Toujours trouver une place de parking" },
  { a: "Chuchoter en permanence", b: "Crier en permanence" },
  { a: "Avoir une voix de robot", b: "Avoir une voix d'enfant de 6 ans" },
  { a: "Être enfermé une nuit dans un supermarché", b: "Être enfermé une nuit dans un parc d'attractions" },
  { a: "Rejouer ta vie en mode facile sans surprises", b: "La rejouer en mode difficile avec des exploits" },
  { a: "Connaître la vérité sur tous les complots", b: "Vivre heureux dans l'ignorance" },
  { a: "Avoir un majordome insolent", b: "Faire toi-même tout, aidé d'applaudissements" },
  { a: "Toujours avoir une blague parfaite en stock", b: "Toujours avoir la playlist parfaite en stock" },
  { a: "Que ta vie ait un narrateur sarcastique", b: "Que ta vie ait des applaudissements enregistrés" },
  { a: "Vieillir sans jamais changer d'avis", b: "Changer d'avis chaque semaine" },
  { a: "Être oublié après ta mort mais heureux vivant", b: "Être célèbre après ta mort mais ignoré vivant" },
  { a: "Avoir un bouton « avancer l'attente »", b: "Avoir un bouton « prolonger le plaisir »" },
  { a: "Répondre à tout par oui pendant 24 h", b: "Répondre à tout par non pendant une semaine" },
  { a: "Un karaoké surprise par mois obligatoire", b: "Un discours surprise par mois obligatoire" },
  { a: "Toujours connaître le fin mot de l'histoire", b: "Toujours avoir le dernier mot" },

  // --- lot 2 ---
  { a: "Ne plus jamais éternuer", b: "Éternuer toutes les 10 minutes" },
  { a: "Avoir toujours les mains froides", b: "Avoir toujours les pieds froids" },
  { a: "Ne plus jamais rêver en dormant", b: "Ne rêver que de cauchemars" },
  { a: "Perdre le sens du goût", b: "Perdre le sens de l'odorat" },
  { a: "Vivre sans clim ni chauffage à vie", b: "Vivre sans électricité un jour par semaine" },
  { a: "Un GPS qui te parle sans arrêt de ta vie", b: "Un GPS muet qui se trompe une fois sur deux" },
  { a: "Toujours gagner aux cartes mais perdre en amour", b: "L'inverse" },
  { a: "Avoir une mémoire photographique", b: "Avoir une imagination débordante" },
  { a: "Être the seul à voir les fantômes", b: "Être le seul que les fantômes ignorent" },
  { a: "Ton téléphone lit tes messages à voix haute en public", b: "Ton téléphone ne vibre plus jamais, silence total" },
  { a: "Toujours arriver avec la bonne réplique", b: "Toujours trouver la bonne réplique… trop tard" },
  { a: "Un travail où tu voyages sans arrêt, jamais chez toi", b: "Un travail confortable, jamais de voyage" },
  { a: "Gagner un procès que tu ne méritais pas", b: "Perdre un procès que tu méritais de gagner" },
  { a: "Avoir un accent différent chaque jour", b: "Avoir toujours la même voix monocorde" },
  { a: "Manger uniquement des surgelés à vie", b: "Cuisiner tout toi-même, chaque jour, sans exception" },
  { a: "Ne plus jamais recevoir de compliments", b: "Ne plus jamais recevoir de cadeaux" },
  { a: "Une seule chanson dans les oreilles à vie", b: "Un silence total dans les oreilles à vie" },
  { a: "Toujours savoir ce que pense ton animal", b: "Toujours savoir ce que pense ton meilleur ami" },
  { a: "Un an sans réseaux sociaux", b: "Un an sans séries ni films" },
  { a: "Perdre au jeu à chaque soirée", b: "Gagner au jeu mais perdre tes amis" },
  { a: "Vivre 200 ans seul", b: "Vivre 60 ans entouré" },
  { a: "Toujours dire ce que tu penses vraiment", b: "Toujours dire ce que les autres veulent entendre" },
  { a: "Un cerveau qui n'oublie jamais un visage", b: "Un cerveau qui n'oublie jamais un chiffre" },
  { a: "Passer pour un génie sans jamais rien prouver", b: "Prouver ton génie sans que personne ne le remarque" },
  { a: "Toujours savoir l'heure exacte sans montre", b: "Toujours savoir où est le nord sans boussole" },
  { a: "Un jardin secret magnifique que tu ne peux jamais montrer", b: "Un jardin banal que tout le monde admire" },
  { a: "Gagner 1 million maintenant", b: "Gagner 10 000 € par an à vie" },
  { a: "Manger épicé à chaque repas", b: "Manger fade à chaque repas" },
  { a: "Vivre sans jamais avoir froid", b: "Vivre sans jamais avoir chaud" },
  { a: "Toujours perdre au dernier moment", b: "Ne jamais participer du tout" },
  { a: "Avoir un rire contagieux", b: "Avoir un regard qui impose le respect" },
  { a: "Connaître ta date de rupture à l'avance", b: "Ne jamais savoir si une relation va durer" },
  { a: "Devenir végétarien à vie", b: "Ne manger que de la viande à vie" },
  { a: "Une seule vraie amitié pour la vie", b: "Cent connaissances superficielles" },
  { a: "Toujours voyager en économique confortable", b: "Voyager en première une fois par an, le reste à pied" },
  { a: "Vivre sans miroir toute ta vie", b: "Vivre avec un miroir qui te juge à voix haute" },
  { a: "Un pouvoir que tu ne contrôles jamais", b: "Aucun pouvoir mais un contrôle total sur ta vie" },
  { a: "Toujours savoir quand quelqu'un te ment", b: "Ne jamais être démasqué quand tu mens" },
  { a: "Un corps increvable mais un mental fragile", b: "Un mental de fer mais un corps fragile" },
  { a: "Vivre avec la même coupe de cheveux à vie", b: "Changer de coiffure imposée chaque semaine" },
  { a: "Toujours avoir le wifi mais jamais de batterie", b: "Toujours de la batterie mais jamais de wifi" },
  { a: "Un an sans dormir plus de 4h par nuit", b: "Un an à dormir 12h par nuit obligatoirement" },
  { a: "Ne plus jamais pouvoir mentir", b: "Ne plus jamais pouvoir dire la vérité" },
  { a: "Gagner à tous les jeux d'argent, une seule fois dans ta vie", b: "Gagner petit mais souvent, toute ta vie" },
  { a: "Avoir un humour que personne ne comprend", b: "Rire de tout ce que les autres trouvent drôle, sans exception" },
  { a: "Toujours choisir la mauvaise file d'attente", b: "Toujours arriver juste après la fermeture" },
  { a: "Une intelligence hors norme mais zéro charisme", b: "Un charisme fou mais une intelligence moyenne" },
  { a: "Vivre dans le passé de quelqu'un d'autre", b: "Vivre dans le futur de quelqu'un d'autre" },
  { a: "Toujours savoir cuisiner sans recette", b: "Toujours savoir réparer n'importe quel objet" },
  { a: "Un an à l'étranger sans parler la langue", b: "Un an chez toi sans sortir de ta ville" },
  { a: "Avoir toujours raison en dernier recours", b: "Avoir toujours de la chance en dernier recours" },
  { a: "Vivre avec les mêmes 5 vêtements à vie", b: "Changer de vêtements imposés chaque jour, jamais les mêmes" },
  { a: "Toujours te souvenir de tes rêves", b: "Ne jamais te souvenir de tes rêves" },
  { a: "Une famille bruyante et envahissante mais aimante", b: "Une famille discrète et distante mais respectueuse" },
  { a: "Perdre goût au sucré", b: "Perdre goût au salé" },
  { a: "Toujours entendre les pensées négatives des autres", b: "Toujours entendre leurs pensées positives, jamais les négatives" },
  { a: "Un métier passionnant mais isolé", b: "Un métier ennuyeux mais entouré d'amis" },
  { a: "Ne plus jamais pouvoir voyager en avion", b: "Ne plus jamais pouvoir voyager en voiture" },
  { a: "Toujours savoir ce que tu vas manger demain", b: "Ne jamais savoir ce que tu manges avant d'y goûter" },
  { a: "Une vie sans imprévu, jamais de surprise", b: "Une vie pleine de surprises, jamais de stabilité" },
  { a: "Toujours porter des lunettes de soleil, même la nuit", b: "Ne plus jamais pouvoir en porter" },
  { a: "Un talent artistique immense mais jamais reconnu", b: "Un talent moyen mais adoré du public" },
  { a: "Vivre sans jamais entendre de musique triste", b: "Vivre sans jamais entendre de musique joyeuse" },
  { a: "Toujours arriver en retard mais pardonné", b: "Toujours arriver à l'heure mais jamais remercié" },
  { a: "Un ami imaginaire qui te donne toujours raison", b: "Un ami réel qui te contredit toujours" },
  { a: "Toujours savoir la fin d'un livre avant de le lire", b: "Oublier systématiquement la fin d'un livre que tu adores" },
  { a: "Une vie sans jamais être malade", b: "Une vie sans jamais avoir mal aux muscles" },
  { a: "Toujours choisir le mauvais film au cinéma", b: "Toujours t'endormir pendant le bon film" },
  { a: "Vivre avec un super-héros comme voisin", b: "Vivre avec un super-vilain comme voisin, mais sympa" },
  { a: "Toujours savoir qui t'aime vraiment", b: "Toujours savoir qui te déteste vraiment" },
  { a: "Un travail bien payé que tu dois cacher à tes proches", b: "Un travail mal payé dont tu es fier devant tout le monde" },
  { a: "Ne plus jamais pouvoir chanter", b: "Ne plus jamais pouvoir danser" },
  { a: "Vivre avec le bruit d'un chantier permanent chez toi", b: "Vivre dans un silence religieux permanent" },
  { a: "Toujours te tromper de prénom en rencard", b: "Toujours te tromper de date en rendez-vous professionnel" },
  { a: "Une vie où tu es toujours le centre d'attention", b: "Une vie où personne ne te remarque jamais" },
  { a: "Toujours perdre tes lunettes alors que tu les portes", b: "Toujours chercher ton téléphone en le tenant dans la main" },
  { a: "Un cerveau qui calcule tout instantanément", b: "Un cœur qui ressent tout intensément" },
  { a: "Vivre avec un majordome parfait mais froid", b: "Vivre seul mais totalement libre" },
  { a: "Toujours savoir la météo du lendemain, jamais celle du jour", b: "Toujours savoir celle du jour, jamais celle du lendemain" },
  { a: "Un rire qu'on entend à des kilomètres", b: "Un rire silencieux que personne n'entend jamais" },
  { a: "Ne plus jamais avoir faim", b: "Ne plus jamais avoir soif" },
  { a: "Toujours réussir tes photos", b: "Toujours réussir tes discours" },
  { a: "Vivre avec la voix de quelqu'un de célèbre", b: "Vivre avec le visage de quelqu'un de célèbre" },
  { a: "Toujours savoir ce que veut dire un regard", b: "Toujours savoir ce que veut dire un silence" },
  { a: "Un jardin qui ne pousse que la nuit", b: "Une maison qui ne chauffe que le jour" },
  { a: "Toujours perdre au jeu contre les enfants", b: "Toujours perdre au jeu contre tes parents" },
  { a: "Une vie sans jamais mentir à toi-même", b: "Une vie sans jamais te tromper toi-même" },
  { a: "Toujours entendre la vérité, même blessante", b: "Toujours entendre des mensonges, même agréables" },
  { a: "Un métier où tu voyages dans le temps sans jamais rien changer", b: "Un métier normal mais avec un jour de congé illimité" },
];
